-- Correção dos 3 items que faltaram

UPDATE score_items SET
  clinical_relevance = 'As medidas objetivas antropométricas constituem ferramentas acessíveis, não invasivas e de baixo custo para avaliação de composição corporal, estratificação de risco metabólico e cardiovascular, e monitoramento de intervenções. Incluem: peso, altura, IMC, circunferências corporais (cintura, quadril, pescoço, braço, coxa, panturrilha), relações (cintura/quadril, cintura/altura, pescoço/altura), pregas cutâneas. Cada medida fornece informações específicas: circunferência de cintura reflete adiposidade abdominal (risco metabólico elevado: >102cm homens, >88cm mulheres); relação cintura/quadril indica distribuição de gordura (androide vs ginoide, risco: >1.0 homens, >0.85 mulheres); relação cintura/altura (ideal <0.5) é preditor de risco cardiometabólico superior ao IMC isolado; circunferência de pescoço correlaciona-se com gordura visceral e apneia obstrutiva do sono (risco: >40cm homens, >36cm mulheres); circunferências de membros (braço, coxa, panturrilha) avaliam massa muscular (panturrilha <31cm sugere sarcopenia em idosos). Limitações: não distinguem massa gorda de magra (exceto pregas), sofrem variação inter-avaliador, influência de edema. Vantagens: praticidade, custo zero, aplicáveis em qualquer contexto. Na medicina funcional integrativa, usamos medidas antropométricas como triagem e monitoramento, complementando com métodos mais sofisticados (bioimpedância, DEXA) quando necessário.',
  patient_explanation = 'As medidas objetivas do seu corpo - peso, circunferências de cintura, quadril, pescoço, braço, coxa, panturrilha - são ferramentas simples mas muito informativas. A circunferência da cintura, por exemplo, é um dos melhores indicadores de gordura visceral (aquela ao redor dos órgãos internos, mais perigosa) e risco de diabetes e doenças cardiovasculares - muitas vezes mais importante que o peso total. A relação entre cintura e quadril nos mostra se você tem distribuição de gordura mais androide (tipo maçã, mais arriscada) ou ginoide (tipo pera, menos arriscada). A circunferência do pescoço pode indicar risco de apneia do sono. As medidas de panturrilha, coxa e braço ajudam a avaliar sua massa muscular. O interessante dessas medidas é que elas podem mudar mesmo quando o peso na balança não muda - você pode estar ganhando músculo e perdendo gordura, o que é excelente, e isso vai aparecer nas medidas mesmo que o peso fique igual.',
  conduct = 'Protocolo padronizado de antropometria: medidas pela manhã, paciente em jejum, bexiga vazia, roupas leves, mesmo avaliador. Utilizar instrumentos calibrados: balança de precisão, estadiômetro, fita métrica inelástica. Registrar: peso, altura, IMC, circunferências (cintura, quadril, pescoço, braço, coxa, panturrilha), relações calculadas. Todas medidas em duplicata, usar média. Comparar com valores de referência por sexo e idade. Reavaliar mensalmente durante fase intensiva, trimestralmente em manutenção.',
  updated_at = NOW()
WHERE id = '662902a2-d3f7-4d08-b3ee-4fde9e633cf8';

UPDATE score_items SET
  clinical_relevance = 'O peso corporal total é a medida mais simples e acessível, mas deve ser interpretado com cautela pois não diferencia massa gorda de massa magra (músculo, osso, água). Indivíduos com mesma altura e peso podem ter composições corporais radicalmente diferentes. O peso é influenciado por: massa gorda, massa muscular esquelética (40-50% do peso em adultos saudáveis), massa óssea (10-15%), água corporal (50-60%), conteúdo intestinal. Variações agudas de peso (1-2kg em dias) refletem primariamente flutuações de água e conteúdo intestinal, não mudanças reais em composição. Perda ponderal sustentada deve ser preferencialmente à custa de massa gorda com preservação ou ganho de massa magra. Perda >1kg/semana sugere perda excessiva, provavelmente incluindo massa magra. Na medicina funcional integrativa, priorizamos mudanças em composição corporal sobre peso total. Peso deve ser monitorado em condições padronizadas: mesma balança, mesmo horário (idealmente ao acordar, após micção, antes de comer), mínimo de roupa.',
  patient_explanation = 'Seu peso é o número mais fácil de medir, mas NÃO conta toda a história. Duas pessoas com mesma altura e mesmo peso podem ter corpos completamente diferentes: uma pode ter muito músculo e pouca gordura (saudável), outra pode ter pouco músculo e muita gordura (não saudável). Além disso, o peso varia diariamente por causa de água e conteúdo intestinal - você pode estar 1-2kg mais pesado depois de uma refeição grande ou em certos dias do ciclo menstrual, sem que isso signifique ganho de gordura. Por isso, não recomendamos se pesar todos os dias. Pesagens semanais ou quinzenais, sempre nas mesmas condições, são suficientes. E mais importante: vamos acompanhar NÃO só o peso, mas principalmente sua composição corporal (quanto é músculo, quanto é gordura), porque você pode ganhar peso ganhando músculo (excelente!) ou perder peso perdendo músculo (ruim!).',
  conduct = 'Protocolo padronizado: mesma balança calibrada, mesma hora do dia (idealmente ao acordar, após urinar, antes de comer), roupas mínimas, bexiga vazia, mulheres evitar período pré-menstrual. Registrar peso em kg com 1 decimal. Orientar: variações diárias são normais (0.5-2kg), não se pesar diariamente, frequência ideal semanal a quinzenal. Meta de perda ponderal saudável: 0.5-1% peso corporal/semana, máximo 4-5kg/mês. SEMPRE correlacionar mudanças de peso com mudanças em composição corporal - o objetivo é perder gordura preservando ou ganhando músculo.',
  updated_at = NOW()
WHERE id = '400295c1-25e5-44c5-8d99-0f355f1aa7cc';

UPDATE score_items SET
  clinical_relevance = 'O Índice de Massa Corporal (IMC = peso/altura²) é a métrica populacional mais utilizada para classificar peso, mas tem limitações significativas pois não diferencia massa gorda de magra nem distribuição de gordura. Classificação OMS: baixo peso <18.5, eutrofia 18.5-24.9, sobrepeso 25-29.9, obesidade grau I 30-34.9, grau II 35-39.9, grau III ≥40 kg/m². Paradoxo do IMC: atletas musculosos podem ter IMC >25 sendo metabolicamente saudáveis; idosos com IMC "normal" podem ter obesidade sarcopênica. Estudos mostram que mortalidade tem curva em J: risco aumenta tanto em IMC muito baixo quanto alto, com nadir entre 22-25. Contudo, distribuição de gordura (visceral vs subcutânea) e massa muscular são mais preditivas de risco metabólico que IMC isolado. Na medicina funcional integrativa, usamos IMC como triagem inicial mas complementamos com avaliação de composição corporal, circunferência de cintura, relação cintura/altura, e marcadores metabólicos. Conceito de obesidade metabolicamente saudável: IMC ≥30 mas sem resistência insulínica, dislipidemia, hipertensão - fenotipo raro. Obesidade abdominal mesmo com IMC normal (TOFI) é metabolicamente perigosa.',
  patient_explanation = 'O IMC é um cálculo simples usando seu peso e altura que classifica se você está abaixo do peso, no peso normal, com sobrepeso ou obesidade. É útil para avaliações populacionais, mas tem limitações importantes. Por exemplo: uma pessoa musculosa pode ter IMC classificado como "sobrepeso" mas ser perfeitamente saudável. Por outro lado, uma pessoa sedentária pode ter IMC "normal" mas ter pouco músculo e muita gordura, especialmente na barriga (obesidade sarcopênica), o que é metabolicamente prejudicial. Por isso, o IMC é apenas um PONTO DE PARTIDA. Precisamos avaliar também sua composição corporal (quanto é músculo vs gordura), onde a gordura está localizada (barriga é mais perigosa), e seus exames metabólicos (glicemia, insulina, colesterol). É possível ter IMC elevado mas ser metabolicamente saudável, ou ter IMC normal mas ter problemas metabólicos. Vamos olhar o quadro completo.',
  conduct = 'Calcular IMC = peso(kg) / altura²(m). Classificar segundo OMS mas SEMPRE interpretar no contexto de composição corporal, distribuição de gordura, massa muscular, perfil metabólico. Em atletas, IMC >25 pode ser normal; usar circunferência de cintura, % gordura corporal, marcadores metabólicos. Em idosos, IMC ideal pode ser ligeiramente maior (23-27). Solicitar exames: glicemia, insulina, HOMA-IR, HbA1c, perfil lipídico completo, PCR-us, transaminases, ultrassom abdominal, pressão arterial. Avaliar composição corporal por bioimpedância ou DEXA. Estabelecer metas individualizadas: nem sempre normalizar IMC é necessário; focar em melhorar composição corporal, parâmetros metabólicos, e funcionalidade.',
  updated_at = NOW()
WHERE id = 'bf875f17-1a90-4bb8-8305-e0e0285aeb80';
