-- ============================================================
-- BATCH 3: ENRIQUECIMENTO - COMPOSIÇÃO CORPORAL (46 items)
-- Gerado em: 2026-01-27
-- Grupo: Composição corporal
-- ============================================================

-- ============================================================
-- SUBGRUPO: HISTÓRICO
-- ============================================================

-- ============================================================
-- Item: Vida adulta (histórico de avaliações de composição corporal)
-- ============================================================

UPDATE score_items
SET
  clinical_relevance = 'A avaliação longitudinal da composição corporal ao longo da vida adulta é fundamental para identificar padrões de risco metabólico, cardiovascular e de fragilidade. O histórico de variações de peso e composição corporal (weight cycling ou efeito sanfona) está associado a alterações no metabolismo adaptativo, resistência progressiva à perda de peso, perda preferencial de massa magra, e maior risco de síndrome metabólica, diabetes tipo 2, doenças cardiovasculares e mortalidade. Estudos demonstram que indivíduos com história de flutuações repetidas apresentam maior adiposidade visceral, resistência insulínica, dislipidemia aterogênica (↑triglicerídeos, ↓HDL, ↑LDL pequeno e denso), estado pró-inflamatório (elevação de TNF-α, IL-6, PCR ultrassensível), e disfunção endotelial. Na medicina funcional integrativa, investigamos as causas raiz dessas alterações: exposição a disruptores endócrinos (BPA, ftalatos, pesticidas), disfunção tireoidiana (hipotireoidismo subclínico, resistência periférica aos hormônios tireoidianos, conversão T4-T3 prejudicada), hipercortisolismo (estresse crônico, síndrome de Cushing subclínica), déficit de testosterona em homens, dominância estrogênica ou hipoestrogenismo em mulheres, resistência à leptina, estresse oxidativo, inflamação de baixo grau, disbiose intestinal, aumento da permeabilidade intestinal, deficiências nutricionais (magnésio, vitamina D, ômega-3, cromo, zinco), cronodisrupção (dessincronização circadiana), privação de sono, sedentarismo, dietas restritivas repetidas (metabolismo adaptativo). A sarcopenia (perda de massa muscular) é fator independente de mortalidade, mesmo em indivíduos com peso normal ou sobrepeso (obesidade sarcopênica).',

  patient_explanation = 'O histórico da sua composição corporal ao longo da vida adulta conta uma história importante sobre sua saúde metabólica. Não se trata apenas do número na balança, mas sim de entender COMO seu corpo mudou ao longo do tempo: quanto de músculo você tinha, quanto ganhou ou perdeu, como a gordura se distribuiu, quantas vezes você emagreceu e reganhou peso. Se você passou por várias dietas com efeito sanfona, seu metabolismo pode ter se adaptado, tornando cada vez mais difícil perder peso e mais fácil recuperá-lo. Além disso, essas flutuações podem ter causado perda de massa muscular e ganho preferencial de gordura, especialmente na região abdominal (gordura visceral), que é mais perigosa para a saúde. A boa notícia é que podemos investigar e corrigir as causas subjacentes: problemas de tireoide, alterações hormonais (testosterona, estrogênio, cortisol, leptina), deficiências de vitaminas e minerais, qualidade do sono, níveis de estresse, saúde intestinal, exposição a toxinas ambientais. Com essa investigação detalhada, criamos um plano personalizado para restaurar sua composição corporal de forma sustentável, preservando ou aumentando sua massa muscular e melhorando seu metabolismo.',

  conduct = 'Anamnese detalhada: histórico ponderal completo (peso ao nascer, infância, adolescência, vida adulta - mínimo, máximo, habitual, atual), número de tentativas de emagrecimento, métodos utilizados (dietas restritivas, medicamentos, cirurgia bariátrica), velocidade de perda e reganho, períodos de melhor e pior composição corporal, uso prévio de hormônios ou esteroides anabolizantes. Questionar sobre história reprodutiva em mulheres (gestações, amamentação, menopausa), uso de contraceptivos hormonais. Investigar: perfil tiroideano completo (TSH, T3 livre, T4 livre, T3 reverso, anticorpos anti-TPO e anti-Tg), cortisol salivar em 4 pontos, cortisol livre urinário 24h, DHEA-S, testosterona total e livre (homens e mulheres), SHBG, estradiol, progesterona (mulheres), FSH, LH, prolactina, glicemia de jejum, insulina basal, HOMA-IR, hemoglobina glicada, perfil lipídico completo (incluindo LDL oxidado, apo B, Lp(a)), marcadores inflamatórios (PCR-us, homocisteína, ferritina), vitamina D (25-OH), magnésio eritrocitário, zinco, ômega-3 index, avaliação de disbiose (teste de microbioma ou marcadores indiretos), permeabilidade intestinal (zonulina), rastreio de metais pesados e disruptores endócrinos. Avaliar composição corporal por método validado (DEXA, bioimpedância multifrequencial, pregas cutâneas). Reavaliação trimestral.',

  updated_at = NOW()
WHERE id = 'ac04ab06-bdc7-4959-a33d-32f3646c1a87';

-- ============================================================
-- Item: Períodos de picos de peso / gordura corporal
-- ============================================================

UPDATE score_items
SET
  clinical_relevance = 'A identificação de períodos de picos de peso e gordura corporal ao longo da vida é crucial para compreender gatilhos metabólicos, hormonais, emocionais e ambientais que promoveram ganho ponderal. Esses períodos frequentemente coincidem com eventos de vida significativos: transições (casamento, divórcio, luto), mudanças ocupacionais (trabalho sedentário, turnos noturnos), gestações e pós-parto, uso de medicamentos obesogênicos (corticoides, antipsicóticos, antidepressivos tricíclicos, estabilizadores de humor, alguns contraceptivos), cessação tabágica, lesões ou cirurgias que limitam mobilidade, períodos de estresse crônico com hipercortisolismo, privação de sono crônica, menopausa (queda estrogênica com redistribuição de gordura para padrão androide). Do ponto de vista fisiopatológico, o ganho rápido de peso com expansão do tecido adiposo leva a hipertrofia e hiperplasia dos adipócitos, hipóxia tecidual, infiltração de macrófagos M1, liberação de adipocinas pró-inflamatórias (TNF-α, IL-6, resistina, visfatina), redução de adiponectina (anti-inflamatória e sensibilizadora à insulina), resistência à leptina (perda do sinal de saciedade), resistência insulínica, esteatose hepática não alcoólica, dislipidemia, hipertensão arterial, estado pró-trombótico. A medicina funcional integrativa investiga a memória metabólica: o tecido adiposo expandido mantém perfil inflamatório e disfuncional mesmo após perda de peso, fenômeno mediado por alterações epigenéticas, senescência celular, fibrose tecidual. Identificar e intervir precocemente nos picos pode prevenir cronificação metabólica.',

  patient_explanation = 'Identificar os momentos da sua vida em que você ganhou mais peso ou gordura nos ajuda a entender os gatilhos que levaram a essas mudanças. Muitas vezes, o ganho de peso coincide com eventos importantes: uma mudança de emprego para trabalho mais sedentário, um período de muito estresse, uso de certos medicamentos (como corticoides ou antidepressivos), após parar de fumar, durante ou após gestações, na menopausa, ou após lesões que limitaram sua capacidade de se exercitar. Compreender esses gatilhos é fundamental porque o ganho rápido de peso não apenas aumenta o número na balança, mas também altera profundamente o funcionamento do seu corpo: as células de gordura ficam inflamadas, liberam substâncias que pioram a resistência à insulina, dificultam o emagrecimento futuro e aumentam risco de diabetes e doenças cardiovasculares. Quando identificamos os gatilhos específicos do seu ganho de peso, podemos criar estratégias personalizadas para evitar que isso se repita, corrigir as alterações metabólicas instaladas e restaurar o equilíbrio hormonal e inflamatório que foi perdido.',

  conduct = 'Anamnese direcionada: mapear cronologicamente os períodos de ganho ponderal significativo (definir ganho >5kg em <6 meses ou >10kg em 1 ano), correlacionar com eventos de vida (casamento, divórcio, luto, mudanças ocupacionais, gestações, menopausa, lesões/cirurgias, cessação tabágica), uso de medicamentos (corticoides, psicotrópicos, contraceptivos), padrões de sono e estresse. Questionar alimentação e atividade física nesses períodos. Investigar: marcadores de inflamação crônica (PCR-us, VHS, ferritina, fibrinogênio), perfil de adipocinas (leptina, adiponectina - se disponível), função hepática (TGO, TGP, GGT, relação AST/ALT), marcadores de esteatose hepática (ultrassonografia, elastografia, índices calculados como FLI - Fatty Liver Index), perfil glicêmico-insulinêmico completo, perfil lipídico com frações aterogênicas, avaliação de disruptores endócrinos (especialmente se ganho associado a exposições ambientais/ocupacionais), cortisol (se história de estresse), perfil tiroideano, hormônios sexuais. Avaliar composição corporal atual e comparar com registros prévios (fotos, medidas, roupas). Estratégia: além da intervenção metabólica-nutricional-hormonal, abordar aspectos emocionais e comportamentais (terapia cognitivo-comportamental, mindfulness, manejo de estresse).',

  updated_at = NOW()
WHERE id = '3b9f7a1e-527e-4a4c-bc23-87c68c41ee89';

-- ============================================================
-- Item: Períodos de melhor composição corporal
-- ============================================================

UPDATE score_items
SET
  clinical_relevance = 'Identificar períodos de melhor composição corporal (maior massa muscular, menor percentual de gordura, melhor distribuição de gordura, melhor performance física e metabólica) fornece informações valiosas sobre fatores protetores e estratégias bem-sucedidas que podem ser replicadas ou adaptadas. Esses períodos frequentemente coincidem com: prática regular de exercícios (especialmente treinamento resistido combinado com aeróbico), alimentação adequada (suficiência proteica, controle glicêmico, densidade nutricional), sono reparador (7-9h/noite, boa qualidade), baixos níveis de estresse crônico, equilíbrio hormonal (testosterona, estrogênio, tireoide, cortisol, GH em níveis adequados), suporte social e emocional, senso de propósito. Do ponto de vista fisiopatológico, esses períodos caracterizam-se por: sensibilidade insulínica preservada, perfil lipídico favorável, baixa inflamação sistêmica, boa função mitocondrial, equilíbrio autonômico (predomínio parassimpático em repouso), adequada secreção de adiponectina, responsividade à leptina, função tireoidiana ótima, anabolismo muscular eficiente (síntese proteica > degradação). A medicina funcional integrativa busca recriar condições metabólicas, hormonais, nutricionais e de estilo de vida que promoveram esses períodos de saúde ótima, adaptando-as à realidade atual do paciente (idade, contexto de vida, comorbidades). Conceito de memória metabólica positiva: o corpo mantém registros epigenéticos de períodos saudáveis que podem ser reativados com estímulos adequados.',

  patient_explanation = 'Lembrar dos momentos da sua vida em que você se sentiu melhor com seu corpo - mais forte, mais magro, mais disposto, com melhor performance física - é tão importante quanto identificar os períodos ruins. Esses momentos bons nos mostram o que FUNCIONA para você especificamente. Talvez tenha sido quando você praticava algum esporte regularmente, quando tinha uma rotina de sono consistente, quando estava em um emprego menos estressante, quando tinha mais tempo para cozinhar em casa, ou quando estava em um relacionamento feliz. O interessante é que seu corpo "lembra" desses períodos em nível celular: as células guardam uma espécie de memória metabólica que pode ser reativada. Nosso objetivo é entender exatamente o que estava acontecendo na sua vida nesses períodos - padrões de alimentação, exercícios, sono, níveis de estresse, suporte social - e recriar essas condições de forma adaptada à sua realidade atual. Não se trata de voltar no tempo, mas de aplicar as lições aprendidas do passado para construir saúde no presente.',

  conduct = 'Anamnese detalhada e empática: identificar períodos de melhor composição corporal (questionar sobre fotos, roupas, performance atlética, exames laboratoriais prévios, sensação de bem-estar), mapear fatores associados: tipo e frequência de atividade física, padrão alimentar (quantidade, qualidade, timing), padrão de sono, níveis de estresse, contexto ocupacional e social, relacionamentos, senso de propósito. Investigar se havia suplementação, terapia hormonal ou outros tratamentos. Tentar resgatar exames laboratoriais desses períodos para comparação (perfil hormonal, tiroideano, metabólico, inflamatório). Avaliar barreiras atuais para replicar essas condições: limitações físicas, contexto de vida, recursos financeiros, suporte social. Co-criar com o paciente um plano realista e personalizado que incorpore elementos bem-sucedidos do passado adaptados ao presente: retomar atividade física prazerosa e viável, ajustar alimentação sem restrições extremas, priorizar sono, implementar práticas de manejo de estresse (meditação, terapia, hobbies), otimizar hormônios se necessário, corrigir deficiências nutricionais. Estabelecer metas processuais (comportamentos) além de metas de resultado (peso, composição). Follow-up frequente inicial (quinzenal a mensal) para ajustes e suporte motivacional.',

  updated_at = NOW()
WHERE id = '7b4975a7-a24d-4bbc-8d27-2dd89f9a99ad';

-- ============================================================
-- Item: Tratamentos já utilizados para modificar composição corporal
-- ============================================================

UPDATE score_items
SET
  clinical_relevance = 'O histórico de tratamentos prévios para modificação de composição corporal fornece informações essenciais sobre resposta individual a intervenções, possíveis efeitos adversos ou complicações, e resistência terapêutica. Intervenções incluem: dietas restritivas (low-carb, cetogênica, jejum intermitente, dietas da moda), farmacoterapia (sibutramina, orlistat, liraglutida, semaglutida, topiramato, bupropiona-naltrexona, anfetamínicos), terapias hormonais (tireoide, testosterona, GH, moduladores estrogênicos), cirurgia bariátrica (bypass gástrico, gastrectomia vertical, banda gástrica), procedimentos estéticos (lipoaspiração, criolipólise, radiofrequência), programas de exercício supervisionado, acompanhamento nutricional. Cada modalidade tem perfil específico de eficácia, segurança e sustentabilidade. Dietas muito restritivas podem causar efeito rebote, perda de massa magra, deficiências nutricionais, alterações hormonais (queda de leptina, T3, testosterona, aumento de cortisol, grelina), metabolismo adaptativo. Medicamentos obesogênicos têm eficácia variável e podem causar efeitos adversos (cardiovasculares, psiquiátricos, gastrintestinais). Cirurgia bariátrica é eficaz para perda ponderal substancial mas requer acompanhamento vitalício (deficiências de B12, ferro, cálcio, vitamina D, proteína, hipoglicemia reativa, dumping syndrome). A medicina funcional integrativa avalia o histórico terapêutico para identificar padrões de não-resposta ou resposta inadequada que sugiram causas metabólicas subjacentes não tratadas: resistência insulínica severa, hipotireoidismo, hipercortisolismo, hipogonadismo, deficiências nutricionais, disbiose, toxicidade, inflamação crônica.',

  patient_explanation = 'Conhecer os tratamentos que você já tentou para mudar sua composição corporal - dietas, remédios, hormônios, cirurgias, exercícios - nos ajuda a entender o que funcionou (mesmo que parcialmente ou temporariamente), o que não funcionou, e por quê. Se você fez várias dietas restritivas e sempre recuperou o peso, isso sugere que apenas restringir calorias não é suficiente - provavelmente há causas metabólicas ou hormonais que não foram tratadas. Se você usou medicamentos e teve efeitos colaterais ou pouca resposta, precisamos investigar mais profundamente. Se fez cirurgia bariátrica, há cuidados específicos vitalícios com suplementação para evitar deficiências graves. Cada tentativa anterior nos dá pistas importantes sobre como seu corpo funciona e responde. Na medicina funcional, não repetimos simplesmente os mesmos tratamentos esperando resultados diferentes - investigamos as causas raiz que impediram o sucesso anterior: problemas de tireoide, alterações hormonais, inflamação crônica, desequilíbrios intestinais, deficiências nutricionais, estresse não gerenciado. Com essa compreensão profunda, criamos um plano mais eficaz e sustentável.',

  conduct = 'Anamnese exaustiva de tentativas prévias: tipo de intervenção, duração, grau de adesão, resultados (perda ponderal, mudança em composição corporal, efeitos em exames laboratoriais), efeitos adversos, razões para descontinuação, padrão de reganho ponderal após interrupção. Para dietas: tipo (low-carb, cetogênica, jejum intermitente, restritivas em calorias, substitutos de refeição), nível de restrição, supervisão profissional, suplementação concomitante, sintomas associados (fadiga, queda de cabelo, alterações menstruais, irritabilidade). Para medicamentos: qual fármaco, dose, duração, eficácia, efeitos colaterais. Para hormônios: qual hormônio (tireoide, testosterona, GH, outros), dose, via de administração, monitoramento laboratorial, efeitos. Para cirurgia bariátrica: tipo, ano, perda ponderal máxima, reganho, complicações, adesão a suplementação pós-operatória, exames de controle de deficiências. Solicitar exames prévios se disponíveis para comparação. Investigação laboratorial atual abrangente: perfil tiroideano completo, hormônios sexuais, cortisol, insulina/glicemia/HOMA-IR, perfil lipídico, vitaminas e minerais (especialmente se cirurgia prévia: B12, ferro, ferritina, vitamina D, cálcio, zinco, cobre, vitaminas lipossolúveis), marcadores de inflamação, função hepática e renal. Avaliar composição corporal por método validado. Formular plano individualizado que corrija causas metabólicas subjacentes.',

  updated_at = NOW()
WHERE id = 'c1c9eb73-b2ac-456f-b854-ed707c817a3d';

-- ============================================================
-- Item: Histórico familiar de composição corporal
-- ============================================================

UPDATE score_items
SET
  clinical_relevance = 'O histórico familiar de composição corporal fornece informações sobre predisposição genética, ambiente compartilhado, padrões alimentares e comportamentais familiares. A obesidade tem componente hereditário significativo (heritabilidade estimada em 40-70%), mediado por múltiplos genes de pequeno efeito (polimorfismos em genes relacionados a FTO, MC4R, POMC, leptina, receptor de leptina, neuropeptídeo Y) e raros casos monogênicos (deficiência congênita de leptina, mutação em MC4R, síndrome de Prader-Willi, síndrome de Bardet-Biedl). Além da genética, famílias compartilham ambiente obesogênico: padrões alimentares (disponibilidade de alimentos ultraprocessados, tamanho de porções, cultura alimentar), nível de atividade física, sedentarismo, estresse familiar, exposição a disruptores endócrinos, microbioma (transmissão vertical mãe-filho, compartilhamento domiciliar). A programação metabólica materno-fetal é crítica: obesidade materna, diabetes gestacional, ganho ponderal excessivo na gestação, desnutrição intrauterina (paradoxalmente) predispõem a obesidade, resistência insulínica e síndrome metabólica na prole (fenômeno epigenético). História familiar de obesidade grave precoce, diabetes tipo 2, esteatose hepática, síndrome metabólica, doenças cardiovasculares aumenta risco individual e justifica rastreio e prevenção agressivos. Na medicina funcional integrativa, investigamos não apenas genética mas também transmissão intergeracional de microbioma, padrões alimentares, exposições ambientais, trauma e estresse (epigenética transgeracional). Intervenções precoces podem modificar trajetória metabólica apesar de predisposição genética.',

  patient_explanation = 'Conhecer o histórico de peso e composição corporal da sua família - pais, irmãos, avós - nos ajuda a entender se você tem predisposição genética para ganhar peso mais facilmente, onde a gordura tende a se acumular no seu corpo, e como seu metabolismo pode funcionar. Se seus pais ou vários familiares têm obesidade, diabetes ou problemas metabólicos, seu risco é maior, mas isso NÃO significa que você está destinado a ter os mesmos problemas. A genética carrega a arma, mas o ambiente e o estilo de vida puxam o gatilho. Além dos genes, famílias compartilham hábitos: o que se come em casa, o nível de atividade física, padrões de estresse, qualidade do sono, e até mesmo as bactérias intestinais (microbioma) que são parcialmente transmitidas de mãe para filho. A boa notícia é que, mesmo com predisposição genética, podemos modificar significativamente a expressão desses genes através de alimentação adequada, exercícios, controle do estresse, sono de qualidade, e correção de desequilíbrios metabólicos. Conhecer sua história familiar nos permite ser mais proativos na prevenção e tratamento.',

  conduct = 'Anamnese familiar detalhada: composição corporal de pais, irmãos, avós (obesidade, sobrepeso, magreza, distribuição de gordura - androide vs ginoide), idade de início de ganho ponderal, presença de diabetes tipo 2, resistência insulínica, síndrome metabólica, esteatose hepática, dislipidemia, hipertensão arterial, doenças cardiovasculares, síndrome dos ovários policísticos. Questionar sobre peso ao nascer do paciente e irmãos, obesidade ou diabetes gestacional materna, ganho ponderal materno nas gestações. Investigar padrões alimentares e de atividade física familiares. Se história familiar muito positiva para obesidade precoce grave, considerar rastreio genético para formas monogênicas (especialmente se obesidade grave antes dos 5 anos, hiperfagia, baixa estatura, atraso desenvolvimento, outras anomalias). Investigação laboratorial: além da avaliação metabólica completa padrão, considerar marcadores de risco cardiovascular em paciente com forte história familiar (escore de cálcio coronariano, ultrassom de carótidas, apo B, Lp(a), LDL oxidado). Avaliar composição corporal atual detalhadamente. Estratégia: prevenção agressiva com modificação de estilo de vida, monitoramento laboratorial frequente, intervenção precoce em alterações metabólicas mesmo discretas. Educação sobre epigenética: empoderar paciente com conhecimento de que pode modificar expressão genética através de escolhas saudáveis.',

  updated_at = NOW()
WHERE id = '03438548-88b3-44a7-8449-5441c26ea829';

-- ============================================================
-- SUBGRUPO: ATUAL
-- ============================================================

-- ============================================================
-- Item: Composição corporal atual (DEXA, bioimpedância, análise de pregas, etc)
-- ============================================================

UPDATE score_items
SET
  clinical_relevance = 'A avaliação objetiva da composição corporal atual é fundamental para diagnóstico, estratificação de risco metabólico e cardiovascular, planejamento terapêutico e monitoramento de intervenções. Diferentes métodos apresentam vantagens e limitações: DEXA (Dual-Energy X-ray Absorptiometry) é padrão-ouro para massa óssea, massa magra e massa gorda, incluindo distribuição regional (visceral vs subcutânea, androide vs ginoide), mas tem custo elevado e exposição à radiação (mínima); bioimpedância multifrequencial é prática, não invasiva, acessível, mas sofre influência de hidratação, ingestão alimentar recente, exercício; pletismografia por deslocamento de ar (Bod Pod) é precisa mas pouco disponível; pesagem hidrostática é padrão-ouro histórico mas impraticável; pregas cutâneas com equações preditivas são operador-dependentes mas úteis para acompanhamento; análise de fotografias com IA é emergente. Parâmetros-chave: percentual de gordura corporal (homens: ótimo <15%, normal 15-20%, sobrepeso 20-25%, obesidade >25%; mulheres: ótimo <23%, normal 23-30%, sobrepeso 30-35%, obesidade >35%), massa muscular absoluta e relativa (sarcopenia: massa apendicular/altura² <7kg/m² homens, <5.5kg/m² mulheres), gordura visceral (risco elevado >100cm² por imagem ou nível >12 em bioimpedância), distribuição androide/ginoide (razão >1.0 homens, >0.8 mulheres indica risco metabólico), ângulo de fase (marcador de integridade celular e prognóstico: ótimo >6° homens, >5.5° mulheres). Obesidade sarcopênica (alto percentual gordura + baixa massa muscular) tem pior prognóstico que obesidade isolada.',

  patient_explanation = 'Avaliar sua composição corporal atual vai muito além de apenas subir na balança. Precisamos saber exatamente QUANTO do seu peso é músculo, quanto é gordura, quanto é água, e ONDE a gordura está localizada. Existem vários métodos: o DEXA (uma espécie de raio-X especial) é o mais completo e preciso, mostrando até a gordura visceral (aquela ao redor dos órgãos, que é mais perigosa); a bioimpedância (balança que passa uma corrente elétrica leve pelo corpo) é prática e acessível; as pregas cutâneas (medidas com um aparelho chamado adipômetro) são simples mas precisam de avaliador treinado. Todos esses métodos nos mostram se você tem massa muscular adequada (importante para força, metabolismo, prevenção de fraturas), se tem gordura em excesso (especialmente na barriga), e como seu corpo está distribuindo esses componentes. Ter peso "normal" não significa necessariamente ser saudável - você pode ter pouco músculo e muita gordura (obesidade sarcopênica), o que aumenta risco de doenças. Por outro lado, alguém com peso acima do "ideal" mas com muita massa muscular e pouca gordura visceral pode ser metabolicamente saudável.',

  conduct = 'Escolher método de avaliação de composição corporal baseado em disponibilidade, custo, e precisão necessária: priorizar DEXA se disponível e viável (especialmente se suspeita de sarcopenia, osteoporose, ou necessidade de avaliar gordura visceral); bioimpedância multifrequencial (ex: InBody, Tanita profissional) como segunda opção (protocolo padronizado: jejum 4h, hidratação normal, sem exercício nas 12h prévias, bexiga vazia, evitar período pré-menstrual em mulheres); pregas cutâneas com adipômetro (Lange ou Harpenden) por avaliador experiente usando protocolo de 7 dobras (Jackson-Pollock) ou 4 dobras (Durnin-Womersley) como alternativa acessível. Registrar: peso, altura, IMC, percentual de gordura, massa gorda absoluta, massa magra absoluta, massa muscular esquelética, índice de massa muscular, gordura visceral, relação androide/ginoide, ângulo de fase (se bioimpedância), água corporal total e distribuição intra/extracelular, taxa metabólica basal estimada. Medidas antropométricas complementares: circunferências (cintura, quadril, pescoço, braço, coxa, panturrilha), relação cintura/quadril, relação cintura/altura. Correlacionar achados com exames laboratoriais (perfil glicêmico, lipídico, hormonal, inflamatório). Estabelecer metas realistas e específicas de composição (não apenas peso total). Reavaliação trimestral com mesmo método e condições padronizadas.',

  updated_at = NOW()
WHERE id = '088b4d4d-1873-45bb-8a3a-19e4463de7a5';

-- ============================================================
-- Item: Tratamentos em uso para modificar composição corporal
-- ============================================================

UPDATE score_items
SET
  clinical_relevance = 'Conhecer tratamentos atuais para modificação de composição corporal é essencial para avaliar efetividade, segurança, interações, e possíveis ajustes. Tratamentos atuais incluem: intervenções nutricionais (dietas low-carb, cetogênica, jejum intermitente, restrição calórica, dietas específicas - vegana, paleo, mediterrânea), farmacoterapia (agonistas GLP-1 como liraglutida e semaglutida, orlistat, topiramato, bupropiona-naltrexona, metformina off-label), terapias hormonais (reposição de tireoide, testosterona, estrogênio, GH), suplementação (proteínas, termogênicos, lipotrópicos, moduladores de saciedade, probióticos), programas de exercício (treino resistido, aeróbico, HIIT), terapias comportamentais (TCC, mindfulness, coaching nutricional), procedimentos estéticos (criolipólise, radiofrequência, ultrassom focado). A medicina funcional integrativa avalia a racionalidade, segurança e efetividade de cada intervenção: agonistas GLP-1 são altamente eficazes para perda ponderal (10-15%) mas caros, requerem uso contínuo, podem causar efeitos gastrintestinais e perda de massa magra se não associados a treinamento resistido e aporte proteico adequado; metformina melhora sensibilidade insulínica mas pode causar deficiência de B12; hormônios devem ser monitorizados rigorosamente (efeitos adversos cardiovasculares, hepáticos, proliferativos). Combinações racionais potencializam resultados: ex. dieta low-carb + exercício resistido + otimização hormonal + modulação de estresse. Evitar polifarmácia desnecessária, priorizar intervenções de estilo de vida como base.',

  patient_explanation = 'É importante conhecermos todos os tratamentos que você está fazendo atualmente para modificar sua composição corporal - seja dieta específica, remédios, hormônios, suplementos, exercícios supervisionados, ou procedimentos estéticos. Isso nos permite avaliar se esses tratamentos estão funcionando, se são seguros quando combinados, se precisam de ajustes, ou se estão faltando componentes importantes. Por exemplo, se você está usando medicamentos como semaglutida (Ozempic, Wegovy) que são muito eficazes para perda de peso, precisamos garantir que você também está fazendo exercícios de musculação e consumindo proteína suficiente, caso contrário pode perder muita massa muscular junto com a gordura. Se está fazendo dieta low-carb ou jejum intermitente, precisamos monitorar seus hormônios e energia. Se está em reposição hormonal (tireoide, testosterona), precisamos checar se as doses estão adequadas através de exames. Nosso objetivo é integrar todas essas ferramentas de forma inteligente e segura, priorizando sempre mudanças sustentáveis de estilo de vida como base, e usando medicamentos ou procedimentos como coadjuvantes quando realmente necessário.',

  conduct = 'Listar todos tratamentos atuais: tipo, dose/intensidade, frequência, duração de uso, prescritor, resultados obtidos até o momento (perda ponderal, mudanças em composição, efeitos em sintomas e exames), efeitos adversos. Para dietas: tipo, restrição calórica ou macronutrientes, acompanhamento profissional, grau de adesão, sintomas associados. Para medicamentos: nome, dose, via, horário, tempo de uso, eficácia (kg perdidos, mudança em %gordura), efeitos colaterais (náuseas, constipação, taquicardia, insônia, etc). Para hormônios: qual, dose, via (oral, transdérmica, injetável), monitoramento laboratorial (dosagens hormonais, função hepática, lipídios, hemograma), sintomas de excesso ou deficiência. Para suplementos: quais, doses, fundamento/evidência. Para exercícios: tipo, frequência, duração, intensidade, supervisão. Solicitar exames atualizados: se em uso de agonistas GLP-1 (glicemia, HbA1c, amilase, lipase, função renal), se hormônios (níveis hormonais, função hepática, PSA em homens em testosterona, densidade mamária em mulheres em estrogênio), se estimulantes (ECG, PA, frequência cardíaca). Avaliar necessidade de ajustes: otimizar doses, adicionar intervenções complementares, descontinuar tratamentos ineficazes ou com efeitos adversos. Educação sobre expectativas realistas e sustentabilidade a longo prazo.',

  updated_at = NOW()
WHERE id = '2579198d-65b8-4cff-9970-7c437076adc7';

-- ============================================================
-- Item: Grau de satisfação com composição atual e objetivos do paciente
-- ============================================================

UPDATE score_items
SET
  clinical_relevance = 'Avaliar o grau de satisfação do paciente com sua composição corporal atual e seus objetivos é fundamental para co-criar um plano terapêutico alinhado, realista e centrado no paciente. A insatisfação corporal é prevalente, afetando qualidade de vida, autoestima, relacionamentos, e aderência a tratamentos. Fatores influenciam percepção corporal: padrões culturais de beleza (frequentemente irrealistas e inalcançáveis), mídias sociais (comparação social, imagens editadas), histórico de bullying ou comentários depreciativos, transtornos de imagem corporal (dismorfismo corporal, transtornos alimentares - anorexia, bulimia, compulsão alimentar), ansiedade, depressão. Há dissociação frequente entre objetivos estéticos e objetivos de saúde: pacientes podem buscar corpo "magro" mesmo com composição corporal saudável, ou priorizar estética sobre saúde metabólica. Na medicina funcional integrativa, valorizamos os objetivos do paciente mas educamos sobre: composição corporal saudável nem sempre corresponde a padrões estéticos comerciais; importância de priorizar massa muscular, não apenas perda ponderal; perigos de metas irrealistas (percentuais de gordura muito baixos comprometem função hormonal, imunidade, fertilidade); sustentabilidade a longo prazo vs resultados rápidos insustentáveis. Objetivos devem ser SMART (específicos, mensuráveis, atingíveis, relevantes, temporais): ex. "ganhar 3kg de massa muscular em 6 meses" ao invés de "ficar magro". Abordar aspectos psicológicos: se insatisfação corporal severa ou transtorno alimentar, encaminhar para psicoterapia especializada concomitante.',

  patient_explanation = 'É muito importante conversarmos sobre como você se sente em relação ao seu corpo hoje e o que você gostaria de alcançar. Seus objetivos são válidos e importantes, mas precisamos alinhá-los com o que é saudável, realista e sustentável para VOCÊ especificamente - considerando sua idade, genética, histórico, contexto de vida, e saúde metabólica. Às vezes, os padrões de corpo "ideal" que vemos nas redes sociais ou revistas são irrealistas (muitas vezes editados digitalmente) ou até insalubres (percentuais de gordura muito baixos comprometem hormônios, ciclos menstruais, fertilidade, imunidade). Nosso objetivo principal é melhorar sua SAÚDE metabólica e sua FUNCIONALIDADE - ter energia, força, disposição, hormônios equilibrados, exames bons, qualidade de vida - e isso nem sempre se parece com as imagens comercializadas. Muitas vezes, focar em GANHAR massa muscular (mesmo que o peso suba um pouco) é mais importante do que simplesmente perder peso. Vamos trabalhar juntos para definir objetivos específicos, mensuráveis e alcançáveis, e também para melhorar sua relação com seu corpo, celebrando conquistas de saúde além da aparência.',

  conduct = 'Avaliação empática e sem julgamento: perguntar ao paciente como ele/ela se sente em relação ao corpo atual (escala 0-10 de satisfação), o que especificamente gostaria de mudar (peso total, percentual de gordura, massa muscular, distribuição de gordura, definição muscular, performance física), por que esses objetivos são importantes (saúde, estética, performance, autoestima, relacionamentos), se há pressão externa (parceiro, família, trabalho, mídia). Investigar histórico de imagem corporal: bullying, comentários depreciativos, comparação social, uso de mídias sociais. Rastrear transtornos alimentares (questionários EAT-26, BITE) e dismorfismo corporal. Avaliar se objetivos são realistas e saudáveis: percentuais de gordura saudáveis (homens 12-20%, mulheres 20-30%), composição alcançável dado genética e contexto de vida, sustentabilidade a longo prazo. Educação: mostrar imagens de composições corporais saudáveis vs comerciais, explicar importância de massa muscular, riscos de gordura corporal muito baixa (amenorreia, osteoporose, imunodeficiência em mulheres; hipogonadismo, fadiga em homens). Co-criar objetivos SMART alinhados com saúde e valores do paciente. Se insatisfação corporal severa, pensamentos obsessivos, comportamentos alimentares disfuncionais, sintomas depressivos/ansiosos, encaminhar para psicoterapia (TCC, terapia de aceitação e compromisso). Monitorar não apenas mudanças físicas mas também percepção corporal e qualidade de vida ao longo do tratamento.',

  updated_at = NOW()
WHERE id = 'f836753e-9e45-48f5-a54c-298195ff0588';

-- Linkar artigos científicos relevantes aos primeiros 8 items
INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, si.id
FROM articles a
CROSS JOIN (
  SELECT id FROM score_items WHERE id IN (
    'ac04ab06-bdc7-4959-a33d-32f3646c1a87',
    '3b9f7a1e-527e-4a4c-bc23-87c68c41ee89',
    '7b4975a7-a24d-4bbc-8d27-2dd89f9a99ad',
    'c1c9eb73-b2ac-456f-b854-ed707c817a3d',
    '03438548-88b3-44a7-8449-5441c26ea829',
    '088b4d4d-1873-45bb-8a3a-19e4463de7a5',
    '2579198d-65b8-4cff-9970-7c437076adc7',
    'f836753e-9e45-48f5-a54c-298195ff0588'
  )
) si
WHERE a.title ILIKE '%emagrecimento%'
   OR a.title ILIKE '%metabol%'
   OR a.title ILIKE '%dieta%'
   OR a.title ILIKE '%hormônio%'
   OR a.title ILIKE '%exercício%'
LIMIT 100
ON CONFLICT DO NOTHING;

