#!/bin/bash

# Batch 20 Items - Exames Laboratoriais
# Token JWT
TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTliMzk2OC0zNTI4LTQ2YTUtYWRkNi03ODYyNmQ1NGJmMTgiLCJlbWFpbCI6ImltcG9ydEBwbGVueWEuY29tIiwicm9sZSI6ImFkbWluIiwiaXNzIjoicGxlbnlhLWVtciIsImV4cCI6MTc2OTM4OTA0NywiaWF0IjoxNzY5Mzg4MTQ3fQ.wmqu6EzmvcXjTnAif0RplMgybsz1i6FKtlyIHr68YIg"

API_URL="http://localhost:3001/api/v1"

# Item 1: HIV 1+2
echo "Processing: HIV 1+2"
curl -X PUT "${API_URL}/score-items/000b74df-0fbb-4aae-ad9f-a52e55c2e311" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{
    "clinicalRelevance": "O teste HIV 1+2 de 4ª geração é um ensaio combinado que detecta simultaneamente anticorpos anti-HIV-1 (grupos M e O), anticorpos anti-HIV-2 e o antígeno p24 do HIV-1, permitindo diagnóstico precoce com janela imunológica reduzida de 18-45 dias pós-exposição (versus 3 meses para testes de 3ª geração). Na medicina funcional integrativa, um resultado não-reagente indica ausência de infecção detectável pelo HIV, sendo considerado ótimo do ponto de vista de saúde imunológica. O teste funciona através de algoritmo diagnóstico de 3 etapas recomendado pelo CDC (2024): Passo 1 - Teste Ag/Ab combo; se reagente, Passo 2 - Teste de diferenciação HIV-1/2; se indeterminado, Passo 3 - HIV-1 RNA NAT quantitativo. Um resultado reagente no teste inicial NÃO confirma infecção, mas indica necessidade urgente de testes confirmatórios, pois pode representar infecção aguda (antígeno p24 positivo antes da soroconversão), infecção estabelecida ou, raramente, falso positivo. Valores de referência: Não-reagente = ótimo; Reagente = crítico, necessita algoritmo completo. A detecção precoce é fundamental pois o início imediato de TARV (terapia antirretroviral) melhora drasticamente o prognóstico, com expectativa de vida normal e prevenção de transmissão (carga viral indetectável = intransmissível, conceito U=U).",
    "patientExplanation": "O teste HIV 1+2 detecta se você teve contato com o vírus da imunodeficiência humana (HIV), que causa a AIDS. É um exame de sangue moderno de 4ª geração que consegue identificar a infecção muito cedo, cerca de 18 a 45 dias após uma possível exposição. Um resultado não-reagente (negativo) significa que você não tem HIV detectável no sangue, o que é ótimo. Um resultado reagente (positivo) NÃO confirma automaticamente que você tem HIV - significa apenas que outros exames mais específicos precisam ser feitos para confirmar ou descartar a infecção. Caso seja confirmado, saiba que hoje existem tratamentos muito eficazes que permitem vida normal e longa. Se você teve uma situação de risco recente (menos de 45 dias), pode ser necessário repetir o exame mesmo com resultado negativo, pois o vírus pode ainda não estar detectável. O exame é confidencial e fundamental para diagnóstico precoce e início rápido de tratamento quando necessário.",
    "conduct": "Resultado Não-Reagente: Indica ausência de infecção detectável. Conduta - manter prevenção com práticas seguras (uso de preservativos, PrEP se exposição frequente). Se exposição recente (<45 dias), repetir após janela imunológica completa. Para profissionais de saúde e populações de risco, manter rastreamento periódico conforme recomendações. Resultado Reagente (Positivo): Conduta URGENTE - (1) Encaminhar imediatamente para infectologista; (2) Iniciar algoritmo CDC 3 etapas: teste de diferenciação HIV-1/2 e HIV-1 RNA NAT; (3) NÃO aguardar resultados confirmatórios para encaminhamento; (4) Oferecer suporte emocional e aconselhamento, pois diagnóstico pode gerar ansiedade; (5) Avaliar parceiros sexuais e contatos de risco; (6) Se confirmado, iniciar TARV o mais rápido possível (preferencialmente dentro de dias a semanas); (7) Solicitar exames complementares: CD4, carga viral, sorologias para HBV/HCV, PPD, VDRL; (8) Avaliação de comorbidades e saúde mental. Na medicina funcional, após diagnóstico: suporte imunológico com nutrição otimizada, suplementação individualizada (vitamina D, ômega-3, probióticos), manejo de inflamação crônica, saúde mitocondrial e intestinal. Monitorar regularmente resposta à TARV, adesão ao tratamento e qualidade de vida."
  }'

# Item 2: Rotina de urina (EAS)
echo "Processing: Rotina de urina"
curl -X PUT "${API_URL}/score-items/0033570f-ff62-4453-824d-3c789231a80f" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{
    "clinicalRelevance": "O Exame de Urina Tipo 1 (EAS - Elementos Anormais e Sedimentoscopia) é um dos exames mais solicitados na prática clínica, fornecendo avaliação abrangente da função renal, metabólica e infecciosa através de 21 parâmetros divididos em: (1) Exame Físico - cor (amarelo-palha ideal) e aspecto (límpido/cristalino ótimo); (2) Exame Químico por fita reagente - densidade (1.015-1.025 ideal), pH (5.5-6.5 funcional ideal), proteínas (negativo), glicose (negativo), cetonas (negativo/traços em jejum ou dieta cetogênica), bilirrubina (negativo), urobilinogênio (normal <1 mg/dL), sangue oculto (negativo), nitrito (negativo - marcador de bacteriúria), leucócito esterase (negativo); (3) Sedimentoscopia - hemácias (<3/campo), leucócitos (<5/campo homens, <10 mulheres), células epiteliais (raras), cilindros hialinos (0-2/campo), cilindros patológicos (ausentes), cristais patológicos (ausentes), bactérias (ausentes/raras), leveduras (ausentes), muco (ausente/raro). Na medicina funcional, valores ideais são mais estritos que laboratório: densidade 1.015-1.020 indica hidratação ótima; pH levemente ácido (5.5-6.5) reflete dieta anti-inflamatória; ausência completa de elementos anormais é o objetivo. Alterações comuns: (1) Proteinúria persistente indica lesão glomerular/tubular; (2) Glicosúria com glicemia normal sugere baixo limiar renal ou deficiência de SGLT2; (3) Cetonúria em jejum/low-carb é fisiológica; (4) Hematúria microscópica pode indicar desde ITU até câncer; (5) Piúria + nitrito positivo = ITU bacteriana; (6) Cilindros granulosos/hemáticos = glomerulonefrite; (7) Cristais de oxalato = risco de nefrolitíase.",
    "patientExplanation": "O exame de urina tipo 1 (também chamado EAS) é um dos exames mais completos e úteis da medicina. Através de uma simples amostra de urina, conseguimos avaliar se seus rins estão funcionando bem, se há infecção urinária, se você está bem hidratado, e até detectar sinais de diabetes ou problemas no fígado. O exame avalia três aspectos: a aparência da urina (cor e se está turva), análise química com uma fita especial que muda de cor (detecta proteínas, açúcar, sangue, bactérias), e exame microscópico para ver células e cristais invisíveis a olho nu. Uma urina ideal é amarelo-palha clara, límpida como água, sem proteínas, sem açúcar, sem sangue e sem sinais de infecção. Urina muito escura pode indicar desidratação; muito clara pode significar que você está bebendo muita água. Proteínas na urina podem ser sinal de que os rins não estão filtrando corretamente. Glicose na urina pode indicar diabetes descompensado. Sangue microscópico invisível pode ter várias causas e precisa investigação. O exame é simples, não invasivo e fornece informações valiosas sobre sua saúde geral.",
    "conduct": "Resultado Normal (todos parâmetros ótimos): Conduta - manter hidratação adequada (1.5-2L/dia água), dieta balanceada, higiene adequada. Repetir anualmente como rastreamento preventivo. Proteinúria Persistente (proteínas ≥1+ ou ≥30 mg/dL em 2+ amostras): Conduta - quantificar com proteinúria de 24h ou relação proteína/creatinina urinária; investigar com US rins, função renal, perfil metabólico; encaminhar nefrologista se persistente ou valores elevados; avaliar diabetes, hipertensão, uso de AINEs. Hematúria Microscópica (>3 hemácias/campo): Conduta - descartar contaminação menstrual, trauma, exercício intenso; repetir em 2-4 semanas; se persistente, investigar com citologia urinária, US rins/vias urinárias, cistoscopia se >40 anos ou fatores de risco; encaminhar urologista/nefrologista. Leucocitúria + Nitrito Positivo (ITU): Conduta - solicitar urocultura com antibiograma; iniciar antibioticoterapia empírica se sintomático (ciprofloxacino, nitrofurantoína); hidratar intensamente; reavaliação em 2-3 dias; após tratamento, avaliar fatores predisponentes (anatomia, higiene, imunidade). Glicosúria: Conduta - medir glicemia de jejum e HbA1c; se glicemia normal, considerar baixo limiar renal (benigno) ou deficiência SGLT2; se glicemia elevada, investigar diabetes. Cetonúria: Conduta - avaliar contexto (jejum, dieta cetogênica, diabetes); se diabético com cetose, avaliar cetoacidose diabética (emergência); se contexto fisiológico, não requer intervenção. Cristalúria (oxalato, ácido úrico): Conduta - aumentar hidratação, ajustar dieta (reduzir oxalato se oxalato de cálcio, alcalinizar urina se ácido úrico), avaliar risco de litíase renal."
  }'

echo "Batch processing completed for first 2 items"
