#!/bin/bash

TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTliMzk2OC0zNTI4LTQ2YTUtYWRkNi03ODYyNmQ1NGJmMTgiLCJlbWFpbCI6ImltcG9ydEBwbGVueWEuY29tIiwicm9sZSI6ImFkbWluIiwiaXNzIjoicGxlbnlhLWVtciIsImV4cCI6MTc2OTQ4NTQyNiwiaWF0IjoxNzY5NDg0NTI2fQ.VWVPjoeG7sCl9DLK4ogKYdzxC8nIqmDz_DjxWZHhrlI"

# Item 1: ad40c276-dabd-4ef6-8f6e-66db64655c69 - 25-hidroxivitamina D
curl -X PUT "http://localhost:3001/api/v1/score-items/ad40c276-dabd-4ef6-8f6e-66db64655c69" \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{
    "clinicalRelevance": "A 25-hidroxivitamina D [25(OH)D] é a principal forma circulante da vitamina D e o melhor marcador do status de vitamina D corporal, refletindo tanto a síntese cutânea quanto a ingestão dietética. Na medicina funcional integrativa, valores ideais são significativamente superiores às referências laboratoriais convencionais que consideram >20 ng/mL como \"suficiente\". A faixa funcional ótima situa-se entre 40-70 ng/mL, com algumas evidências sugerindo 50-80 ng/mL para maximização da saúde óssea, função imunológica, prevenção de autoimunidade, regulação hormonal e proteção cardiovascular.\n\nA vitamina D atua como hormônio pleiotrópico com receptores (VDR) presentes em virtualmente todos os tecidos: ossos, sistema imune, cérebro, coração, pâncreas, próstata, mama. Pesquisas atualizadas demonstram que níveis acima de 40 ng/mL estão associados à redução da mortalidade por todas as causas, enquanto valores de 55 ng/mL ou superiores correlacionam-se com redução do risco de câncer. A Endocrine Society define deficiência como valores <30 ng/mL e recomenda faixa preferencial de 40-60 ng/mL.\n\nNíveis subótimos (<40 ng/mL) estão associados a: maior risco de osteoporose/fraturas, infecções respiratórias recorrentes, doenças autoimunes (esclerose múltipla, diabetes tipo 1, tireoidite de Hashimoto, artrite reumatoide), câncer (mama, cólon, próstata), doenças cardiovasculares, resistência à insulina, síndrome metabólica, depressão e declínio cognitivo. A deficiência funcional é epidêmica globalmente, afetando >80% da população em algumas regiões, devido a: exposição solar inadequada (uso de protetor solar, trabalho indoor), latitude elevada, pigmentação da pele (melanina reduz síntese cutânea), obesidade (sequestro em tecido adiposo), idade avançada (redução da síntese), doenças de má absorção e uso de medicamentos (anticonvulsivantes, glicocorticoides).",
    "patientExplanation": "A vitamina D é na verdade um hormônio fundamental produzido pelo seu corpo quando a pele recebe luz solar. Ela é essencial para muito mais do que apenas ossos fortes: fortalece o sistema imunológico (protegendo contra infecções e doenças autoimunes), regula o humor (deficiência está associada à depressão), ajuda a prevenir câncer, diabetes e doenças do coração.\n\nO exame 25-hidroxivitamina D mede seus estoques corporais. A maioria das pessoas tem níveis insuficientes devido ao uso de protetor solar, trabalho em ambientes fechados e estilo de vida moderno. Valores abaixo de 40 ng/mL indicam que você não está aproveitando todos os benefícios preventivos da vitamina D. Níveis muito baixos (<30 ng/mL) podem causar fadiga, dores musculares, maior suscetibilidade a gripes/resfriados e, a longo prazo, osteoporose e outras condições crônicas.",
    "conduct": "Solicitar 25(OH)D em todos os pacientes na avaliação inicial e repetir a cada 3-6 meses durante reposição, depois anualmente para manutenção. Meta funcional: 40-70 ng/mL (algumas referências mais agressivas sugerem 50-80 ng/mL para prevenção de câncer e autoimunidade).\n\nIntervenções:\n1. Exposição solar: 15-30 minutos/dia (braços/pernas expostos, horários 10h-15h, sem protetor solar), respeitando tom de pele e risco de câncer cutâneo. Pele clara necessita menos tempo; pele escura necessita exposição mais prolongada.\n\n2. Suplementação com vitamina D3 (colecalciferol - forma superior à D2):\n   - Deficiência (<30 ng/mL): dose de ataque 10.000 UI/dia por 8-12 semanas, depois manutenção\n   - Insuficiência (30-40 ng/mL): 5.000-10.000 UI/dia\n   - Manutenção (>40 ng/mL): 2.000-5.000 UI/dia\n   - Ajustar conforme resposta individual (monitorar a cada 3-6 meses)\n\n3. Cofatores essenciais:\n   - Magnésio 400-600 mg/dia (necessário para ativação da vitamina D)\n   - Vitamina K2 (MK-7) 180-360 mcg/dia (direciona cálcio aos ossos, prevenindo calcificação arterial)\n   - Zinco e boro também podem otimizar metabolismo da vitamina D\n\n4. Alimentos (quantidades insuficientes isoladamente): peixes gordos (salmão selvagem, sardinha, cavala), gema de ovo, cogumelos expostos ao sol, laticínios fortificados.\n\n5. Monitoramento:\n   - Acompanhar cálcio sérico e PTH se doses muito elevadas\n   - Toxicidade é rara (<1% com doses <10.000 UI/dia), geralmente ocorre apenas com níveis >150 ng/mL\n   - Se hipercalcemia, reduzir dose imediatamente\n   - Se PTH elevado apesar de vitamina D adequada, investigar hiperparatireoidismo primário ou deficiência de magnésio"
  }'

echo "Item 1 processado"
sleep 1
