#!/bin/bash

TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTliMzk2OC0zNTI4LTQ2YTUtYWRkNi03ODYyNmQ1NGJmMTgiLCJlbWFpbCI6ImltcG9ydEBwbGVueWEuY29tIiwicm9sZSI6ImFkbWluIiwiaXNzIjoicGxlbnlhLWVtciIsImV4cCI6MTc2OTM5NDY4MiwiaWF0IjoxNzY5MzkzNzgyfQ.lxNqy-W_YTJjPXS12eDDgI0iaJdtMXs19o1ZL_xK0WQ"
API_URL="http://localhost:3001/api/v1"

# Item 1: Estradiol - Mulheres Pós-Menopausa (Sem TRH)
curl -X PUT "${API_URL}/score-items/0766887c-73fd-4c8e-89d7-becfd6d6a375" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{
    "clinicalRelevance": "O estradiol é o principal hormônio estrogênico produzido pelos ovários durante a idade reprodutiva. Após a menopausa, os níveis caem drasticamente para valores típicos de 2,7-7,4 pg/mL (9,8-27,1 pmol/L), resultado da cessação da função ovariana. Em medicina funcional, níveis extremamente baixos (<5 pg/mL) podem estar associados a sintomas vasomotores intensos, perda acelerada de massa óssea (osteoporose), disfunção cognitiva, atrofia urogenital e aumento do risco cardiovascular. A deficiência severa impacta negativamente a qualidade de vida, função sexual, saúde óssea e metabolismo lipídico. Mulheres sem terapia de reposição hormonal (TRH) com sintomas menopausais significativos e níveis <5 pg/mL podem se beneficiar de avaliação para TRH, considerando riscos e benefícios individuais. A dosagem de estradiol é fundamental para confirmar status menopáusico, investigar sintomas atípicos e avaliar função ovariana residual.",
    "patientExplanation": "O estradiol é o principal hormônio feminino produzido pelos ovários. Após a menopausa, os níveis diminuem significativamente (valores normais: 2,7-7,4 pg/mL) porque os ovários param de produzir hormônios. Níveis muito baixos podem causar ondas de calor, suores noturnos, ressecamento vaginal, alterações de humor, insônia, perda de memória e enfraquecimento dos ossos. Este exame confirma se você está na menopausa e ajuda a avaliar se os sintomas que você sente estão relacionados à queda hormonal. Se os níveis estiverem muito baixos e você tiver sintomas importantes, pode ser considerada terapia de reposição hormonal após avaliação médica cuidadosa.",
    "conduct": "**Interpretação:** Níveis <2 pg/mL confirmam menopausa; 2-7,4 pg/mL são esperados sem TRH; >10 pg/mL podem indicar função ovariana residual ou fontes extra-ovarianas. **Conduta para níveis baixos com sintomas:** Avaliar indicação de TRH (estradiol transdérmico alvo: 60-150 pg/mL para alívio sintomático e proteção óssea); considerar contraindicações (câncer de mama, tromboembolismo, doença hepática). **Intervenções não-hormonais:** Fitoestrógenos (isoflavonas de soja 40-80 mg/dia), cimicífuga racemosa, exercícios de impacto para saúde óssea, suplementação de cálcio (1.200 mg/dia) e vitamina D (2.000-4.000 UI/dia), dieta rica em ômega-3. **Monitoramento:** Se iniciar TRH, dosar estradiol após 3-6 meses para ajuste de dose; mamografia e densitometria óssea anuais; reavaliar necessidade de TRH anualmente."
  }'

echo "Item 1 processado: Estradiol Pós-Menopausa"

# Item 2: pH Urinário
curl -X PUT "${API_URL}/score-items/07fdac8b-3b4b-4e89-bace-e71b69f73aaa" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{
    "clinicalRelevance": "O pH urinário reflete o equilíbrio ácido-base renal e sistêmico, sendo um indicador dinâmico da capacidade dos rins de excretar íons hidrogênio. A faixa normal é 4,5-8,0, com valores típicos entre 5,5-6,5 em condições basais. Em medicina funcional, o pH urinário persistentemente ácido (<5,5) pode indicar acidose metabólica crônica de baixo grau, dieta hiperproteica, cetose, diabetes mellitus descompensado ou acidose tubular renal. Por outro lado, pH alcalino (>7,0) pode sugerir infecção urinária por bactérias produtoras de urease (Proteus, Klebsiella), alcalose metabólica, dieta vegetariana estrita ou uso de inibidores da anidrase carbônica. O rim normal deve acidificar a urina (<5,0) durante acidose metabólica; pH >5,5 na presença de acidemia sugere defeito na acidificação (acidose tubular renal tipo I). A monitorização do pH urinário é útil para prevenir nefrolitíase (cálculos de ácido úrico em pH <5,5; cálculos de fosfato em pH >7,0) e avaliar resposta a intervenções dietéticas alcalinizantes.",
    "patientExplanation": "O pH urinário mede se sua urina está mais ácida ou alcalina, variando de 4,5 a 8,0 (valores normais: 5,5-6,5). A alimentação influencia muito: dietas ricas em proteínas animais tornam a urina ácida, enquanto vegetais e frutas a tornam alcalina. pH muito ácido (<5,5) pode indicar excesso de proteínas, diabetes descontrolado ou problemas renais, e favorece pedras nos rins de ácido úrico. pH muito alcalino (>7,0) pode sugerir infecção urinária ou dieta muito alcalina. Este exame ajuda a avaliar seu equilíbrio metabólico, risco de pedras nos rins e função renal.",
    "conduct": "**Interpretação:** pH <5,5 (urina ácida) - investigar acidose metabólica, dieta, cetose; pH 5,5-6,5 (normal); pH >7,0 (alcalina) - descartar infecção urinária (urocultura), avaliar dieta. **Para pH ácido persistente (<5,5):** Aumentar consumo de vegetais, frutas e verduras (alvo: 7-9 porções/dia); reduzir proteínas animais; suplementar citrato de potássio 20-40 mEq/dia (alcalinizante) se risco de nefrolitíase; corrigir diabetes se glicemia elevada. **Para pH alcalino (>7,0):** Solicitar urocultura para descartar infecção; se negativa, avaliar dieta e uso de medicamentos; reduzir excesso de alimentos alcalinos se necessário. **Monitoramento:** Repetir pH urinário após 4-6 semanas de intervenção dietética; acompanhar com gasometria venosa se suspeita de distúrbio ácido-base sistêmico; avaliação nefrológica se acidose tubular renal."
  }'

echo "Item 2 processado: pH Urinário"

# Item 3: pO2 Venoso
curl -X PUT "${API_URL}/score-items/0899a7f5-e9d5-4adf-a825-4374ecc3292f" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{
    "clinicalRelevance": "A pressão parcial de oxigênio venoso (PvO2) mede a tensão de oxigênio no sangue venoso, refletindo a oferta de oxigênio aos tecidos após extração metabólica. Valores normais situam-se entre 35-45 mmHg. A PvO2 é um indicador crucial de oxigenação tecidual e balanço entre oferta e consumo de oxigênio. Em medicina funcional, PvO2 <35 mmHg indica hipoxia tecidual, podendo resultar de baixo débito cardíaco, anemia severa, hipoxemia arterial ou aumento do consumo de oxigênio (febre, sepse, tireotoxicose). A hipoxia tecidual prolongada leva à produção de lactato (acidose lática), disfunção mitocondrial e dano celular. PvO2 reduzida é particularmente crítica em pacientes com insuficiência cardíaca, hipertensão pulmonar e doenças críticas. O monitoramento da saturação venosa de oxigênio (SvO2), derivada da PvO2, tem valor prognóstico em pacientes com hipertensão pulmonar (PvO2 <35 mmHg associa-se a pior prognóstico). A interpretação deve considerar o contexto clínico, incluindo níveis de hemoglobina, débito cardíaco e demanda metabólica.",
    "patientExplanation": "A PvO2 (pressão de oxigênio no sangue venoso) mede quanto oxigênio sobra no sangue depois que os tecidos do corpo o utilizaram. Valores normais são 35-45 mmHg. Níveis baixos (<35 mmHg) indicam que seus tecidos estão retirando muito oxigênio do sangue, o que pode acontecer por falta de oxigênio chegando aos órgãos (problema cardíaco, pulmonar ou anemia) ou porque o corpo está consumindo oxigênio demais (febre, infecções graves). Este exame ajuda a avaliar se seus órgãos estão recebendo oxigênio suficiente e é especialmente importante em doenças cardíacas e pulmonares graves.",
    "conduct": "**Interpretação:** PvO2 35-45 mmHg (normal); <35 mmHg (hipoxia tecidual) - investigar causa; >45 mmHg (aumento de oferta ou redução de consumo). **Para PvO2 baixa (<35 mmHg):** Avaliar hemoglobina (tratar anemia se Hb <10 g/dL com ferro, B12, folato); otimizar função cardíaca (avaliar fração de ejeção, considerar inotrópicos se insuficiência cardíaca); investigar hipoxemia arterial (gasometria arterial, oxigenoterapia se PaO2 <60 mmHg); tratar causas de hipermetabolismo (febre, sepse, tireotoxicose). **Suporte nutricional:** Coenzima Q10 100-300 mg/dia (função mitocondrial), L-carnitina 1-2 g/dia, antioxidantes (vitamina C 500-1.000 mg/dia, vitamina E 400 UI/dia). **Monitoramento:** Gasometria venosa seriada em pacientes críticos; SvO2 contínua em UTI se disponível; ecocardiograma e teste de caminhada de 6 minutos em hipertensão pulmonar."
  }'

echo "Item 3 processado: pO2 Venoso"

# Item 4: Potássio
curl -X PUT "${API_URL}/score-items/08afead7-7ce4-4435-93d0-1b0147ed4131" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{
    "clinicalRelevance": "O potássio é o principal cátion intracelular, essencial para função neuromuscular, contratilidade cardíaca, equilíbrio ácido-base e regulação da pressão arterial. A faixa de referência é 3,5-5,0 mEq/L, mas em medicina funcional e cardiologia preventiva, valores ótimos situam-se entre 4,0-5,0 mEq/L, especialmente em pacientes com doenças cardiovasculares. Estudos recentes (POTCAST trial) demonstram que manter potássio em 4,5-5,0 mEq/L reduz arritmias ventriculares e mortalidade cardiovascular em 24% comparado ao manejo padrão. Hipocalemia (<3,5 mEq/L) aumenta risco de arritmias, fraqueza muscular, constipação, rabdomiólise e nefropatia crônica. Em pacientes com insuficiência cardíaca, potássio <4,1 mEq/L é preditor independente de morte súbita. Hipercalemia (>5,5 mEq/L) causa arritmias letais, especialmente em insuficiência renal ou uso de IECA/BRA. A reposição agressiva de potássio (alvos 4,5-5,0 mEq/L) beneficia pacientes cardiopatas, hipertensos e usuários de diuréticos.",
    "patientExplanation": "O potássio é um mineral essencial para o coração, músculos e nervos. Níveis normais estão entre 3,5-5,0 mEq/L, mas valores ideais para saúde cardiovascular são 4,0-5,0 mEq/L. Potássio baixo (<3,5 mEq/L) pode causar fraqueza muscular, cãibras, batimentos cardíacos irregulares, constipação e fadiga. Potássio alto (>5,5 mEq/L) é perigoso, podendo causar arritmias graves. Níveis na faixa alta-normal (4,5-5,0 mEq/L) protegem o coração contra arritmias e morte súbita, especialmente se você tem problemas cardíacos, pressão alta ou usa diuréticos. Alimentação rica em vegetais, frutas e legumes ajuda a manter bons níveis de potássio.",
    "conduct": "**Interpretação:** <3,5 mEq/L (hipocalemia) - repor urgente; 3,5-4,0 mEq/L (baixo-normal) - otimizar em cardiopatas; 4,0-5,0 mEq/L (ótimo para saúde cardiovascular); >5,5 mEq/L (hipercalemia) - investigar causa e tratar. **Para hipocalemia (<4,0 mEq/L em cardiopatas):** Suplementação oral de cloreto de potássio 20-40 mEq/dia (ajustar conforme resposta); aumentar alimentos ricos em potássio (banana, laranja, batata-doce, abacate, espinafre, feijão - alvo: 4.700 mg/dia); considerar antagonistas de aldosterona (espironolactona 25-50 mg/dia) se hipertensão ou insuficiência cardíaca. **Para hipercalemia (>5,5 mEq/L):** Suspender suplementos de potássio e IECA/BRA temporariamente; resina quelante (sorcal) se K >6,0 mEq/L; hemodiálise se K >7,0 mEq/L ou arritmias. **Monitoramento:** Dosar potássio semanalmente durante reposição; ECG se K <3,0 ou >6,0 mEq/L; ajustar meta para 4,5-5,0 mEq/L em alto risco cardiovascular; monitorar função renal (creatinina) concomitantemente."
  }'

echo "Item 4 processado: Potássio"

# Item 5: pH Venoso
curl -X PUT "${API_URL}/score-items/08c5d89b-976b-437b-8771-c6066d46d1db" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{
    "clinicalRelevance": "O pH venoso mede a acidez ou alcalinidade do sangue venoso, refletindo o equilíbrio ácido-base sistêmico. A faixa normal é 7,32-7,42 (ligeiramente mais baixo que o pH arterial 7,35-7,45 devido ao CO2 tecidual). O pH venoso é um indicador sensível de distúrbios metabólicos e respiratórios, sendo menos invasivo que gasometria arterial. Em medicina funcional, pH <7,32 indica acidose (metabólica por excesso de ácidos/perda de bicarbonato ou respiratória por retenção de CO2), enquanto pH >7,42 sugere alcalose (metabólica por perda de ácidos/excesso de bicarbonato ou respiratória por hiperventilação). Acidose metabólica crônica de baixo grau está associada a perda de massa muscular, desmineralização óssea, resistência à insulina e progressão de doença renal crônica. A interpretação requer análise conjunta de pCO2, HCO3 e ânion gap. Distúrbios ácido-base afetam função enzimática, transporte de oxigênio, contratilidade cardíaca e função neurológica.",
    "patientExplanation": "O pH venoso mede se seu sangue está ácido ou alcalino (valores normais: 7,32-7,42). O corpo mantém este equilíbrio rigorosamente para que células e órgãos funcionem bem. pH baixo (<7,32) indica acidose, que pode ser causada por diabetes descontrolado, diarreia severa, insuficiência renal, problemas pulmonares ou exercício intenso. pH alto (>7,42) indica alcalose, que pode resultar de vômitos, uso excessivo de antiácidos ou hiperventilação. Desequilíbrios graves afetam respiração, coração, músculos e consciência. Este exame ajuda a diagnosticar e monitorar distúrbios metabólicos e respiratórios.",
    "conduct": "**Interpretação:** pH 7,32-7,42 (normal); <7,32 (acidose) - classificar como metabólica (HCO3 baixo) ou respiratória (pCO2 alto); >7,42 (alcalose) - classificar como metabólica (HCO3 alto) ou respiratória (pCO2 baixo). **Para acidose metabólica (pH <7,32, HCO3 <22 mEq/L):** Calcular ânion gap (Na - Cl - HCO3); investigar cetoacidose diabética (glicemia, cetonas), acidose láctica (lactato), insuficiência renal (ureia, creatinina), intoxicações; tratar causa base; bicarbonato de sódio IV se pH <7,1 e HCO3 <10 mEq/L. **Para alcalose metabólica (pH >7,42, HCO3 >28 mEq/L):** Investigar vômitos, uso de diuréticos, hiperaldosteronismo; repor cloreto de potássio; reduzir diuréticos se possível. **Dieta alcalinizante para acidose leve:** Aumentar vegetais, frutas, reduzir proteínas animais; citrato de potássio 20 mEq/dia. **Monitoramento:** Gasometria venosa seriada até normalização; tratar distúrbio de base; avaliar eletrólitos (K, Cl, Na) concomitantemente."
  }'

echo "Item 5 processado: pH Venoso"

echo ""
echo "=== Processamento concluído para os primeiros 5 items ==="
echo "Continuando com os próximos..."
