UPDATE score_items
SET
  clinical_relevance = 'A avaliação da saúde genital masculina representa um componente essencial da medicina preventiva, frequentemente negligenciada na prática clínica. A disfunção erétil (DE) merece atenção especial pois funciona como marcador precoce de doença cardiovascular, precedendo eventos cardíacos em média 3-5 anos devido ao comprometimento endotelial sistêmico. Estudos demonstram que homens com DE apresentam risco 25% maior de doença cardiovascular, tornando fundamental a investigação de fatores de risco metabólicos e cardiovasculares nestes pacientes. O câncer testicular, embora relativamente raro (1% dos cânceres masculinos), é a neoplasia sólida mais comum em homens jovens (15-35 anos), com taxa de cura superior a 95% quando detectado precocemente através do exame físico e ultrassonografia. A varicocele afeta 15% da população masculina geral e até 35% dos homens com infertilidade primária, podendo comprometer a espermatogênese através de hipertermia testicular, estresse oxidativo e alterações hormonais. Outras condições prevalentes incluem hidrocele, fimose, infecções sexualmente transmissíveis e massas escrotais benignas. A detecção precoce através de exame físico sistemático, educação para autoexame testicular e investigação apropriada de sintomas permite intervenção oportuna, prevenção de complicações e melhora significativa na qualidade de vida e prognóstico.',

  patient_explanation = 'A saúde da região genital masculina é fundamental para o bem-estar geral e qualidade de vida. Problemas comuns incluem dificuldade de ereção (que pode indicar problemas no coração ou vasos sanguíneos), varizes nos testículos (varicocele), acúmulo de líquido ao redor do testículo (hidrocele), estreitamento da pele do pênis (fimose) e nódulos nos testículos. É importante conhecer seu próprio corpo através do autoexame testicular mensal, realizado após banho morno: palpe delicadamente cada testículo procurando por caroços, mudanças de tamanho ou consistência. Procure atendimento médico se notar qualquer nódulo testicular, mudança súbita no tamanho escrotal, dor persistente, dificuldade de ereção (especialmente se você tem diabetes, hipertensão ou colesterol alto), corrimento uretral, lesões ou feridas genitais. A maioria das condições genitais masculinas é tratável quando identificada precocemente. Não deixe vergonha ou desconforto impedirem você de buscar cuidado médico - profissionais de saúde estão treinados para avaliar estas condições de forma respeitosa e confidencial. O cuidado preventivo e a detecção precoce podem salvar vidas, especialmente no caso de câncer testicular.',

  conduct = 'AVALIAÇÃO CLÍNICA: Iniciar com anamnese detalhada investigando disfunção erétil, dor, nódulos, corrimento, lesões, mudanças no tamanho ou formato escrotal, histórico de criptorquidia, trauma, cirurgias prévias e infertilidade. Questionar sobre fatores de risco cardiovasculares (diabetes, hipertensão, dislipidemia, tabagismo). EXAME FÍSICO: Realizar em ambiente privativo e aquecido. Inspeção: avaliar distribuição de pelos, lesões cutâneas, edema, eritema, corrimento uretral. Palpação testicular: cada testículo deve ser palpado sistematicamente procurando massas, consistência (normal = borracha firme), simetria de tamanho. Avaliar epidídimo e cordão espermático. Manobra de Valsalva em pé para detectar varicocele (sensação de saco de vermes que desaparece em decúbito). Avaliar presença de hidrocele (transiluminação positiva). INVESTIGAÇÃO COMPLEMENTAR: Ultrassonografia escrotal está indicada para massas palpáveis, assimetria testicular significativa, dor escrotal persistente, suspeita de varicocele ou hidrocele. Para disfunção erétil: solicitar glicemia, perfil lipídico, testosterona total (manhã), TSH. Marcadores tumorais (AFP, beta-hCG, LDH) se massa testicular suspeita. CONDUTA: Massas testiculares sólidas requerem encaminhamento urgente à urologia (suspeita de câncer). Varicocele sintomática ou associada à infertilidade: referenciar urologia para considerar varicocelectomia. Disfunção erétil: otimizar fatores de risco cardiovasculares, considerar inibidores PDE-5 se sem contraindicações. Fimose em adultos: avaliação urológica para circuncisão eletiva. ISTs: tratamento conforme protocolo e rastreamento de parceiros. PREVENÇÃO: Educar sobre autoexame testicular mensal, uso de preservativos, importância de avaliação médica regular especialmente após 40 anos.',

  last_review = NOW()

WHERE id = 'fe938ed9-3cf9-4ddf-a1ae-2f67c03e54a4';

SELECT
  question,
  LENGTH(clinical_relevance) as clin_rel_chars,
  LENGTH(patient_explanation) as pat_exp_chars,
  LENGTH(conduct) as conduct_chars,
  last_review
FROM score_items
WHERE id = 'fe938ed9-3cf9-4ddf-a1ae-2f67c03e54a4';
