-- Anexo IV da IN 28/2018 (texto consolidado). Gerado do texto da norma, não digitado à mão.
-- Fonte: LegisWeb, IN 28 de 26/07/2018 consolidada até a IN 373/2025.
BEGIN;
INSERT INTO in28_limits (nutrient, unit, max_adult, kind) VALUES
  ('2''-fucosil-lactose', 'g', 3.0, 'valor'),
  ('Proteínas', 'g', NULL, 'NE'),
  ('Carboidratos', 'g', NULL, 'NE'),
  ('D-ribose', 'g', 2.5, 'valor'),
  ('Fibras alimentares', 'g', NULL, 'NE'),
  ('Lipídeos totais', 'g', NULL, 'NE'),
  ('EPA e DHA', 'mg', 2000.0, 'valor'),
  ('Teanina', 'mg', 250.0, 'valor'),
  ('DHA e EPA obtido de lisinato de ômega 3', 'mg', 2000.0, 'valor'),
  ('Ácido linoleico n-6', 'G', 25.5, 'valor'),
  ('Ácido alfa-linolênico n-3', 'G', 2.4, 'valor'),
  ('Colina', 'mg', 3235.15, 'valor'),
  ('Vitamina Ai', 'µg', 2623.61, 'valor'),
  ('Vitamina B6', 'mg', 98.6, 'valor'),
  ('Vitamina C', 'mg', 1916.02, 'valor'),
  ('Vitamina Dii', 'µg', 50.0, 'valor'),
  ('Niacina', 'mg', 35.0, 'valor'),
  ('Vitamina Eiii', 'mg', 1000.0, 'valor'),
  ('Ácido fólico iv', 'mcg', 1281.5, 'valor'),
  ('Ácido pantotênico', 'mg', 5.64, 'valor'),
  ('Biotina', 'µg', 45.0, 'valor'),
  ('Riboflavina', 'mg', 2.74, 'valor'),
  ('Tiamina', 'mg', 2.02, 'valor'),
  ('Vitamina B12', 'µg', 9.94, 'valor'),
  ('Vitamina K', 'µg', 149.06, 'valor'),
  ('Cálciov', 'mg', 1534.67, 'valor'),
  ('Cobre', 'µg', 8975.52, 'valor'),
  ('Manganês', 'mg', 1.66, 'valor'),
  ('Molibdênio', 'µg', 1955.0, 'valor'),
  ('Fósforov', 'mg', 2083.89, 'valor'),
  ('Selênio', 'µg', 319.75, 'valor'),
  ('Zinco', 'mg', 29.59, 'valor'),
  ('Iodo', 'µg', 919.02, 'valor'),
  ('Ferro', 'mg', 34.31, 'valor'),
  ('Magnésio', 'mg', 350.0, 'valor'),
  ('Cromo', 'µg', 250.0, 'valor'),
  ('Leucina', 'mg', 5660.0, 'valor'),
  ('Lisina', 'mg', 4940.0, 'valor'),
  ('Valina', 'mg', 3600.0, 'valor'),
  ('Isoleucina', 'mg', 3240.0, 'valor'),
  ('Treonina', 'mg', 2720.0, 'valor'),
  ('Fenilalanina', 'mg', 2820.0, 'valor'),
  ('Tirosina', 'mg', 2750.0, 'valor'),
  ('Metionina', 'mg', 1530.0, 'valor'),
  ('Cisteína', 'mg', 830.0, 'valor'),
  ('Histidina', 'mg', 2120.0, 'valor'),
  ('Triptofano', 'mg', 860.0, 'valor'),
  ('Arginina', 'mg', 3810.0, 'valor'),
  ('Aspartato', 'mg', 5320.0, 'valor'),
  ('Glicina', 'mg', 2980.0, 'valor'),
  ('Serina', 'mg', 3151.0, 'valor'),
  ('Ácido glutâmico', 'mg', 15880.0, 'valor'),
  ('Prolina', 'mg', 5360.0, 'valor'),
  ('Alanina', 'mg', 3320.0, 'valor'),
  ('Beta-alanina', 'g', 2.0, 'valor'),
  ('Glutamina', 'mg', 5000.0, 'valor'),
  ('Taurina', 'mg', 2000.0, 'valor'),
  ('L-Carnitina', 'mg', 2000.0, 'valor'),
  ('Creatina', 'mg', 3000.0, 'valor'),
  ('Adenosina', 'mg', 1.2, 'valor'),
  ('Inositol', 'g', 2.0, 'valor'),
  ('Ácido estearidônico (SDA) do óleo da semente de Buglossoides arvensis (L.)', 'mg', 420.0, 'valor'),
  ('Ácido gama aminobutírico (GABA)', 'mg', 300.0, 'valor'),
  ('Ácido hialurônico', 'mg', 157.7, 'valor'),
  ('Boro', 'mg', 8.866, 'valor'),
  ('Cafeína', 'mg', 200.0, 'valor'),
  ('Coenzima Q10', 'mg', 200.0, 'valor'),
  ('Colágeno', 'mg', NULL, 'NE'),
  ('Colágeno tipo II não desnaturado', 'mg', NULL, 'NE'),
  ('Compostos fenólicos deOpuntia ficus-indica', 'mg', 54.6, 'valor'),
  ('Fitoesterois e fitoestanois', 'g', 3.0, 'valor'),
  ('Licopeno', 'mg', 8.0, 'valor'),
  ('Luteína', 'mg', 20.0, 'valor'),
  ('Metilsulfonilmetano', 'mg', 900.0, 'valor'),
  ('Palmitoiletanolamida', 'mg', 600.0, 'valor'),
  ('Zeaxantina', 'mg', 3.0, 'valor'),
  ('Astaxantina', 'mg', 6.0, 'valor'),
  ('Alicina', 'mg', 3.0, 'valor'),
  ('Compostos fenólicos totais', 'mg', NULL, 'NE'),
  ('Compostos fenólicos de Extrato de polpa de oliva (Olea europaea L.)', 'mg', 23.2, 'valor'),
  ('Condroitina', 'mg', 600.0, 'valor'),
  ('Curcumina', 'mg', NULL, 'NA'),
  ('Dihidrocapsiato (DHC)', 'mg', 9.0, 'valor'),
  ('D-Limoneno', 'mg', 150.0, 'valor'),
  ('Extrato de cacauviii', 'mg', 300.0, 'valor'),
  ('10-HDA (ácido hidroxidecenóico)', 'mg', 25.0, 'valor'),
  ('Rutina', 'mg', 0.6, 'valor'),
  ('Saponinas de glicosídeos de furostanol', 'mg', 450.0, 'valor'),
  ('Silício', 'mg', 15.67, 'valor'),
  ('Ácido clorogênico', 'mg', 400.0, 'valor'),
  ('Ácido rosmarínico', 'mg', 160.0, 'valor'),
  ('Alfa-casozepina', 'mg', 21.0, 'valor'),
  ('Antocianinas da laranja moro', 'mg', 5.0, 'valor'),
  ('Antocianinas da casca de jabuticaba', 'mg', 28.0, 'valor'),
  ('Arabinogalactana', 'g', 20.0, 'valor'),
  ('Beta-glucana (Euglena gracilis)', 'mg', 187.5, 'valor'),
  ('Beta-glucana de levedura (Saccharomyces cerevisiae)', 'mg', 1275.0, 'valor'),
  ('Colostro bovino desnatado viii', 'g', 4.0, 'valor'),
  ('Colostro bovino integral viii', 'g', 4.0, 'valor'),
  ('Proantociadininas Proantocianidinas de cranberry', 'mg', NULL, 'NA'),
  ('Fosfatidilserina', 'mg', 400.0, 'valor'),
  ('Glucosamina', 'mg', 750.0, 'valor'),
  ('Glicosaminoglicanos', 'mg', 19.2, 'valor'),
  ('Glutationa', 'mg', 500.0, 'valor'),
  ('Hidroximetilbutirato', 'g', 3.0, 'valor'),
  ('Hidroxitirosol e derivados', 'mg', NULL, 'NA'),
  ('Lactoferrina', 'mg', 1200.0, 'valor'),
  ('L-citrulinilarginina', 'mg', 52.8, 'valor'),
  ('Melatonina', 'mg', 0.21, 'valor'),
  ('Peptídeos bioativos de colágeno hidrolisado com peso molecular médio de 2kDa', 'g', NULL, 'NE'),
  ('Peptídeos bioativos de soro de leite', 'mg', NULL, 'NE'),
  ('Proantocianidinas de semente de uva', 'mg', 116.0, 'valor'),
  ('Proantocianidinas do tipo A', 'mg', 25.0, 'valor'),
  ('Procianidinas', 'mg', 262.5, 'valor'),
  ('Tetraidrocurcuminoides', 'mg', 120.0, 'valor'),
  ('Trans-resveratrol', 'mg', 165.0, 'valor'),
  ('Verbascosídeo', 'mg', 7.68, 'valor'),
  ('Xilo-oligossacarídeos', 'mg', 2.0, 'valor'),
  ('Alfa-galactosidase de Aspergillus niger', 'GaIU', 4800.0, 'valor'),
  ('Protease de Aspergillus niger expressa em Aspergillus niger', 'PPI', 2000000.0, 'valor'),
  ('Fitase', 'FTU', NULL, 'NE'),
  ('Lactase', 'U.FCC', NULL, 'NE'),
  ('Associação deLactobacillus plantarum(CECT 7484),Lactobacillus plantarum(CECT 7485) ePediococcus acidilactici(CECT 7483)', 'UFC', NULL, 'NE'),
  ('Bacillus clausii O/C (CNCM-I-276), SIN (CNCM-I-275), N/R (CNCM-I-274), T (CNCM-I-273)', 'Esporos/ porção', NULL, 'NE'),
  ('Bacillus clausii UBBC-07', 'UFC', NULL, 'NE'),
  ('Bacillus coagulansSNZ 1969 (MTCC 5724; BCCM LMG S-27484; ATCC 3560)', 'Esporos/ porção', NULL, 'NE'),
  ('Bacillus subtilis HU58 (NCIMB 30283)', 'UFC', NULL, 'NE'),
  ('Bifidobacterium animalis subsp. lactis HN019 (ATCC SD5674)', 'UFC', NULL, 'NE'),
  ('Bifidobacterium animalis subsp. lactis BB12 (DSM 15954)', 'UFC', NULL, 'NE'),
  ('Bifidobacterium animalis subsp. lactis LAFTI® B94', 'UFC', NULL, 'NE'),
  ('Bifidobacterium lactis NCC 2818', 'UFC', NULL, 'NA'),
  ('Lactobacillus acidophillusDDS-1® (NCIMB 30333)', 'UFC', NULL, 'NE'),
  ('Lactobacillus acidophilus NCFM (ATCC SD5221)', 'UFC', NULL, 'NE'),
  ('Lactobacillus coryniformis CECT 5711', 'UFC', NULL, 'NE'),
  ('Lactobacillus gasseri BNR17 (KCTC 10902BP)', 'UFC', NULL, 'NE'),
  ('Lactobacillus rhamnosus GG (DSM 33156)', 'UFC', NULL, 'NE'),
  ('Lactobacillus rhamnosus GG (ATCC 53103)', 'UFC', NULL, 'NE'),
  ('Lactobacillus rhamnosus HN001 (ATCC SD5675)', 'UFC', NULL, 'NA'),
  ('Lactobacillus rhamnosus NCC 4007', 'UFC', NULL, 'NE'),
  ('Limosilactobacillus reuteri DSM 17938', 'UFC', NULL, 'NE'),
  ('Associação de Lactobacillus rhamnosus R0011 (CNCM I-1720) e de Lactobacillus helveticus R0052 (CNCM I-1722)', 'UFC', NULL, 'NE'),
  ('Associação de Lactobacillus helveticus R0052 (CNCM I-1722) e de Bifidobacterium longum R0175 (CNCM I-3470)', 'UFC', NULL, 'NE'),
  ('Associação de Lactobacillus helveticus R0052, Bifidobacterium longum ssp. Infantis R0033 e Bifidobacterium bifidum R0071', 'UFC', NULL, 'NA'),
  ('Associação de Lactobacillus plantarum CECT 7527, Lactobacillus plantarum CECT 7528 e Lactobacillus plantarum CECT 7529', 'UFC', NULL, 'NE'),
  ('Associação de Bifidobacterium lactis BI- 07 (ATCC SD5220), de Lactobacillus acidophilus NCFM (ATCC SD5221), de Bifidobacterium lactis BI-04 (ATCC SD5219) e de Lactobacillus paracasei Lpc-37 (ATCC SD5275)', 'UFC', NULL, 'NE'),
  ('Associação de Bifidobacterium longum subsp. longum BB536, Bifidobacterium longum subsp. infantis M-63 e Bifidobacterium breve M-16V', 'UFC', NULL, 'NA'),
  ('Associação de Pediococcus pentosaceus (CECT 8330) e Bifidobacterium longum (CECT 7894)', 'UFC', NULL, 'NA'),
  ('Associação de Lactobacillus acidophilus La-14 (ATCC SD5212) e Lactobacillus rhamnosus HN001 (ATCC SD5675)', 'UFC', NULL, 'NE'),
  ('Associação de Lactobacillus rhamnosus GR-1 (DSM33426) e Limosillactobacillus reuteri RC-14 (DSM33016)', 'UFC', NULL, 'NE'),
  ('Niacina ix', 'mg', 35.0, 'valor'),
  ('Beta-glucana (Euglena gracilis) viii', 'mg', 244.0, 'valor'),
  ('Extrato Aquoso de Cogumelo Shiitake (Lentinula edodes) viii', 'mg', 1800.0, 'valor'),
  ('Hidrolisado de pectina de cenoura (Daucus carotasativus) rico em ramnogalacturonano (cRG-I) viii', 'mg', 4140.0, 'valor'),
  ('Oleuropeína', 'mg', 161.0, 'valor'),
  ('Oligopeptídeos de colágeno', 'g', NULL, 'NE'),
  ('Quercetina', 'mg', 280.0, 'valor'),
  ('Bacillus subtilissubsp.inaquosorumDE111', 'UFC', NULL, 'NE'),
  ('Bifidobacterium lactisNCC 2818', 'UFC', NULL, 'NE'),
  ('Bifidobacterium longumsubsp.longumBB536', 'UFC', NULL, 'NE'),
  ('Lactobacillus plantarumDR-7', 'UFC', NULL, 'NE'),
  ('Associação deLactobacillus rhamnosus19070-2 (DSM 26357) eLactobacillus reuteriDSM 12246 (CBS 145621)', 'UFC', NULL, 'NA')
ON CONFLICT (nutrient) DO UPDATE
  SET unit = EXCLUDED.unit, max_adult = EXCLUDED.max_adult, kind = EXCLUDED.kind, updated_at = now();
COMMIT;
