-- Escore Plenya Light — SQL gerado a partir da curadoria v5
-- Marca items com is_light_version=true, light_order, light_question
BEGIN;

-- 1. Resetar todos os items para garantir estado limpo
UPDATE score_items SET is_light_version = false, light_order = NULL, light_question = NULL WHERE is_light_version = true;

-- 2. Marcar items selecionados
UPDATE score_items SET is_light_version = true, light_order = 1, light_question = 'Como você descreveria seu nível atual de atividade física?' WHERE id = 'c77cedd3-2800-7bb3-9e74-b76061206583'; -- Estratégia macro atual
UPDATE score_items SET is_light_version = true, light_order = 2, light_question = 'Você tem ou já teve lesões relacionadas ao exercício?' WHERE id = 'c77cedd3-2800-7de9-ad64-b75ed1037b5e'; -- Lesões relacionadas ao exercício
UPDATE score_items SET is_light_version = true, light_order = 3, light_question = 'Por quantos segundos você consegue sustentar uma prancha frontal? (com cronômetro, em forma correta)' WHERE id = '019cbe7a-213e-7bcb-9770-cbda22cf5164'; -- Resistência Neuromuscular - Prancha (Homens)
UPDATE score_items SET is_light_version = true, light_order = 3, light_question = 'Por quantos segundos você consegue sustentar uma prancha frontal? (com cronômetro, em forma correta)' WHERE id = '019cbe7a-2145-7931-a655-5afec9787eee'; -- Resistência Neuromuscular - Prancha (Mulheres)
UPDATE score_items SET is_light_version = true, light_order = 4, light_question = 'Como você descreveria a qualidade da sua alimentação nos últimos anos?' WHERE id = '019bf31d-2ef0-7683-8814-9f18e88dea60'; -- Qualidade da alimentação na vida adulta
UPDATE score_items SET is_light_version = true, light_order = 5, light_question = 'Quantas porções de verduras e legumes você consome por dia? (1 porção ≈ 1 prato pequeno ou 1 xícara)' WHERE id = '019c5376-ca0e-7b9b-b9e7-e3cd66486705'; -- Consumo de Verduras e Legumes
UPDATE score_items SET is_light_version = true, light_order = 6, light_question = 'Com que frequência você consome refrigerantes ou bebidas energéticas?' WHERE id = '019c535e-d7b0-7f20-8c8c-b3c2dee441fc'; -- Refrigerantes e energéticos
UPDATE score_items SET is_light_version = true, light_order = 7, light_question = 'Em quantas das suas refeições diárias você se senta à mesa, com calma e sem distratores (TV, celular)?' WHERE id = '019bf31d-2ef0-7285-bc84-86d015569d31'; -- Onde e como come
UPDATE score_items SET is_light_version = true, light_order = 8, light_question = 'Como são a divisão e os horários das suas refeições?' WHERE id = 'c77cedd3-2800-73cc-8694-dae1f7d682df'; -- Divisão e Horários das refeições
UPDATE score_items SET is_light_version = true, light_order = 9, light_question = 'As pessoas que moram com você seguem o mesmo padrão alimentar que o seu?' WHERE id = '019bf31d-2ef0-7fc2-9d5c-a7d275642ead'; -- Todos seguem o mesmo padrão alimentar do paciente
UPDATE score_items SET is_light_version = true, light_order = 10, light_question = 'Qual é a sua circunferência abdominal? Meça na altura do umbigo, sem apertar a fita.' WHERE id = 'c77cedd3-2800-7aac-985c-c075f020e9e0'; -- Abdominal (cintura em cm) - homem
UPDATE score_items SET is_light_version = true, light_order = 10, light_question = 'Qual é a sua circunferência abdominal? Meça na altura do umbigo, sem apertar a fita.' WHERE id = 'c77cedd3-2800-7a74-99ad-56ca4b6dddc1'; -- Abdominal (cintura em cm) - mulher
UPDATE score_items SET is_light_version = true, light_order = 11, light_question = 'Qual é a circunferência do seu pescoço? Meça logo abaixo do pomo de adão.' WHERE id = '019bf31d-2ef0-767a-a87e-b4587192005b'; -- Pescoço - homem
UPDATE score_items SET is_light_version = true, light_order = 11, light_question = 'Qual é a circunferência do seu pescoço? Meça logo abaixo do pomo de adão.' WHERE id = '019bf31d-2ef0-7f0a-8188-216affee192f'; -- Pescoço - mulher
UPDATE score_items SET is_light_version = true, light_order = 12, light_question = 'IMC calculado automaticamente a partir do seu peso e altura.' WHERE id = '019bf31d-2ef0-7bb8-8305-e0e0285aeb80'; -- IMC (kg/m²)
UPDATE score_items SET is_light_version = true, light_order = 13, light_question = 'Razão cintura/altura calculada automaticamente.' WHERE id = '019bf31d-2ef0-7171-a061-3bcc500957f7'; -- Razão cintura/altura (cm/cm)
UPDATE score_items SET is_light_version = true, light_order = 14, light_question = 'Se você fez bioimpedância ou DEXA: qual o seu ASMI (Índice de Massa Apendicular)?' WHERE id = 'c77cedd3-2800-7338-9d58-9d43abcd81a7'; -- ASMI (kg/m²) - homem
UPDATE score_items SET is_light_version = true, light_order = 14, light_question = 'Se você fez bioimpedância ou DEXA: qual o seu ASMI (Índice de Massa Apendicular)?' WHERE id = '019bf31d-2ef0-7a69-9963-ae68d65a713d'; -- ASMI (kg/m²) - mulher
UPDATE score_items SET is_light_version = true, light_order = 15, light_question = 'Se você fez bioimpedância ou DEXA: qual seu valor de gordura visceral em cm²?' WHERE id = '019bf31d-2ef0-7a29-b825-a84bc8f38f3e'; -- Gordura visceral (cm²) - homem
UPDATE score_items SET is_light_version = true, light_order = 15, light_question = 'Se você fez bioimpedância ou DEXA: qual seu valor de gordura visceral em cm²?' WHERE id = '019bf31d-2ef0-7126-a8b7-ac530f86aa68'; -- Gordura visceral (cm²) - mulher
UPDATE score_items SET is_light_version = true, light_order = 16, light_question = 'Se você fez bioimpedância ou DEXA: qual seu percentual de gordura corporal?' WHERE id = '019bf31d-2ef0-78d5-bb48-f5e21ba33ab4'; -- % Gordura corporal - homem
UPDATE score_items SET is_light_version = true, light_order = 16, light_question = 'Se você fez bioimpedância ou DEXA: qual seu percentual de gordura corporal?' WHERE id = 'c77cedd3-2800-706c-acc0-f6b5da2aa203'; -- % Gordura corporal - mulher
UPDATE score_items SET is_light_version = true, light_order = 17, light_question = 'Você tem ou já teve doença cardiovascular (infarto, angioplastia, AVC)?' WHERE id = '019bf31d-2ef0-7de7-a98d-603c41d12ae6'; -- Doença cardiovascular (IAM, revascularização, AVC, etc)
UPDATE score_items SET is_light_version = true, light_order = 18, light_question = 'Você tem diagnóstico de insuficiência cardíaca?' WHERE id = '019bf31d-2ef0-7e03-bb24-dbdc747e5fd4'; -- Insuficiência cardíaca
UPDATE score_items SET is_light_version = true, light_order = 19, light_question = 'Você tem diagnóstico de diabetes mellitus?' WHERE id = '019bf31d-2ef0-7f17-a053-7f45b7162dd2'; -- Diabetes mellitus
UPDATE score_items SET is_light_version = true, light_order = 20, light_question = 'Você tem diagnóstico de pré-diabetes ou resistência insulínica?' WHERE id = '019bf31d-2ef0-7c5c-bc5b-00fbf09daf98'; -- Pré-diabetes / resistência a insulina
UPDATE score_items SET is_light_version = true, light_order = 21, light_question = 'Você tem diagnóstico de arritmia cardíaca?' WHERE id = 'c77cedd3-2800-7b94-ac6e-c404259efa2e'; -- Arritmia
UPDATE score_items SET is_light_version = true, light_order = 22, light_question = 'Você tem diagnóstico de asma?' WHERE id = 'c77cedd3-2800-7ef5-b90a-7b4b6cc19d5b'; -- Asma
UPDATE score_items SET is_light_version = true, light_order = 23, light_question = 'Algum parente próximo (pais, irmãos, avós) tem ou teve doença cardiovascular?' WHERE id = 'c77cedd3-2800-70c7-942e-a1134e3aa05e'; -- Doença cardiovascular (IAM, revascularização, arritmias, AVC)
UPDATE score_items SET is_light_version = true, light_order = 24, light_question = 'Algum parente próximo tem ou teve câncer?' WHERE id = 'c77cedd3-2800-7e0c-b44f-ccf9c3b926ef'; -- Câncer
UPDATE score_items SET is_light_version = true, light_order = 25, light_question = 'Algum parente próximo tem diabetes, pré-diabetes ou resistência insulínica?' WHERE id = 'c77cedd3-2800-7524-9049-f4559170db14'; -- Diabetes mellitus / pré-diabetes / resistência insulínica
UPDATE score_items SET is_light_version = true, light_order = 26, light_question = 'Algum parente próximo tem dislipidemia (colesterol/triglicérides alterados)?' WHERE id = 'c77cedd3-2800-74b8-976d-8e90ecd896be'; -- Dislipidemia
UPDATE score_items SET is_light_version = true, light_order = 27, light_question = 'Algum parente próximo tem hipertensão arterial?' WHERE id = 'c77cedd3-2800-75fe-b483-ea0183478225'; -- Hipertensão arterial
UPDATE score_items SET is_light_version = true, light_order = 28, light_question = 'Algum parente próximo tem obesidade?' WHERE id = 'c77cedd3-2800-70b8-b444-b05d15b96a57'; -- Obesidade
UPDATE score_items SET is_light_version = true, light_order = 29, light_question = 'Você usa medicamentos para pressão alta atualmente?' WHERE id = 'c77cedd3-2800-7ce0-a970-351333e28cae'; -- Anti-hipertensivos (IECA, BRA, betabloqueadores, BCC, diuréticos)
UPDATE score_items SET is_light_version = true, light_order = 30, light_question = 'Você usa estatinas ou outros medicamentos para colesterol?' WHERE id = '019bf31d-2ef0-7c2d-b263-5ba6bc208d28'; -- Estatinas / Hipolipemiantes
UPDATE score_items SET is_light_version = true, light_order = 31, light_question = 'Você usa medicamentos análogos de GLP-1 (Ozempic, Mounjaro, Wegovy, Saxenda)?' WHERE id = 'c77cedd3-2800-769d-874f-ade1376eceea'; -- Análogos de GLP-1 / Agonistas GIP / Obesidade
UPDATE score_items SET is_light_version = true, light_order = 32, light_question = 'Você usa insulina?' WHERE id = '019bf31d-2ef0-7398-a3a3-1f2d8a7954ce'; -- Insulinas
UPDATE score_items SET is_light_version = true, light_order = 33, light_question = 'Você sente ou já sentiu dor no peito (dor torácica)?' WHERE id = '019bf31d-2ef0-73fc-b353-73eadb4940d5'; -- Dor torácica
UPDATE score_items SET is_light_version = true, light_order = 34, light_question = 'Você sente falta de ar (dispneia) em situações cotidianas?' WHERE id = '019bf31d-2ef0-71ae-8f72-8330e3072647'; -- Dispnéia
UPDATE score_items SET is_light_version = true, light_order = 35, light_question = 'Você sente palpitações cardíacas?' WHERE id = '019bf31d-2ef0-7f0a-b7d9-5d22d7a40484'; -- Palpitação
UPDATE score_items SET is_light_version = true, light_order = 36, light_question = 'Você sente dor nas pernas ao caminhar que melhora ao parar (claudicação)?' WHERE id = '019bf31d-2ef0-7193-b496-afe7ce51ed91'; -- Claudicação
UPDATE score_items SET is_light_version = true, light_order = 37, light_question = 'Você apresenta inchaço (edema) nos membros?' WHERE id = '019bf31d-2ef0-7297-bd6d-4c83d8081d2d'; -- Edema
UPDATE score_items SET is_light_version = true, light_order = 38, light_question = 'Você sente azia ou queimação no estômago?' WHERE id = 'c77cedd3-2800-73d3-8d0f-6bdeb10d1680'; -- Azia
UPDATE score_items SET is_light_version = true, light_order = 39, light_question = 'Você tem dificuldade para evacuar (intestino preso/obstipação)?' WHERE id = '019bf31d-2ef0-751d-b2c8-1ef3913bf002'; -- Obstipação
UPDATE score_items SET is_light_version = true, light_order = 40, light_question = 'Como é seu histórico de doença periodontal (gengivite, periodontite)?' WHERE id = '019bf31d-2ef0-7f92-900b-138dfe299a5f'; -- Histórico Periodontal
UPDATE score_items SET is_light_version = true, light_order = 41, light_question = 'Como é sua rotina de higiene bucal e acompanhamento odontológico?' WHERE id = '019bf31d-2ef0-76f9-8525-94f68cf574ab'; -- Higiene e Acompanhamento
UPDATE score_items SET is_light_version = true, light_order = 42, light_question = 'Se você tem o resultado: qual seu valor de Apolipoproteína B (ApoB) em mg/dL?' WHERE id = '019bf31d-2ef0-7179-bf54-dcd082ca05cc'; -- Apolipoproteína B
UPDATE score_items SET is_light_version = true, light_order = 43, light_question = 'Se você tem o resultado: qual seu valor de Lipoproteína(a) em nmol/L?' WHERE id = '019bf31d-2ef0-7401-8c83-7a09665eb36a'; -- Lipoproteína A
UPDATE score_items SET is_light_version = true, light_order = 44, light_question = 'Se você tem o resultado: qual seu valor de PCR ultrassensível (hs-CRP) em mg/L?' WHERE id = '019bf31d-2ef0-78e2-b15d-ee2aeba78c83'; -- PCR ultrassensível
UPDATE score_items SET is_light_version = true, light_order = 45, light_question = 'Se você tem o resultado: qual seu valor de LDL colesterol em mg/dL?' WHERE id = 'c77cedd3-2800-7cfa-a75c-05dfcd1bfb4d'; -- LDL Colesterol
UPDATE score_items SET is_light_version = true, light_order = 46, light_question = 'Se você tem o resultado: qual seu valor de HDL colesterol em mg/dL?' WHERE id = 'c77cedd3-2800-78d6-8eb4-e496bd62d509'; -- HDL Colesterol
UPDATE score_items SET is_light_version = true, light_order = 47, light_question = 'Se você tem o resultado: qual seu valor de triglicerídeos em mg/dL?' WHERE id = '019bf31d-2ef0-791f-b7c5-d2fe8c694daa'; -- Triglicerídeos
UPDATE score_items SET is_light_version = true, light_order = 48, light_question = 'Razão TG/HDL calculada automaticamente.' WHERE id = '019bf31d-2ef0-7de3-aff2-96dceb4a9b68'; -- Relação Triglicerídeos/HDL
UPDATE score_items SET is_light_version = true, light_order = 49, light_question = 'Se você tem o resultado: qual seu valor de NT-proBNP em pg/mL?' WHERE id = '019bf31d-2ef0-788b-bcc3-9da32e59adfb'; -- NT-proBNP (50-75 anos)
UPDATE score_items SET is_light_version = true, light_order = 49, light_question = 'Se você tem o resultado: qual seu valor de NT-proBNP em pg/mL?' WHERE id = '019bf31d-2ef0-7d19-8b60-64765b6fc8f0'; -- NT-proBNP (<50 anos)
UPDATE score_items SET is_light_version = true, light_order = 49, light_question = 'Se você tem o resultado: qual seu valor de NT-proBNP em pg/mL?' WHERE id = 'c77cedd3-2800-72eb-bb38-fb9dc94b73f2'; -- NT-proBNP (>75 anos)
UPDATE score_items SET is_light_version = true, light_order = 50, light_question = 'Se você tem o resultado: qual sua hemoglobina glicada (HbA1c) em %?' WHERE id = 'c77cedd3-2800-7255-a15a-f049c099b68b'; -- Hemoglobina glicada
UPDATE score_items SET is_light_version = true, light_order = 51, light_question = 'Se você tem o resultado: qual seu HOMA-IR?' WHERE id = '019bf31d-2ef0-735b-9582-5964b8fd4f4d'; -- HOMA-IR
UPDATE score_items SET is_light_version = true, light_order = 52, light_question = 'Se você tem o resultado: qual seu valor de Vitamina D (25-OH) em ng/mL?' WHERE id = 'c77cedd3-2800-7ef6-8f6e-66db64655c69'; -- 25-hidroxivitamina D
UPDATE score_items SET is_light_version = true, light_order = 53, light_question = 'Se você tem o resultado: qual seu valor de homocisteína em µmol/L?' WHERE id = '019bf31d-2ef0-7b72-a5d6-bfa546d8de8d'; -- Homocisteína
UPDATE score_items SET is_light_version = true, light_order = 54, light_question = 'Se você tem o resultado: qual seu valor de ferritina em ng/mL?' WHERE id = '019bf31d-2ef0-7a1c-96bb-07ca58662932'; -- Ferritina - Homens
UPDATE score_items SET is_light_version = true, light_order = 54, light_question = 'Se você tem o resultado: qual seu valor de ferritina em ng/mL?' WHERE id = '019bf31d-2ef0-74be-92bb-3aaad9c448a7'; -- Ferritina - Mulheres Pré-Menopausa
UPDATE score_items SET is_light_version = true, light_order = 54, light_question = 'Se você tem o resultado: qual seu valor de ferritina em ng/mL?' WHERE id = '019bf31d-2ef0-7236-8694-5e28d8748475'; -- Ferritina - Mulheres Pós-Menopausa
UPDATE score_items SET is_light_version = true, light_order = 55, light_question = 'Se você tem o resultado: qual seu valor de TSH em mIU/L?' WHERE id = '019bf31d-2ef0-76d8-874e-a7364c014877'; -- TSH
UPDATE score_items SET is_light_version = true, light_order = 56, light_question = 'Se você tem o resultado: qual seu valor de T3 Livre em pg/mL?' WHERE id = '019bf31d-2ef0-78f2-899d-3f0d57ec7cc3'; -- T3 Livre
UPDATE score_items SET is_light_version = true, light_order = 57, light_question = 'Se você tem o resultado: qual seu valor de testosterona total em ng/dL?' WHERE id = 'c77cedd3-2800-728a-80bc-788e05f0ad1f'; -- Testosterona Total - Homens
UPDATE score_items SET is_light_version = true, light_order = 57, light_question = 'Se você tem o resultado: qual seu valor de testosterona total em ng/dL?' WHERE id = '019bf31d-2ef0-75c6-bad3-8dff164c977a'; -- Testosterona Total - Mulheres Pré-Menopausa
UPDATE score_items SET is_light_version = true, light_order = 57, light_question = 'Se você tem o resultado: qual seu valor de testosterona total em ng/dL?' WHERE id = 'c77cedd3-2800-7a73-bd66-aeb35ff300b8'; -- Testosterona Total - Mulheres Pós-Menopausa
UPDATE score_items SET is_light_version = true, light_order = 58, light_question = 'Se você tem o resultado: qual seu valor de estradiol em pg/mL?' WHERE id = '019bf31d-2ef0-73de-9eae-c0e7ef1741f7'; -- Estradiol - Homens
UPDATE score_items SET is_light_version = true, light_order = 58, light_question = 'Se você tem o resultado: qual seu valor de estradiol em pg/mL?' WHERE id = 'c77cedd3-2800-7332-8030-53e795aa5ef4'; -- Estradiol - Mulheres Fase Folicular Inicial (Dias 1-7)
UPDATE score_items SET is_light_version = true, light_order = 58, light_question = 'Se você tem o resultado: qual seu valor de estradiol em pg/mL?' WHERE id = 'c77cedd3-2800-75b6-ae6e-8461c3043e64'; -- Estradiol - Mulheres Fase Ovulatória (Pico Meio do Ciclo)
UPDATE score_items SET is_light_version = true, light_order = 58, light_question = 'Se você tem o resultado: qual seu valor de estradiol em pg/mL?' WHERE id = 'c77cedd3-2800-7dff-a8f4-328b0a41e9e9'; -- Estradiol - Mulheres Fase Lútea (Dias 19-21)
UPDATE score_items SET is_light_version = true, light_order = 58, light_question = 'Se você tem o resultado: qual seu valor de estradiol em pg/mL?' WHERE id = 'c77cedd3-2800-7c8e-89d7-becfd6d6a375'; -- Estradiol - Mulheres Pós-Menopausa (Sem TRH)
UPDATE score_items SET is_light_version = true, light_order = 58, light_question = 'Se você tem o resultado: qual seu valor de estradiol em pg/mL?' WHERE id = '019bf31d-2ef0-78fb-a542-b61a7e1fd979'; -- Estradiol - Mulheres Pós-Menopausa (Com TRH)
UPDATE score_items SET is_light_version = true, light_order = 59, light_question = 'Se você tem o resultado: qual seu valor de microalbuminúria/creatininúria em mg/g?' WHERE id = 'c77cedd3-2800-7cce-9809-9b202222501e'; -- Microalbuminúria/creatininúria – urina amostra isolada
UPDATE score_items SET is_light_version = true, light_order = 60, light_question = 'Se você fez: qual seu escore de cálcio coronariano (Agatston Units)?' WHERE id = 'c77cedd3-2800-76a7-b671-5d0f54885bf5'; -- TC coração para escore de cálcio coronariano
UPDATE score_items SET is_light_version = true, light_order = 61, light_question = 'Se você fez ultrassom abdominal: qual o grau de esteatose hepática?' WHERE id = 'c77cedd3-2800-7d99-9f7d-61dc4773da58'; -- USG Abdome - Esteatose Hepática
UPDATE score_items SET is_light_version = true, light_order = 62, light_question = 'Se você fez densitometria óssea: qual seu T-score do colo femoral?' WHERE id = 'c77cedd3-2800-7ac1-b242-dcd64194e6ad'; -- Densitometria - T-Score Colo Femoral
UPDATE score_items SET is_light_version = true, light_order = 63, light_question = 'Escala PHQ-9 (humor): some os 9 itens que vão aparecer e informe seu total /27.' WHERE id = 'c77cedd3-2800-721b-94d8-b5515b895753'; -- Escala PHQ-9 (humor): ___/27
UPDATE score_items SET is_light_version = true, light_order = 64, light_question = 'Como está a sua memória hoje, comparada ao seu auge?' WHERE id = 'c77cedd3-2800-7bec-942e-c1eed243a6a0'; -- Capacidade da memória percebida
UPDATE score_items SET is_light_version = true, light_order = 65, light_question = 'Como está sua vida social nos últimos 6 meses?' WHERE id = '019c54fc-edfb-73d7-8525-3e326e91a976'; -- Socialização atual (últimos 6 meses)
UPDATE score_items SET is_light_version = true, light_order = 66, light_question = 'Como você descreveria seu nível atual de estresse e capacidade de manejá-lo?' WHERE id = 'c77cedd3-2800-7360-bf3c-5b4f28c660ef'; -- Fontes de stress percebidas atualmente (trabalho, família, doenças, financeiro, etc)
UPDATE score_items SET is_light_version = true, light_order = 67, light_question = 'Qual seu padrão de consumo de tabaco?' WHERE id = '019bf31d-2ef0-7a08-ab7e-d9c06d8d2103'; -- Tabaco
UPDATE score_items SET is_light_version = true, light_order = 68, light_question = 'Qual seu padrão de consumo de álcool?' WHERE id = '019bf31d-2ef0-7eff-b67d-00e5eec8c2d0'; -- Álcool
UPDATE score_items SET is_light_version = true, light_order = 69, light_question = 'Como está sua situação familiar e rede de suporte?' WHERE id = '019c2e64-1522-74db-a6b5-97595412d14a'; -- Situação familiar
UPDATE score_items SET is_light_version = true, light_order = 70, light_question = 'Quantas horas, em média, você dorme por noite?' WHERE id = '019c53a6-f1a3-7704-9868-354859c750cd'; -- Tempo de sono
UPDATE score_items SET is_light_version = true, light_order = 71, light_question = 'A que horas você costuma deitar para dormir?' WHERE id = 'c77cedd3-2800-74fb-9aca-432654d7e0d8'; -- Hora de dormir
UPDATE score_items SET is_light_version = true, light_order = 72, light_question = 'Como você percebe a qualidade do seu sono?' WHERE id = 'c77cedd3-2800-735f-bf28-c5d07d7d7092'; -- Qualidade percebida do sono
UPDATE score_items SET is_light_version = true, light_order = 73, light_question = 'Em quantos dias do mês você acorda no mesmo horário?' WHERE id = '019c53a6-72b5-7718-afac-c14a539f7bca'; -- Regularidade no acordar
UPDATE score_items SET is_light_version = true, light_order = 74, light_question = 'Você usa CPAP ou BiPAP para dormir?' WHERE id = '019c28f0-05c1-7c0f-92b5-9cc9adac6eb3'; -- Uso de BiPAP/CPAP
UPDATE score_items SET is_light_version = true, light_order = 75, light_question = 'Você apresenta pausas respiratórias durante o sono (apneias)?' WHERE id = 'c77cedd3-2800-7ca1-9dd2-ac6e478cd0e5'; -- Apneias
UPDATE score_items SET is_light_version = true, light_order = 76, light_question = 'Você ronca durante o sono?' WHERE id = '019c164e-cb2c-747a-bfc7-ffb3e787229f'; -- Roncos
UPDATE score_items SET is_light_version = true, light_order = 77, light_question = 'Com que frequência você usa telas (celular, TV, tablet) na hora antes de dormir?' WHERE id = '019bf31d-2ef0-7f44-a617-84562c569b71'; -- Tempo tela noturna (1h antes de dormir - celular, tablet, TV, dormir assintindo à TV)

COMMIT;

-- Total: 94 registros marcados