-- Pendências de DEV->PROD anteriores ao 00054 (catálogo + score), espelhando dev no prod.
-- TUDO derivado de diff dev<->prod (dump prod 2026-06-27 03:00) por id; zero conflito com outras
-- sessões (nenhuma def teve specimen mudado de um valor pra outro — todas NULL->valor).
-- Conteúdo:
--  * lab_test_definitions: 218 UPDATE (specimen_type populado + alt_names + unit /µL nos sedimentos)
--    + 4 INSERT (Prolinfócitos/Linfócitos atípicos, percentual+absoluto).
--  * lab_test_unit_conversions: 3 INSERT (Leucócitos/Hemácias/Células Epiteliais - Sedimento, /µL<->/mL x1000).
--  * score_levels: re-base/gate clínico de 11 itens — Eosinófilos, Monócitos, pH Urinário (U),
--    Glicemia (+L3 100-110), 3 Sedimentos (/µL, rótulos corrigidos), Consumo de Proteínas (vírgula),
--    Regularidade acordar/dormir (gap 27-28), Doppler PSV Carótida Interna (remove L3 ≤125 duplicado).
-- Idempotente (UPDATE por id; INSERT por id + ON CONFLICT; soft-delete por id).

-- +goose Up

-- ===== lab_test_definitions: 218 UPDATE (specimen_type / alt_names / unit) =====
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["bastonetes", "neutrofilos bastonetes", "neutrofilos em bastao", "band cells", "bastoes"]'::jsonb, updated_at=NOW() WHERE id='bea69651-8280-4ad5-a608-43f676ef8648';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["blastos", "celulas blastocitarias", "blastos percentual"]'::jsonb, updated_at=NOW() WHERE id='019c3603-59de-7c1b-9472-ef8b0d13aca0';
UPDATE lab_test_definitions SET unit='mL/min/1.73m²', specimen_type='Sangue', alt_names='["taxa de filtracao glomerular estimada", "estimativa da taxa de filtracao glomerular", "etfg", "tfg", "egfr", "ckd-epi"]'::jsonb, updated_at=NOW() WHERE id='8a514764-c406-40f1-9c05-c2a5580c5f19';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["glicemia media estimada", "estimated average glucose", "eag", "gme"]'::jsonb, updated_at=NOW() WHERE id='aac63fa7-2107-403b-a196-86422aa0fbee';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["homa-beta", "homa beta", "indice homa-beta", "funcao celulas beta"]'::jsonb, updated_at=NOW() WHERE id='15079e79-1c7d-4b7e-88cc-476c0ebed5ad';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["metamielocitos", "metamielocitos percentual", "metamielo"]'::jsonb, updated_at=NOW() WHERE id='019c3603-59e5-76d8-839a-94eae9d2f6a8';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["mielocitos", "mielocitos percentual", "mielo"]'::jsonb, updated_at=NOW() WHERE id='019c3603-59e4-7edd-8916-6a2e2b41040c';
UPDATE lab_test_definitions SET unit='fL', specimen_type='Sangue', alt_names='["pdw", "platelet distribution width", "amplitude de distribuicao plaquetaria", "pdw-sd"]'::jsonb, updated_at=NOW() WHERE id='019c3603-59e6-7858-ad42-933b50ce31b3';
UPDATE lab_test_definitions SET unit='ng/dL', specimen_type='Sangue', alt_names='["dihidrotestosterona", "di-hidrotestosterona", "di-hidrotestosterona", "dht", "dihidrotestosterona/dht"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7321-a20e-d4e7d6d5cec8';
UPDATE lab_test_definitions SET unit='Descritivo', specimen_type='Urina', alt_names='["leveduras - sedimento", "leveduras no sedimento urinario", "leveduras na urina", "fungos no sedimento"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7e89-9424-c8538b084983';
UPDATE lab_test_definitions SET unit='µg/L', specimen_type='Sangue', alt_names='["mercurio", "mercurio no sangue", "mercurio serico", "dosagem de mercurio no sangue", "mercurio organico", "hg"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7747-98ea-1596d9a54e47';
UPDATE lab_test_definitions SET unit='Descritivo', specimen_type='Urina', alt_names='["bacterias - sedimento", "bacterias no sedimento urinario", "bacterias urina", "bacteriuria"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-73e9-be20-e081864b3191';
UPDATE lab_test_definitions SET unit='ratio', specimen_type='Sangue', alt_names='["relacao colesterol total/hdl", "indice de castelli", "razao ct/hdl"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7b81-946c-4529d81c7e09';
UPDATE lab_test_definitions SET unit='ng/mL', specimen_type='Sangue', alt_names='["leptina", "leptina - homens", "leptina - mulheres", "leptina serica"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7d88-9d0e-682c2581be77';
UPDATE lab_test_definitions SET unit='/µL', specimen_type='Urina', alt_names='["leucocitos (wbc) - sedimento", "leucocitos - sedimento", "leucocitos no sedimento urinario", "piocitos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7190-9330-f35c561bace0';
UPDATE lab_test_definitions SET unit='specific gravity', specimen_type='Urina', alt_names='["densidade urinaria (usg)", "densidade urinaria", "densidade urina", "densidade especifica da urina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-72db-a174-8694bfefe5b4';
UPDATE lab_test_definitions SET unit='ng/mL', specimen_type='Sangue', alt_names='["cea", "antigeno carcinoembrionario", "antigeno carcinoembrionico"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-734f-bc86-18a3b5ee7020';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["bilirrubina direta", "bilirrubina conjugada", "bd", "bild"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7dbc-b422-f8ff1fc0cc3a';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='019ec882-4bcf-7c19-b813-3a14ff01bafc';
UPDATE lab_test_definitions SET unit='µg/mL', specimen_type='Sangue', alt_names='["coenzima q10", "ubiquinona", "ubiquinol", "coenzima q10 dosagem plasma"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7e41-8b7b-cb3fe0b81388';
UPDATE lab_test_definitions SET unit='ng/dL', specimen_type='Sangue', alt_names='["t3 reverso", "triiodotironina reversa", "t3 reversa", "rt3"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7409-9b89-51fa83d051e0';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["corpos cetonicos", "cetonuria", "corpos cetonicos na urina", "pesquisa de corpos cetonicos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7d4e-9884-44d748120e15';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["bilirrubina indireta", "bilirrubina nao conjugada", "bi"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-75dc-b195-77062b269075';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["glicose 60 min", "glicose 60 minutos", "glicemia 60 minutos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7660-beb6-830be9f54a0e';
UPDATE lab_test_definitions SET unit='ng/mL', specimen_type='Sangue', alt_names='["25-hidroxivitamina d", "vitamina d 25-hidroxi", "25-hidroxi vitamina d", "calcidiol", "vitamina d3", "25 ohd", "vitamina d 25 oh", "25 hidroxivitamina d", "25-oh-vitamina d", "25-oh vitamina d", "vitamina d"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-75ab-be16-196abe89ad40';
UPDATE lab_test_definitions SET unit='ng/mL', specimen_type='Sangue', alt_names='["psa total", "antigeno prostatico especifico", "antigeno prostatico especifico total", "psa", "psa/antigeno prostatico especifico"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7784-af1a-7e490fea2521';
UPDATE lab_test_definitions SET unit='pg/mL', specimen_type='Sangue', alt_names='["pth", "paratormonio", "hormonio da paratireoide", "paratormonio intacto", "paratormonio molecula intacta", "paratormonio/pth"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-73d9-99d2-fce037f7870c';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["imunoglobulina g (igg)", "imunoglobulina g", "imunoglobulina g serica"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7a0f-a14f-57d64745c491';
UPDATE lab_test_definitions SET unit='µUI/mL', specimen_type='Sangue', alt_names='["insulina 60 min", "insulina 60 minutos", "insulina apos 60 minutos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-753a-b572-b9a50269a16a';
UPDATE lab_test_definitions SET unit='pg/mL', specimen_type='Sangue', alt_names='["testosterona livre", "testosterona livre - homens", "testosterona livre - mulheres pre-menopausa", "testosterona livre - mulheres pos-menopausa", "testosterona livre serica", "free testosterone", "testosterona livre calculada", "tl"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7c5a-a964-646a68f8c091';
UPDATE lab_test_definitions SET unit='mg/g', specimen_type='Urina', alt_names='["microalbuminuria/creatininuria - urina amostra isolada", "relacao albumina/creatinina urinaria", "microalbuminuria em amostra isolada", "relacao albumina creatinina em amostra isolada de urina", "albuminuria amostra isolada", "microalbuminuria", "microalbuminuria amostra isolada", "microalbuminuria/isolada", "rac"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-78b8-b871-655dced49f0a';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["glicose 30 min", "glicose 30 minutos", "glicemia 30 minutos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-749f-9dba-782db78ef03b';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["anti-ro (ssa)", "anticorpos anti-ro", "anticorpos anti-ssa", "anti-ro/ssa", "anticorpos para sjogren"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7436-83cd-77f99b23fe53';
UPDATE lab_test_definitions SET unit='g/dL', specimen_type='Sangue', alt_names='["gama globulina", "gamaglobulina", "fracao gama", "imunoglobulinas totais"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7e72-b0f3-20d5700f2141';
UPDATE lab_test_definitions SET unit='g/dL', specimen_type='Sangue', alt_names='["globulinas totais", "globulinas", "globulinas sericas totais"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-76db-85f8-0b118f982354';
UPDATE lab_test_definitions SET unit='µUI/mL', specimen_type='Sangue', alt_names='["insulina 0 min (jejum)", "insulina jejum", "insulina basal", "insulina tempo zero", "insulina em jejum", "insulina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-73a3-89e1-0a1803908a28';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["urobilinogenio", "urobilinogenio urinario", "urobilinogenio urina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7bf0-8c23-a58ab7361012';
UPDATE lab_test_definitions SET unit='IU/mL', specimen_type='Sangue', alt_names='["anti-tireoglobulina", "anticorpos anti-tireoglobulina", "anticorpo antitireoglobulina", "anticorpos antitireoglobulina", "anti tireoglobulina", "anti-tg"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7cc3-acd4-ab44832131ce';
UPDATE lab_test_definitions SET unit='pg/mL', specimen_type='Sangue', alt_names='["t3 livre", "triiodotironina livre", "free t3", "t3l", "ft3"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-72bd-8f76-07bde9f3761c';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["calcio total", "calcio serico", "calcemia", "calcio, soro", "calcio", "ca"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7ad6-a4c9-89145b4893ec';
UPDATE lab_test_definitions SET unit='unidade', specimen_type='Urina', alt_names='["ph urinario", "ph urina", "determinacao do ph urinario"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7334-9732-2ffe17fb7531';
UPDATE lab_test_definitions SET unit='k/µL', specimen_type='Sangue', alt_names='["leucocitos totais (wbc)", "leucocitos totais", "leucocitos", "globulos brancos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-70c9-8fc4-97fb1255f2f6';
UPDATE lab_test_definitions SET unit='M/µL', specimen_type='Sangue', alt_names='["hemacias", "hemacias - homens", "hemacias - mulheres", "eritrocitos", "contagem de hemacias"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7206-b2d2-ccddfb136bf9';
UPDATE lab_test_definitions SET unit='U/L', specimen_type='Sangue', alt_names='["transaminase piruvica (alt)", "transaminase piruvica", "tgp", "alanina aminotransferase", "transaminase glutamica piruvica", "alt", "tgp/alt", "alt/tgp", "tgp - alanina aminotransferase", "alt/tgp/alanina aminotransferase"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7354-ad60-3778817ecf70';
UPDATE lab_test_definitions SET unit='µg/L', specimen_type='Sangue', alt_names='["cromo", "cromo serico", "cromo sanguineo"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7bfd-90bd-48e91f25542c';
UPDATE lab_test_definitions SET unit='ng/mL', specimen_type='Sangue', alt_names='["acido folico plasmatico", "acido folico serico", "folato", "folatemia", "vitamina b9", "acido folico"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7bfd-82d0-23c0d0bf6cf1';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["creatinina", "creatinina serica", "creatinina soro", "creat"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-79ad-87a2-5011b5d21fb4';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["bilirrubinas totais", "bilirrubina total", "bt", "btf", "bilirrubina total e fracoes", "bilirrubinas total e fracoes"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7344-b95e-b100a22657cb';
UPDATE lab_test_definitions SET unit='g/dL', specimen_type='Sangue', alt_names='["beta globulina", "betaglobulina", "β-globulina", "beta-1 globulina", "beta-2 globulina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7741-b54a-5189ae629aba';
UPDATE lab_test_definitions SET unit='μg/L', specimen_type='Sangue', alt_names='["aluminio", "aluminio serico", "dosagem de aluminio no soro", "aluminio no sangue", "al"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7db7-93fa-c651e9da634c';
UPDATE lab_test_definitions SET unit='IU/mL', specimen_type='Sangue', alt_names='["imunoglobulina e (ige)", "imunoglobulina e", "imunoglobulina e total"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7264-b320-3649a8295a5c';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["hemoglobina glicada", "a1c", "hemoglobina glicosilada", "hemoglobina glicada/a1c", "hemoglobina glicada/a1c/hplc", "hba1c"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-79d3-b10b-f3ae1a5d7a14';
UPDATE lab_test_definitions SET unit='nmol/L', specimen_type='Sangue', alt_names='["vitamina b1 por hplc em sangue total", "vitamina b1", "tiamina", "vitamina b1 sangue total"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-77de-bc77-8873f8f14da1';
UPDATE lab_test_definitions SET unit='mg/L', specimen_type='Sangue', alt_names='["cistatina c", "cistatina c serica"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7177-b8b1-d0e30f85e7fc';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["complemento c4", "complemento serico c4", "fracao c4 do complemento", "c4 - componente do complemento", "c4"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-73cd-93a4-3af5ac0e70c7';
UPDATE lab_test_definitions SET unit='/µL', specimen_type='Urina', alt_names='["celulas epiteliais - sedimento", "celulas epiteliais", "celulas epiteliais na urina", "celulas epiteliais no sedimento urinario"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-732a-ac02-fb8c9c350a52';
UPDATE lab_test_definitions SET unit='nmol/L', specimen_type='Sangue', alt_names='["piridoxal-5-fosfato (plp) por hplc em sangue total", "vitamina b6", "piridoxal 5 fosfato", "vitamina b6 ativa", "piridoxina", "piridoxal-5-fosfato"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-72fe-8f80-183b9d7b4b33';
UPDATE lab_test_definitions SET unit='mg/L', specimen_type='Sangue', alt_names='["vitamina e (alfa-tocoferol)", "vitamina e", "alfa-tocoferol", "tocoferol"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-702b-b283-96000c413573';
UPDATE lab_test_definitions SET unit='ng/mL', specimen_type='Sangue', alt_names='["progesterona", "progesterona - homens", "progesterona - mulheres fase folicular", "progesterona - mulheres fase lutea", "progesterona - mulheres gestacao 1º trimestre", "progesterona - mulheres gestacao 2º trimestre", "progesterona - mulheres gestacao 3º trimestre", "progesterona - mulheres pos-menopausa", "progesterona serica", "progesterona na gravidez", "p4"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7f8a-9cbe-150057f57cd8';
UPDATE lab_test_definitions SET unit='pg/mL', specimen_type='Sangue', alt_names='["nt-probnp", "fragmento n-terminal do peptideo natriuretico tipo b", "pro-bnp n-terminal", "n-terminal pro-peptideo natriuretico tipo-b", "probnp n terminal", "probnp nterminal", "pro bnp", "peptideo natriuretico", "probnp", "nt probnp"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-73b7-a3b7-d472f3bb4ff0';
UPDATE lab_test_definitions SET unit='IU/L', specimen_type='Sangue', alt_names='["trab (anticorpos anti-receptor de tsh)", "anticorpos anti-receptor de tsh", "anticorpo anti-receptor do tsh", "trab", "trab/anti-receptor de tsh", "anti-receptor de tsh"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-78e5-8e78-5c1f1f8dc95c';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["rdw", "amplitude de distribuicao dos globulos vermelhos", "largura de distribuicao dos globulos vermelhos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-79ad-9135-0baaceafb321';
UPDATE lab_test_definitions SET unit='ng/dL', specimen_type='Sangue', alt_names='["t4 livre", "tiroxina livre", "free t4", "t4l", "tetraiodotironina livre", "t4 livre/tiroxina livre", "ft4"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7d71-9b7e-324b563cc2d5';
UPDATE lab_test_definitions SET unit='pg/mL', specimen_type='Sangue', alt_names='["interleucina-6 (il-6)", "interleucina 6", "interleucina-6", "fator estimulador de celulas b"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-735b-b509-c75e042b4325';
UPDATE lab_test_definitions SET unit='fL', specimen_type='Sangue', alt_names='["vcm (mcv)", "vcm", "volume corpuscular medio"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7d54-b9a2-a242c3260ca8';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["hematocrito", "hematocrito - homens", "hematocrito - mulheres", "hematocrito masculino", "hematocrito feminino", "ht"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-78ec-9fba-2f111fba36ce';
UPDATE lab_test_definitions SET unit='mIU/mL', specimen_type='Sangue', alt_names='["hepatite b - anti-hbs", "anticorpo contra antigeno de superficie da hepatite b", "hepatite b - anticorpo contra antigeno de superficie", "anti-hbs"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7ca2-951d-d536f21da1c5';
UPDATE lab_test_definitions SET unit='U/L', specimen_type='Sangue', alt_names='["gama gt", "gama glutamil transferase", "gamaglutamiltransferase", "gama-glutamiltransferase", "ggt", "gama-gt"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7363-a767-f25f19705e2b';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["hdl colesterol", "colesterol hdl", "alfa colesterol", "lipoproteina de alta densidade", "colesterol fracao hdl", "hdl", "hdl-colesterol"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7668-b7a5-fb0a838bbc6f';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["apolipoproteina b", "apo b", "apo b 100", "apolipoproteina b 100", "apoproteina b", "apob", "apo b100"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7008-8b7f-acfd36f8964a';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Urina', alt_names='["arsenio fracionado urina (inorganico + metabolitos)", "arsenio urinario", "arsenio inorganico urina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7bb9-b373-8783f5989908';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["proteinas (qualitativo)", "proteinas na urina", "proteinuria qualitativa"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7d80-8e86-054f772a2973';
UPDATE lab_test_definitions SET unit='U/L', specimen_type='Sangue', alt_names='["creatino fosfoquinase", "creatinofosfoquinase", "creatinoquinase", "creatinoquinase total", "cpk", "ck", "cpk/creatinofosfoquinase", "ck/creatinafosfoquinase total", "cpk - creatinofosfocinase", "creatina quinase"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7d01-b55b-d25ef0af24b2';
UPDATE lab_test_definitions SET unit='g/dL', specimen_type='Sangue', alt_names='["hemoglobina", "hemoglobina - homens", "hemoglobina - mulheres", "hemoglobina total", "hemoglobina masculina", "hemoglobina feminina", "hb"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-792e-971e-0a7fa083953e';
UPDATE lab_test_definitions SET unit='pg/mL', specimen_type='Sangue', alt_names='["acth", "hormonio adrenocorticotrofico", "hormonio adrenocorticotropico", "corticotrofina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7d8d-9d4a-2e30a484bf4f';
UPDATE lab_test_definitions SET unit='ng/mL', specimen_type='Sangue', alt_names='["prolactina", "prolactina - homens", "prolactina - mulheres", "prolactina serica", "prl"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7184-b25f-55852e792f9d';
UPDATE lab_test_definitions SET unit='U/L', specimen_type='Sangue', alt_names='["amilase", "amilase serica", "amilasemia", "alfa amilase pancreatica", "amilase pancreatica e salivar"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7665-affa-5749ae9a9699';
UPDATE lab_test_definitions SET unit='ratio', specimen_type='Sangue', alt_names='["tempo de protrombina (inr)", "tempo de protrombina", "razao normalizada internacional", "inr", "tap", "rni"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7052-ba8e-7d5acdc21a5c';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Fezes', alt_names='["calprotectina fecal", "calprotectina nas fezes", "calprotectina em fezes", "dosagem de calprotectina nas fezes"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7fd4-b375-5d1b9298506d';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Urina', alt_names='["arsenio total urina", "arsenio urina", "arsenico urina", "dosagem de arsenio na urina", "arsenio urinario"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7b89-9ce1-ffe3e4388d8a';
UPDATE lab_test_definitions SET unit='nmol/L', specimen_type='Sangue', alt_names='["shbg", "shbg - homens", "shbg - mulheres", "globulina ligadora de hormonios sexuais", "sex hormone binding globulin", "shbg/globulina transportadora dos hormonios sexuais"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7565-bbcf-3c6628edc4d4';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["perfil lipidico / lipidograma", "lipidograma", "perfil lipidico", "colesterol total e fracoes com triglicerideos", "estudo lipidico", "colesterol total e fracoes"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7012-91b3-1c75573387a7';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["reticulocitos", "contagem de reticulocitos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7959-b559-7f8b8574a36a';
UPDATE lab_test_definitions SET unit='g/dL', specimen_type='Sangue', alt_names='["albumina", "albumina serica", "albumina soro", "albumina sanguinea", "dosagem de albumina", "alb"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7cca-bab9-dce362f067e5';
UPDATE lab_test_definitions SET unit='g/dL', specimen_type='Sangue', alt_names='["chcm (mchc)", "concentracao de hemoglobina corpuscular media", "chcm"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7301-bec5-2bf488501cea';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["tyg index", "indice tyg", "indice triglicerides-glicose", "indice de triglicerideos-glicose"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7fc2-89bd-82b912e49b9e';
UPDATE lab_test_definitions SET unit='/µL', specimen_type='Urina', alt_names='["hemacias (rbc) - sedimento", "eritrocitos no sedimento urinario", "hemacias na urina", "hemacias - sedimento", "hemacias sedimento", "hemacias no sedimento urinario"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7222-a7da-7a1912971a14';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["colesterol nao-hdl", "colesterol nao hdl", "colesterol total menos hdl", "col nao hdl"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-790b-bc26-e5b4ea5bc37c';
UPDATE lab_test_definitions SET unit='cilindros/campo', specimen_type='Sangue', alt_names='["cilindros hialinos", "cilindros hialinos na urina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7745-8c61-bae621bf0d3e';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["complemento c3", "complemento serico c3", "fracao c3 do complemento", "c3 - componente do complemento", "complemento serico/c3", "c3"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7d2c-b43c-24d7f7ac9ed7';
UPDATE lab_test_definitions SET unit='k/µL', specimen_type='Sangue', alt_names='["neutrofilos (absoluto)", "neutrofilos absolutos", "contagem absoluta de neutrofilos", "neutrofilos segmentados"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-76aa-a1a9-e8f05f09ae35';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["glicose 120 min", "glicose 120 minutos", "glicose 2 horas", "glicemia 120 minutos", "glicose pos-prandial 2 horas"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-74c0-8a75-6e61404e0cb6';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Urina', alt_names='["rotina de urina", "exame de urina tipo i", "urina tipo 1", "sumario de urina", "parcial de urina", "urinalise", "exame qualitativo de urina", "urina tipo i", "eas"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-70aa-9562-229a95222cfd';
UPDATE lab_test_definitions SET unit='ratio', specimen_type='Sangue', alt_names='["relacao triglicerideos/hdl", "razao tg/hdl", "indice aterogenico", "indice aterogenico plasmatico"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7bb2-95be-25304cffe2f0';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["vitamina c (acido ascorbico)", "vitamina c", "acido ascorbico", "acido ascorbico plasma", "vitamina c/acido ascorbico"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7c3d-892d-359a2bae7b69';
UPDATE lab_test_definitions SET unit='mm/hr', specimen_type='Sangue', alt_names='["vhs (esr)", "vhs", "velocidade de hemossedimentacao", "taxa de sedimentacao globular", "hemossedimentacao/vhs", "hemossedimentacao", "velocidade de hemossedimentacao/vhs", "vhs 1 hora"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-763f-bdd8-5642408b5bee';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Urina', alt_names='["urocultura com contagem de colonias e antibiograma automatizado", "cultura de urina com antibiograma", "urinocultura com antibiograma", "urocultura e antibiograma com contagem de colonias", "cultura - urina", "urocultura", "urinocultura"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7849-9705-b7e3b3cd9e90';
UPDATE lab_test_definitions SET unit='mEq/L', specimen_type='Sangue', alt_names='["potassio", "potassio serico", "k", "calemia"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7fdd-b67a-67a5ea3ca2d3';
UPDATE lab_test_definitions SET unit='Qualitativo', specimen_type='Fezes', alt_names='["sangue oculto (hemoglobina)", "pesquisa de sangue oculto nas fezes", "sangue oculto nas fezes"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7e55-8526-7833ca3c8595';
UPDATE lab_test_definitions SET unit='ratio', specimen_type='Sangue', alt_names='["relacao t3 livre:t3 reverso", "razao t3 livre/t3 reverso", "indice t3 livre/t3 reverso"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-740f-9cf1-2a18c430ea32';
UPDATE lab_test_definitions SET unit='µg/dL', specimen_type='Sangue', alt_names='["zinco", "zinco serico", "zinco plasma", "zincemia", "zn"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7dd8-bf45-347d61416add';
UPDATE lab_test_definitions SET unit='Qualitativo', specimen_type='Sangue', alt_names='["hepatite c - anti-hcv", "anticorpos contra virus da hepatite c", "hepatite c - anticorpos", "anti-hcv"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7215-becc-b8cc87b60ccc';
UPDATE lab_test_definitions SET unit='Descritivo', specimen_type='Sangue', alt_names='["cristais patologicos", "cristais de cistina", "cristais de leucina", "cristais de tirosina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7a36-bd5b-2562ee525ab6';
UPDATE lab_test_definitions SET unit='Qualitativo', specimen_type='Sangue', alt_names='["nitrito", "teste de nitrito urinario", "griess"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7517-9a1b-52e8c442379b';
UPDATE lab_test_definitions SET unit='mIU/mL', specimen_type='Sangue', alt_names='["lh", "lh - homens", "lh - mulheres fase folicular", "lh - mulheres fase lutea", "lh - mulheres ovulacao", "lh - mulheres pos-menopausa", "hormonio luteinizante", "lh/hormonio luteinizante"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7b5a-8d5f-42334110db33';
UPDATE lab_test_definitions SET unit='µg/dL', specimen_type='Sangue', alt_names='["dhea-s", "dhea-s - homens (20-29 anos)", "dhea-s - homens (30-39 anos)", "dhea-s - homens (40-49 anos)", "dhea-s - homens (50-59 anos)", "dhea-s - homens (60-69 anos)", "dhea-s - homens (70+ anos)", "dhea-s - mulheres (20-29 anos)", "dhea-s - mulheres (30-39 anos)", "dhea-s - mulheres (40-49 anos)", "dhea-s - mulheres (50-59 anos)", "dhea-s - mulheres (60-69 anos)", "dhea-s - mulheres (70+ anos)", "sulfato de dehidroepiandrosterona", "sdhea", "dehidroepiandrosterona sulfato", "dheas", "dheas/sulfato de dehidroepiandrosterona"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7be3-873c-9520150db9b0';
UPDATE lab_test_definitions SET unit='Descritivo', specimen_type='Urina', alt_names='["aspecto da urina (turbidez)", "aspecto da urina", "turbidez urinaria", "aspecto", "transparencia da urina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-77b8-80c6-00f67f6711ed';
UPDATE lab_test_definitions SET unit='Leu/µL', specimen_type='Sangue', alt_names='["leucocito esterase", "esterase leucocitaria", "esterase leucocitaria"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7d6e-bf6d-cf42b7f169fb';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["homa-ir", "indice de homa", "indice homa-ir", "resistencia a insulina", "avaliacao de resistencia a insulina", "calculo homa", "homa ir"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7f25-8a0b-5335adf7dafb';
UPDATE lab_test_definitions SET unit='µg/dL', specimen_type='Sangue', alt_names='["chumbo", "plumbemia", "chumbo sangue total", "pesquisa e dosagem no sangue chumbo", "saturnismo", "pb"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7a35-b3f8-569eb041ab9d';
UPDATE lab_test_definitions SET unit='µUI/mL', specimen_type='Sangue', alt_names='["insulina 120 min", "insulina 120 minutos", "insulina 2 horas", "insulina apos 120 minutos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7ff9-ace0-d89a89c80c93';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["glicose 90 min", "glicose 90 minutos", "glicemia 90 minutos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7db9-9a9b-a8462cffc55a';
UPDATE lab_test_definitions SET unit='U/L', specimen_type='Sangue', alt_names='["desidrogenase latica", "lactato desidrogenase", "desidrogenase lactica", "ldh"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7fd3-8ac5-dc6f2ee5a9ad';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["vdrl", "sifilis vdrl", "treponema pallidum floculacao"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7204-a152-295adda6b5f3';
UPDATE lab_test_definitions SET unit='k/µL', specimen_type='Sangue', alt_names='["plaquetas", "contagem de plaquetas"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7bef-9d13-20f95f323490';
UPDATE lab_test_definitions SET unit='g/dL', specimen_type='Sangue', alt_names='["proteinas totais", "proteinas totais no soro", "proteina total", "pt"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-78ee-90f9-eda330ee9b60';
UPDATE lab_test_definitions SET unit='Qualitativo', specimen_type='Sangue', alt_names='["hepatite b - anti-hbc", "anticorpos totais contra antigeno central da hepatite b", "hepatite b - anticorpo contra antigeno central", "anti-hbc total"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7f24-88d0-34d4969739ca';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["imunoglobulina m (igm)", "imunoglobulina m", "imunoglobulina m serica"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7719-9566-fb402f740ebb';
UPDATE lab_test_definitions SET unit='U/mL', specimen_type='Sangue', alt_names='["anti-transglutaminase igg", "anticorpos anti-transglutaminase tecidual igg", "transglutaminase tecidual - anticorpos igg", "anti-transglutaminase igg"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7779-a6c5-b7c53e71380f';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["sato2 venosa", "saturacao venosa central de oxigenio", "saturacao de oxigenio venosa"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7843-b4ea-6e5a47cb7d56';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["magnesio rbc", "magnesio eritrocitario", "magnesio intraeritrocitario", "magnesio intracelular", "magnesio eritrocitario sangue"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-743d-91e8-410f7a7c3649';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["colesterol total", "colesterol total e fracoes", "colesterol total e fracoes com triglicerides", "perfil lipidico", "lipidograma", "colesterol", "col total"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7928-89e4-b53f27e1bb5c';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["anti-endomisio iga (ema-iga)", "anticorpos anti-endomisio iga", "endomisio - anticorpos iga", "anti-endomisio iga"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7dbd-9e02-89d4cc7e9aa4';
UPDATE lab_test_definitions SET unit='ng/mL', specimen_type='Sangue', alt_names='["alfafetoproteina", "alfa fetoproteina", "alfa-fetoproteina", "marcador tumoral defeito congenito de tubo neural"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7f7f-bcfb-63447ec9be5a';
UPDATE lab_test_definitions SET unit='g/dL', specimen_type='Sangue', alt_names='["alfa-1 globulina", "alfa-1-globulina", "α1-globulina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7fd3-b854-2247f92fcf94';
UPDATE lab_test_definitions SET unit='mIU/mL', specimen_type='Sangue', alt_names='["fsh", "fsh - homens", "fsh - mulheres fase lutea", "fsh - mulheres ovulacao", "fsh - mulheres pre-menopausa (dia 3)", "fsh - mulheres pos-menopausa", "hormonio foliculo estimulante", "hormonio foliculo-estimulante", "fsh/hormonio foliculo estimulante"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7ee2-961c-6abf51ea994b';
UPDATE lab_test_definitions SET unit='ng/mL', specimen_type='Sangue', alt_names='["acido folico eritrocitario", "folato eritrocitario", "acido folico intraeritrocitario", "folato em hemacias"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7c16-8857-08ecd1f7d78b';
UPDATE lab_test_definitions SET unit='µg/dL', specimen_type='Sangue', alt_names='["cobre", "cobre serico", "cupremia", "cobre plasma", "cobre ligado a ceruloplasmina", "cu"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-71a5-87aa-ac932eda0ce1';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["vldl colesterol", "colesterol vldl", "lipoproteina de muito baixa densidade", "vldl", "vldl/colesterol"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7c00-a193-70158b44853b';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["glicose 0 min (jejum)", "glicose jejum", "glicose basal", "glicose tempo 0", "glicemia de jejum", "glicose", "glicemia", "glicose em jejum"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7006-a888-846cc9de63ed';
UPDATE lab_test_definitions SET unit='pg/mL', specimen_type='Sangue', alt_names='["vitamina b12 (cobalamina)", "vitamina b12", "cobalamina", "cianocobalamina", "vitamina b-12", "b12"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7dd1-8e6d-7304b2306ab0';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["curva de insulina e glicose apos carga de 75 g de glicose (0, 30, 60, 90, 120 min)", "teste oral de tolerancia a glicose", "curva glicemica", "curva glico-insulinica", "totg"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7465-ba55-f849ad4059c2';
UPDATE lab_test_definitions SET unit='µg/dL', specimen_type='Sangue', alt_names='["cortisol plasmatico basal", "cortisol basal", "cortisol", "cortisol salivar"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7ef4-bc9d-181444f742b4';
UPDATE lab_test_definitions SET unit='nmol/L', specimen_type='Sangue', alt_names='["acido metilmalonico", "acido metilmalonico serico", "acido 2-metilpropanodioico"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7493-8c53-2e6c88c3a82e';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["fan", "fator antinuclear", "anticorpos antinucleares", "pesquisa de autoanticorpos anticelula", "pesquisa de anticorpos contra antigenos celulares"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-74e7-9757-5e66a81acf83';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["triglicerideos", "triglicerides", "triglicerideos soro", "triglicerides soro", "trigliceridos", "tg", "trigliceridios"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7378-8d4e-315854e76b94';
UPDATE lab_test_definitions SET unit='células/µL', specimen_type='Sangue', alt_names='["eosinofilos (absoluto)", "eosinofilos absolutos", "contagem absoluta de eosinofilos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7c82-8577-43bdb4466300';
UPDATE lab_test_definitions SET unit='nmol/L', specimen_type='Sangue', alt_names='["lipoproteina a", "lipoproteina (a)", "lp(a)", "lpa"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7a4e-b370-d6ee192553f8';
UPDATE lab_test_definitions SET unit='g/dL', specimen_type='Sangue', alt_names='["alfa-2 globulina", "alfa-2-globulina", "α2-globulina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7472-8d9d-c3c1b6cbf412';
UPDATE lab_test_definitions SET unit='U/mL', specimen_type='Sangue', alt_names='["anti-transglutaminase iga", "anticorpos anti-transglutaminase tecidual iga", "transglutaminase tecidual - anticorpos iga", "anti-transglutaminase iga"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7a09-b53b-eba1930b5f11';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["gasometria venosa", "gasometria e eletrolitos, venosa", "gases sanguineos venosos", "equilibrio acido-base venoso"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-770e-ab46-43b3a80c69b6';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["apolipoproteina a1", "apolipoproteina a-i", "apo a1", "apo a-i", "apolipoproteina a-1"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7759-b788-fef56a1e8305';
UPDATE lab_test_definitions SET unit='µg/L', specimen_type='Sangue', alt_names='["manganes", "manganes serico", "manganes plasmatico", "manganes sanguineo", "manganes sangue total"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7170-8691-3a919a5fc657';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["ldl colesterol", "colesterol ldl", "ldl-colesterol", "lipoproteina de baixa densidade", "colesterol ldl dosagem", "ldl", "colesterol fracao ldl"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7ca3-90d8-48c88e24f0de';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='019ec829-03dd-7e4e-b0c1-a029053c17e9';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='019ec882-4bd1-7cfc-83e0-58696ced5f38';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["igf-1 (somatomedina c)", "somatomedina c", "fator de crescimento semelhante a insulina tipo 1", "igf1", "igf-1 (20-30 anos)", "igf-1 (31-50 anos)", "igf-1 (51-70 anos)", "igf-1 (70+ anos)", "igf-1", "somatomedina c/igf-1"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-70dc-9d37-8a9f58acc823';
UPDATE lab_test_definitions SET unit='ng/mL FEU', specimen_type='Sangue', alt_names='["d-dimero", "dimero d", "dimero-d"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7920-97ed-89d5cb4cf257';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["fosforo", "fosforo serico", "fosforo, soro", "fosforo inorganico", "fosfato serico", "fosfato", "p"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7cab-a13b-239fdcff5780';
UPDATE lab_test_definitions SET unit='U/L', specimen_type='Sangue', alt_names='["transaminase oxalacetica (ast)", "transaminase oxalacetica", "tgo", "aspartato aminotransferase", "transaminase glutamica oxalacetica", "ast", "tgo/ast", "ast/tgo", "tgo - aspartato aminotransferase", "ast/tgo/aspartato aminotransferase"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7de5-9dcc-152247891a06';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["matsuda index", "indice de matsuda", "isi matsuda", "insulin sensitivity index matsuda"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-770c-bbdf-4dbf01824f24';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["anti-la (ssb)", "anticorpos anti-la", "anticorpos anti-ssb", "anti-la/ssb", "anticorpos para sjogren"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7c4f-85cb-d60b999630a6';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Urina', alt_names='["cadmio urina 24h", "cadmio urinario 24 horas", "cadmio urina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7f0d-81f9-ffe52419ee89';
UPDATE lab_test_definitions SET unit='mg/L', specimen_type='Sangue', alt_names='["pcr ultrassensivel", "proteina c reativa ultrassensivel", "proteina c reativa de alta sensibilidade", "proteina c reativa quantitativa ultrassensivel", "pcr cardiaca", "proteina c reativa", "pcr", "proteina c reativa/ultra-sensivel", "pcr-us"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-72c0-b6ef-24438e187388';
UPDATE lab_test_definitions SET unit='mEq/L', specimen_type='Sangue', alt_names='["sodio", "sodio serico", "sodio soro", "natremia", "na"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-74c3-a62b-c9aeeacbc87f';
UPDATE lab_test_definitions SET unit='U/L', specimen_type='Sangue', alt_names='["fosfatase alcalina", "fosfatase alcalina, soro", "fosfatase alcalina serica", "fa", "alp"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7bf9-bec6-d849ba213218';
UPDATE lab_test_definitions SET unit='Fórmula: 1/[log(I₀)+log(G₀)]', specimen_type='Sangue', alt_names='["quicki", "indice quicki", "quantitative insulin sensitivity check index", "indice de sensibilidade a insulina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-774c-8da4-f08c35673f1a';
UPDATE lab_test_definitions SET unit='Descritivo', specimen_type='Urina', alt_names='["muco - sedimento", "muco no sedimento urinario", "filamentos de muco"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7797-8890-cbeadef93bfa';
UPDATE lab_test_definitions SET unit='µmol/L', specimen_type='Sangue', alt_names='["homocisteina", "homocisteina total no plasma", "homocisteina no plasma", "homocisteina no sangue", "dosagem de homocisteina", "homocisteina total", "hcy"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7ed0-853c-b4976cb9c9ea';
UPDATE lab_test_definitions SET unit='cilindros/campo', specimen_type='Sangue', alt_names='["cilindros patologicos", "cilindros hematicos", "cilindros leucocitarios", "cilindros granulosos", "cilindros cereos", "cilindros de celulas epiteliais"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7c77-a25b-76c7c15c9496';
UPDATE lab_test_definitions SET unit='mEq/L', specimen_type='Sangue', alt_names='["hco3 (bicarbonato)", "bicarbonato", "bicarbonato (reserva alcalina)", "bicarbonato standard"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7242-b47c-ae88e99456f1';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["eletroforese de proteinas", "proteinograma", "proteinograma eletroforetico", "eletroforese de proteinas sericas", "proteinas, eletroforese, soro"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7738-89c7-ccaabf564e85';
UPDATE lab_test_definitions SET unit='mmHg', specimen_type='Sangue', alt_names='["po2 venoso", "pressao parcial de oxigenio venoso", "pvo2"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7222-be76-3bb2b95157bc';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["calcio ionico", "calcio ionizado", "ca++", "calcio ionizado (ca++)", "calcio ionizavel", "calcio livre"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7474-9d93-de54177adb25';
UPDATE lab_test_definitions SET unit='unidade', specimen_type='Sangue', alt_names='["ph venoso", "ph gasometria venosa", "ph sangue venoso"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7be1-a1fe-90504cc98bae';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='019ec882-4bd1-77dc-8c1c-c26411aab2e2';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='019ec882-4bd1-794f-88b6-22eb8562df4d';
UPDATE lab_test_definitions SET unit='pg', specimen_type='Sangue', alt_names='["hcm (mch)", "hemoglobina corpuscular media", "hcm"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-76bf-8f36-93b3a35dad1c';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Urina', alt_names=NULL, updated_at=NOW() WHERE id='019ec829-03dd-72cf-899e-6301d2a46d26';
UPDATE lab_test_definitions SET unit='ng/mL', specimen_type='Sangue', alt_names='["ferritina", "ferritina - homens", "ferritina - mulheres pre-menopausa", "ferritina - mulheres pos-menopausa", "ferritina serica", "ferro ferritina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-739b-bf30-8e198d57667a';
UPDATE lab_test_definitions SET unit='U/mL', specimen_type='Sangue', alt_names='["gliadina deaminada iga (dgp-iga)", "anticorpo anti-gliadina deaminada iga", "anti-dgp iga", "gliadina deaminada, anticorpo iga"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7cd8-848b-b371b7b27449';
UPDATE lab_test_definitions SET unit='µg/dL', specimen_type='Sangue', alt_names='["vitamina a - dosagem", "vitamina a", "retinol", "vitamina a serica"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7aec-8e84-694059ae0dd0';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='019ec865-91df-7e5a-87c2-28b00f5a9a1a';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Saliva', alt_names=NULL, updated_at=NOW() WHERE id='019ec927-6863-7796-88c5-8e1fa726da37';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Saliva', alt_names=NULL, updated_at=NOW() WHERE id='019ec927-6860-73d1-8397-8674e769a0bc';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Saliva', alt_names=NULL, updated_at=NOW() WHERE id='019ec882-4bd1-77f5-aade-a5952762d3d3';
UPDATE lab_test_definitions SET unit='k/µL', specimen_type='Sangue', alt_names='["linfocitos (absoluto)", "linfocitos absoluto", "linfocitos valor absoluto", "numero absoluto de linfocitos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7cde-a16b-c0610dbb17f7';
UPDATE lab_test_definitions SET unit='µUI/mL', specimen_type='Sangue', alt_names='["insulina 90 min", "insulina 90 minutos", "insulina apos 90 minutos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-77d7-b102-3792524056ce';
UPDATE lab_test_definitions SET unit='Qualitativo', specimen_type='Sangue', alt_names='["hepatite b - hbsag", "antigeno de superficie da hepatite b", "antigeno australia", "hepatite b antigeno de superficie"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-79df-b8e4-f8169f60a6e2';
UPDATE lab_test_definitions SET unit='mIU/L', specimen_type='Sangue', alt_names='["tsh", "hormonio tireoestimulante", "tsh ultrassensivel", "tireotrofina", "tsh/hormonio tireoestimulante", "tsh - tireoestimulante", "hormonio tireo estimulante"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7dcb-b106-0bd0d2f2fe9f';
UPDATE lab_test_definitions SET unit='Qualitativo', specimen_type='Sangue', alt_names='["bilirrubina", "bilirrubina urinaria", "bilirrubina na urina", "pesquisa de bilirrubina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7a63-a6f5-e6df6cb1962a';
UPDATE lab_test_definitions SET unit='nmol/L', specimen_type='Sangue', alt_names='["vitamina b2 por hplc em sangue total", "vitamina b2", "riboflavina", "vitamina b2 sangue total"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7077-85f1-6213af521928';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["capacidade de fixacao de ferro - ist", "indice de saturacao da transferrina", "saturacao da transferrina", "capacidade total de ligacao do ferro", "capacidade de ligacao de ferro", "capacidade de fixacao do ferro", "capacidade de fixacao de ferro", "tibc", "ctlf", "ist"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7698-87c6-b23d1390e90f';
UPDATE lab_test_definitions SET unit='Qualitativo', specimen_type='Sangue', alt_names='["hiv 1+2", "anticorpos anti-hiv 1 e 2", "sorologia para hiv 1 e 2", "retrovirus anticorpos totais", "anti-hiv 1+2", "hiv 1 e 2", "pesquisa de antigeno e anticorpos hiv", "hiv combo", "hiv ag/ac", "hiv 1 e 2 pesquisa de antigeno e anticorpos", "hiv pesquisa de antigeno e anticorpos", "antigeno e anticorpos hiv"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-78a9-a52e-2083d80a2877';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["apob / apoa1", "razao apob/apoa1", "indice apob/apoa1", "relacao apolipoproteina b apolipoproteina a1"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7b3d-80be-1db370caf22b';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names='["hemograma completo", "hemograma", "eritrograma + leucograma + plaquetas", "hemograma com contagem de plaquetas"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-72c3-b84e-f18f7199a091';
UPDATE lab_test_definitions SET unit='U/L', specimen_type='Sangue', alt_names='["ldl oxidada", "ldl oxidada anticorpos", "lipoproteina de baixa densidade oxidada", "anti ldl oxidada", "auto-anticorpos anti ldl oxidada"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7f21-98e1-ba0682a5b6ab';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["linfocitos (percentual)", "linfocitos percentual", "linfocitos relativo", "linfocitos valor relativo"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-79ac-b609-1e7c630c8c2e';
UPDATE lab_test_definitions SET unit='ng/dL', specimen_type='Sangue', alt_names='["testosterona total", "testosterona total - homens", "testosterona total - mulheres pre-menopausa", "testosterona total - mulheres pos-menopausa", "testosterona total serica", "total testosterone", "testosterona", "testosterona plasmatica", "testosterona serica"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-710c-820c-7f5f0ef7b817';
UPDATE lab_test_definitions SET unit='células/µL', specimen_type='Sangue', alt_names='["basofilos (absoluto)", "basofilos absolutos", "contagem absoluta de basofilos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7b56-b49f-d0620692ffc6';
UPDATE lab_test_definitions SET unit='Descritivo', specimen_type='Urina', alt_names='["cor da urina", "cor da urina amarelo citrino", "coloracao da urina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-74f1-9944-f37042a9e8d6';
UPDATE lab_test_definitions SET unit='ng/L', specimen_type='Sangue', alt_names='["troponina i ultrassensivel", "troponina i ultrassensivel - homens", "troponina i ultrassensivel - mulheres", "troponina i de alta sensibilidade", "hs-tni"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-70cf-b762-8b518d7d7f7e';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["fibrinogenio", "fator i", "fator 1", "fibrinogenio coagulavel"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-710e-8453-4094aeee87ea';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Urina', alt_names='["glicose urinaria", "glicosuria", "glicose na urina", "glicose urina"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7642-b527-99eedc496ccb';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["psa livre/total (%free psa)", "relacao psa livre/psa total", "percentual de psa livre", "razao psa livre/total", "psa livre", "psa livre/total", "%free psa"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-77b9-b379-b9a0c78162b1';
UPDATE lab_test_definitions SET unit='mUI/mL', specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='019eb9bd-22b9-77c9-871a-640044788b9a';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["imunoglobulina a (iga)", "imunoglobulina a", "dosagem de iga"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7106-be4e-ed9c38c357ba';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["acido urico", "uricemia", "acido urico serico", "urato", "acido urico total"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7249-95cf-7fe017130d95';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["ureia", "ureia serica", "ureia soro", "nitrogenio ureico no sangue", "bun"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7404-a097-798cb4cc6a83';
UPDATE lab_test_definitions SET unit='k/µL', specimen_type='Sangue', alt_names='["monocitos (absoluto)", "monocitos absolutos", "contagem absoluta de monocitos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7e71-a02d-3e7124bd0444';
UPDATE lab_test_definitions SET unit='mmHg', specimen_type='Sangue', alt_names='["pco2 venoso", "pressao parcial de co2 venoso", "pco2 gasometria venosa", "pco2 venoso"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7de2-a8b1-7382f0dd3c6e';
UPDATE lab_test_definitions SET unit='µg/dL', specimen_type='Sangue', alt_names='["ferro", "ferro serico", "ferro soro", "siderose", "sideremia"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7053-a1cc-abe1541e702c';
UPDATE lab_test_definitions SET unit='IU/mL', specimen_type='Sangue', alt_names='["anti-tpo", "anticorpos anti-tireoperoxidase", "anticorpos antitiroperoxidase", "tireoperoxidase", "anticorpos antiperoxidase", "anti tpo", "anti-tpo/tireoperoxidase"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7eef-ac07-b8709ad0042c';
UPDATE lab_test_definitions SET unit='μg/mL', specimen_type='Sangue', alt_names='["adiponectina", "adipoq", "acrp30"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7548-839a-262e8f07bc49';
UPDATE lab_test_definitions SET unit='µUI/mL', specimen_type='Sangue', alt_names='["insulina 30 min", "insulina 30 minutos", "insulina apos 30 minutos"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7720-94fb-e3ac1dde4d42';
UPDATE lab_test_definitions SET unit='mg/dL', specimen_type='Sangue', alt_names='["magnesio serico", "magnesio soro", "magnesemia", "magnesio no soro", "dosagem de magnesio no soro", "magnesio", "mg"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7b78-9681-7ddada0b2f7c';
UPDATE lab_test_definitions SET unit='µg/L', specimen_type='Sangue', alt_names='["selenio", "selenio serico", "selenio plasma", "se"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-7656-b5c2-b4b5cec35400';
UPDATE lab_test_definitions SET unit='U/mL', specimen_type='Sangue', alt_names='["ca-125", "ca 125", "ca125", "antigeno carboidrato 125", "marcador tumoral ca125", "ca 125-2", "ca 125ii"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-76c8-a6f5-53bafe3b7cae';
UPDATE lab_test_definitions SET unit='pg/mL', specimen_type='Sangue', alt_names='["estradiol", "estradiol - homens", "estradiol - mulheres fase folicular inicial (dias 1-7)", "estradiol - mulheres fase lutea (dias 19-21)", "estradiol - mulheres fase ovulatoria (pico meio do ciclo)", "estradiol - mulheres pos-menopausa (com trh)", "estradiol - mulheres pos-menopausa (sem trh)", "17-beta estradiol", "estradiol serico", "e2"]'::jsonb, updated_at=NOW() WHERE id='019bf793-96eb-723f-b177-46fe64b1d179';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='0d6417c0-9368-4540-839d-3d1449894789';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Urina', alt_names=NULL, updated_at=NOW() WHERE id='019ec829-03dd-7a82-a057-7ba73d3a52bf';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='019ec847-5d4e-7c9b-be0b-2c6907c01712';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='019ec882-4bd1-7c76-92bf-6042c63afefd';
UPDATE lab_test_definitions SET unit=NULL, specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='019ec829-03dd-7228-95f9-8dbff5c4d468';
UPDATE lab_test_definitions SET unit='segundos', specimen_type='Sangue', alt_names=NULL, updated_at=NOW() WHERE id='0c9e7d10-0000-7000-8000-0000000000a2';
UPDATE lab_test_definitions SET unit='%', specimen_type='Sangue', alt_names='["promielocitos", "promielocitos percentual", "promielo"]'::jsonb, updated_at=NOW() WHERE id='019c3603-59e2-7cfa-9940-548e104eab8b';
UPDATE lab_test_definitions SET unit='fL', specimen_type='Sangue', alt_names='["vmp", "volume medio plaquetario", "mpv", "mean platelet volume"]'::jsonb, updated_at=NOW() WHERE id='11bebd18-cacf-4dbd-884f-0f6acf622ba1';
UPDATE lab_test_definitions SET unit='fL', specimen_type='Sangue', alt_names='["vpm", "volume plaquetario medio", "mpv", "mean platelet volume"]'::jsonb, updated_at=NOW() WHERE id='019c3603-59e8-70aa-8956-a45dceafa48e';

-- ===== lab_test_definitions: 4 defs novos (Prolinfócitos / Linfócitos atípicos) =====
INSERT INTO lab_test_definitions (id, code, name, short_name, tuss_code, loinc_code, category, is_requestable, parent_test_id, unit, unit_conversion, result_type, collection_method, fasting_hours, specimen_type, description, clinical_indications, display_order, is_active, created_at, updated_at, deleted_at, clinical_significance, longevity_context, clinical_recommendations, alt_names, sex_applicability, request_justification) VALUES ('ded3b219-52a1-4c45-a6c2-3b4432cca36b', 'PROLINFP', 'Prolinfócitos (percentual)', NULL, NULL, NULL, 'hematology', false, NULL, '%', NULL, 'numeric', NULL, NULL, 'Sangue', NULL, NULL, 0, true, '2026-06-27 21:14:11.030975-03', '2026-06-27 21:14:11.030975-03', NULL, NULL, NULL, NULL, NULL, 'all', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lab_test_definitions (id, code, name, short_name, tuss_code, loinc_code, category, is_requestable, parent_test_id, unit, unit_conversion, result_type, collection_method, fasting_hours, specimen_type, description, clinical_indications, display_order, is_active, created_at, updated_at, deleted_at, clinical_significance, longevity_context, clinical_recommendations, alt_names, sex_applicability, request_justification) VALUES ('60d1203a-eed9-4dd1-8912-f84f5e33e816', 'PROLINFA', 'Prolinfócitos (absoluto)', NULL, NULL, NULL, 'hematology', false, NULL, '/mm3', NULL, 'numeric', NULL, NULL, 'Sangue', NULL, NULL, 0, true, '2026-06-27 21:14:11.030975-03', '2026-06-27 21:14:11.030975-03', NULL, NULL, NULL, NULL, NULL, 'all', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lab_test_definitions (id, code, name, short_name, tuss_code, loinc_code, category, is_requestable, parent_test_id, unit, unit_conversion, result_type, collection_method, fasting_hours, specimen_type, description, clinical_indications, display_order, is_active, created_at, updated_at, deleted_at, clinical_significance, longevity_context, clinical_recommendations, alt_names, sex_applicability, request_justification) VALUES ('f22e33fe-9941-4e2b-a6e0-a8df79e67576', 'LINFATIPP', 'Linfócitos atípicos (percentual)', NULL, NULL, NULL, 'hematology', false, NULL, '%', NULL, 'numeric', NULL, NULL, 'Sangue', NULL, NULL, 0, true, '2026-06-27 21:14:11.030975-03', '2026-06-27 21:14:11.030975-03', NULL, NULL, NULL, NULL, NULL, 'all', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lab_test_definitions (id, code, name, short_name, tuss_code, loinc_code, category, is_requestable, parent_test_id, unit, unit_conversion, result_type, collection_method, fasting_hours, specimen_type, description, clinical_indications, display_order, is_active, created_at, updated_at, deleted_at, clinical_significance, longevity_context, clinical_recommendations, alt_names, sex_applicability, request_justification) VALUES ('924abcfa-f5bb-4f42-9572-a182ec347e31', 'LINFATIPA', 'Linfócitos atípicos (absoluto)', NULL, NULL, NULL, 'hematology', false, NULL, '/mm3', NULL, 'numeric', NULL, NULL, 'Sangue', NULL, NULL, 0, true, '2026-06-27 21:14:11.030975-03', '2026-06-27 21:14:11.030975-03', NULL, NULL, NULL, NULL, NULL, 'all', NULL) ON CONFLICT (id) DO NOTHING;

-- ===== lab_test_unit_conversions: 3 conversões dos sedimentos (/µL <-> /mL, x1000) =====
INSERT INTO lab_test_unit_conversions (id, lab_test_definition_id, main_unit, secondary_unit, conversion_factor, created_at, updated_at)
SELECT 'e8e165ef-f372-4a5e-9a94-815c459af66e', d.id, '/µL', '/mL', 1000, NOW(), NOW()
FROM lab_test_definitions d WHERE d.code='PLN6B5C27A4' ON CONFLICT (id) DO NOTHING;
INSERT INTO lab_test_unit_conversions (id, lab_test_definition_id, main_unit, secondary_unit, conversion_factor, created_at, updated_at)
SELECT '9536d3c3-7f2b-4047-8e20-64bf5c71eb7e', d.id, '/µL', '/mL', 1000, NOW(), NOW()
FROM lab_test_definitions d WHERE d.code='PLN0CE7409E' ON CONFLICT (id) DO NOTHING;
INSERT INTO lab_test_unit_conversions (id, lab_test_definition_id, main_unit, secondary_unit, conversion_factor, created_at, updated_at)
SELECT 'cd72e4b9-6802-40d0-b8c0-d9bb53d00a1b', d.id, '/µL', '/mL', 1000, NOW(), NOW()
FROM lab_test_definitions d WHERE d.code='PLN444CDDE8' ON CONFLICT (id) DO NOTHING;

-- ===== score_levels: 11 itens (re-base / gate clínico) =====
UPDATE score_levels SET level=5, operator='<=', lower_limit=NULL, upper_limit='15', name='≤15', updated_at=NOW() WHERE id='019bf31d-2ef0-7af7-9ef1-717b0d55575c';
UPDATE score_levels SET level=4, operator='between', lower_limit='15', upper_limit='31', name='15-31', updated_at=NOW() WHERE id='019bf31d-2ef0-7520-aca9-3767c5ffb356';
UPDATE score_levels SET level=3, operator='between', lower_limit='31', upper_limit='60', name='31-60', updated_at=NOW() WHERE id='019bf31d-2ef0-782b-a472-82ca80c75c42';
UPDATE score_levels SET level=2, operator='between', lower_limit='60', upper_limit='100', name='60-100', updated_at=NOW() WHERE id='019bf31d-2ef0-7b3f-a698-576e5008b805';
UPDATE score_levels SET level=1, operator='between', lower_limit='100', upper_limit='200', name='100-200', updated_at=NOW() WHERE id='019bf31d-2ef0-7384-a1b5-c1f1c65b983a';
UPDATE score_levels SET level=0, operator='>', lower_limit='200', upper_limit=NULL, name='>200 (Contaminação)', updated_at=NOW() WHERE id='019bf31d-2ef0-7a60-a4d2-7d0470b8cb6d';
UPDATE score_levels SET level=5, operator='between', lower_limit='1.5', upper_limit='2', name='1.5 a 2 g/kg/dia', updated_at=NOW() WHERE id='019c5378-99e5-7395-94d1-09bc7df39b38';
UPDATE score_levels SET level=4, operator='between', lower_limit='1', upper_limit='1.5', name='1 a 1.5 g/kg/dia', updated_at=NOW() WHERE id='019c5378-99de-7bb8-b570-52d6d7e2a09a';
UPDATE score_levels SET level=3, operator='between', lower_limit='2', upper_limit='2.5', name='2 a 2.5 g/kg/dia', updated_at=NOW() WHERE id='019c5378-99c0-7527-a7fd-c6c103cfc22c';
UPDATE score_levels SET level=1, operator='>', lower_limit='2.5', upper_limit=NULL, name='>2.5 g/kg/dia', updated_at=NOW() WHERE id='019c537b-54a0-7924-ada4-fdfeb678ac16';
UPDATE score_levels SET level=0, operator='<', lower_limit='1', upper_limit=NULL, name='< 1 g/kg/dia', updated_at=NOW() WHERE id='019c5378-98a7-7b35-b8d2-01f3f71fc5e0';
UPDATE score_levels SET level=5, operator='<=', lower_limit=NULL, upper_limit='125', name='≤125 (s/ placa)', updated_at=NOW() WHERE id='019bf7af-d85e-7811-8a16-90f2dfdcec57';
UPDATE score_levels SET level=1, operator='between', lower_limit='125', upper_limit='230', name='125-230', updated_at=NOW() WHERE id='019bf7af-d85e-7e94-92ff-293ce49d63ad';
UPDATE score_levels SET level=0, operator='>', lower_limit='230', upper_limit=NULL, name='>230', updated_at=NOW() WHERE id='019bf7af-d85e-7e06-8559-2801e42c6a34';
UPDATE score_levels SET level=5, operator='between', lower_limit='30', upper_limit='200', name='30-200', updated_at=NOW() WHERE id='019bf31d-2ef0-7b65-8008-3799138c62b0';
UPDATE score_levels SET level=4, operator='between', lower_limit='200', upper_limit='350', name='200-350', updated_at=NOW() WHERE id='019bf31d-2ef0-78fd-9617-9f5558657d6a';
UPDATE score_levels SET level=3, operator='<=', lower_limit=NULL, upper_limit='30', name='≤30', updated_at=NOW() WHERE id='019bf31d-2ef0-7d14-9a85-32d00a471218';
UPDATE score_levels SET level=2, operator='between', lower_limit='350', upper_limit='500', name='350-500', updated_at=NOW() WHERE id='019bf31d-2ef0-784f-bd54-d6cfcf90971f';
UPDATE score_levels SET level=1, operator='between', lower_limit='500', upper_limit='1500', name='500-1500', updated_at=NOW() WHERE id='019bf31d-2ef0-711b-a294-84bbb597b56f';
UPDATE score_levels SET level=0, operator='>', lower_limit='1500', upper_limit=NULL, name='>1500', updated_at=NOW() WHERE id='019bf31d-2ef0-7b17-a6f6-14eccf15e38f';
UPDATE score_levels SET level=5, operator='between', lower_limit='60', upper_limit='85', name='60-85', updated_at=NOW() WHERE id='019bf7af-ba01-7608-aaef-e28d1f306c30';
UPDATE score_levels SET level=4, operator='between', lower_limit='85', upper_limit='100', name='85-100', updated_at=NOW() WHERE id='019bf7af-ba01-7528-8466-477c5abf7369';
UPDATE score_levels SET level=2, operator='<=', lower_limit=NULL, upper_limit='60', name='≤60', updated_at=NOW() WHERE id='019bf7af-ba01-7d1b-911c-4e809798bd51';
UPDATE score_levels SET level=1, operator='between', lower_limit='110', upper_limit='126', name='110-126', updated_at=NOW() WHERE id='019bf7af-ba01-7ae1-96c9-7ca18e02ca4f';
UPDATE score_levels SET level=0, operator='>', lower_limit='126', upper_limit=NULL, name='>126', updated_at=NOW() WHERE id='019bf7af-ba01-7886-ad6d-b0aededc8aed';
UPDATE score_levels SET level=5, operator='<=', lower_limit=NULL, upper_limit='5', name='≤5', updated_at=NOW() WHERE id='019bf31d-2ef0-7a34-a2af-0bd4aba0ca15';
UPDATE score_levels SET level=4, operator='between', lower_limit='5', upper_limit='25', name='5-25', updated_at=NOW() WHERE id='019bf31d-2ef0-7045-8bfe-e398af214987';
UPDATE score_levels SET level=3, operator='between', lower_limit='25', upper_limit='50', name='25-50', updated_at=NOW() WHERE id='019bf31d-2ef0-7780-aa31-cf497f374d8a';
UPDATE score_levels SET level=2, operator='between', lower_limit='50', upper_limit='100', name='50-100', updated_at=NOW() WHERE id='019bf31d-2ef0-7973-a743-36ddcfdc394a';
UPDATE score_levels SET level=1, operator='between', lower_limit='100', upper_limit='250', name='100-250', updated_at=NOW() WHERE id='019bf31d-2ef0-7336-9fab-fe6f4776a967';
UPDATE score_levels SET level=0, operator='>', lower_limit='250', upper_limit=NULL, name='>250', updated_at=NOW() WHERE id='019bf31d-2ef0-736e-8bfe-e173edebc9c4';
UPDATE score_levels SET level=5, operator='<=', lower_limit=NULL, upper_limit='10', name='≤10', updated_at=NOW() WHERE id='019bf7af-d85e-776b-9ab5-47116027e32e';
UPDATE score_levels SET level=4, operator='between', lower_limit='10', upper_limit='25', name='10-25', updated_at=NOW() WHERE id='019bf7af-d85e-74d4-9951-68cf9578dabc';
UPDATE score_levels SET level=3, operator='between', lower_limit='25', upper_limit='50', name='25-50', updated_at=NOW() WHERE id='019bf7af-d85e-7f8c-a99d-3da3f631e6c4';
UPDATE score_levels SET level=2, operator='between', lower_limit='50', upper_limit='100', name='50-100', updated_at=NOW() WHERE id='019bf7af-d85e-709d-b8e7-307bea733d40';
UPDATE score_levels SET level=1, operator='between', lower_limit='100', upper_limit='250', name='100-250', updated_at=NOW() WHERE id='019bf7af-d85e-7124-95ba-42d64263897f';
UPDATE score_levels SET level=0, operator='>', lower_limit='250', upper_limit=NULL, name='>250', updated_at=NOW() WHERE id='019bf7af-d85e-718d-a5a6-2ddb8440b25c';
UPDATE score_levels SET level=5, operator='between', lower_limit='0.2', upper_limit='0.45', name='0,2-0,45', updated_at=NOW() WHERE id='019bf7af-ba01-7a1e-b4d5-78abdee46c1f';
UPDATE score_levels SET level=4, operator='between', lower_limit='0.45', upper_limit='0.65', name='0,45-0,65', updated_at=NOW() WHERE id='019bf7af-ba01-77d7-9b9f-c9c938bca1ea';
UPDATE score_levels SET level=3, operator='between', lower_limit='0.65', upper_limit='0.85', name='0,65-0,85', updated_at=NOW() WHERE id='019bf7af-ba01-73ed-b545-3f4edcf08f6f';
UPDATE score_levels SET level=2, operator='between', lower_limit='0.85', upper_limit='1.0', name='0,85-1,0', updated_at=NOW() WHERE id='019bf7af-ba01-72dd-849d-64807c35042d';
UPDATE score_levels SET level=1, operator='<=', lower_limit=NULL, upper_limit='0.2', name='≤0,2', updated_at=NOW() WHERE id='019bf7af-ba01-7afe-a57b-1a881f792256';
UPDATE score_levels SET level=0, operator='>', lower_limit='1.0', upper_limit=NULL, name='>1,0', updated_at=NOW() WHERE id='019bf7af-ba01-7de8-9d66-5fd060ca28f5';
UPDATE score_levels SET level=5, operator='between', lower_limit='5.5', upper_limit='7.0', name='5,5-7', updated_at=NOW() WHERE id='019bf7af-d85e-7081-98ee-2e5a81d86636';
UPDATE score_levels SET level=4, operator='between', lower_limit='4.5', upper_limit='5.5', name='4,5-5,5', updated_at=NOW() WHERE id='019bf7af-d85e-71a8-87bd-31bf6e3f335f';
UPDATE score_levels SET level=3, operator='between', lower_limit='7.0', upper_limit='7.5', name='7-7,5', updated_at=NOW() WHERE id='019bf7af-d85e-71ae-a41f-183f01921824';
UPDATE score_levels SET level=2, operator='between', lower_limit='7.5', upper_limit='8.0', name='7,5-8', updated_at=NOW() WHERE id='019bf7af-d85e-70ec-a22d-1a3464e9b022';
UPDATE score_levels SET level=1, operator='<=', lower_limit=NULL, upper_limit='4.5', name='≤4,5', updated_at=NOW() WHERE id='019bf7af-d85e-784d-9735-e4f249295a02';
UPDATE score_levels SET level=0, operator='>', lower_limit='8.0', upper_limit=NULL, name='>8', updated_at=NOW() WHERE id='019bf7af-d85e-7375-b5cb-a4b9ca24974d';
UPDATE score_levels SET level=5, operator='>', lower_limit='27', upper_limit=NULL, name='28 ou mais dias no mês', updated_at=NOW() WHERE id='019c53a6-7435-7914-bd09-9cf2481a1180';
UPDATE score_levels SET level=4, operator='between', lower_limit='24', upper_limit='27', name='24 a 27 dias no mês', updated_at=NOW() WHERE id='019c53a6-7412-71ea-b7d9-0b591c56624b';
UPDATE score_levels SET level=2, operator='between', lower_limit='21', upper_limit='24', name='21 a 24 dias no mês', updated_at=NOW() WHERE id='019c53a6-7409-7e50-9d61-5868b2b053f4';
UPDATE score_levels SET level=1, operator='between', lower_limit='17', upper_limit='21', name='18 a 21 dias no mês', updated_at=NOW() WHERE id='019c53a6-73f0-7767-a953-7718cf7e6947';
UPDATE score_levels SET level=0, operator='<=', lower_limit=NULL, upper_limit='17', name='17 ou menos  dias no mês', updated_at=NOW() WHERE id='019c53a6-72d2-7918-b003-681af14896cd';
UPDATE score_levels SET level=5, operator='>', lower_limit='27', upper_limit=NULL, name='>=28 dias no mês', updated_at=NOW() WHERE id='019c53a4-79b4-7d0c-8bab-d0bddbc09b6d';
UPDATE score_levels SET level=4, operator='between', lower_limit='24', upper_limit='27', name='24 a 27 dias no mês', updated_at=NOW() WHERE id='019c53a3-1ab1-750a-808c-55982923a256';
UPDATE score_levels SET level=2, operator='between', lower_limit='21', upper_limit='24', name='21 a 24 dias no mês', updated_at=NOW() WHERE id='019c53a3-1aa7-77c7-8283-a887c289eb23';
UPDATE score_levels SET level=1, operator='between', lower_limit='17', upper_limit='21', name='18 a 21 dias no mês', updated_at=NOW() WHERE id='019c53a3-1a9e-764b-9c66-f9189fce46f8';
UPDATE score_levels SET level=0, operator='<=', lower_limit=NULL, upper_limit='17', name='<= 17  dias no mês', updated_at=NOW() WHERE id='019c53a3-1966-734c-9f10-3de7d219649e';

-- score_levels: soft-delete da L3 ≤125 duplicada do Doppler PSV Carótida Interna
UPDATE score_levels SET deleted_at=NOW(), updated_at=NOW() WHERE id='019bf7af-d85e-7517-8cb3-b4c62a1be199';
-- score_levels: L3 nova da Glicemia (100-110) — id gerado no dev (dev≡prod)
INSERT INTO score_levels (id, level, name, operator, lower_limit, upper_limit, item_id, created_at, updated_at)
SELECT '019f0bcc-6d28-7c3e-936d-1e0196dbc81d', 3, '100-110', 'between', '100', '110', si.id, NOW(), NOW()
FROM score_items si WHERE si.name='GLICOSE 0 MIN (JEJUM)' AND si.deleted_at IS NULL
ON CONFLICT (id) DO NOTHING;

-- +goose Down
-- Reverte inserts e o soft-delete; os UPDATEs de campo (218 defs + 59 níveis) rollback via backup pré-deploy.
DELETE FROM lab_test_unit_conversions WHERE id IN ('e8e165ef-f372-4a5e-9a94-815c459af66e','9536d3c3-7f2b-4047-8e20-64bf5c71eb7e','cd72e4b9-6802-40d0-b8c0-d9bb53d00a1b');
DELETE FROM lab_test_definitions WHERE code IN ('PROLINFP','PROLINFA','LINFATIPP','LINFATIPA');
DELETE FROM score_levels WHERE id='019f0bcc-6d28-7c3e-936d-1e0196dbc81d';
UPDATE score_levels SET deleted_at=NULL, updated_at=NOW() WHERE id='019bf7af-d85e-7517-8cb3-b4c62a1be199';
