-- Continuação Batch 6.2

-- Item 17: Imunobiológicos
UPDATE score_items
SET
  clinical_significance = 'Imunobiológicos são medicamentos de origem biológica (anticorpos monoclonais, proteínas recombinantes) que modulam sistema imune com alta especificidade. Incluem anti-TNF (infliximabe, adalimumabe), anti-IL (ustekinumabe, secukinumabe), anti-CD20 (rituximabe). Usados em doenças autoimunes e inflamatórias refratárias (artrite reumatoide, doença inflamatória intestinal, psoríase, espondilite). Custo elevado, risco infecções.',

  functional_aspects = 'Fisiopatologia: Doenças autoimunes envolvem desregulação imune com citocinas pró-inflamatórias (TNF-alfa, IL-17, IL-23, IL-6). Imunobiológicos bloqueiam vias específicas, reduzindo inflamação e dano tecidual. Efeitos adversos: (1) Infecções oportunistas (tuberculose latente, fúngicas, virais); (2) Reativação hepatite B; (3) Reações infusionais; (4) Aumento discreto risco câncer (linfoma - controverso); (5) Desmielinização (raro); (6) Insuficiência cardíaca (anti-TNF); (7) Citopenias. MFI: reduzir inflamação de base (dieta, intestino, estresse), suporte imune equilibrado, prevenir infecções.',

  risk_factors = 'Causas raiz MFI autoimunidade: (1) Permeabilidade intestinal (leaky gut) - translocação antígenos; (2) Disbiose severa - perda tolerância oral; (3) Mimetismo molecular (glúten, infecções); (4) Deficiência vitamina D (Tregs comprometidos); (5) Estresse crônico (desregula Th1/Th2/Th17); (6) Toxinas ambientais (metais pesados, solventes, pesticidas); (7) Infecções crônicas (EBV, CMV); (8) Polimorfismos (HLA, PTPN22, CTLA4); (9) Estrogênio (mulheres>homens); (10) Estresse oxidativo.',

  recommendations = 'Protocolo MFI com imunobiológicos: (1) Modulação intestinal: (a) Dieta eliminação (glúten, lácteos, ovos, soja, milho por 30-60 dias), (b) Protocolo 5R (Remove-Replace-Reinoculate-Repair-Rebalance), (c) L-glutamina 15-20g/dia, (d) Zinco-carnosina 150mg, (e) Probióticos: Lactobacillus plantarum, Bifidobacterium infantis, Saccharomyces boulardii, (f) Prebióticos: inulina, GOS; (2) Vitamina D3: 5000-10000UI (alvo >60ng/mL) - imunomodulação, induz Tregs; (3) Ômega-3: EPA 3-4g/dia (resolvinas anti-inflamatórias); (4) Curcumina: 1000-2000mg lipossomal (inibe NFkB, múltiplas vias); (5) Moduladores Nrf2: sulforafano 30mg, EGCG 400mg (antioxidante, anti-inflamatório); (6) Vitamina A: 10000-25000UI (Tregs, mucosas) - monitorar; (7) Glutationa: NAC 1800mg, glutationa lipossomal (detox, antioxidante); (8) Controle glicêmico: berberina 1500mg (AGEs inflamatórios); (9) Suporte mitocondrial: CoQ10 300mg, PQQ 20mg (reduz citocinas); (10) Magnésio: 400-600mg (Tregs, estresse); (11) Manejo estresse: mindfulness 20min/dia, yoga, psicoterapia; (12) Sono: 8h (reparador imune); (13) Exercício moderado: 150min/semana (anti-inflamatório) - evitar overtraining; (14) Evitar toxinas: pesticidas (orgânicos), plásticos (BPA), metais pesados; (15) Detox suave: sauna, hidratação, fibras; (16) Profilaxia infecções: (a) Vacinas antes de iniciar (não vivas), (b) Teste tuberculose (PPD, IGRA), (c) Hepatite B/C screening, (d) Probióticos contínuos, (e) Higiene rigorosa; (17) Monitorar: hemograma, função hepática, marcadores inflamatórios (PCR, VHS), vitamina D, ferritina; (18) Sinais alerta infecção: febre, tosse persistente, lesões cutâneas.',

  article_ids = ARRAY[]::uuid[]
WHERE id = '6c79c2b5-9042-4cf2-9572-77271dc50145';

-- Item 18: Imunossupressores
UPDATE score_items
SET
  clinical_significance = 'Imunossupressores tradicionais (azatioprina, metotrexato, ciclosporina, tacrolimus, micofenolato) suprimem sistema imune de forma não-específica. Usados em transplantes, doenças autoimunes graves, vasculites. Uso indica condição autoimune/inflamatória severa ou órgão transplantado. Risco infecções e câncer significativo.',

  functional_aspects = 'Mecanismos: Azatioprina (inibe síntese purinas), Metotrexato (inibe folato, proliferação linfócitos), Ciclosporina/Tacrolimus (inibem calcineurina, IL-2), Micofenolato (inibe síntese guanosina). Efeitos adversos: (1) Mielossupressão (leucopenia, anemia, trombocitopenia); (2) Hepatotoxicidade; (3) Nefrotoxicidade (ciclosporina, tacrolimus); (4) Infecções oportunistas (Pneumocystis, CMV, fúngicas); (5) Aumento risco câncer (pele, linfoma); (6) Fibrose pulmonar (metotrexato); (7) Teratogenicidade. MFI: suporte hepático/renal, prevenção infecções, monitoramento rigoroso, reduzir necessidade se possível via modulação raiz.',

  risk_factors = 'Similar ao item anterior (imunobiológicos) quanto a causas raiz autoimunidade. Adicional com imunossupressores: (1) Depleção folato (metotrexato) - homocisteína elevada, defeitos tubo neural; (2) Disfunção mitocondrial; (3) Estresse oxidativo massivo; (4) Depleção glutationa; (5) Permeabilidade intestinal exacerbada; (6) Disbiose severa com Candida.',

  recommendations = 'Protocolo MFI com imunossupressores: (1) Suporte folato (metotrexato): ácido folínico (leucovorin) 5-10mg 24h após dose OU ácido fólico 1-5mg/dia dias sem metotrexato - ESSENCIAL prevenir toxicidade; (2) Vitamina B12: 1000mcg (homocisteína); (3) Hepatoproteção: cardo mariano (silimarina) 300-600mg, NAC 1200-1800mg, ácido alfa-lipóico 600mg, colina 500mg; (4) Nefroproteção (ciclosporina/tacrolimus): hidratação abundante, CoQ10 200mg, ômega-3 2g, evitar AINEs; (5) Proteção medular: ácido fólico (azatioprina), vitamina B12, ferro se anemia; (6) Antioxidantes: NAC, glutationa lipossomal, vitamina C 2g, vitamina E 400UI, selênio 200mcg; (7) Suporte intestinal: probióticos, L-glutamina, zinco-carnosina, dieta anti-inflamatória; (8) Vitamina D3: 5000UI (alvo 50-70ng/mL) - imunomodulação; (9) Ômega-3: 2-3g (anti-inflamatório); (10) Profilaxia infecções: (a) Sulfametoxazol-trimetoprim 3x/semana (Pneumocystis se CD4<200), (b) Vacinas não-vivas antes iniciar, (c) Probióticos, (d) Higiene rigorosa, (e) Evitar contato doentes; (11) Proteção solar: FPS 50+ (risco câncer pele); (12) Evitar álcool (hepatotoxicidade); (13) Controle glicêmico: alguns aumentam risco diabetes; (14) Monitoramento: hemograma semanal (início) depois mensal, função hepática/renal, marcadores inflamatórios; (15) Interações: evitar grapefruit (ciclosporina, tacrolimus), alopurinol+azatioprina (grave); (16) Contracepção: teratogênicos (metotrexato, micofenolato); (17) Rastreamento câncer: exame pele anual, colonoscopia.',

  article_ids = ARRAY[]::uuid[]
WHERE id = 'b70b3945-f22e-4bff-b781-ebde75069941';

-- Item 19: Insulinas
UPDATE score_items
SET
  clinical_significance = 'Insulina exógena (ultrarrápida, rápida, intermediária, longa) é essencial para diabetes tipo 1 e indicada em tipo 2 avançado. Insulina regula glicemia, metabolismo lipídico/proteico, sinalização anabólica. Uso indica insuficiência de células beta pancreáticas (destruição autoimune T1, exaustão T2) ou resistência insulínica extrema.',

  functional_aspects = 'Fisiopatologia: DM1: autoimunidade contra células beta (GAD, IA-2, ZnT8 autoanticorpos), deficiência absoluta insulina. DM2: resistência insulínica periférica + disfunção beta (exaustão, glicotoxicidade, lipotoxicidade, amilina). Complicações hiperglicemia: (1) Microvasculares (retinopatia, nefropatia, neuropatia) por glicação (AGEs), estresse oxidativo, via poliol; (2) Macrovasculares (aterosclerose acelerada); (3) Infecções (imunidade comprometida). Insulinoterapia: risco hipoglicemia (grave se assintomática), ganho peso, lipodistrofia. MFI DM1: preservar células beta residuais, reduzir autoimunidade, prevenir complicações. MFI DM2: reverter resistência insulínica, restaurar função beta.',

  risk_factors = 'Causas raiz MFI DM1: (1) Permeabilidade intestinal na infância (glúten, proteínas leite); (2) Disbiose precoce; (3) Infecções virais (enterovírus, coxsackie); (4) Deficiência vitamina D (<30ng/mL); (5) Predisposição genética (HLA-DR3, DR4). DM2: (1) Resistência insulínica: obesidade visceral, dieta alto IG/carga glicêmica, sedentarismo, estresse crônico, sono inadequado; (2) Inflamação crônica (TNF-alfa, IL-6 bloqueiam sinalização insulina); (3) Estresse oxidativo mitocondrial; (4) Lipotoxicidade (ácidos graxos saturados); (5) Disbiose com endotoxemia; (6) Deficiências: cromo, magnésio, vitamina D; (7) Metais pesados.',

  recommendations = 'Protocolo MFI diabetes: (1) DM1 - preservação beta: (a) Vitamina D3 10000UI (alvo >60ng/mL) - imunomodulação, (b) Ômega-3 EPA 3g - reduz autoimunidade, (c) NAC 1800mg - antioxidante, preserva beta, (d) Eliminação glúten (mimetismo molecular), (e) Probióticos, L-glutamina (intestino); (2) DM2 - reversão resistência: (a) Berberina 1500mg/dia - eficácia similar metformina, ativa AMPK, (b) Ácido alfa-lipóico 600-1800mg - sensibilidade insulina, neuropatia, (c) Cromo picolinato 200-1000mcg - potencializa insulina, (d) Magnésio 400-600mg - cofator 300+ reações glicose, (e) Canela 1-6g/dia - mimetiza insulina, (f) Gymnema sylvestre 400mg - regeneração beta (estudos animais), reduz absorção glicose; (3) Controle glicêmico otimizado: (a) Dieta baixo IG/CG, mediterrânea/plant-based, (b) Jejum intermitente 16:8 (T2), (c) Contagem carboidratos (T1), (d) Exercício: aeróbico 150min + resistido 2x/semana; (4) Prevenção complicações: (a) Antioxidantes: vitamina E 400UI, vitamina C 1-2g, ácido alfa-lipóico (neuropatia), (b) Benfotiamina 300-600mg (tiamina lipofílica, previne AGEs), (c) Ômega-3 2-3g (micro/macrovascular), (d) Controle PA rigoroso (<130/80), (e) Estatina se indicado (RCV); (5) Neuropatia: ácido alfa-lipóico 600mg 3x/dia IV→oral, acetil-L-carnitina 2g, metilcobalamina 1mg; (6) Retinopatia: luteína 20mg, zeaxantina 4mg, controle glicêmico estrito; (7) Nefropatia: controle PA, ômega-3, evitar nefrotóxicos; (8) Suporte mitocondrial: CoQ10 200mg, L-carnitina 2g, PQQ 20mg; (9) Monitoramento: HbA1c <7% (individualizar), glicemia capilar, tempo no alvo (CGM >70%), lipídios, albuminúria, função renal, fundo olho, monofilamento (pés); (10) Hipoglicemia: glucagon kit, educar família, usar CGM com alarmes; (11) Cuidado pés: inspeção diária, calçados adequados, podologia.',

  article_ids = ARRAY[]::uuid[]
WHERE id = '1aab24a1-a23b-4398-a3a3-1f2d8a7954ce';

-- Item 20: Laxativos crônicos / Antidiarreicos crônicos
UPDATE score_items
SET
  clinical_significance = 'Uso crônico de laxativos (estimulantes, osmóticos, formadores de bolo) ou antidiarreicos (loperamida, difenoxilato) indica disfunção intestinal persistente. Laxativos crônicos sugerem constipação funcional, síndrome intestino lento, ou dependência medicamentosa. Antidiarreicos crônicos sugerem SII-D, DII, má absorção, SIBO. Na MFI, tratar causas raiz, não sintomas.',

  functional_aspects = 'Fisiopatologia constipação: (1) Trânsito lento (disfunção neuromuscular); (2) Dieta pobre fibras; (3) Desidratação; (4) Disfunção assoalho pélvico; (5) Hipotireoidismo; (6) Medicamentosa (opioides, anticolinérgicos, cálcio, ferro); (7) Disbiose. Laxativos estimulantes (senna, bisacodil): dependência, cólon catártico (atonia), depleção eletrólitos. Diarreia crônica: (1) SIBO/IMO; (2) Má absorção (celíaca, insuficiência pancreática); (3) DII; (4) Intolerâncias (lactose, frutose); (5) Medicamentosa (metformina, IBP, antibióticos); (6) Disbiose. Loperamida crônica: mascara doença de base, risco megacólon tóxico se DII.',

  risk_factors = 'Causas raiz MFI disfunção intestinal: (1) Disbiose: SIBO, SIFO, parasitas; (2) Permeabilidade intestinal aumentada; (3) Deficiência magnésio (constipação - peristalse); (4) Deficiência vitamina D (motilidade); (5) Disfunção tireoidiana (TSH>2,5); (6) Estresse crônico (eixo cérebro-intestino); (7) Sedentarismo; (8) Dieta pobre fibras/água; (9) Disautonomia (neuropatia diabética, Parkinson); (10) Adesões pós-cirúrgicas.',

  recommendations = 'Protocolo MFI constipação: (1) Hidratação: 2-3L/dia; (2) Fibras graduais: 25-35g/dia (vegetais, frutas, psyllium 5-10g) - aumentar devagar; (3) Magnésio: citrato/óxido 400-800mg noite (osmótico natural, seguro); (4) Vitamina C: doses altas 3-10g (osmótico); (5) Probióticos: Bifidobacterium lactis, Lactobacillus casei (motilidade); (6) Exercício: 30min diário (estimula peristalse); (7) Treinamento intestinal: horário regular pós-refeições; (8) Posição fisiológica: squatty potty (ângulo anorretal); (9) Otimizar tireoide se TSH>2,5; (10) Reduzir medicamentos constipantes; (11) Biofeedback se disfunção assoalho; (12) Ervas procinéticas: gengibre, alcachofra; (13) Tratar SIBO/IMO se presente. Diarreia: (1) Investigar causas: (a) Teste SIBO (breath test), (b) Celíaca (anti-tTG, biópsia), (c) Insuficiência pancreática (elastase fecal), (d) Calprotectina (DII), (e) Parasitas (PCR fezes); (2) SIBO: rifaximina + herbal antimicrobials (berberina, óleo orégano, alicina); (3) Enzimas digestivas se insuficiência; (4) Probióticos: Saccharomyces boulardii 250mg 2x/dia (antidiarreico, anti-SIBO); (5) L-glutamina 10-15g (repara mucosa); (6) Zinco: 30-50mg (diarreia); (7) Dieta baixo FODMAP se SII; (8) Evitar gatilhos: lactose, frutose, sorbitol, cafeína, álcool; (9) Psyllium: 5g (forma bolo, absorve água); (10) Berberina 500mg 3x/dia (antimicrobiana, antidiarreica); (11) Manejo estresse: mindfulness, terapia; (12) Desmame laxativos/antidiarreicos gradual sob supervisão.',

  article_ids = ARRAY[]::uuid[]
WHERE id = 'b810ab23-6af0-417c-95d3-12c4bc1ce4f7';

-- Item 21: Quimioterápicos
UPDATE score_items
SET
  clinical_significance = 'Quimioterapia citotóxica (alquilantes, antimetabólitos, antraciclinas, taxanos, platinum) destrói células de divisão rápida (câncer, mas também mucosas, medula, folículos). Uso indica/indicou diagnóstico oncológico. Efeitos adversos agudos e tardios significativos. Na MFI, foco em suporte durante tratamento e recuperação pós, prevenção recidiva via terreno.',

  functional_aspects = 'Mecanismos: danificam DNA, impedem divisão celular. Toxicidades: (1) Mielossupressão (neutropenia, anemia, trombocitopenia); (2) Mucosite GI (náusea, diarreia, mucosite oral); (3) Neuropatia periférica (platinum, taxanos); (4) Cardiotoxicidade (antraciclinas - insuficiência cardíaca); (5) Nefrotoxicidade; (6) Hepatotoxicidade; (7) Neurotoxicidade (quimio-brain); (8) Fadiga severa; (9) Infertilidade; (10) Câncer secundário. MFI: suporte nutricional intensivo, antioxidantes (timing!), suporte medular, proteção órgãos, modulação terreno pós-tratamento.',

  risk_factors = 'Causas raiz MFI câncer (terreno): (1) Inflamação crônica sistêmica (NFkB); (2) Estresse oxidativo excessivo (dano DNA); (3) Disfunção mitocondrial (Warburg effect); (4) Desregulação imune (NK cells, Tregs); (5) Disbiose com genotoxinas; (6) Permeabilidade intestinal (endotoxemia); (7) Resistência insulínica (IGF-1, mTOR); (8) Obesidade (adipocinas, estrogênio); (9) Toxinas ambientais (pesticidas, VOCs); (10) Deficiências: vitamina D, selênio, ômega-3.',

  recommendations = 'Protocolo MFI durante quimioterapia: (1) ANTIOXIDANTES - TIMING CRUCIAL: (a) EVITAR durante infusão e 24-48h após (podem proteger células cancerosas - controverso), (b) Usar entre ciclos para recuperação; (2) Proteção medular: (a) Glutamina 10-30g/dia (mucosa, imune), (b) Ômega-3 EPA 2g, (c) Vitamina D3 5000-10000UI, (d) Probióticos, (e) Whey protein 20-30g (glutationa precursor); (3) Cardioprotection (antraciclinas): CoQ10 ubiquinol 300-600mg, L-carnitina 2-3g, magnésio 400-600mg - iniciar ANTES quimio; (4) Neuroprotection (platinum, taxanos): ácido alfa-lipóico 600mg, acetil-L-carnitina 2g, vitaminas B (B6, B12, folato), ômega-3; (5) Náusea: gengibre 1-2g, acupuntura, canabinoides (THC/CBD) se legalizado; (6) Mucosite oral: glutamina swish & swallow, mel, photobiomodulation; (7) Diarreia: glutamina, probióticos (Saccharomyces boulardii), zinco; (8) Fadiga: ginseng americano 2g/dia, exercício leve-moderado, correção anemia (ferro, B12, EPO se indicado); (9) Chemo-brain: ômega-3, bacopa 300mg, ginkgo 120mg, exercício cognitivo; (10) Nutrição: (a) Proteína 1,5-2g/kg (preservar massa muscular), (b) Calorias adequadas (evitar perda peso), (c) Vegetais coloridos (fitoquímicos - timing!), (d) Evitar açúcar excessivo (IGF-1, insulina); (11) Hidratação: 2-3L/dia (excreção toxinas); (12) Exercício: 150min/semana moderado (melhora sobrevida, QV, fadiga); (13) Manejo estresse: mindfulness, suporte psicológico, grupo apoio; (14) Sono: 8-9h (reparador); (15) Monitorar: hemograma, função renal/hepática, ecocardiograma (antraciclinas), eletrólitos. Pós-quimioterapia: (1) Recuperação terreno: dieta anti-câncer (plant-based, mediterrânea, cetogênica cíclica), jejum intermitente, exercício regular, controle peso; (2) Suporte detox: NAC, glutationa, cardo mariano, hidratação, sauna; (3) Modulação imune: vitamina D >50ng/mL, ômega-3, cogumelos medicinais (turkey tail, reishi), probióticos; (4) Anti-inflamatórios: curcumina 1g, boswellia, resveratrol; (5) Modulação metabólica: berberina, metformina (off-label), controle glicemia/insulina; (6) Suporte mitocondrial: CoQ10, PQQ, L-carnitina; (7) Rastreamento recidiva: exames periódicos conforme protocolo oncológico.',

  article_ids = ARRAY[]::uuid[]
WHERE id = '8f7abde9-c22b-4671-b30a-fbb314fff861';

-- Item 22: Terapia de reposição hormonal (estrogênio, testosterona)
UPDATE score_items
SET
  clinical_significance = 'TRH envolve reposição de hormônios sexuais em deficiência. Estrogênio ± progesterona para menopausa (sintomas vasomotores, perda óssea, atrofia geniturinária). Testosterona para hipogonadismo masculino (libido, massa muscular, energia, densidade óssea, humor). Na MFI, otimizar produção endógena primeiro, usar TRH bioidentical quando necessário.',

  functional_aspects = 'Fisiopatologia: Menopausa: depleção folicular ovariana, estrogênio despenca, FSH/LH aumentam. Sintomas: fogachos, suor noturno, insônia, alterações humor, ressecamento vaginal, osteoporose, risco cardiovascular. Hipogonadismo: testosterona <300ng/dL (primário ou secundário). Sintomas: libido reduzida, DE, fadiga, perda muscular, ganho adiposo, depressão, osteoporose. TRH riscos: Estrogênio: trombose venosa, AVC (oral), câncer mama (estrogênio+progestina sintética >5 anos), vesícula. Testosterona: eritrocitose, apneia, acne, agressividade, atrofia testicular, infertilidade, risco cardiovascular (controverso). MFI: TRH bioidentical transdérmico (evita first-pass), progesterona micronizada (não sintética), monitoramento rigoroso.',

  risk_factors = 'Causas raiz MFI deficiência hormonal: (1) Obesidade: aromatase converte testosterona→estrogênio; (2) Resistência insulínica: reduz SHBG, testosterona livre paradoxalmente baixa; (3) Estresse crônico: cortisol rouba pregnenolona; (4) Sono inadequado: testosterona produzida durante sono; (5) Deficiências: vitamina D, zinco, magnésio, colesterol (precursor); (6) Toxinas: xenoestrogênios (plásticos, pesticidas), metais pesados; (7) Álcool excessivo: hepatotóxico, aumenta aromatase; (8) Sedentarismo; (9) Inflamação crônica; (10) Medicamentos: opioides, estatinas, finasterida.',

  recommendations = 'Protocolo MFI otimização hormonal: (1) Estilo vida: (a) Perda peso se IMC>25 (reduz aromatase), (b) Exercício: resistido (testosterona) + HIIT, (c) Sono: 7-9h (testosterona noturna), (d) Manejo estresse: adapógenos, mindfulness; (2) Nutrição: (a) Gorduras saudáveis 25-35% calorias (precursor hormônios), (b) Proteína adequada 1,5g/kg, (c) Crucíferas (DIM/I3C - metaboliza estrogênio), (d) Lignanas (linhaça), (e) Reduzir álcool, açúcar; (3) Suplementos testosterona: (a) Vitamina D3 5000UI (alvo >50), (b) Zinco 30-50mg, (c) Magnésio 400mg, (d) Ashwagandha 600mg, (e) Tongkat ali 200mg, (f) Tribulus 750mg, (g) DHEA 25-50mg se baixo, (h) Boro 6mg (reduz SHBG); (4) Suporte estrogênio menopausa: (a) Fitoestrógenos: isoflavonas soja 50mg, cohosh preto 40mg, (b) Lignanas: linhaça 2 colheres, (c) Vitamina E 400UI (fogachos), (d) Ômega-3 2g; (5) Modulação estrogênio: (a) DIM 200-400mg ou I3C (metabolismo 2-OH benéfico), (b) Cálcio-D-glucarato (excreção), (c) Fibras 30g (excreção fecal), (d) Probióticos (estroboloma); (6) TRH se necessário: (a) Estrogênio: 17-beta-estradiol TRANSDÉRMICO (patch, gel) 0,025-0,1mg/dia + progesterona micronizada 100-200mg noite (protege endométrio) - evitar progestinas sintéticas!, (b) Testosterona: gel/injeção 50-100mg/semana (alvo 500-800ng/dL), (c) Bioidentical > sintético, (d) Dose mínima efetiva, (e) Duração limitada se possível; (7) Monitorar: (a) Hormônios: testosterona total/livre, estradiol, progesterona (dia 21 ciclo), SHBG, DHEA-S, cortisol, (b) Lipídios, glicemia, hematócrito (testosterona), (c) Densitometria óssea, (d) Mamografia/ultrassom mama (estrogênio), (e) PSA, toque retal (testosterona); (8) Contraindicações: câncer hormônio-dependente ativo, trombose ativa; (9) Risco-benefício individualizado.',

  article_ids = ARRAY[]::uuid[]
WHERE id = 'a8b10e3f-6e76-450e-bda7-232a3ab8e49b';

-- Item 23: Terapias hormonais oncológicas (tamoxifeno, inibidores de aromatase)
UPDATE score_items
SET
  clinical_significance = 'Hormonioterapia para câncer de mama receptor hormonal positivo (RE+/RP+). Tamoxifeno (modulador seletivo receptor estrogênio) em pré-menopausa ou inibidores aromatase (anastrozol, letrozol, exemestano) em pós-menopausa. Bloqueia estímulo estrogênico em células tumorais. Uso 5-10 anos. Efeitos adversos significativos na qualidade de vida.',

  functional_aspects = 'Mecanismos: Tamoxifeno: antagonista RE em mama, agonista em osso/útero. Inibidores aromatase (IA): bloqueiam conversão androgênios→estrogênio periférico (pós-menopausa). Efeitos adversos: (1) Tamoxifeno: fogachos, trombose venosa (3x risco), câncer endométrio (2-3x risco), catarata; (2) IA: artralgias severas (50%), perda óssea acelerada (osteoporose, fraturas), dislipidemia, sintomas menopáusicos intensos, atrofia geniturinária, fadiga, disfunção cognitiva. MFI: suporte sintomas, proteção óssea/cardiovascular, otimizar adesão (não descontinuar!).',

  risk_factors = 'Fatores preditivos câncer mama RE+: (1) Exposição estrogênica cumulativa: menarca precoce, menopausa tardia, nuliparidade; (2) Obesidade pós-menopausa (aromatase adiposa); (3) TRH prolongada; (4) Álcool; (5) Deficiência vitamina D; (6) Polimorfismos CYP2D6 (tamoxifeno metabolização). Recidiva: (1) Descontinuação prematura; (2) Obesidade; (3) Inflamação crônica; (4) Resistência insulínica.',

  recommendations = 'Protocolo MFI hormonioterapia oncológica: (1) Artralgias (IA): (a) Ômega-3 EPA 2-3g (anti-inflamatório), (b) Curcumina 1000mg, (c) Boswellia 400mg, (d) Vitamina D3 >50ng/mL, (e) Acupuntura (evidência), (f) Exercício resistido + flexibilidade, (g) Glucosamina/condroitina 1500/1200mg; (2) Proteção óssea: (a) Cálcio 1200mg + vitamina D3 2000-5000UI + vitamina K2 MK-7 200mcg, (b) Magnésio 400mg, (c) Colágeno tipo I 10g, (d) Exercício resistido (osteogênico), (e) DEXA anual, considerar bifosfonatos se T-score <-2,5; (3) Fogachos: (a) Cohosh preto 40mg, (b) Vitamina E 800UI, (c) Magnésio 400mg, (d) Acupuntura, (e) EVITAR fitoestrógenos potentes (controverso em RE+); (4) Saúde cardiovascular: (a) Ômega-3 2g, (b) CoQ10 200mg, (c) Magné, (d) Controle PA/lipídios, (e) Exercício aeróbico 150min; (5) Atrofia geniturinária: (a) Lubrificantes/hidratantes vaginais, (b) Vitamina E óleo tópico, (c) Ácido hialurônico vaginal, (d) Laser vaginal fracionado, (e) EVITAR estrogênio vaginal se possível (absorção sistêmica controversa); (6) Fadiga: (a) CoQ10 200mg, (b) L-carnitina 2g, (c) Exercício moderado (paradoxal, melhora), (d) Sono adequado, (e) Correção anemia/tireoide; (7) Trombose (tamoxifeno): (a) Hidratação, (b) Exercício, (c) Ômega-3, (d) Evitar imobilização, (e) Meia compressão se voo longo; (8) Prevenção recidiva: (a) Peso saudável (IMC 20-25) - ESSENCIAL, (b) Exercício 150-300min/semana (reduz recidiva 30-40%), (c) Dieta anti-inflamatória plant-based, (d) Reduzir álcool (<1 dose/dia ou zero), (e) Sono 7-9h, (f) Manejo estresse, (g) Vitamina D >50ng/mL, (h) Ômega-3 2g, (i) Curcumina 1g, (j) Cogumelos medicinais, (k) Chá verde 3-5 xícaras/dia; (9) Monitorar: hemograma, lipídios, glicemia, função hepática, DEXA, mamografia anual, exame pélvico (tamoxifeno - risco endométrio); (10) Adesão: não descontinuar sem oncologista! Suportar efeitos adversos para completar 5-10 anos.',

  article_ids = ARRAY[]::uuid[]
WHERE id = 'e2d32ee9-2fb7-4e4d-9c33-8b8a95f36642';

-- Item 24: Tabaco
UPDATE score_items
SET
  clinical_significance = 'Tabagismo é principal causa evitável de morte no mundo (8+ milhões mortes/ano). Tabaco contém >7000 químicos, 70+ carcinogênicos. Causa câncer (pulmão, boca, esôfago, bexiga, pâncreas, rim, cólo uterino), DPOC, doença cardiovascular (aterosclerose, IAM, AVC), complicações gravidez. Na MFI, cessação é PRIORIDADE ABSOLUTA e suporte para desintoxicação e reparo.',

  functional_aspects = 'Fisiopatologia: (1) Nicotina: dependência (receptores nicotínicos acetilcolina), vasoconstrição, liberação catecolaminas; (2) Monóxido carbono: reduz capacidade oxigênio (carboxihemoglobina); (3) Alcatrão: carcinogênicos, depósito pulmonar; (4) Radicais livres: estresse oxidativo massivo; (5) Inflamação crônica sistêmica; (6) Disfunção endotelial (aterosclerose acelerada); (7) Mutagênese (dano DNA); (8) Imunossupressão (infecções, câncer). Impactos: (1) Pulmonar: DPOC, câncer, enfisema, fibrose; (2) Cardiovascular: aterosclerose, IAM 2-4x risco, AVC; (3) Câncer múltiplos sítios; (4) Metabólico: resistência insulínica; (5) Reprodutivo: infertilidade, complicações gravidez; (6) Ósseo: osteoporose; (7) Pele: envelhecimento precoce.',

  risk_factors = 'Fatores MFI pós-tabagismo: (1) Estresse oxidativo residual crônico; (2) Inflamação persistente; (3) Disfunção endotelial; (4) Carga tóxica acumulada (metais pesados, HAPs); (5) Depleções nutricionais: vitamina C (fumante consume 35mg/dia extra), vitamina E, beta-caroteno, folato, B12; (6) Disfunção mitocondrial; (7) Metilação DNA alterada (epigenética); (8) Microbiota alterada; (9) Risco câncer persiste anos após cessar.',

  recommendations = 'Protocolo MFI cessação tabagismo: (1) Cessação - combinações aumentam sucesso: (a) Farmacológico: vareniclina (Champix) ou bupropiona + TRN (adesivo nicotina), (b) Comportamental: terapia cognitivo-comportamental, grupos apoio, apps, (c) Motivacional: entrevista motivacional, (d) Alternativas: vaping como redução dano (controverso, não ideal); (2) Suporte abstinência: (a) NAC 1200-1800mg (reduz craving, antioxidante), (b) Rhodiola 400mg (ansiedade, foco), (c) Lobelia (contém lobelina, agonista nicotínico fraco), (d) Magnésio 400-600mg (ansiedade), (e) 5-HTP 100-300mg ou triptofano (humor); (3) Detoxificação: (a) Antioxidantes massivos: vitamina C 3-5g/dia, vitamina E 400UI, NAC 1800mg, glutationa lipossomal, (b) Suporte hepático: cardo mariano, SAMe, (c) Quelação metais pesados se indicado, (d) Hidratação 3L/dia, (e) Sauna (excreção cutânea), (f) Exercício (excreção respiratória); (4) Reparação pulmonar: (a) NAC 600-1200mg (mucolítico), (b) Ômega-3 2-3g (anti-inflamatório), (c) Quercetina 500-1000mg, (d) Curcumina 1000mg, (e) Vitamina A 10000UI (reparo epitélio), (f) Exercício respiratório, fisioterapia respiratória; (5) Proteção cardiovascular: (a) Ômega-3 EPA/DHA 3-4g, (b) CoQ10 200mg, (c) Magnésio 400-600mg, (d) Arginina+citrulina (NO, endotélio), (e) Vitamina K2 (descalcificar), (f) Niacina 500-2000mg (lipídios); (6) Quimioprevenção câncer: (a) Curcumina 1-2g, (b) Resveratrol 500mg, (c) EGCG (chá verde) 400mg, (d) Sulforafano 30mg (brócolis), (e) Vitamina D >50ng/mL, (f) Selênio 200mcg, (g) Ômega-3; (7) Reposição nutrientes: (a) Multivitamínico completo, (b) Vitamina C 2-3g, (c) Folato metilado 1mg, (d) B12 1000mcg, (e) Zinco 30mg; (8) Estilo vida: (a) Exercício 150min/semana (reduz craving, reparo), (b) Dieta anti-inflamatória rica antioxidantes (colorful!), (c) Mindfulness/meditação (craving), (d) Sono adequado; (9) Evitar gatilhos: álcool, café (associações), ambientes fumantes; (10) Monitorar: função pulmonar (espirometria), rastreamento câncer (TC tórax baixa dose se >30 maços-ano), risco cardiovascular (escore cálcio, lipídios).',

  article_ids = ARRAY[]::uuid[]
WHERE id = 'c8103f42-dff4-4a08-ab7e-d9c06d8d2103';

-- Continua próximo bloco...
