-- Continuação Batch 6.2 - Parte 3

-- Item 25: Álcool
UPDATE score_items
SET
  clinical_significance = 'Álcool etílico (etanol) é substância psicoativa depressora do SNC, hepatotóxica, carcinogênica (Grupo 1 IARC). Consumo excessivo crônico causa dependência física/psicológica, doenças hepáticas (esteatose, hepatite, cirrose), cardiovasculares, câncer (boca, esôfago, fígado, mama), neuropsiquiátricas. Na MFI, investigar padrão uso, dependência, impactos metabólicos e suporte cessar/reduzir.',

  functional_aspects = 'Metabolismo: (1) Álcool desidrogenase (ADH)→acetaldeído (tóxico); (2) Aldeído desidrogenase (ALDH2)→acetato; (3) Sistema microssomal CYP2E1 (gera radicais livres). Efeitos agudos: desinibição, sedação, incoordenação. Crônicos: (1) Hepatotoxicidade: esteatose (acúmulo triglicérides), inflamação, fibrose, cirrose; (2) Neurotoxicidade: déficit tiamina (Wernicke-Korsakoff), demência alcoólica, neuropatia; (3) Cardiovascular: cardiomiopatia, arritmias, HAS; (4) GI: gastrite, pancreatite, má absorção; (5) Câncer: acetaldeído danifica DNA, hormônio (mama - estrogênio); (6) Imunossupressão; (7) Depleções: tiamina, B6, B12, folato, magnésio, zinco; (8) Disbiose, permeabilidade intestinal.',

  risk_factors = 'Causas raiz MFI uso problemático: (1) Genética: ALDH2 deficiente (asiáticos - acúmulo acetaldeído), polimorfismos ADH, receptores GABA/glutamato; (2) Neurobiologia: desregulação sistema recompensa dopaminérgico; (3) Comorbidades psiquiátricas: depressão, ansiedade, TEPT; (4) Estresse crônico; (5) Microbioma: disbiose predispõe; (6) Deficiências nutricionais prévias. Impactos MFI pós-uso: (1) Disfunção hepática com detox comprometida; (2) Permeabilidade intestinal, disbiose; (3) Neuroinflamação; (4) Estresse oxidativo; (5) Disfunção mitocondrial; (6) Depleções severas vitaminas B.',

  recommendations = 'Protocolo MFI dependência alcoólica: (1) Desintoxicação médica: benzodiazepínicos (previne convulsão), tiamina IV (Wernicke), hospitalização se severa - NUNCA cessar álcool severo ambulatorial (risco morte); (2) Farmacoterapia manutenção: naltrexona 50mg (reduz craving, bloqueia opioides endógenos), acamprosato 2g/dia (modula GABA/glutamato), dissulfiram 250mg (aversivo); (3) Suporte nutricional: (a) Tiamina (B1) 100-300mg/dia IM→oral (ESSENCIAL - previne Wernicke), (b) Folato 1-5mg, (c) B12 1000mcg, (d) B6 50-100mg, (e) Multivitamínico completo; (4) Hepatoproteção: (a) Cardo mariano (silimarina) 300-600mg, (b) SAMe 800-1600mg (metilação, glutationa), (c) NAC 1200-1800mg (glutationa, antioxidante), (d) Ácido alfa-lipóico 600mg, (e) Colina 500mg (previne esteatose); (5) Suporte cerebral: (a) Ômega-3 DHA 2-3g (membrana neuronal), (b) Magnésio L-treonato 2000mg (GABA, ansiedade), (c) Taurina 1-3g (GABA), (d) L-glutamina 5-10g (reduz craving - precursor GABA), (e) NAC 1200mg (glutamato/glutationa); (6) Modulação neurotransmissores: (a) Kudzu (Pueraria lobata) 1-2g (reduz consumo), (b) Rhodiola 400mg (craving, humor), (c) 5-HTP 100-300mg (serotonina), (d) L-tirosina 1-2g (dopamina); (7) Restauração intestinal: (a) Probióticos: Lactobacillus rhamnosus GG, Bifidobacterium, (b) L-glutamina 10-15g (permeabilidade), (c) Zinco-carnosina 150mg, (d) Dieta anti-inflamatória; (8) Antioxidantes: (a) Vitamina C 2-3g, (b) Vitamina E 400UI, (c) Selênio 200mcg, (d) Glutationa lipossomal; (9) Suporte mitocondrial: CoQ10 200mg, L-carnitina 2g, PQQ 20mg; (10) Psicoterapia: (a) Terapia cognitivo-comportamental, (b) Entrevista motivacional, (c) Grupos: AA (Alcoólicos Anônimos), SMART Recovery; (11) Tratamento comorbidades: depressão, ansiedade, trauma; (12) Exercício: 150min/semana (dopamina, humor, reduz recaída); (13) Mindfulness: meditação, yoga (craving); (14) Sono: higiene sono, melatonina 3-5mg; (15) Monitorar: função hepática (AST, ALT, GGT), hemograma (macrocitose), eletrólitos, glicemia, tiamina sérica, amilase (pancreatite); (16) Prevenção recaída: evitar gatilhos, rede suporte, plano emergência. Uso moderado: Se não dependente, limitar ≤1 dose/dia mulheres, ≤2 homens (1 dose=14g etanol) - mas nenhum álcool é "seguro" para câncer.',

  article_ids = ARRAY[]::uuid[]
WHERE id = '74440d97-63b7-4eff-b67d-00e5eec8c2d0';

-- Item 26: Drogas ilícitas
UPDATE score_items
SET
  clinical_significance = 'Substâncias psicoativas ilícitas incluem estimulantes (cocaína, anfetaminas, metanfetamina), opioides (heroína, fentanil), cannabis, alucinógenos (LSD, psilocibina), dissociativos (ketamina), entre outros. Riscos: dependência, overdose, transmissão doenças (HIV, hepatites), complicações cardiovasculares/psiquiátricas, impactos sociais/ocupacionais. Na MFI, abordagem harm reduction, tratamento dependência, suporte recuperação.',

  functional_aspects = 'Mecanismos variam: (1) Estimulantes: bloqueiam recaptação dopamina/norepinefrina (euforia, energia) - cardiotoxicidade, psicose, depleção neurotransmissores; (2) Opioides: agonistas receptores mu (analgesia, euforia) - depressão respiratória fatal, dependência severa, constipação, hipogonadismo; (3) Cannabis: agonista CB1/CB2 (euforia, relaxamento) - síndrome amotivacional, psicose em predispostos, dependência psicológica; (4) Alucinógenos: agonistas serotonina 5-HT2A - baixo risco dependência, mas bad trips, HPPD. Impactos MFI: (1) Neurotoxicidade (metanfetamina, MDMA); (2) Cardiotoxicidade (cocaína - IAM, arritmias); (3) Hepatotoxicidade; (4) Infecções (compartilhamento seringas); (5) Depleções nutricionais; (6) Comorbidades psiquiátricas.',

  risk_factors = 'Vulnerabilidades: (1) Genética: polimorfismos sistema dopaminérgico, receptores opioides; (2) Trauma, adversidade infância; (3) Comorbidades psiquiátricas (50-70% dual diagnosis); (4) Ambiente (disponibilidade, pares); (5) Estresse crônico; (6) Déficit habilidades coping. Impactos saúde: (1) HIV, hepatite C (injetáveis); (2) Endocardite (IV); (3) Psicose induzida; (4) Depressão, ansiedade; (5) Declínio cognitivo.',

  recommendations = 'Protocolo MFI dependência substâncias: (1) Tratamento médico especializado: (a) Opioides: buprenorfina/naloxona (Suboxone), metadona (MAT - medication-assisted treatment), naltrexona depot (Vivitrol), (b) Estimulantes: sem FDA aprovado, suporte sintomático, psicoterapia, (c) Cannabis: psicoterapia, sem farmacoterapia específica; (2) Desintoxicação segura: (a) Médica supervisionada (opioides: sintomas graves mas não fatais; álcool/benzos: fatais), (b) Clonidina (sintomas retirada opioide), (c) Suporte sintomático; (3) Harm reduction: (a) Programa troca seringas, (b) Naloxona (overdose opioide) - kits domiciliares, (c) Fentanil test strips, (d) Safe injection sites; (4) Suporte nutricional: (a) Multivitamínico completo, (b) Ômega-3 DHA 2-3g (reparação neuronal), (c) Aminoácidos: L-tirosina 2-3g (dopamina - estimulantes), L-triptofano 2g (serotonina), (d) Vitaminas B: B6, B12, folato (metilação); (5) Neuroproteção: (a) NAC 1200-1800mg (glutamato, glutationa, reduz craving), (b) Magnésio L-treonato (NMDA, ansiedade), (c) Vitamina C 2-3g (antioxidante, detox), (d) Ácido alfa-lipóico 600mg; (6) Modulação neurotransmissores: (a) Mucuna pruriens 300-600mg (L-dopa), (b) 5-HTP 100-300mg (serotonina), (c) SAMe 400-800mg (metilação, humor), (d) Rhodiola 400mg (energia, foco); (7) Suporte opioide: (a) Vitamina D3 (>50ng/mL - dor, humor), (b) Magnésio 600mg, (c) DL-fenilalanina (DLPA) 500-1500mg (endorfinas, dor); (8) Suporte estimulantes: (a) Magnésio (depleta), (b) L-tirosina (restaura dopamina), (c) Sono: melatonina 5-10mg, trazodona; (9) Hepatoproteção: cardo mariano 300mg, NAC, ácido alfa-lipóico; (10) Teste infecções: HIV, hepatite B/C - tratar se positivo; (11) Psicoterapia: (a) Terapia cognitivo-comportamental, (b) Contingency management (reforço abstinência), (c) Terapia familiar, (d) Grupos: NA (Narcóticos Anônimos), SMART Recovery; (12) Tratamento dual diagnosis: comorbidades psiquiátricas concomitantemente; (13) Exercício: 150min/semana (dopamina natural, humor); (14) Mindfulness: meditação, yoga, breathwork; (15) Espiritualidade/propósito: práticas espirituais, voluntariado, conexão comunidade; (16) Reintegração social: moradia, emprego, educação; (17) Prevenção recaída: identificar gatilhos, plano coping, rede suporte, evitar ambientes alto risco; (18) Monitoramento: testes urina (accountability, não punitivo), sintomas, função hepática/renal. Cannabis medicinal: Considerar CBD (não psicoativo) para ansiedade, dor, sono - 25-75mg/dia.',

  article_ids = ARRAY[]::uuid[]
WHERE id = '876dc074-6d92-4295-958a-97935e4329ca';

-- Item 27: Jogos / apostas
UPDATE score_items
SET
  clinical_significance = 'Jogo patológico (transtorno jogo) é dependência comportamental reconhecida pelo DSM-5. Envolve jogo persistente apesar de consequências negativas (financeiras, relacionais, ocupacionais). Ativa mesmos circuitos de recompensa (dopamina) que substâncias. Comorbidade alta com depressão, ansiedade, abuso substâncias, suicídio. Na MFI, tratar como addiction comportamental.',

  functional_aspects = 'Neurobiologia: (1) Desregulação sistema dopaminérgico mesolímbico (recompensa); (2) Hipoativação córtex pré-frontal (controle impulsos, tomada decisão); (3) Liberação dopamina por "quase-ganhos" (near-misses); (4) Tolerância (precisa apostar mais para mesma excitação); (5) Abstinência (irritabilidade, ansiedade sem jogo). Comorbidades: (1) Depressão 50%; (2) Ansiedade 40%; (3) Abuso substâncias 60%; (4) TDAH; (5) Transtorno bipolar. Consequências: (1) Dívidas massivas, falência; (2) Perda relacionamentos; (3) Desemprego; (4) Problemas legais; (5) Suicídio (20% tentativas).',

  risk_factors = 'Vulnerabilidades MFI: (1) Genética: polimorfismos sistema dopaminérgico (DRD2, DRD4); (2) Impulsividade elevada; (3) Busca sensações; (4) Comorbidades psiquiátricas; (5) Trauma, estresse; (6) Isolamento social; (7) Acesso facilitado (online gambling); (8) Fatores neurobiológicos: déficit executivo frontal.',

  recommendations = 'Protocolo MFI jogo patológico: (1) Psicoterapia - primeira linha: (a) Terapia cognitivo-comportamental (CBT) - reestruturação cognitiva (ilusão controle, vieses), (b) Entrevista motivacional, (c) Terapia familiar; (2) Farmacoterapia: (a) Naltrexona 50-150mg/dia (antagonista opioide, reduz craving/impulsividade) - evidência moderada, (b) NAC 1200-1800mg/dia (glutamato, controle impulsos) - evidência emergente, (c) Tratar comorbidades: antidepressivos (ISRS), estabilizadores humor; (3) Grupos suporte: Jogadores Anônimos (GA - Gamblers Anonymous) - programa 12 passos; (4) Modulação neurotransmissores: (a) L-tirosina 1-2g (dopamina), (b) 5-HTP 100-300mg (serotonina, impulsos), (c) SAMe 400-800mg (metilação, humor); (5) Controle impulsos: (a) NAC 1200-1800mg (glutamato/glutationa), (b) Inositol 12-18g/dia (evidência TOC), (c) Magnésio L-treonato 2000mg (função executiva); (6) Ômega-3: EPA/DHA 2-3g (neuroinflamação, humor); (7) Suporte cognitivo: Bacopa 300mg, ginkgo 120mg, fosfatidilserina 300mg; (8) Manejo estresse: (a) Mindfulness 20min/dia (reduz impulsividade), (b) Yoga, (c) Exercício 150min/semana (dopamina saudável); (9) Sono adequado: melatonina 3-5mg, higiene sono; (10) Barreiras comportamentais: (a) Auto-exclusão casinos/sites, (b) Bloqueadores software (GamBlock, Gamban), (c) Controle financeiro: cônjuge gerencia finanças, conta sem acesso online; (11) Tratamento comorbidades: depressão, ansiedade, abuso substâncias concomitantemente; (12) Atividades alternativas: exercício, hobbies, voluntariado (preencher vazio); (13) Rede suporte: família, amigos (não-jogadores); (14) Monitoramento: frequência jogo, dívidas, humor, ideação suicida; (15) Prevenção recaída: identificar gatilhos (estresse, tédio, emoções negativas), plano coping, linha suporte 24/7.',

  article_ids = ARRAY[]::uuid[]
WHERE id = '4f7ed913-190c-4fe6-ba81-35b2005375c1';

-- Item 28: Sexo (vício sexual)
UPDATE score_items
SET
  clinical_significance = 'Transtorno comportamento sexual compulsivo envolve padrão persistente de falha em controlar impulsos/urgências sexuais intensas resultando em comportamento sexual repetitivo. Inclui pornografia compulsiva, masturbação excessiva, múltiplos parceiros, sexo de risco. Causa sofrimento, prejuízo ocupacional/relacional. Debate se é addiction verdadeira vs. controle impulsos. Na MFI, tratar neurobiologia subjacente.',

  functional_aspects = 'Neurobiologia: (1) Hiperativação sistema recompensa dopaminérgico com estímulo sexual; (2) Dessensibilização: precisa estímulos mais intensos/novos para mesma resposta (escalation); (3) Hipoativação córtex pré-frontal (controle impulsos); (4) Possível neuroplasticidade com pornografia internet (supernormal stimulus). Similar a addiction: craving, perda controle, persistência apesar consequências, abstinência. Comorbidades: (1) Depressão, ansiedade; (2) TDAH; (3) Abuso substâncias; (4) Trauma (histórico abuso sexual 40-60%). Consequências: (1) Relacionamentos prejudicados; (2) Disfunção erétil psicogênica (pornografia-induced ED); (3) Perda produtividade; (4) DSTs; (5) Problemas legais (exposição ilegal).',

  risk_factors = 'Vulnerabilidades MFI: (1) Impulsividade elevada; (2) Comorbidades psiquiátricas; (3) Trauma, especialmente sexual; (4) Busca sensações; (5) Déficit habilidades intimidade; (6) Isolamento social; (7) Acesso fácil internet pornography; (8) Polimorfismos sistema dopaminérgico.',

  recommendations = 'Protocolo MFI comportamento sexual compulsivo: (1) Psicoterapia - ESSENCIAL: (a) Terapia cognitivo-comportamental (reestruturação, controle impulsos, prevenção recaída), (b) Terapia aceitação e compromisso (ACT), (c) Terapia sexual (com parceiro), (d) Terapia trauma se histórico abuso; (2) Farmacoterapia (off-label, evidência limitada): (a) Naltrexona 50mg (craving, impulsos), (b) ISRS (se comorbidade TOC, depressão), (c) NAC 1200-1800mg/dia (glutamato, controle impulsos); (3) Modulação neurotransmissores: (a) 5-HTP 100-300mg (serotonina, impulsos), (b) L-tirosina 1-2g (dopamina - cuidado, pode aumentar impulsos), (c) SAMe 400-800mg (metilação, humor); (4) Controle impulsos: (a) NAC 1200-1800mg, (b) Inositol 12-18g, (c) Magnésio L-treonato 2000mg (função executiva); (5) Ômega-3: EPA/DHA 2-3g (neuroinflamação); (6) Suporte cognitivo/controle executivo: Bacopa 300mg, rhodiola 400mg; (7) Barreiras comportamentais: (a) Filtros internet (Covenant Eyes, Net Nanny) com accountability, (b) Smartphone: remover apps, usar basic phone, (c) Ambiente: não ficar sozinho em casa, porta quarto aberta, computador em área comum; (8) Grupo suporte: (a) Sex Addicts Anonymous (SAA), (b) Sexaholics Anonymous (SA), (c) Sex and Love Addicts Anonymous (SLAA); (9) Manejo estresse/emoções: (a) Mindfulness 20min/dia (awareness urges sem reagir), (b) Exercício 150min/semana (dopamina saudável, reduz impulsos), (c) Yoga, meditação; (10) Sono: higiene sono, melatonina 3-5mg (urges piores fadiga); (11) "Rebooting": abstinência pornografia/masturbação 90 dias (reset sensibilidade dopamina - anedotal, sem evidência científica robusta); (12) Atividades alternativas: hobbies, socialização, esportes (preencher tempo); (13) Intimidade saudável: desenvolver conexão emocional com parceiro, sexo consciente; (14) Tratamento comorbidades: depressão, ansiedade, TDAH, trauma; (15) Educação sexual: desmistificar pornografia (não realista), sexualidade saudável; (16) Monitoramento: frequência comportamentos, horas pornografia, humor, relacionamento; (17) Prevenção recaída: identificar gatilhos (H.A.L.T. - Hungry, Angry, Lonely, Tired), plano coping, accountability partner. IMPORTANTE: Abordagem compassiva, sem vergonha/julgamento.',

  article_ids = ARRAY[]::uuid[]
WHERE id = '8836b4a5-a715-4e2d-8a49-94a50eae4437';

-- Item 29: Outros vícios
UPDATE score_items
SET
  clinical_significance = 'Inclui addictions comportamentais diversas: compras compulsivas, internet/gaming, trabalho, exercício, comida, cafeína. Compartilham características: (1) Perda controle; (2) Persistência apesar consequências; (3) Craving; (4) Tolerância; (5) Abstinência (irritabilidade). Ativam circuitos recompensa dopaminérgicos. Na MFI, tratar neurobiologia e drivers psicológicos subjacentes.',

  functional_aspects = 'Neurobiologia comum: desregulação sistema dopaminérgico mesolímbico (recompensa) e hipoativação córtex pré-frontal (controle). Específicos: (1) Gaming: dopamina por achievements, socialização virtual; (2) Compras: dopamina por novidade, alívio ansiedade; (3) Trabalho: validação, evitação problemas; (4) Exercício: endorfinas, dismorfia corporal; (5) Comida: açúcar/gordura hiperstimulam recompensa (binge eating disorder); (6) Cafeína: adenosina antagonism, dependência física. Comorbidades: depressão, ansiedade, TDAH, TOC, trauma.',

  risk_factors = 'Vulnerabilidades MFI: (1) Genética: polimorfismos dopaminérgicos; (2) Impulsividade, busca sensações; (3) Comorbidades psiquiátricas; (4) Trauma, adversidade; (5) Déficit regulação emocional; (6) Isolamento social; (7) Ambiente facilitador (acesso); (8) Estresse crônico.',

  recommendations = 'Protocolo MFI addictions comportamentais: (1) Psicoterapia - ESSENCIAL: (a) CBT (reestruturação, controle impulsos, prevenção recaída), (b) ACT (aceitação urges, valores), (c) DBT (regulação emocional), (d) Entrevista motivacional; (2) Farmacoterapia: (a) Naltrexona 50mg (craving geral - off-label), (b) NAC 1200-1800mg (glutamato, controle impulsos), (c) ISRS se comorbidades; (3) Modulação neurotransmissores: (a) L-tirosina 1-2g (dopamina), (b) 5-HTP 100-300mg (serotonina), (c) SAMe 400-800mg, (d) DLPA 500-1500mg (endorfinas); (4) Controle impulsos: (a) NAC 1200-1800mg, (b) Inositol 12-18g (TOC-like), (c) Magnésio L-treonato 2000mg; (5) Ômega-3: EPA/DHA 2-3g; (6) Suporte cognitivo: Bacopa 300mg, rhodiola 400mg, ginkgo 120mg; (7) Manejo estresse: (a) Mindfulness 20min/dia, (b) Yoga, (c) Exercício 150min/semana (mas moderado se vício exercício!); (8) Sono adequado: higiene sono, melatonina; (9) Barreiras comportamentais: (a) Gaming: deletar jogos, vender console, apps bloqueio, (b) Compras: cartões com cônjuge, cash only, unsubscribe marketing, (c) Trabalho: limites rígidos horário, desligar notificações, (d) Comida: não comprar trigger foods, meal prep, mindful eating, (e) Cafeína: taper gradual (evita abstinência); (10) Atividades substitutivas: hobbies saudáveis, socialização, voluntariado; (11) Grupos suporte: (a) Workaholics Anonymous, (b) Overeaters Anonymous, (c) Online Gamers Anonymous; (12) Tratamento comorbidades: depressão, ansiedade, TDAH; (13) Regulação emocional: identificar emoções → estratégias saudáveis (não usar behavior); (14) Conexão social: reduz isolamento que perpetua addiction; (15) Propósito/significado: espiritualidade, valores, metas vida; (16) Monitoramento: frequência behavior, gatilhos, humor; (17) Prevenção recaída: H.A.L.T. (Hungry, Angry, Lonely, Tired), plano coping. Específico comida: dieta anti-inflamatória, proteína adequada, eliminar açúcares refinados, tratar deficiências (zinco, magnésio, ômega-3).',

  article_ids = ARRAY[]::uuid[]
WHERE id = '22681f12-e8f9-47a4-8a16-8174b61dcb8a';

-- Continua próximo bloco (saúde bucal)...
