-- ============================================
-- BATCH 6.1: HISTÓRICO DE DOENÇAS - PARTE 1 (Continuação)
-- Items 11-20
-- ============================================

-- Item 11: Varicela
UPDATE score_items
SET
  clinical_relevance = 'Varicela (catapora) é infecção primária por Vírus Varicela-Zoster (VZV), altamente contagiosa, comum infância. Transmissão: aerossóis respiratórios, contato direto lesões. Incubação: 10-21 dias. Manifestações: pródromo (febre, mal-estar 1-2 dias) → exantema maculopapular → vesículas ("gota de orvalho em pétala de rosa") → crostas, lesões em diferentes estágios evolutivos, prurido intenso. Distribuição centrípeta (tronco → extremidades), mucosas (enantema oral, genital). Duração: 5-7 dias até todas lesões em crosta. Complicações criança: infecção bacteriana secundária (Streptococcus, Staphylococcus), pneumonia, cerebelite, encefalite pós-infecciosa. Adultos: pneumonia varicelosa (25% hospitalizados, risco 25x vs crianças), hepatite. Gestação: síndrome varicela congênita se 1º-2º trimestre (hipoplasia membros, cicatrizes cutâneas, microcefalia), varicela neonatal severa se mãe 5 dias pré-parto a 2 dias pós (30% mortalidade). Imunossuprimidos: varicela disseminada, hepatite, pneumonite, encefalite, mortalidade elevada. Após varicela, VZV estabelece latência gânglios dorsais/cranianos → risco herpes zoster futuro. Na MFI: suporte imune (vitamina A, D, C, zinco), prevenção infecção secundária, cicatrização (zinco tópico), vacinação (>12 meses, 2 doses, 90% eficácia).',

  patient_explanation = 'Varicela (catapora) é doença viral muito contagiosa, comum na infância. Transmite pelo ar (tosse, espirro) e contato com as bolhas. Sintomas: febre, depois surgem manchas vermelhas que viram bolhas com líquido, estouram e formam casquinhas. As lesões coçam muito! Aparecem em surtos durante 5-7 dias, então você tem lesões em fases diferentes (manchas novas + bolhas + cascas). Começam no tronco e espalham para braços/pernas/rosto. Criança geralmente passa bem, mas pode complicar com infecção bacteriana nas lesões (coçar com unhas sujas). Adultos que pegam varicela pela primeira vez podem ter forma grave com pneumonia. Gestantes têm risco de má-formação fetal ou varicela grave no bebê se pegar próximo ao parto. Após você ter varicela, vírus nunca sai - fica dormindo nos nervos e pode reativar décadas depois como herpes zoster (cobreiro). Prevenção: vacina a partir de 1 ano (2 doses), 90% eficaz. Tratamento: controle coceira (anti-histamínicos, loções), antiviral (aciclovir) em casos graves ou grupos de risco. Manter unhas curtas e limpas para não infectar lesões. Na abordagem funcional: vitamina A, C, D e zinco fortalecem imunidade e aceleram cicatrização.',

  conduct = 'Diagnóstico clínico (típico): exantema vesicular polimórfico (lesões em diferentes estágios), febre, prurido, história contato. Confirmação raramente necessária: PCR lesão, sorologia VZV IgM/IgG (IgM+ infecção aguda, IgG+ imunidade). Avaliar gravidade: extensão lesões, febre alta persistente, comprometimento mucosas, sinais pneumonia (tosse, dispneia, taquipneia), alterações neurológicas (ataxia cerebelar, encefalite). Grupos risco complicações: adultos, gestantes, imunossuprimidos, <1 ano. Investigar MFI: hemograma (leucopenia viral), função hepática se suspeita hepatite, radiografia tórax se pneumonia. Tratamento suporte: repouso, hidratação, antitérmicos (paracetamol, nunca AAS - risco Reye), anti-histamínicos (prurido), banhos mornos, loções calamina. Antiviral (aciclovir 800mg 5x/dia ou 20mg/kg/dose criança 5-7 dias): adultos, >12 anos, gestantes, imunossuprimidos, complicações, iniciar <24h. Prevenção infecção secundária: unhas curtas, banhos, evitar coçar. Isolamento até todas lesões em crosta. Suplementação MFI: vitamina A 100.000-200.000UI dose única (reduz morbimortalidade), vitamina C 1-2g, vitamina D3 2.000-4.000UI, zinco 20-30mg, probióticos. Tópico: zinco óxido (cicatrização). Vacinação pós-exposição <72h (previne/atenua). Imunoglobulina antivaricela se gestante/imunossuprimido exposto. Prevenção: vacina varicela >12 meses (2 doses 4-8 semanas intervalo, 90% eficácia).',

  updated_at = NOW()
WHERE id = 'dae8d555-ef69-444f-810c-40fa736da05f';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, 'dae8d555-ef69-444f-810c-40fa736da05f'
FROM articles a
WHERE a.title ILIKE '%varicela%' OR a.title ILIKE '%viral%' OR a.title ILIKE '%pediatria%' OR a.title ILIKE '%imun%'
LIMIT 5
ON CONFLICT DO NOTHING;

-- Item 12: CMV (Citomegalovírus)
UPDATE score_items
SET
  clinical_relevance = 'Citomegalovírus (CMV, HHV-5) é beta-herpesvírus DNA, soroprevalência 50-90% adultos (maior países desenvolvimento). Transmissão: saliva, urina, secreções genitais, sangue, leite materno, transplante órgãos. Infecção primária imunocompetente: 90% assintomática, 10% síndrome mononucleose-like (febre, fadiga, linfadenopatia, hepatoesplenomegalia, transaminases elevadas, linfocitose atípica). Latência: monócitos, células endoteliais, glândulas salivares. Reativação: imunossupressão (HIV CD4<50, transplante, corticoides altas doses, quimioterapia). CMV ativa imunocomprometidos: retinite (cegueira), colite, esofagite, pneumonite, encefalite, polirradiculite, adrenalite. CMV congênita (0,6% nascidos, maior causa infecção congênita): assintomática 90%, sintomática 10% (microcefalia, calcificações intracranianas, surdez neurossensorial, retinite, hepatoesplenomegalia, petéquias, coriorretinite). Sequelas tardias: surdez (até 15%), atraso desenvolvimento. Gestação: soroconversão 1-4%, transmissão vertical 30-40% infecção primária vs 1-2% reativação. Na MFI: rastreio gestacional (IgG/IgM, avidez), investigar reativações (fadiga crônica, disfunção cognitiva em imunocompetentes), suporte imune (vitamina D, zinco, lactoferrina), antivirais (ganciclovir, valganciclovir) se doença ativa.',

  patient_explanation = 'Citomegalovírus (CMV) é vírus da família herpes muito comum - maioria dos adultos já teve contato. Transmite por saliva, urina, relação sexual, amamentação, transfusão sangue. Quando pessoa saudável pega pela primeira vez, geralmente não sente nada ou tem sintomas leves tipo gripe/mononucleose: cansaço, febre, gânglios aumentados. Depois vírus fica dormindo no corpo para sempre. Problema: CMV pode reativar quando imunidade cai muito (HIV avançado, transplante, quimioterapia) causando doenças graves - inflamação nos olhos podendo cegar, inflamação intestino, pulmão, cérebro. Maior risco é na gestação: se grávida pega CMV pela primeira vez, pode passar para bebê causando surdez, microcefalia, atraso desenvolvimento. Por isso é importante rastreio CMV no pré-natal. Se você já teve CMV antes de engravidar (IgG positivo), risco para bebê é baixo. Algumas pessoas relatam fadiga persistente e problemas memória associados a reativações CMV mesmo sem imunossupressão grave. Na medicina funcional, fortalecemos imunidade para manter vírus adormecido: vitamina D alta, zinco, lactoferrina (proteína leite com ação antiviral), alimentação anti-inflamatória, sono adequado.',

  conduct = 'Sorologia: CMV IgG/IgM, teste avidez IgG (diferencia infecção recente <12 semanas - baixa avidez vs antiga - alta avidez). IgG+ IgM-: infecção prévia/latente. IgG+ IgM+: infecção aguda/reativação (avidez diferencia). IgG- IgM+: infecção aguda recente. IgG- IgM-: suscetível. Doença ativa: CMV PCR DNA quantitativo sangue (carga viral, >1.000 cópias/ml significativo), antigenemia pp65, PCR líquor (encefalite), biópsia com imunohistoquímica (colite, pneumonite). Gestação: rastreio pré-natal CMV IgG/IgM + avidez se IgM+, ultrassom fetal se soroconversão (calcificações, microcefalia), amniocentese PCR CMV >21 semanas se infecção materna confirmada. Recém-nascido: CMV PCR urina/saliva <21 dias vida (diagnóstico infecção congênita), BERA (surdez), fundoscopia, TC crânio. Avaliar MFI: hemograma (linfocitose atípica, trombocitopenia), transaminases, função imune (CD4/CD8, carga viral HIV se positivo). Tratamento doença ativa: ganciclovir IV 5mg/kg 2x/dia 14-21 dias (indução) → valganciclovir oral 900mg 2x/dia manutenção ou foscarnet se resistência. CMV congênito sintomático: valganciclovir oral 6 meses (reduz sequelas auditivas/neurodesenvolvimento). Suporte MFI: vitamina D3 5.000UI, zinco 30mg, lactoferrina 300mg, vitamina C 1-2g, cogumelos medicinais, probióticos. Prevenção gestação: higiene mãos (trabalha creche/crianças pequenas), evitar compartilhar utensílios.',

  updated_at = NOW()
WHERE id = '736c482e-2e1b-40b0-be6d-b11e371fd6ee';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, '736c482e-2e1b-40b0-be6d-b11e371fd6ee'
FROM articles a
WHERE a.title ILIKE '%citomegalovírus%' OR a.title ILIKE '%CMV%' OR a.title ILIKE '%viral%' OR a.title ILIKE '%imun%'
LIMIT 5
ON CONFLICT DO NOTHING;

-- Item 13: EBV (Epstein-Barr Vírus)
UPDATE score_items
SET
  clinical_relevance = 'Epstein-Barr Vírus (EBV, HHV-4) é gamma-herpesvírus, soroprevalência >90% adultos. Transmissão: saliva ("doença do beijo"). Infecção primária: mononucleose infecciosa (adolescentes/adultos jovens) - febre alta, faringoamigdalite exsudativa severa, linfadenopatia generalizada (cervical posterior característica), hepatoesplenomegalia, fadiga intensa, rash se uso ampicilina. Duração: 2-4 semanas, fadiga pode persistir meses. Laboratório: linfocitose com linfócitos atípicos >10%, trombocitopenia leve, transaminases elevadas 2-3x. Complicações: ruptura esplênica (0,1-0,5%), anemia hemolítica, trombocitopenia severa, miocardite, encefalite, Guillain-Barré, obstrução vias aéreas. Latência: células B memória. Reativação: imunossupressão. Associações malignidade: linfoma Burkitt (África), linfoma Hodgkin (40% EBV+), carcinoma nasofaríngeo, linfoproliferação pós-transplante, linfomas SNC (AIDS). Síndrome fadiga crônica: EBV reativação crônica/persistente em subgrupo pacientes (fadiga incapacitante >6 meses, mal-estar pós-esforço, disfunção cognitiva, dor, sono não reparador). Autoimunidade: mimetismo molecular EBV pode desencadear LES, artrite reumatoide, esclerose múltipla (associação forte). Na MFI: investigar carga viral EBV (PCR), reativações (VCA IgM+, EBNA IgG-), suporte imune, antivirais naturais (monolaurina, lactoferrina), modulação inflamação.',

  patient_explanation = 'Epstein-Barr (EBV) é vírus que causa mononucleose - "doença do beijo" porque transmite pela saliva. Maioria pega na adolescência/início vida adulta. Sintomas: febre alta, garganta muito inflamada com placas de pus, gânglios inchados (principalmente pescoço atrás), fígado e baço aumentados, cansaço extremo. Dura 2-4 semanas, mas fadiga pode persistir meses. Risco: baço aumentado pode romper (evitar esportes contato 4-6 semanas). Após mononucleose, vírus fica dormindo em células do sistema imune para sempre. Problema: EBV pode reativar causando fadiga crônica severa, névoa mental, dores musculares - alguns casos de síndrome fadiga crônica estão ligados a reativações EBV. EBV também está associado a alguns cânceres (linfomas) e doenças autoimunes (lúpus, esclerose múltipla, artrite reumatoide) - vírus pode "confundir" sistema imune. Na medicina funcional, investigamos se EBV está reativando (exames sangue específicos) quando há fadiga inexplicada. Tratamento foca fortalecer imunidade: vitamina D muito alta, zinco, vitamina C, cogumelos medicinais (reishi), monolaurina (gordura coco com ação antiviral), lactoferrina, dieta anti-inflamatória, sono profundo, controle estresse rigoroso. Alguns suplementos antivirais naturais ajudam controlar reativações.',

  conduct = 'Sorologia EBV (complexa): VCA IgM (agudo, positivo 4-6 semanas), VCA IgG (aparece agudo, persiste vida toda), EBNA IgG (aparece após 3-6 meses, persiste). Padrões: Infecção aguda: VCA IgM+ VCA IgG+ EBNA-. Infecção prévia/latente: VCA IgM- VCA IgG+ EBNA+. Reativação: VCA IgM+ VCA IgG+ EBNA+ (ou VCA IgG títulos muito altos). Nunca exposto: todos negativos. PCR EBV DNA sangue quantitativo (carga viral, avaliar reativação/doença ativa). Monotest ou Paul-Bunnell (heterófilos): positivo 85% mononucleose, menos sensível. Hemograma: leucocitose/leucopenia, linfocitose >50%, linfócitos atípicos >10%, trombocitopenia. Transaminases: AST/ALT elevadas 80%. Ultrassom abdome: hepatoesplenomegalia, avaliar baço pré-esportes. Fadiga crônica pós-EBV: investigar EBV PCR DNA, perfil tireoidiano (tireoidite autoimune), cortisol (fadiga adrenal), vitamina D, B12, ferro, microbioma. Tratamento mononucleose: suporte (repouso, hidratação, analgesia, antitérmicos), evitar esportes 4-6 semanas (ruptura esplênica), corticoides se obstrução vias aéreas/complicações graves. Protocolo MFI reativação/fadiga crônica: vitamina D3 10.000UI (alvo >60ng/ml), zinco 50mg, vitamina C 2-3g, L-lisina 3g, monolaurina 3g (antiviral), lactoferrina 900mg, cogumelos medicinais (reishi 3g, cordyceps), probióticos, NAC 1.200mg, CoQ10 200mg, magnésio 400mg. Dieta: eliminar açúcar/glúten/laticínios, anti-inflamatória. Sono 8-9h, manejo estresse profundo (meditação). Considerar antivirais (valaciclovir 1g 3x/dia) se doença ativa severa.',

  updated_at = NOW()
WHERE id = '9e9a6233-fd9e-416b-8327-11c00851402e';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, '9e9a6233-fd9e-416b-8327-11c00851402e'
FROM articles a
WHERE a.title ILIKE '%Epstein%' OR a.title ILIKE '%EBV%' OR a.title ILIKE '%mononucleose%' OR a.title ILIKE '%fadiga%'
LIMIT 5
ON CONFLICT DO NOTHING;

-- Item 14: Dengue
UPDATE score_items
SET
  clinical_relevance = 'Dengue é arbovirose por flavivírus (DENV-1, 2, 3, 4), transmitida Aedes aegypti, endêmica América Latina/Ásia. Incidência BR: 1-3 milhões casos/ano, epidemias cíclicas. Fase febril (3-7 dias): febre alta súbita, cefaleia intensa retro-orbitária, mialgia/artralgia ("quebra-ossos"), exantema, náusea, vômitos, leucopenia, plaquetopenia. Prova laço positiva (fragilidade capilar). Classificação: dengue sem sinais alarme, com sinais alarme (dor abdominal intensa, vômitos persistentes, sangramento mucosas, hepatomegalia dolorosa, plaquetas <50.000, hematócrito aumentado), dengue grave (choque - extravasamento plasmático, sangramento grave, disfunção orgânica). Fase crítica (24-48h após defervescência): extravasamento plasmático, hemoconcentração, choque hipovolêmico se não hidratado. Recuperação: reabsorção fluidos, melhora plaquetas, exantema tardio pruriginoso. Hemorrágicos: gengivorragia, epistaxe, metrorragia, melena, hematêmese. Complicações: choque (mortalidade 10-20% sem tratamento, <1% com manejo), hepatite, miocardite, encefalite, Guillain-Barré. Sequelas pós-dengue (10-30%): fadiga crônica, artralgia persistente (meses), depressão, alopecia. Reinfecção outro sorotipo: risco dengue grave aumentado (facilitação anticorpo-dependente). Na MFI: hidratação vigorosa fase crítica, suporte hepático, modulação inflamação (curcumina, ômega-3), recuperação (micronutrientes, adaptógenos fadiga).',

  patient_explanation = 'Dengue é doença transmitida pela picada do mosquito Aedes aegypti infectado. Existem 4 tipos de vírus dengue (sorotipos 1,2,3,4). Sintomas: febre alta repentina (39-40°C), dor de cabeça forte atrás dos olhos, dor no corpo e juntas muito intensa ("quebradeira"), manchas vermelhas na pele, náusea. Evolução: febre dura 3-7 dias, quando cai é momento mais perigoso (fase crítica 24-48h) - pode haver extravasamento líquido dos vasos causando choque se não hidratar bem. Sinais alarme (procurar emergência): dor barriga intensa, vômitos sem parar, sangramento nariz/gengiva, sonolência, pressão baixa. Maioria se recupera, mas 10-30% ficam com cansaço e dor nas juntas por meses. Se você já teve dengue e pegar outro sorotipo, risco de forma grave aumenta. Tratamento: NÃO TEM ANTIVIRAL. É suporte: hidratação abundante (soro caseiro, água coco, água), repouso, paracetamol para dor/febre. NUNCA use AAS ou anti-inflamatórios (aumentam sangramento). Na fase crítica, hidratação venosa pode ser necessária. Prevenir: eliminar água parada (foco mosquito), repelente, telas. Na medicina funcional: após dengue, suplementamos para recuperação (vitaminas, minerais, adaptógenos) e modulamos inflamação residual.',

  conduct = 'Diagnóstico clínico-epidemiológico: febre + 2 critérios (cefaleia retro-orbitária, mialgia, artralgia, exantema, manifestações hemorrágicas, leucopenia) + epidemiologia. Confirmação laboratorial: NS1 antígeno (dias 1-5, alta especificidade), PCR dengue (dias 1-5, identifica sorotipo), sorologia IgM/IgG (IgM+ dia 5+, IgG+ após 7-10 dias). Hemograma seriado (dias alternados fase febril e crítica): leucopenia <4.000, plaquetopenia progressiva (<100.000 atenção, <50.000 alarme), hematócrito (aumento >20% indica hemoconcentração/extravasamento). Transaminases elevadas 2-5x (hepatite dengue). Classificação risco: SEM alarme (ambulatorial, hidratação oral 60ml/kg/dia + perdas), COM alarme (internação, hidratação IV cristaloide), GRAVE (UTI, reposição volêmica agressiva, transfusão se necessário). Conduta fase crítica: monitorar hematócrito/plaquetas 6-12h, sinais vitais, diurese >1ml/kg/h. Manejo hidratação cuidadoso (risco sobrecarga). Evitar: AAS, AINES (sangramento), IM (hematomas). Suporte MFI recuperação: hidratação otimizada (água coco, caldos), repouso completo fase aguda. Suplementação pós-dengue: vitamina C 2g (antioxidante), vitamina D3 5.000UI, ômega-3 2g (modula inflamação), curcumina 1g, multivitamínico, magnésio 400mg, probióticos, adaptógenos fadiga (rhodiola 300mg, ashwagandha 500mg, cordyceps). Dieta anti-inflamatória. Retorno gradual atividades.',

  updated_at = NOW()
WHERE id = '881f7ba9-820f-4ebc-8831-6a3925345344';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, '881f7ba9-820f-4ebc-8831-6a3925345344'
FROM articles a
WHERE a.title ILIKE '%dengue%' OR a.title ILIKE '%arbovirose%' OR a.title ILIKE '%infeccios%'
LIMIT 5
ON CONFLICT DO NOTHING;

-- Item 15: Zika
UPDATE score_items
SET
  clinical_relevance = 'Zika é arbovirose por flavivírus, transmitida Aedes aegypti/albopictus, sexual, vertical. Epidemia Brasil 2015-2016. Infecção: 80% assintomática. Sintomática (3-7 dias): febre baixa/ausente, exantema maculopapular pruriginoso difuso (face → tronco → extremidades), conjuntivite não-purulenta bilateral, artralgia (mãos/pés, menos intensa que chikungunya), mialgia, cefaleia. Raramente gravidade ou morte. Complicações neurológicas: síndrome Guillain-Barré (autoimune desmielinizante, paralisia flácida ascendente, insuficiência respiratória 25%, recuperação lenta meses-anos, sequelas 20%), meningoencefalite, mielite. Zika congênita (síndrome congênita Zika): microcefalia severa (perímetro cefálico <-2DP), calcificações intracranianas, lisencefalia, hipoplasia cerebral/cerebelar, ventriculomegalia, alterações oculares (coriorretinite, atrofia nervo óptico), artrogripose, hipertonia. Sequelas: atraso neurodesenvolvimento grave, epilepsia refratária, disfagia, surdez. Risco maior: infecção 1º trimestre (até 42% microcefalia), mas pode ocorrer qualquer trimestre. Transmissão sexual: vírus persiste sêmen >6 meses. Diagnóstico: PCR urina/sangue (dias 1-14), sorologia IgM (dia 5+), reação cruzada dengue. Gestação: PCR soro/urina materno, amniocentese se infecção confirmada, ultrassom seriado. Não há tratamento específico. Na MFI: suporte sintomático, prevenção gestação (repelente, camisinha, evitar áreas endêmicas).',

  patient_explanation = 'Zika é vírus transmitido pelo mesmo mosquito da dengue (Aedes aegypti). Maioria das pessoas (80%) não sente nada. Quando tem sintomas, são leves: febre baixa ou sem febre, manchas vermelhas pelo corpo que coçam, olhos vermelhos sem pus, dor leve nas juntas (mãos e pés principalmente), dor no corpo, dor de cabeça. Dura 3-7 dias e passa sozinho. Raramente é grave em adultos. Problemas: 1) Pode causar Guillain-Barré (doença onde sistema imune ataca nervos, causando fraqueza/paralisia que sobe das pernas, pode precisar respirador, recuperação lenta). 2) RISCO GRAVÍSSIMO NA GESTAÇÃO: Zika atravessa placenta e ataca cérebro do bebê causando microcefalia (cabeça muito pequena, cérebro não desenvolveu), além de outros problemas neurológicos graves, epilepsia, cegueira, surdez. Bebês ficam com sequelas permanentes severas. Risco existe durante TODA gestação, maior no 1º trimestre. Zika também transmite por relação sexual (vírus fica no sêmen até 6 meses). Se você está grávida ou planejando: evite áreas com Zika, use repelente religiosamente, parceiro deve usar camisinha se viajou para área endêmica. Não existe tratamento ou vacina. Prevenção é essencial: eliminar focos mosquito, repelente, telas, camisinha.',

  conduct = 'Diagnóstico: PCR Zika vírus soro + urina (sensibilidade maior urina, positivo até dia 14) preferencial, sorologia IgM (dia 5+, reação cruzada dengue/outras flaviviroses - PRNT para confirmação). Gestante: rastreio Zika se sintomas ou exposição (viagem área endêmica, parceiro exposto): PCR soro/urina materno, ultrassom morfológico detalhado (perímetro cefálico, calcificações, ventriculomegalia), amniocentese PCR Zika se infecção materna confirmada >15 semanas. Ultrassom seriado mensal até termo. RN mãe Zika+: avaliação clínica detalhada, perímetro cefálico, fundoscopia, BERA, TC crânio, sorologias STORCH. Guillain-Barré: eletroneuromiografia (desmielinização), punção lombar (dissociação proteíno-citológica), monitorar função respiratória (CVF). Tratamento: suporte sintomático (analgesia, anti-histamínicos prurido, hidratação), repouso. Evitar AAS/AINES até descartar dengue. Guillain-Barré: imunoglobulina IV 2g/kg 5 dias ou plasmaférese, UTI se insuficiência respiratória, fisioterapia. Prevenção gestação: evitar viagem áreas Zika, repelente DEET/icaridina, roupas longas, telas, ar-condicionado. Abstinência sexual ou camisinha se parceiro exposto (6 meses sêmen, 8 semanas outros fluidos). Suporte MFI: vitamina C 1-2g, vitamina D3 5.000UI, zinco 30mg, probióticos. Guillain-Barré: vitaminas B (neuroproteção), ômega-3, fisioterapia intensiva.',

  updated_at = NOW()
WHERE id = '5be4bc08-7625-4422-a5ee-e02540370f7a';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, '5be4bc08-7625-4422-a5ee-e02540370f7a'
FROM articles a
WHERE a.title ILIKE '%zika%' OR a.title ILIKE '%arbovirose%' OR a.title ILIKE '%gestação%' OR a.title ILIKE '%neurolog%'
LIMIT 5
ON CONFLICT DO NOTHING;
