-- ============================================
-- BATCH 6.1: HISTÓRICO DE DOENÇAS - PARTE 1 (Continuação)
-- Items 6-15
-- ============================================

-- Item 6: Questionar sobre qualquer outra doença crônica
UPDATE score_items
SET
  clinical_relevance = 'Campo aberto para documentar outras doenças crônicas não listadas especificamente. Importância: muitas condições crônicas compartilham mecanismos fisiopatológicos comuns (inflamação sistêmica, estresse oxidativo, disfunção mitocondrial, resistência insulínica, disbiose) e podem ter abordagem funcional integrativa. Exemplos: fibromialgia, síndrome fadiga crônica, endometriose, síndrome ovários policísticos, psoríase, vitiligo, tireoidite Hashimoto, Graves, artrite reumatoide, espondilite anquilosante, miastenia gravis, esclerose múltipla, doença Parkinson, Alzheimer, bronquiectasias, sarcoidose, amiloidose, vasculites, síndrome antifosfolípide, doença Behçet, etc. Na MFI: investigar sempre causas raiz independente do diagnóstico - eixos: inflamação (PCR-us, citocinas), microbiota (disbiose, SIBO, permeabilidade), metabólico (resistência insulínica, disfunção mitocondrial), hormonal (tireóide, adrenal, sexual), toxicidade (metais pesados, mofo, químicos), nutricional (deficiências múltiplas), imunológico (autoimunidade, imunodeficiências). Abordagem: corrigir desequilíbrios fundamentais antes tratar doença específica - muitas vezes sintomas melhoram dramaticamente otimizando sono, dieta anti-inflamatória, exercício, manejo estresse, suplementação direcionada.',

  patient_explanation = 'Este campo serve para registrar qualquer doença crônica que você tenha e que não estava listada especificamente nas perguntas anteriores. Pode ser condição autoimune (como artrite reumatoide, tireoidite de Hashimoto, psoríase), neurológica (Parkinson, esclerose múltipla, enxaqueca crônica), metabólica, respiratória, dermatológica - qualquer problema de saúde que você convive há mais de 6 meses. É muito importante documentar TODAS suas condições porque na medicina funcional olhamos o corpo como sistema integrado: muitas doenças diferentes têm causas raiz semelhantes (inflamação crônica, intestino permeável, deficiências nutricionais, toxinas acumuladas, estresse não gerenciado). Por exemplo: alguém com fibromialgia + síndrome intestino irritável + ansiedade pode ter disbiose intestinal como causa comum das três. Ao corrigir o desequilíbrio fundamental (restaurar microbiota saudável), todas melhoram juntas. Por isso precisamos visão completa do seu histórico. Quanto mais detalhes você fornecer sobre suas condições crônicas, melhor podemos identificar padrões e criar plano terapêutico personalizado.',

  conduct = 'Documentação detalhada: nome doença, ano diagnóstico, como foi diagnosticada (exames, critérios), evolução (estável, progressiva, remitente-recorrente), grau controle atual (controlada, parcialmente controlada, descompensada), tratamentos prévios e atuais (medicações, doses, tempo uso, eficácia, efeitos colaterais), complicações desenvolvidas, impacto qualidade vida (escala 0-10), limitações funcionais. Solicitar relatórios médicos, laudos exames diagnósticos. Investigação MFI genérica: hemograma completo, PCR ultrassensível, VHS, perfil metabólico (glicemia, insulina, HOMA-IR, HbA1c), perfil lipídico avançado (LDL-p, ApoB, Lp(a)), perfil hepático/renal, eletrólitos, micronutrientes (vitamina D, B12, folato, ferro, ferritina, zinco, magnésio, selênio), perfil tireoidiano (TSH, T4L, T3L, T3R, anti-TPO, anti-Tg), cortisol salivar 4 pontos, homocisteína, ácido úrico, marcadores intestinais (calprotectina, zonulina), autoanticorpos se suspeita autoimune (FAN, FR, anti-CCP). Protocolo básico MFI: dieta anti-inflamatória mediterrânea ou AIP, sono 7-9h, exercício regular, manejo estresse (meditação, respiração), suplementação conforme deficiências identificadas. Encaminhar especialista se necessário.',

  updated_at = NOW()
WHERE id = '8557eaca-88d8-4186-b669-ed5f667eb1c8';

-- Item 7: Doenças infecciosas
UPDATE score_items
SET
  clinical_relevance = 'Campo categórico para rastrear histórico infecções significativas que podem ter impacto duradouro na saúde. Infecções agudas/crônicas podem: desencadear autoimunidade (mimetismo molecular - Streptococcus → febre reumática, Campylobacter → Guillain-Barré), causar inflamação persistente pós-infecciosa (long-COVID, síndrome pós-dengue), cronificar (HIV, hepatites B/C, tuberculose latente, herpesvírus reativantes), predispor complicações tardias (HPV → câncer cervical, H.pylori → câncer gástrico, EBV → linfomas). Vírus herpes (HSV, VZV, EBV, CMV, HHV-6) estabelecem latência vitalícia em gânglios/células B, reativando quando imunidade celular cai (estresse, sono ruim, deficiências). Reativações: fadiga crônica, disfunção cognitiva, autoimunidade. Arboviroses (dengue, zika, chikungunya): sequelas articulares/neurológicas meses-anos. COVID-19: síndrome pós-COVID (fadiga, brain fog, disautonomia, fibrose pulmonar) em 10-30%. Tuberculose: sequelas pulmonares, disseminação. Na MFI: investigar carga viral latente (sorologia IgG/IgM, PCR), função imune celular (relação CD4/CD8, NK cells), reativações (IgM+, IgG avidez baixa), suporte imune (vitamina D >50ng/ml, zinco, selênio, vitamina C, cogumelos medicinais, lactoferrina), modulação inflamação pós-infecciosa.',

  patient_explanation = 'Esta seção investiga seu histórico de infecções importantes - doenças causadas por vírus, bactérias, fungos ou parasitas que você já teve. Por que importa? Porque algumas infecções deixam marcas duradouras no corpo mesmo depois de "curadas". Exemplos: vírus da família herpes (herpes labial, catapora, mononucleose) nunca saem completamente - ficam dormindo em células nervosas e podem reativar quando imunidade cai, causando cansaço persistente, dor crônica, névoa mental. Dengue, zika e chikungunya podem deixar dor nas juntas por meses/anos. COVID pode virar "COVID longa" com fadiga extrema, falta de ar, problemas memória. Tuberculose pode deixar sequelas nos pulmões. HPV pode causar câncer de colo uterino. H.pylori aumenta risco câncer estômago. Na medicina funcional, investigamos se infecções antigas estão reativando ou se deixaram inflamação residual. Sinais: cansaço que não melhora, infecções recorrentes (herpes labial frequente indica imunidade baixa), dores inexplicadas. Tratamento foca fortalecer sistema imune: vitamina D alta, zinco, vitamina C, sono adequado, dieta anti-inflamatória, controle estresse.',

  conduct = 'Histórico detalhado: infecções prévias significativas (tuberculose, hepatites, HIV, herpes recorrentes, mononucleose, dengue/zika/chikungunya, COVID-19 e sequelas), infecções recorrentes (ITU, sinusites, candidíase, herpes >6x/ano indica imunodeficiência). COVID-19: duração sintomas agudos, hospitalização/UTI, sequelas persistentes >3 meses (fadiga, dispneia, brain fog, palpitações, dor torácica). Investigar: sorologia viral ampla (HIV 1/2, hepatites A/B/C, HTLV, herpesvírus - HSV-1/2 IgG/IgM, VZV IgG, EBV VCA IgG/IgM + EBNA IgG, CMV IgG/IgM, HHV-6), PPD ou IGRA (tuberculose latente), toxoplasmose IgG, VDRL (sífilis), marcadores inflamação pós-infecciosa (PCR-us, VHS, ferritina). Função imune: hemograma (linfopenia?), imunoglobulinas (IgG, IgA, IgM, IgE), subpopulações linfocitárias (CD4, CD8, NK cells, relação CD4/CD8), complemento C3/C4. Micronutrientes: vitamina D (alvo >50ng/ml), zinco, selênio, vitamina A, vitamina C. Protocolo suporte imune: vitamina D3 5.000-10.000UI, zinco 30-50mg, vitamina C 1-2g, selênio 200mcg, probióticos multi-cepas, cogumelos medicinais (shiitake, maitake 1-3g), lactoferrina 300mg, beta-glucanas, sono 8h, exercício moderado, manejo estresse. Se reativações herpéticas: L-lisina 1-3g, reduzir arginina (nozes, chocolate).',

  updated_at = NOW()
WHERE id = '40cf97e4-e3da-4ece-b1af-2aecca8ded54';

-- Item 8: Tuberculose
UPDATE score_items
SET
  clinical_relevance = 'Tuberculose (TB) é infecção por Mycobacterium tuberculosis, principal causa morte por agente infeccioso único (pré-COVID). Incidência BR: 35/100.000 (2023), áreas endêmicas >100/100.000. Transmissão: aerossóis, tosse paciente bacilífero. Formas: pulmonar (85% - tosse >3 semanas, hemoptise, febre vespertina, sudorese noturna, perda peso) e extrapulmonar (pleural, ganglionar, meníngea, óssea, renal, miliar). Infecção latente (ILTB): 25% população mundial, PPD+/IGRA+ sem doença ativa, 5-10% risco reativação (principalmente <2 anos pós-infecção ou imunossupressão). Fatores risco reativação: HIV (risco 20-30x), diabetes (3x), IRC, imunobiológicos (anti-TNF), desnutrição, etilismo. Diagnóstico: baciloscopia escarro, cultura (padrão-ouro), Xpert MTB/RIF (resistência rifampicina), radiografia tórax (infiltrado, cavitação lobo superior). Tratamento: esquema básico 6 meses (RIPE 2 meses: rifampicina, isoniazida, pirazinamida, etambutol; RI 4 meses). Complicações: fibrose pulmonar residual, bronquiectasias, aspergiloma (bola fúngica em cavidade), cor pulmonale. Na MFI: investigar deficiências (vitamina D <20ng/ml aumenta risco 2-3x, zinco, vitamina A, selênio), desnutrição proteico-calórica, diabetes, suporte nutricional durante tratamento (hepatoproteção, neuropatia por isoniazida).',

  patient_explanation = 'Tuberculose é doença causada por bactéria (Mycobacterium tuberculosis) que ataca principalmente pulmões, mas pode atingir outros órgãos. Transmite pelo ar quando pessoa doente tosse. Sintomas: tosse persistente >3 semanas (pode ter sangue), febre baixa à tarde/noite, suores noturnos encharcando roupa, perda peso não intencional, cansaço extremo. Muitas pessoas têm TB "latente" - carregam bactéria adormecida sem doença ativa, só descobrem no teste PPD (tuberculina) ou IGRA positivo. TB latente pode reativar se imunidade cair (HIV, diabetes, medicações que baixam imunidade, desnutrição). TB ativa precisa tratamento urgente: 6 meses de antibióticos combinados (rifampicina, isoniazida, pirazinamida, etambutol). Sem tratamento, pode ser fatal. Mesmo curada, TB pode deixar sequelas nos pulmões (cicatrizes, bronquiectasias). Na abordagem funcional, investigamos por que você pegou/reativou: vitamina D muito baixa é fator de risco importante. Durante tratamento, suplementamos para proteger fígado (medicações são pesadas) e prevenir neuropatia. Alimentação rica em proteínas e calorias é essencial para recuperação.',

  conduct = 'Rastreio: PPD (Mantoux >5mm HIV/imunossuprimidos, >10mm risco aumentado, >15mm população geral) ou IGRA (QuantiFERON, T-SPOT, mais específico, não interfere BCG). TB ativa: baciloscopia escarro 3 amostras (BAAR), cultura Löwenstein-Jensen (4-8 semanas, antibiograma), Xpert MTB/RIF (PCR, 2h, detecta resistência rifampicina), radiografia tórax (infiltrado/cavitação lobos superiores, padrão miliar), TC tórax se RX inconclusivo. Extrapulmonar: biópsia, cultura materiais (líquor, líquido pleural, urina, linfonodo). Avaliar: HIV (testar sempre), glicemia/HbA1c (diabetes), albumina, transaminases basais (monitorar hepatotoxicidade), hemograma, função renal. Investigar MFI: vitamina D (alvo >40ng/ml, suplementar se baixa), zinco, vitamina A, selênio, estado nutricional (IMC, albumina, pré-albumina). Tratamento ILTB: isoniazida 300mg 9 meses ou rifampicina 600mg 4 meses. TB ativa: RIPE 2 meses (rifampicina 600mg, isoniazida 300mg, pirazinamida 2g, etambutol 1.200mg) → RI 4 meses. Suplementação protetora: vitamina B6 50mg (previne neuropatia isoniazida), vitamina D3 5.000UI, NAC 1.200mg (hepatoproteção), probióticos, zinco 30mg, silimarina 300mg. Monitorar transaminases mensal, adesão (DOT - directly observed therapy). Controle: baciloscopia mensal (negativação esperada 2º mês), radiografia controle.',

  updated_at = NOW()
WHERE id = '817ceb1a-a06f-4829-b9ee-dda47b6b55d4';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, '817ceb1a-a06f-4829-b9ee-dda47b6b55d4'
FROM articles a
WHERE a.title ILIKE '%tuberculos%' OR a.title ILIKE '%infeccios%' OR a.title ILIKE '%pulmonar%'
LIMIT 5
ON CONFLICT DO NOTHING;

-- Item 9: Herpes Simples
UPDATE score_items
SET
  clinical_relevance = 'Herpes Simples Vírus (HSV) - DNA vírus neurotropico alfa-herpesvírus, estabelece latência vitalícia em gânglios nervosos. Tipos: HSV-1 (orolabial 67% adultos, genital 20-40% novos casos) e HSV-2 (genital 80%, soroprevalência 16%). Transmissão: contato direto lesões/secreções, assintomática (shedding viral). Primo-infecção: gengivoestomatite herpética (crianças HSV-1), herpes genital (vesículas agrupadas, ulcerações dolorosas, adenopatia, febre). Recorrências: pródromo (formigamento, ardor) → vesículas → úlceras → crostas 7-10 dias, frequência variável (0 a >12/ano). Gatilhos reativação: estresse físico/emocional, febre, exposição UV, menstruação, imunossupressão, privação sono, deficiência L-lisina. Latência: gânglio trigêmeo (HSV-1 oral), gânglios sacrais (HSV-2 genital), reativação quando imunidade celular (CD8+ específicas) diminui. Complicações: encefalite herpética (HSV-1, 1/500.000, mortalidade 70% sem tratamento), herpes neonatal (transmissão parto, 60% mortalidade), ceratite (cegueira), eritema multiforme, meningite. Na MFI: modulação imune (vitamina D >50ng/ml, zinco, vitamina C), L-lisina 1-3g (compete arginina, bloqueia replicação), reduzir arginina (nozes, chocolate, amendoim), probióticos Lactobacillus, monolaurina, própolis, melissa tópica.',

  patient_explanation = 'Herpes simples é vírus muito comum que causa feridas dolorosas. Existem 2 tipos: HSV-1 (principalmente herpes labial - aquelas bolhinhas nos lábios) e HSV-2 (principalmente herpes genital). Maioria das pessoas pega na infância/adolescência. Após primeira infecção, vírus nunca sai do corpo - fica dormindo em nervos perto da medula. Quando sua imunidade cai (estresse, doença, cansaço, sol forte, menstruação), vírus "acorda" e desce pelo nervo causando nova lesão. Sintomas: começa com formigamento/ardência, depois aparecem bolhinhas agrupadas que doem, estouram virando feridas, depois formam casca e cicatrizam em 7-10 dias. Algumas pessoas têm crises raras (1-2x/ano), outras frequentes (todo mês). Não tem cura, mas tem controle! Medicações antivirais (aciclovir) diminuem duração e frequência. Na abordagem funcional, focamos em fortalecer imunidade para vírus ficar dormindo: vitamina D bem alta (>50), zinco, vitamina C, sono adequado, controle estresse. L-lisina (aminoácido) tomado diariamente previne crises. Evitar alimentos ricos em arginina (chocolate, nozes, amendoim) que favorecem replicação viral.',

  conduct = 'Diagnóstico clínico (típico): lesões vesiculares agrupadas em base eritematosa. Confirmação laboratorial se necessário: PCR lesão (padrão-ouro, tipagem HSV-1/2), cultura viral, sorologia IgG/IgM HSV-1/2 (IgM+ infecção aguda/reativação, IgG+ infecção prévia). Casos especiais: PCR líquor se encefalite, swab genital se assintomático. Avaliar frequência recorrências (>6/ano indica imunossupressão), gatilhos identificados. Investigar MFI: função imune celular (linfócitos CD4/CD8, NK cells), vitamina D (alvo >50ng/ml, baixa associada mais recorrências), zinco sérico/eritrocitário, vitamina C, estresse (cortisol salivar 4 pontos), sono (polissonografia se suspeita apneia), perfil tireoidiano (hipotireoidismo diminui imunidade), glicemia (diabetes piora). Tratamento agudo: aciclovir 400mg 5x/dia 5-10 dias ou valaciclovir 1g 2x/dia 7-10 dias, iniciar primeiras 24-48h (mais eficaz). Supressão crônica (≥6 crises/ano): aciclovir 400mg 2x/dia ou valaciclovir 500mg 1x/dia continuamente. Protocolo MFI prevenção: L-lisina 1.000-3.000mg/dia (reduz 50% recorrências), vitamina D3 5.000-10.000UI (alvo >50ng/ml), zinco 30mg, vitamina C 1-2g, probióticos Lactobacillus, monolaurina 1-3g (antiviral), própolis 500mg, cogumelos medicinais (reishi). Reduzir arginina: evitar nozes, amendoim, chocolate, sementes. Tópico: melissa (Melissa officinalis) creme 4x/dia (acelera cicatrização). Manejo estresse: meditação, sono 8h.',

  updated_at = NOW()
WHERE id = '7678a313-d0a4-4f2e-b0b3-72f23851469f';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, '7678a313-d0a4-4f2e-b0b3-72f23851469f'
FROM articles a
WHERE a.title ILIKE '%herpes%' OR a.title ILIKE '%viral%' OR a.title ILIKE '%imun%'
LIMIT 5
ON CONFLICT DO NOTHING;

-- Item 10: Herpes Zoster
UPDATE score_items
SET
  clinical_relevance = 'Herpes Zoster (HZ, cobreiro) é reativação do Vírus Varicela-Zoster (VZV) latente em gânglios dorsais/cranianos após varicela prévia. Incidência: 3-5/1.000/ano, aumenta >50 anos (10/1.000) e >80 anos (20/1.000). Fisiopatologia: queda imunidade celular VZV-específica (envelhecimento, imunossupressão, estresse) → replicação viral gânglio → migração nervo periférico → erupção dermatomal unilateral. Manifestações: pródromo (dor, parestesia, prurido dermátomo 1-5 dias) → erupção maculopapular → vesículas agrupadas dermátomo (T3-L3 55%, região oftálmica V1 10-25%) → crostas 2-4 semanas. Complicações: neuralgia pós-herpética (NPH 10-20%, >50% se >60 anos, dor neuropática persistente >3 meses, refratária, incapacitante), herpes zoster oftálmico (ceratite, uveíte, necrose retina, cegueira), síndrome Ramsay-Hunt (paralisia facial + vesículas orelha/canal auditivo), encefalite, mielite, AVC (vasculite VZV). Fatores risco: idade >50, imunossupressão (HIV, quimio, corticoides, anti-TNF), neoplasias, estresse severo, deficiência vitamina D. Na MFI: profilaxia com vacinação >50 anos (Shingrix 90% eficácia), suporte imune (vitamina D >50ng/ml, zinco, L-lisina), tratamento precoce (<72h) reduz NPH, suplementação vitaminas B (neuropatia), capsaicina tópica NPH.',

  patient_explanation = 'Herpes zoster (cobreiro) é reativação do vírus da catapora que fica dormindo nos nervos após você ter tido varicela (geralmente na infância). Quando imunidade cai (idade avançada, estresse intenso, doença, medicações que baixam imunidade), vírus acorda e desce por um nervo causando dor intensa e erupção em faixa (segue trajeto do nervo, só um lado do corpo). Sintomas: começa com dor/ardência/formigamento em área específica (tórax, barriga, rosto), depois surgem bolhas agrupadas vermelhas muito dolorosas que viram feridas e formam cascas. Problema mais temido: neuralgia pós-herpética (NPH) - dor neuropática que persiste meses/anos após lesões cicatrizarem, extremamente incapacitante, difícil tratar. Risco NPH aumenta com idade e demora para iniciar tratamento. Herpes zoster no olho pode causar cegueira. IMPORTANTE: procure médico nas primeiras 72 horas! Antiviral precoce (aciclovir, valaciclovir) reduz muito risco de NPH. Existe vacina (Shingrix) recomendada >50 anos, previne 90% dos casos. Na medicina funcional, fortalecemos imunidade para prevenir: vitamina D alta, zinco, sono adequado, controle estresse, alimentação anti-inflamatória.',

  conduct = 'Diagnóstico clínico: erupção vesicular dolorosa unilateral dermatomal. Confirmação se necessário: PCR vesícula (padrão-ouro), Tzanck (células gigantes multinucleadas), DFA, sorologia VZV IgM (menos sensível). Casos especiais: PCR líquor (encefalite/mielite), avaliação oftalmológica urgente se HZ oftálmico (V1). Avaliar fatores risco: idade, comorbidades, imunossupressão (HIV, neoplasias), estresse, micronutrientes. Investigar MFI: vitamina D (alvo >50ng/ml), zinco, vitamina B12 (neuropatia), hemograma, função imune se <50 anos (CD4/CD8), glicemia (diabetes associado). Tratamento agudo (<72h início): valaciclovir 1g 3x/dia 7 dias (preferencial) ou aciclovir 800mg 5x/dia 7-10 dias ou famciclovir 500mg 3x/dia 7 dias. Analgesia: paracetamol, dipirona, opioides fracos se dor severa, pregabalina/gabapentina 300-900mg (dor neuropática), antidepressivos tricíclicos (amitriptilina 25-75mg noturno). Tópico: calamina, capsaicina creme (após fase aguda). Prevenção NPH: tratamento antiviral <72h (reduz 50%), pregabalina precoce. Protocolo MFI: vitamina D3 10.000UI (modulação imune), zinco 50mg, L-lisina 3g, vitamina B12 1.000mcg + B1 300mg + B6 100mg (neuroproteção), vitamina C 2g, probióticos, cogumelos medicinais. NPH estabelecida: pregabalina 150-300mg 2x/dia, duloxetina 60mg, lidocaína adesivo 5%, capsaicina patch 8%, bloqueios nervosos, acupuntura. Vacinação Shingrix >50 anos (2 doses, 90% eficácia).',

  updated_at = NOW()
WHERE id = '09558858-1545-483f-94a6-86102fae8ca4';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, '09558858-1545-483f-94a6-86102fae8ca4'
FROM articles a
WHERE a.title ILIKE '%zoster%' OR a.title ILIKE '%herpes%' OR a.title ILIKE '%viral%' OR a.title ILIKE '%dor%'
LIMIT 5
ON CONFLICT DO NOTHING;
