-- ============================================================================
-- BATCH PARTE 6 - ENRIQUECIMENTO DE 20 ITEMS DE EXAMES LABORATORIAIS
-- Items: Cistatina C, Cobre, CoQ10, Colesterol, Colonoscopia scores
-- ============================================================================

-- 1. CILINDROS PATOLÓGICOS (1 item)
-- ID: 83d713f2-4b20-43fe-8b7e-c3dea08a3cb1
UPDATE score_items
SET
    clinical_relevance = 'Cilindros patológicos na urina são estruturas formadas no lúmen tubular renal indicando doença glomerular ou tubular ativa. Cilindros hemáticos (eritrocitários) são patognomônicos de glomerulonefrite aguda ou vasculite, apresentando-se como agregados de hemácias em matriz proteica. Cilindros granulosos indicam lesão tubular com descamação celular e degeneração, frequentes em necrose tubular aguda (NTA). Cilindros leucocitários sugerem nefrite intersticial ou pielonefrite. Cilindros céreos de base larga indicam insuficiência renal crônica avançada com estase tubular prolongada. A presença de cilindros patológicos (>2/campo de baixo aumento) sempre demanda investigação nefrológica urgente. Cilindros hialinos isolados são benignos (desidratação, exercício), mas cilindros patológicos indicam doença renal estrutural. A diferenciação microscópica requer experiência: hemáticos são amarelo-acastanhados com células reconhecíveis; granulosos mostram grânulos refringentes; céreos são quebradiços e largo. Estudos recentes (2023) demonstram que cilindros eritrocitários têm VPP >85% para nefrite glomerular, enquanto cilindros leucocitários têm sensibilidade 70% para nefrite intersticial aguda.',
    patient_explanation = 'Cilindros patológicos são pequenas estruturas em forma de tubo encontradas na urina quando há inflamação ou lesão nos rins. Eles são formados dentro dos tubos microscópicos dos rins (túbulos) e sua presença indica que algo está afetando ativamente a função renal. Existem vários tipos: cilindros com sangue sugerem inflamação dos filtros renais, cilindros com células brancas indicam infecção ou reação inflamatória, e cilindros granulosos mostram lesão das células renais. Encontrar cilindros patológicos no exame de urina é um sinal de alerta importante que requer avaliação médica, pois pode indicar desde infecções urinárias até doenças mais sérias dos rins. O tipo específico de cilindro ajuda o médico a identificar qual parte do rim está afetada e orientar o tratamento adequado.',
    conduct = 'Presença de cilindros patológicos: solicitar urgente proteinúria 24h, creatinina sérica, ureia, eletrólitos, hemograma completo. Cilindros hemáticos: investigar glomerulonefrite (complemento C3/C4, FAN, ANCA, anti-GBM, sorologias hepatite B/C, HIV). Considerar biópsia renal em <7 dias se TFG em queda ou síndrome nefrítica/nefrótica. Cilindros leucocitários: afastar pielonefrite (urocultura) e nefrite intersticial (revisar medicações: AINEs, antibióticos, IBP). Cilindros granulosos: investigar NTA (história de hipotensão, nefrotóxicos, rabdomiólise). Cilindros céreos: indicam DRC avançada, encaminhar nefrologia para planejamento dialítico. Monitoramento: repetir EAS em 48-72h após início do tratamento para avaliar resolução. Cilindros persistentes >7 dias ou piora da função renal são critérios para encaminhamento nefrológico urgente (24-48h). Evitar nefrotóxicos (contraste iodado, aminoglicosídeos, AINEs) até esclarecimento diagnóstico.',
    last_review = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = '83d713f2-4b20-43fe-8b7e-c3dea08a3cb1';

-- 2. CISTATINA C (2 items)
-- IDs: be74b5ba-6a8b-414b-a6dc-f1b50ae1b84f, 600b5157-efeb-4863-aa5e-6ae48d291c2d
UPDATE score_items
SET
    clinical_relevance = 'Cistatina C é um inibidor de protease cistêina produzido constantemente por todas as células nucleadas, filtrado livremente pelos glomérulos e completamente reabsorvido/catabolizado nos túbulos proximais, tornando-se marcador superior de taxa de filtração glomerular (TFG) comparado à creatinina. Valores de referência: 0,57-1,02 mg/L (adultos <50 anos), até 1,20 mg/L (>70 anos). Cistatina C não sofre influência significativa de massa muscular, dieta proteica, sexo ou etnia, superando limitações da creatinina. É especialmente útil em populações com massa muscular alterada (idosos, amputados, desnutridos, atletas) e na detecção precoce de disfunção renal leve (TFG 60-89 mL/min), onde creatinina ainda permanece normal. Equações combinadas (CKD-EPI cis-creat) apresentam acurácia 15-20% superior às baseadas apenas em creatinina. Metanálise 2022 (>90.000 pacientes) demonstrou que cistatina C é preditor independente de mortalidade cardiovascular e progressão para DRC terminal, mesmo com creatinina normal. Elevações podem ocorrer em hipotireoidismo grave, corticoterapia em altas doses e tabagismo intenso.',
    patient_explanation = 'Cistatina C é uma proteína produzida constantemente por todas as células do corpo e eliminada exclusivamente pelos rins. Ela é considerada um marcador mais preciso da função renal do que a creatinina tradicional, especialmente em idosos, pessoas com pouca massa muscular ou aqueles com função renal no limite. Como a cistatina C não é influenciada pela musculatura, alimentação ou características físicas individuais, ela detecta problemas renais mais cedo do que outros exames. Níveis elevados de cistatina C indicam que os rins não estão filtrando adequadamente o sangue, podendo sinalizar desde redução leve da função renal até doença renal mais avançada. Este exame é particularmente útil para ajustar doses de medicamentos que são eliminados pelos rins e para avaliar risco cardiovascular, pois função renal reduzida aumenta significativamente o risco de problemas cardíacos.',
    conduct = 'Cistatina C normal (0,57-1,02 mg/L): TFG preservada, manter rotina preventiva. Elevação leve (1,03-1,30 mg/L): calcular TFG por equação CKD-EPI-cis ou combinada. Se TFG 60-89 mL/min: investigar albuminúria, controlar fatores de risco CV (PA, glicemia, lipídios), revisar medicações nefrotóxicas, repetir em 3 meses. Elevação moderada (1,31-1,80 mg/L, TFG 30-59): DRC estágio 3, encaminhar nefrologia para estratificação de risco, otimizar IECA/BRA, ajustar doses medicamentosas, evitar contrastes iodados, monitorar K+/acidose, avaliar metabolismo ósseo-mineral (PTH, Ca, P, 25-OH-vitamina D). Elevação grave (>1,80 mg/L, TFG <30): encaminhamento nefrológico urgente para planejamento de terapia renal substitutiva, correção de anemia, acidose e hiperparatireoidismo secundário. Em discordância cistatina/creatinina: priorizar cistatina C para decisões clínicas. Monitoramento: TFG >60: anual; TFG 30-60: semestral; TFG <30: trimestral.',
    last_review = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN ('be74b5ba-6a8b-414b-a6dc-f1b50ae1b84f', '600b5157-efeb-4863-aa5e-6ae48d291c2d');

-- 3. COBRE SÉRICO (2 items)
-- IDs: 18dc38ee-5cc6-4c51-b48f-933d0bc54933, 971326a7-f2f5-405c-82fc-52dfa89be9d0
UPDATE score_items
SET
    clinical_relevance = 'Cobre sérico reflete homeostase deste micronutriente essencial para oxidases (citocromo c oxidase, superóxido dismutase, tirosinase, ceruloplasmina). Valores de referência: 70-140 µg/dL (adultos), >90% ligado à ceruloplasmina. Deficiência de cobre (<60 µg/dL) causa mielopatia por desmielinização medular posterior (mimetizando deficiência de B12), neutropenia, anemia sideroblástica e osteoporose. Etiologias: cirurgia bariátrica, suplementação excessiva de zinco (competição absortiva), doença celíaca, síndrome nefrótica. Excesso de cobre (>200 µg/dL) ocorre em inflamação aguda (ceruloplasmina é reagente de fase aguda), colestase, uso de ACO e gravidez. Doença de Wilson apresenta paradoxo: cobre sérico baixo (<70 µg/dL) por ceruloplasmina reduzida, mas cobre livre elevado e acúmulo hepático/cerebral. Diagnóstico de Wilson requer ceruloplasmina <20 mg/dL + cobre urinário 24h >100 µg + anel de Kayser-Fleischer. Estudos 2023 associam razão cobre/zinco elevada (>1,2) com estresse oxidativo aumentado, neuroinflamação e risco de Alzheimer. Toxicidade aguda (>500 µg/dL) por ingestão acidental causa hemólise, hepatite fulminante e IRA.',
    patient_explanation = 'Cobre é um mineral essencial que o corpo necessita em pequenas quantidades para produzir energia nas células, formar células sanguíneas e manter ossos e nervos saudáveis. O corpo mantém níveis muito controlados de cobre: pouco causa anemia, problemas neurológicos e enfraquecimento dos ossos; muito pode ser tóxico e causar problemas no fígado e cérebro. A deficiência de cobre é rara, mas pode ocorrer após cirurgias bariátricas ou em pessoas que tomam muito zinco em suplementos (pois zinco e cobre competem pela absorção). Uma doença genética rara chamada Doença de Wilson causa acúmulo excessivo de cobre no fígado e cérebro, necessitando tratamento específico. O exame de cobre geralmente é solicitado quando há sintomas neurológicos inexplicados, anemia que não responde ao tratamento ou suspeita de problemas hepáticos. Níveis alterados ajudam o médico a identificar a causa e orientar o tratamento adequado.',
    conduct = 'Cobre normal (70-140 µg/dL): sem necessidade de intervenção específica. Deficiência (<60 µg/dL): solicitar ceruloplasmina, zinco sérico, cobre urinário 24h, vitamina B12, ácido metilmalônico. Investigar má-absorção (doença celíaca, DII), cirurgia bariátrica, excesso de zinco. Suplementação: sulfato de cobre 2-4 mg/dia VO por 4-12 semanas, monitorar hemograma (recuperação de neutropenia em 2-4 semanas). Em mielopatia: ressonância medular, avaliar concomitância com deficiência de B12. Cobre elevado (>200 µg/dL): repetir em 2 semanas. Se persistente: dosar ceruloplasmina, PCR, avaliar função hepática. Suspeita de Wilson (<50 anos com hepatopatia ou sintomas neuropsiquiátricos): solicitar ceruloplasmina, cobre urinário 24h, cobre hepático (biópsia), exame oftalmológico (anel KF), genotipagem ATP7B. Se Wilson confirmado: encaminhar hepatologia, iniciar quelante (penicilamina ou trientina), restrição dietética de cobre. Razão Cu/Zn >1,2: suplementar zinco 30-50 mg/dia, antioxidantes. Monitoramento: deficiência corrigida: mensal por 3 meses; Wilson: cobre urinário trimestral.',
    last_review = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN ('18dc38ee-5cc6-4c51-b48f-933d0bc54933', '971326a7-f2f5-405c-82fc-52dfa89be9d0');

-- 4. COENZIMA Q10 (2 items)
-- IDs: 41a30bb0-39f1-491c-846a-f8842942e4ed, a30bd1e6-fe1a-444d-a89e-876a5ef1a3f5
UPDATE score_items
SET
    clinical_relevance = 'Coenzima Q10 (ubiquinona) é componente essencial da cadeia transportadora de elétrons mitocondrial (complexo III) e potente antioxidante lipofílico. Valores de referência: 0,5-1,7 µg/mL (plasma). Deficiência primária (<0,4 µg/mL) é rara, causada por mutações em genes de biossíntese (COQ2, COQ9, PDSS1/2), manifestando-se como encefalopatia mitocondrial, cardiomiopatia, síndrome nefrótica corticorresistente ou ataxia cerebelar. Deficiência secundária é comum: estatinas reduzem CoQ10 em 30-50% (inibem HMG-CoA redutase, bloqueando via do mevalonato compartilhada), correlacionando-se com mialgia induzida por estatinas. Outras causas secundárias: envelhecimento (redução 50% após 70 anos), insuficiência cardíaca, doenças neurodegenerativas (Parkinson, Huntington), diabetes. Metanálise 2022 (17 RCTs, n=684) demonstrou que suplementação CoQ10 200-300 mg/dia reduz mialgia por estatinas em 40% sem comprometer eficácia lipídica. Estudos em IC (Q-SYMBIO, 2014) mostraram redução de mortalidade CV com CoQ10 100 mg 3x/dia. Forma ubiquinol (reduzida) tem biodisponibilidade 3-4x superior à ubiquinona oxidada. Não há toxicidade conhecida mesmo em doses elevadas (>1200 mg/dia).',
    patient_explanation = 'Coenzima Q10 (CoQ10) é uma substância semelhante a vitamina que existe em todas as células do corpo, essencial para produção de energia dentro das mitocôndrias (as "usinas" das células). O corpo produz CoQ10 naturalmente, mas os níveis diminuem com a idade e podem ser reduzidos por alguns medicamentos, especialmente estatinas (remédios para colesterol). Níveis baixos de CoQ10 estão associados a fadiga, fraqueza muscular, dores musculares em quem usa estatinas, e podem contribuir para problemas cardíacos. A suplementação de CoQ10 é frequentemente recomendada para pessoas que tomam estatinas e apresentam dores musculares, para pacientes com insuficiência cardíaca, e em condições de fadiga crônica. Embora o corpo produza CoQ10, após os 40 anos a produção diminui significativamente. Alimentos ricos em CoQ10 incluem carnes, peixes e nozes, mas as quantidades são limitadas, tornando a suplementação necessária em alguns casos.',
    conduct = 'CoQ10 normal (0,5-1,7 µg/mL): sem intervenção, manter fontes alimentares (carnes, peixes oleosos). Deficiência leve (0,4-0,5 µg/mL): avaliar uso de estatinas, idade, IC. Considerar suplementação ubiquinol 100-200 mg/dia se sintomas (fadiga, mialgia) ou IC. Reavaliar em 8-12 semanas. Deficiência moderada a grave (<0,4 µg/mL): suplementação obrigatória. Ubiquinol 200-300 mg/dia dividido em 2-3 tomadas com refeições gordurosas (aumenta absorção). Se miopatia por estatinas: CoQ10 200 mg 2x/dia, considerar redução de dose ou troca de estatina (rosuvastatina tem menor impacto). Se IC: 100 mg 3x/dia, monitorar FEVE e classe funcional NYHA a cada 3-6 meses. Deficiência primária genética: doses elevadas 30-50 mg/kg/dia, acompanhamento neurologia/genética, avaliar resposta com lactato sérico, CK. Interações: CoQ10 pode reduzir eficácia de varfarina (monitorar INR). Sem necessidade de ajuste renal ou hepático. Monitoramento: mialgia por estatinas: reavaliação clínica em 4-8 semanas; IC: trimestral; deficiência primária: mensal até estabilização, depois trimestral. Resposta terapêutica esperada em 4-12 semanas.',
    last_review = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN ('41a30bb0-39f1-491c-846a-f8842942e4ed', 'a30bd1e6-fe1a-444d-a89e-876a5ef1a3f5');

-- 5. COLESTEROL TOTAL (3 items)
-- IDs: 498a8637-8bf5-45e0-891b-a0c51a47ccc1, abe4824c-0a2e-424a-9ae3-5e83a2c085ce, 1e19e29f-cd22-4e23-9c8f-40a46f1ac739
UPDATE score_items
SET
    clinical_relevance = 'Colesterol total representa soma de todas as frações lipoproteicas (LDL + HDL + VLDL/5). Diretrizes ESC/EAS 2019 e AHA 2019 estratificam risco CV baseado em múltiplos fatores, não apenas colesterol isolado. Valores: ótimo <190 mg/dL (prevenção primária baixo risco); desejável <160 mg/dL (risco intermediário); ideal <130 mg/dL (risco alto/muito alto). Hipercolesterolemia primária: hipercolesterolemia familiar heterozigótica (HeFH, 1:250) apresenta CT >310 mg/dL + xantomas + história familiar de DAC precoce, causada por mutações LDLR, APOB ou PCSK9. Forma homozigótica (HoFH, 1:300.000) apresenta CT >500 mg/dL na infância, xantomas antes dos 10 anos e DAC na adolescência, requerendo aférese de LDL. Causas secundárias: hipotireoidismo (TSH sempre em dislipidemia nova), síndrome nefrótica, colestase, diabetes mal controlado, obesidade. Guideline 2023 da ESC enfatiza LDL e não-HDL como alvos primários, reservando CT para triagem populacional. Colesterol total isolado tem limitações: não distingue partículas aterogênicas (LDL, Lp(a)) de protetoras (HDL). Estudo Framingham demonstrou que razão CT/HDL >5,0 tem maior valor preditivo CV que CT isolado. Alvos terapêuticos baseiam-se em LDL (não CT): prevenção primária baixo risco <116 mg/dL, intermediário <100, alto <70, muito alto <55.',
    patient_explanation = 'Colesterol total é a soma de todos os tipos de colesterol no sangue: LDL (colesterol "ruim"), HDL (colesterol "bom") e VLDL (outro tipo de gordura). Embora seja um exame comum, o colesterol total sozinho não conta toda a história - é necessário avaliar cada fração separadamente para entender o verdadeiro risco cardiovascular. O corpo precisa de colesterol para produzir hormônios, vitamina D e bile, mas excesso de colesterol "ruim" (LDL) se acumula nas artérias causando placas que podem levar a infarto e derrame. O colesterol "bom" (HDL) ajuda a remover o excesso de colesterol das artérias. Valores elevados de colesterol total podem indicar risco aumentado de doença cardíaca, mas o médico precisa avaliar as frações individuais, especialmente LDL e HDL, além de outros fatores como pressão arterial, diabetes, tabagismo e histórico familiar. Mudanças no estilo de vida (dieta mediterrânea, exercícios, perda de peso) são sempre recomendadas, e medicamentos podem ser necessários dependendo do risco individual.',
    conduct = 'CT <190 mg/dL: avaliar frações (LDL, HDL, triglicérides). Se LDL ótimo e sem fatores de risco: orientação preventiva, repetir em 5 anos. CT 190-239 mg/dL: calcular LDL e não-HDL, estratificar risco CV por escore (Framingham, ASCVD, SCORE2). Se risco baixo-intermediário: intervenção no estilo de vida (dieta DASH/Mediterrânea, exercício 150 min/sem, IMC <25), reavaliar em 3-6 meses. Se LDL não atingir meta: considerar estatina conforme risco. CT 240-309 mg/dL: provável hipercolesterolemia primária ou secundária. Afastar causas: TSH, glicemia, EAS (proteinúria), função hepática. Calcular LDL (Friedewald ou direto se TG >400). Iniciar estatina moderada-alta intensidade conforme risco. Exame físico: xantomas, xantelasmas, arco corneal. CT ≥310 mg/dL em adultos ou ≥230 em <30 anos: investigar HeFH (critérios Dutch Lipid Clinic, escore ≥6). Solicitar LDL direto, apo B, Lp(a), considerar teste genético (LDLR, APOB, PCSK9). Se HeFH: estatina alta potência + ezetimiba, meta LDL <70 (prevenção 1ª) ou <55 (prevenção 2ª), considerar inibidores PCSK9 se meta não atingida. Rastreio familiar em cascata (parentes 1º grau). Monitoramento: baixo risco: 5 anos; risco intermediário-alto ou em tratamento: 3-12 meses.',
    last_review = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN ('498a8637-8bf5-45e0-891b-a0c51a47ccc1', 'abe4824c-0a2e-424a-9ae3-5e83a2c085ce', '1e19e29f-cd22-4e23-9c8f-40a46f1ac739');

-- 6. COLESTEROL NÃO-HDL (3 items)
-- IDs: fa5aa2b0-5cc2-467f-b78d-83ebd69a714c, ac752e50-6c53-4eaf-b72e-1d4e810251cb, cc6dfdcf-845f-4070-9d5c-4115810e3fc4
UPDATE score_items
SET
    clinical_relevance = 'Colesterol não-HDL (CT - HDL) representa todas as lipoproteínas aterogênicas: LDL, VLDL, IDL, Lp(a) e remanescentes de quilomícrons. É superior ao LDL isolado para predição de risco CV, especialmente em hipertrigliceridemia, diabetes e síndrome metabólica, onde partículas VLDL e remanescentes contribuem significativamente. Guidelines ESC/EAS 2019 e ACC/AHA 2019 reconhecem não-HDL como alvo secundário preferencial, 30 mg/dL acima do alvo de LDL. Valores desejáveis: <130 mg/dL (prevenção primária baixo risco), <100 (intermediário), <85 (alto risco), <70 (muito alto risco), <55 (extremo risco). Não-HDL não requer jejum, pode ser calculado em qualquer lipidograma e não sofre interferência de triglicérides elevados (fórmula de Friedewald falha se TG >400). Estudos prospectivos (INTERHEART, Framingham) demonstram que razão apoB/apoA1 e não-HDL superam LDL na predição de eventos CV, com HR 1,15-1,25 por aumento de 30 mg/dL. Em diabéticos tipo 2, não-HDL correlaciona-se melhor com aterosclerose subclínica (CIMT, CAC score) que LDL isolado. Discordância LDL/não-HDL (não-HDL alto com LDL aparentemente normal) indica partículas pequenas e densas de LDL (padrão B), Lp(a) elevada ou hipertrigliceridemia com VLDL aumentada, todos altamente aterogênicos. Apolipoproteína B (apoB) mede diretamente número de partículas aterogênicas, sendo ainda mais preciso, mas não-HDL é excelente substituto (correlação r=0,95).',
    patient_explanation = 'Colesterol não-HDL é calculado subtraindo o colesterol "bom" (HDL) do colesterol total, representando todo o colesterol "ruim" no sangue. É considerado um indicador melhor de risco cardiovascular do que o LDL sozinho, porque inclui outras partículas prejudiciais que também entopem as artérias (VLDL e remanescentes). Este valor é especialmente útil em pessoas com triglicérides elevados ou diabetes, onde o cálculo tradicional do LDL pode não ser totalmente preciso. Pense no não-HDL como todos os "caminhões" que carregam gordura para dentro das artérias (ruim), enquanto o HDL são os "caminhões" que removem gordura (bom). Valores elevados de não-HDL indicam que você tem muitas partículas prejudiciais circulando, aumentando o risco de formação de placas nas artérias coronárias e, consequentemente, de infarto e derrame. A vantagem deste marcador é que não requer jejum e funciona bem mesmo quando os triglicérides estão muito altos, tornando-o mais prático e confiável para avaliar seu risco cardiovascular real.',
    conduct = 'Não-HDL <130 mg/dL: se LDL também na meta, sem intervenção farmacológica. Otimizar estilo de vida, repetir em 1-5 anos conforme risco. Não-HDL 130-159 mg/dL: calcular risco CV (ASCVD/SCORE2). Se LDL na meta mas não-HDL elevado: indica partículas remanescentes elevadas. Intensificar estilo de vida: dieta baixa em carboidratos refinados e álcool, exercício aeróbico, perda de peso se IMC >25. Considerar ômega-3 (EPA 2-4g/dia) se TG 200-499. Reavaliar em 3-6 meses. Se persistir e risco intermediário-alto: adicionar ezetimiba 10 mg/dia ao tratamento. Não-HDL 160-189 mg/dL: iniciar ou otimizar estatina. Meta: reduzir não-HDL para <100 (risco intermediário) ou <85 (alto risco). Se LDL na meta mas não-HDL não: adicionar ezetimiba 10 mg + fenofibrato 145-200 mg (se TG >200) ou ômega-3 EPA. Avaliar Lp(a) (se >50 mg/dL, contribui para não-HDL elevado, considerar ácido bempedoico ou anti-PCSK9). Não-HDL ≥190 mg/dL: hipercolesterolemia grave ou hipertrigliceridemia familiar. Estatina alta intensidade (atorvastatina 40-80 mg ou rosuvastatina 20-40 mg) + ezetimiba 10 mg. Meta <70 (muito alto risco). Se não atingir: adicionar inibidor PCSK9 (evolocumabe 140 mg SC 2x/mês ou alirocumabe 75-150 mg SC 2x/mês). Monitoramento: inicial: 6-12 semanas após ajuste; manutenção: 3-6 meses; discordância LDL/não-HDL: dosar apoB e Lp(a).',
    last_review = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN ('fa5aa2b0-5cc2-467f-b78d-83ebd69a714c', 'ac752e50-6c53-4eaf-b72e-1d4e810251cb', 'cc6dfdcf-845f-4070-9d5c-4115810e3fc4');

-- 7. COLONOSCOPIA - MAYO SCORE UC (3 items)
-- IDs: 4e601b8f-e3e0-484e-9d16-d59e7f1682b2, c5d52258-9298-44f9-978a-92717e6dba4b, 59585a72-8bc9-4ab7-a81f-2cf21706bcee
UPDATE score_items
SET
    clinical_relevance = 'Mayo Endoscopic Score (MES) é sistema validado de graduação endoscópica da atividade inflamatória em retocolite ulcerativa (RCU). Escala de 0-3: 0=mucosa normal com padrão vascular preservado; 1=eritema, padrão vascular reduzido, sem friabilidade; 2=friabilidade marcada, erosões, padrão vascular ausente; 3=ulceração com sangramento espontâneo. MES é componente do Mayo Score completo (0-12 pontos: MES + frequência evacuações + sangramento retal + avaliação médica global). Remissão endoscópica (MES 0-1) é alvo terapêutico primário por associar-se com menor risco de recidiva, redução de colectomia e menor progressão para displasia/câncer colorretal. Estudos prospectivos (VARSITY, GEMINI-LTS) demonstram que cicatrização mucosa (MES 0) tem outcomes superiores à remissão clínica isolada. MES 2-3 indica doença ativa moderada-grave requerendo otimização terapêutica. Limitações: não diferencia atividade em colite extensa vs distal; variabilidade interobservador (kappa 0,7); não avalia inflamação histológica (RHI - Robarts Histopathology Index). Diretrizes ECCO 2022 recomendam reavaliação colonoscópica 3-6 meses após início/mudança de terapia biológica para documentar cicatrização mucosa. MES persistentemente elevado (≥2) apesar de tratamento otimizado por 12 semanas indica falha terapêutica e necessidade de troca/escalonamento.',
    patient_explanation = 'O Mayo Score de colonoscopia é uma escala de 0 a 3 que classifica o grau de inflamação intestinal vista durante o exame em pacientes com retocolite ulcerativa. Pontuação 0 significa intestino com aparência normal; 1 indica leve vermelhidão mas sem feridas; 2 mostra fragilidade da mucosa com pequenas feridas; e 3 apresenta úlceras sangrantes. Este score é muito importante porque o objetivo do tratamento não é apenas melhorar os sintomas (diarreia, sangue nas fezes), mas também cicatrizar completamente a parede intestinal. Quando o intestino está cicatrizado (score 0-1), há muito menos chance de a doença piorar novamente, menor risco de precisar de cirurgia e menor possibilidade de desenvolver câncer intestinal no futuro. Por isso, seu médico solicita colonoscopias periódicas mesmo quando você está se sentindo bem - para verificar se a inflamação realmente desapareceu. Scores altos (2-3) indicam que o tratamento atual pode não estar sendo suficiente e ajustes podem ser necessários.',
    conduct = 'MES 0 (remissão): mucosa cicatrizada, manter tratamento atual. Colonoscopia de vigilância para displasia: se RCU extensa por >8 anos ou colite esquerda >15 anos, anual-bienal conforme fatores de risco (CEP concomitante, história familiar CCR, estenose, displasia prévia). Se biológico: considerar desescalonamento após 1-2 anos de remissão profunda (clínica + endoscópica + biomarcadores). MES 1 (remissão endoscópica): adequado como alvo terapêutico, manter tratamento. Monitorar calprotectina fecal trimestralmente (<150 µg/g). Repetir colonoscopia em 12-24 meses para confirmar remissão sustentada. MES 2 (atividade moderada): otimizar terapia atual. Se aminossalicilatos: escalonar para biológico (anti-TNF: infliximabe 5 mg/kg IV semanas 0-2-6 depois 8/8sem; adalimumabe 160/80/40 mg; vedolizumabe 300 mg IV semanas 0-2-6 depois 8/8sem; ustekinumabe). Se já em biológico: avaliar níveis séricos e anticorpos, considerar otimização de dose ou troca de classe. Adicionar corticoide tópico (enema budesonida 2 mg/100 mL/noite) ou sistêmico curto prazo (prednisona 40 mg/dia 1-2 semanas). MES 3 (atividade grave): hospitalização se toxicidade sistêmica (febre, taquicardia, leucocitose, albumina <3). Corticoide IV (metilprednisolona 60 mg/dia ou hidrocortisona 100 mg 8/8h), avaliar terapia de resgate (infliximabe, ciclosporina, tofacitinibe). TC abdome para excluir megacólon tóxico. Cirurgia colorrectal se refratariedade ou complicações.',
    last_review = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN ('4e601b8f-e3e0-484e-9d16-d59e7f1682b2', 'c5d52258-9298-44f9-978a-92717e6dba4b', '59585a72-8bc9-4ab7-a81f-2cf21706bcee');

-- 8. COLONOSCOPIA - NÚMERO TOTAL ADENOMAS (3 items)
-- IDs: 7a182c48-8b53-49e7-baeb-71f282325420, 3e0353cd-a928-4a5e-b96f-c7cea26262d2, 0296e16f-52e2-411a-b4bb-9948ea1eb598
UPDATE score_items
SET
    clinical_relevance = 'Número total de adenomas detectados em colonoscopia é preditor crítico de risco de câncer colorretal (CCR) e neoplasia metacrônica. Adenomas são lesões pré-malignas com potencial de progressão para carcinoma através da sequência adenoma-carcinoma (10-15 anos). Guidelines USMSTF 2020 e ESGE 2020 estratificam risco: baixo (1-2 adenomas <10mm, baixo grau), intermediário (3-4 adenomas ou 1 adenoma ≥10mm ou componente viloso ou displasia de alto grau), alto (≥5 adenomas ou adenoma ≥20mm ou >10 serrilhados incluindo TSA). Adenomas múltiplos (≥10) sugerem síndromes polipoides hereditárias: polipose adenomatosa familiar atenuada (aFAP, mutação APC, 20-100 adenomas) ou polipose associada a MUTYH (MAP, biallelic, 15-100 adenomas). Mais de 100 adenomas: PAF clássica (>100 adenomas, mutação APC, CCR 100% se não tratado). Taxa de detecção de adenomas (ADR) >25% em colonoscopias de rastreio é indicador de qualidade do exame. Metanálise 2020 (>1,2 milhão de colonoscopias) demonstrou que cada aumento de 1% no ADR associa-se com redução de 3% em CCR intervalar. Adenomas sincrônicos múltiplos aumentam risco de lesão metacrônica: 3-4 adenomas conferem OR 2,5; ≥5 adenomas OR 5,0 para novo adenoma avançado em 3 anos. Vigilância inadequada em adenomas alto risco aumenta mortalidade CCR em 30-50%.',
    patient_explanation = 'Adenomas (também chamados pólipos adenomatosos) são pequenos crescimentos na parede interna do intestino grosso que podem, com o tempo, se transformar em câncer colorretal - processo que geralmente leva 10 anos ou mais. O número de adenomas encontrados durante a colonoscopia ajuda o médico a avaliar seu risco de desenvolver novos pólipos e câncer no futuro. Ter 1-2 adenomas pequenos é considerado baixo risco; 3-4 adenomas ou um adenoma grande (≥1cm) é risco intermediário; e 5 ou mais adenomas é alto risco, exigindo vigilância mais frequente. Se forem encontrados muitos adenomas (mais de 10), pode indicar uma condição genética que requer avaliação especial e colonoscopias muito mais frequentes. A boa notícia é que remover os adenomas durante a colonoscopia previne que eles se tornem câncer. Por isso, é crucial seguir as recomendações do seu médico sobre quando repetir o exame - geralmente entre 1 a 10 anos dependendo do número, tamanho e características dos pólipos encontrados.',
    conduct = '0 adenomas: próxima colonoscopia em 10 anos (rastreio médio risco). Se história familiar CCR em parente 1º grau <60 anos: 5 anos. 1-2 adenomas tubulares <10mm, baixo grau: baixo risco. Próxima colonoscopia em 7-10 anos. Reforçar prevenção: dieta rica em fibras, atividade física, IMC <25, cessar tabagismo, limitar álcool e carne vermelha processada. Considerar aspirina 100 mg/dia se risco CV também elevado. 3-4 adenomas OU ≥1 adenoma ≥10mm OU componente viloso/tubuloviloso OU displasia alto grau: risco intermediário-alto. Colonoscopia em 3 anos. Se adenoma ≥20mm ou ressecção piecemeal: colonoscopia em 3-6 meses para avaliar ressecção completa. ≥5 adenomas: alto risco. Colonoscopia em 1-3 anos. Se ≥5 adenomas em <60 anos: considerar encaminhamento genética para avaliar síndromes polipoides (PAF atenuada, MAP). Solicitar colonoscopia em familiares de 1º grau a partir dos 40 anos ou 10 anos antes da idade do diagnóstico. ≥10 adenomas: suspeita de síndrome polipótica. Encaminhamento urgente oncogenética. Solicitar: colonoscopia completa de alta qualidade com cromoendoscopia, painel genético (APC, MUTYH, POLE, POLD1, NTHL1), avaliação primeiro grau. Se PAF confirmada (>100 adenomas): discutir colectomia profilática. Vigilância: repetir conforme categoria de risco; qualidade do preparo influencia intervalo (se inadequado, repetir em 1 ano).',
    last_review = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN ('7a182c48-8b53-49e7-baeb-71f282325420', '3e0353cd-a928-4a5e-b96f-c7cea26262d2', '0296e16f-52e2-411a-b4bb-9948ea1eb598');

-- 9. COLONOSCOPIA - SES-CD CROHN (1 item)
-- ID: 14dec504-0061-446b-b6f1-4ac464b0e463
UPDATE score_items
SET
    clinical_relevance = 'Simple Endoscopic Score for Crohn Disease (SES-CD) é sistema validado para quantificar gravidade endoscópica da Doença de Crohn (DC). Avalia 5 segmentos (íleo, cólon D, cólon T, cólon E, reto) em 4 variáveis (tamanho de úlceras 0-3, superfície ulcerada 0-3, superfície com doença 0-3, estenose 0-3), resultando em escore 0-60. Interpretação: 0-2=remissão; 3-6=doença leve; 7-15=moderada; >15=grave. SES-CD >3 indica inflamação ativa e correlaciona-se com níveis de calprotectina fecal (>250 µg/g). Cicatrização mucosa (SES-CD ≤2 ou redução >50%) é alvo terapêutico primário, associando-se com menor necessidade de cirurgia, menor progressão de dano intestinal estrutural e menor recidiva clínica. Estudos SONIC e EXTEND demonstraram que pacientes em biológicos com cicatrização mucosa têm taxa de colectomia 70% menor em 5 anos. SES-CD não captura doença do intestino delgado além do íleo terminal (requer enterografia/cápsula endoscópica) nem diferencia atividade inflamatória de dano fibrótico (estenoses). CDEIS (Crohn Disease Endoscopic Index of Severity) é score mais complexo mas mais sensível a mudanças. Guidelines ECCO 2020 recomendam reavaliação endoscópica 6-12 meses após início de biológico ou troca de terapia para documentar resposta mucosa. SES-CD persistente >6 apesar de terapia otimizada por 12-16 semanas indica falha terapêutica primária ou secundária.',
    patient_explanation = 'O SES-CD é uma pontuação de 0 a 60 que mede a gravidade da inflamação intestinal vista na colonoscopia em pacientes com Doença de Crohn. O médico avalia diferentes partes do intestino (íleo e segmentos do cólon) verificando o tamanho das úlceras, quanto da superfície está ulcerada, extensão da doença e presença de estreitamentos. Scores baixos (0-2) indicam remissão com mucosa cicatrizada; 3-6 é doença leve; 7-15 moderada; acima de 15 é grave. O objetivo do tratamento moderno da Doença de Crohn não é apenas controlar os sintomas (dor, diarreia), mas também cicatrizar completamente o intestino. Quando o intestino está cicatrizado (score baixo), há menor chance de complicações como estreitamentos, fístulas e necessidade de cirurgia no futuro. Por isso, colonoscopias periódicas são importantes para verificar se o tratamento está realmente funcionando profundamente. Se o score continuar alto mesmo com tratamento, pode ser necessário ajustar medicações para evitar danos permanentes ao intestino.',
    conduct = 'SES-CD 0-2 (remissão endoscópica): cicatrização mucosa atingida, manter tratamento atual. Monitorar calprotectina fecal trimestralmente (<150 µg/g). Repetir colonoscopia em 12-24 meses para confirmar remissão sustentada. Considerar otimização/desescalonamento de biológico após 2 anos de remissão profunda (clínica + endoscópica + biomarcadores). Vigilância para displasia se DC por >8 anos. SES-CD 3-6 (doença leve): otimizar terapia. Se não em biológico: considerar iniciar anti-TNF (infliximabe 5 mg/kg IV 0-2-6 semanas depois 8/8sem; adalimumabe 160/80/40 mg SC) ou anti-integrinas (vedolizumabe). Se já em biológico: dosar níveis séricos e anticorpos, otimizar dose ou reduzir intervalo se níveis subterapêuticos. Associar imunomodulador (azatioprina 2-2,5 mg/kg/dia) se monoterapia anti-TNF. Repetir colonoscopia em 6-12 meses. SES-CD 7-15 (doença moderada): escalonar tratamento. Se aminossalicilatos ou sem tratamento: iniciar biológico + curso curto de corticoide (budesonida 9 mg/dia 8 semanas ou prednisona 40 mg/dia com desmame). Se biológico com níveis terapêuticos: considerar troca de classe (anti-TNF → vedolizumabe ou ustekinumabe; ou vice-versa) ou adicionar molécula pequena (upadacitinibe 45 mg/dia, tofacitinibe). Avaliar complicações: RM enterografia para avaliar estenoses, fístulas, abcessos. SES-CD >15 (doença grave): considerar hospitalização se toxicidade sistêmica. Corticoide IV, nutrição enteral exclusiva, descartar infecção (CMV, C. difficile). Cirurgia se refratariedade, estenose sintomática, fístulas complexas ou abscesso. Referência cirurgia colorrectal/DII. Monitoramento: doença ativa: colonoscopia 6-12 meses após mudança terapêutica; remissão: 12-24 meses.',
    last_review = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = '14dec504-0061-446b-b6f1-4ac464b0e463';

-- ============================================================================
-- Verificação Final
-- ============================================================================
SELECT
    si.name,
    CASE
        WHEN si.clinical_relevance IS NOT NULL AND si.patient_explanation IS NOT NULL AND si.conduct IS NOT NULL
        THEN '✅ COMPLETO'
        ELSE '❌ INCOMPLETO'
    END as status,
    LENGTH(si.clinical_relevance) as len_clinical,
    LENGTH(si.patient_explanation) as len_patient,
    LENGTH(si.conduct) as len_conduct,
    si.last_review
FROM score_items si
WHERE si.id IN (
    '83d713f2-4b20-43fe-8b7e-c3dea08a3cb1',
    'be74b5ba-6a8b-414b-a6dc-f1b50ae1b84f',
    '600b5157-efeb-4863-aa5e-6ae48d291c2d',
    '18dc38ee-5cc6-4c51-b48f-933d0bc54933',
    '971326a7-f2f5-405c-82fc-52dfa89be9d0',
    '41a30bb0-39f1-491c-846a-f8842942e4ed',
    'a30bd1e6-fe1a-444d-a89e-876a5ef1a3f5',
    '498a8637-8bf5-45e0-891b-a0c51a47ccc1',
    'abe4824c-0a2e-424a-9ae3-5e83a2c085ce',
    '1e19e29f-cd22-4e23-9c8f-40a46f1ac739',
    'fa5aa2b0-5cc2-467f-b78d-83ebd69a714c',
    'ac752e50-6c53-4eaf-b72e-1d4e810251cb',
    'cc6dfdcf-845f-4070-9d5c-4115810e3fc4',
    '4e601b8f-e3e0-484e-9d16-d59e7f1682b2',
    'c5d52258-9298-44f9-978a-92717e6dba4b',
    '59585a72-8bc9-4ab7-a81f-2cf21706bcee',
    '7a182c48-8b53-49e7-baeb-71f282325420',
    '3e0353cd-a928-4a5e-b96f-c7cea26262d2',
    '0296e16f-52e2-411a-b4bb-9948ea1eb598',
    '14dec504-0061-446b-b6f1-4ac464b0e463'
)
ORDER BY si.name;
