#!/usr/bin/env python3
"""
Batch 41 - SONO Parte 3
20 items: Histórico medicamentos, Histórico familiar, Hábitos cônjuge, Idade desfralde,
Iluminação, Infância, Janelas, Lençóis, Melhores épocas, Motivos, etc.

Gera clinical_explanation, how_it_affects_health, why_it_matters, recommendations_text
baseado em evidências científicas.
"""

import json
import sys
from typing import Dict, List

def generate_clinical_content(item_name: str, item_id: str) -> Dict[str, str]:
    """Gera conteúdo clínico científico para cada item de sono."""

    content_map = {
        # Item 1: Histórico medicamentos/suplementos para dormir
        "f3a9a72b-813c-4b49-9eab-f0551ae8c311": {
            "clinical_explanation": "O histórico de uso de medicamentos e suplementos para sono documenta a exposição prévia a benzodiazepínicos, hipnóticos Z-drugs (zolpidem, zopiclona), antidepressivos sedativos, antihistamínicos, melatonina e fitoterápicos. Estes compostos atuam em receptores GABA-A, histamina H1, receptores de melatonina ou outros sistemas neuromodulatórios. O uso crônico de hipnóticos está associado a tolerância farmacológica, dependência física, efeitos residuais diurnos (hangover), risco aumentado de quedas, acidentes e declínio cognitivo. Estudos longitudinais mostram que benzodiazepínicos prolongam o início do sono mas reduzem sono de ondas lentas (N3) e sono REM, comprometendo a qualidade da arquitetura do sono. Além disso, a retirada abrupta pode causar insônia rebote e ansiedade, perpetuando o ciclo de dependência.",
            "how_it_affects_health": "O uso prolongado de hipnóticos está associado a aumento de mortalidade (estudos de coorte com HR 1.5-3.5), maior risco de demência (uso >5 anos aumenta risco em 50%), quedas e fraturas em idosos (OR 1.5-2.0), acidentes de trânsito, disfunção cognitiva, depressão, maior risco de câncer (dados controversos mas sugestivos), síndrome de apneia induzida por sedativos, e má qualidade de sono crônica. Além disso, a tolerância reduz a eficácia ao longo do tempo, levando a doses progressivamente maiores e risco de overdose. A dependência psicológica cria um ciclo vicioso onde o paciente sente-se incapaz de dormir sem medicação, perpetuando o uso.",
            "why_it_matters": "Este histórico identifica pacientes em risco de dependência, permite estratégia de desmame gradual supervisionado, orienta intervenções não-farmacológicas (TCC-I é primeira linha), detecta interações medicamentosas, permite rastreamento de efeitos adversos, e documenta tentativas prévias de tratamento. Além disso, conhecer o histórico permite personalizar abordagens, evitando repetir medicações ineficazes e priorizando estratégias de higiene do sono e terapia cognitivo-comportamental para insônia (TCC-I), que tem eficácia comparável a hipnóticos mas sem os riscos de longo prazo.",
            "recommendations_text": "1. Documentar detalhadamente: medicação, dose, duração, frequência, eficácia, efeitos colaterais, tentativas de desmame; 2. Para uso crônico de benzodiazepínicos/Z-drugs: planejar desmame gradual supervisionado (redução 10-25% a cada 1-2 semanas), combinar com TCC-I; 3. Evitar prescrição de hipnóticos como primeira linha: priorizar TCC-I, higiene do sono, tratamento de comorbidades (apneia, dor crônica, transtornos mentais); 4. Se necessário uso farmacológico: preferir melatonina (3-5mg), antagonistas de orexina (suvorexant, lemborexant), ou antidepressivos sedativos (trazodona 25-100mg) com melhor perfil de segurança; 5. Monitorar sinais de dependência, tolerância, efeitos residuais diurnos; 6. Considerar suplementos baseados em evidências: magnésio (200-400mg), L-teanina (200mg), glicina (3g), apigenina (50mg); 7. Educar sobre riscos de uso crônico e benefícios de abordagens não-farmacológicas."
        },

        # Item 2: Histórico familiar de problemas de sono
        "cf2629a0-3877-441a-89a6-c8216317e1d2": {
            "clinical_explanation": "O histórico familiar de distúrbios do sono revela predisposição genética significativa. A insônia crônica tem herdabilidade estimada em 30-60% em estudos com gêmeos. Polimorfismos em genes como CLOCK, PER2, PER3, BMAL1 (relógio circadiano), COMT (catabolismo de catecolaminas), ADORA2A (receptor de adenosina) e 5-HTTLPR (transportador de serotonina) estão associados a distúrbios do sono. A síndrome das pernas inquietas (SPI) tem herdabilidade de 50-70% e está ligada a variantes em genes como BTBD9, MEIS1 e MAP2K5. A apneia obstrutiva do sono tem componente familiar (risco 2-4x aumentado) relacionado a características craniofaciais herdadas, obesidade familiar e polimorfismos em genes de controle ventilatório. O histórico familiar também pode indicar padrões comportamentais aprendidos e ambientes domésticos que perpetuam má higiene do sono.",
            "how_it_affects_health": "A predisposição genética aumenta significativamente o risco individual de desenvolver insônia crônica (OR 2.0-3.5), apneia do sono (OR 2-4), síndrome das pernas inquietas (OR 3-6), narcolepsia (OR 10-40 em familiares de primeiro grau), e distúrbios do ritmo circadiano. Além disso, famílias com distúrbios do sono compartilham fatores de risco metabólicos (obesidade, diabetes tipo 2, hipertensão), psiquiátricos (depressão, ansiedade) e cardiovasculares (doença arterial coronariana, AVC), criando um perfil de risco multidimensional que requer vigilância preventiva intensificada.",
            "why_it_matters": "Este histórico permite rastreamento precoce de alto risco, justifica investigação aprofundada (polissonografia, actigrafia), orienta estratégias preventivas familiares, identifica necessidade de aconselhamento genético em casos sindrômicos, e alerta para transtornos específicos (narcolepsia HLA-DQB1*06:02, SPI variantes BTBD9). Além disso, permite educação familiar sobre higiene do sono e intervenções ambientais que beneficiam múltiplos membros, criando uma cultura familiar de saúde do sono.",
            "recommendations_text": "1. Rastrear sistematicamente histórico familiar: insônia, apneia, ronco, SPI, narcolepsia, sonambulismo, terror noturno; 2. Para histórico positivo de apneia: rastreamento precoce com questionários (STOP-BANG, Epworth), oximetria noturna, considerar polissonografia mesmo em pacientes jovens/assintomáticos; 3. Para histórico de SPI: rastrear deficiência de ferro (ferritina <50 ng/mL requer reposição), avaliar sintomas prodrômicos; 4. Implementar educação familiar sobre higiene do sono, criando ambiente doméstico favorável para todos os membros; 5. Considerar teste genético em casos de narcolepsia familiar (HLA-DQB1*06:02); 6. Documentar idade de início dos distúrbios em familiares para estimar risco temporal no paciente."
        },

        # Item 3: Hábitos de sono do cônjuge/parceiro(a)
        "9bf7ac98-a997-4a1e-9246-56cc681b444c": {
            "clinical_explanation": "Os hábitos de sono do parceiro de cama têm impacto significativo na qualidade do sono do indivíduo. O ronco do parceiro (presente em 40-50% de adultos) causa despertares fragmentados (arousal), reduz eficiência do sono e está associado a insônia secundária, fadiga diurna e irritabilidade no cônjuge. Estudos com actigrafia mostram que parceiros de roncadores têm 2-3x mais despertares noturnos e perdem em média 1-2 horas de sono por noite. Diferenças de cronotipo entre parceiros (matutino vs vespertino) criam conflitos de horários, pressão social para sincronizar horários incompatíveis com biologia individual, e estresse relacional. Além disso, hábitos como uso de telas na cama, ruído, movimentos excessivos (SPI, transtorno de comportamento do sono REM) e temperatura preferencial do quarto afetam ambos os parceiros.",
            "how_it_affects_health": "Incompatibilidade de sono entre parceiros está associada a menor satisfação conjugal (correlação r=-0.4 a -0.6), maior risco de divórcio, aumento de conflitos, piora da saúde mental (depressão, ansiedade), maior risco cardiovascular (hipertensão por fragmentação do sono), disfunção imune (redução de células NK), e pior desempenho cognitivo. Estudos mostram que mulheres são mais vulneráveis à interferência do parceiro devido a maior sensibilidade a ruídos noturnos. Além disso, a privação crônica de sono secundária aos hábitos do parceiro aumenta risco de acidentes, obesidade, diabetes e doenças cardiovasculares.",
            "why_it_matters": "Avaliar os hábitos do parceiro identifica causas externas modificáveis de distúrbio do sono, permite intervenções conjuntas (tratamento de apneia do parceiro, terapia de casal, educação sobre higiene do sono), justifica estratégias como camas separadas (sleep divorce, que melhora qualidade do sono em 60-70% dos casos sem impacto negativo na relação), e reconhece que o sono é um fenômeno diádico que requer abordagem sistêmica familiar. Além disso, o tratamento da apneia do parceiro melhora o sono do cônjuge quase tanto quanto do próprio paciente.",
            "recommendations_text": "1. Investigar detalhadamente hábitos do parceiro: ronco, apneia, movimentos, horários, uso de telas, temperatura preferida, nível de ruído; 2. Se parceiro ronca ou tem apneia suspeita: encaminhar para avaliação médica e polissonografia; 3. Para ronco isolado: orientar posicionadores para dormir de lado, perda de peso, evitar álcool/sedativos antes de dormir, considerar dilatadores nasais; 4. Para incompatibilidade de cronotipo: negociar horários flexíveis, respeitar biologia individual, considerar quartos separados se necessário; 5. Implementar regras de higiene do sono conjuntas: sem telas 1h antes de dormir, temperatura do quarto 18-20°C, uso de máscara/tampões se necessário; 6. Considerar 'sleep divorce' (quartos separados) como estratégia válida: estudos mostram melhora de 60-70% na qualidade do sono sem impacto negativo na satisfação conjugal; 7. Terapia de casal se conflitos de sono geram estresse relacional significativo."
        },

        # Item 4: Idade do desfralde (controle de esfíncter noturno)
        "99b8fa5b-a949-4799-abdb-ce0be9930287": {
            "clinical_explanation": "A idade do desfralde noturno reflete a maturação neurológica do controle vesical e a coordenação do ciclo sono-vigília com reflexos autonômicos. O controle esfincteriano noturno normalmente se estabelece entre 2-5 anos de idade. Enurese noturna persistente após 5-7 anos (presente em 5-10% das crianças) sugere múltiplos mecanismos: imaturidade do eixo ADH (hormônio antidiurético) com produção insuficiente durante o sono, bexiga hiperativa com redução da capacidade vesical funcional, disfunção do despertar com limiar elevado para sensação de bexiga cheia, fatores genéticos (herdabilidade 70%, se ambos os pais tiveram enurese o risco é 77%), e associação com apneia obstrutiva do sono (30-40% das crianças com enurese têm AOS). Desfralde tardio pode indicar distúrbios do sono subjacentes que comprometem despertares adequados.",
            "how_it_affects_health": "Enurese noturna persistente está associada a baixa autoestima, ansiedade social, bullying, restrição de atividades sociais (não dormir na casa de amigos), estresse familiar, punições inadequadas que pioram ansiedade, maior risco de infecções urinárias recorrentes, e possível marcador de apneia obstrutiva do sono não diagnosticada. Além disso, a fragmentação do sono causada pela enurese ou pela apneia subjacente contribui para déficit de atenção, hiperatividade, dificuldades escolares e problemas comportamentais. O impacto psicossocial é significativo, com estudos mostrando que crianças com enurese têm qualidade de vida comparável a crianças com asma moderada.",
            "why_it_matters": "Este histórico identifica crianças que necessitam investigação de apneia do sono (polissonografia se ronco + enurese), rastreamento de diabetes mellitus/insipidus, avaliação urológica, e intervenções específicas (alarme de enurese 70% eficaz, desmopressina, terapia comportamental). Em adultos, o histórico de enurese prolongada pode indicar vulnerabilidade persistente a distúrbios do sono e apneia. Além disso, permite identificar traumas infantis relacionados a punições inadequadas que podem perpetuar ansiedade e distúrbios do sono na vida adulta.",
            "recommendations_text": "1. Documentar idade do desfralde noturno e qualquer histórico de enurese persistente; 2. Para enurese após 5 anos: investigar apneia do sono (questionário, observação de ronco, polissonografia se indicado), diabetes mellitus (glicemia de jejum), diabetes insipidus (densidade urinária, sódio sérico); 3. Avaliar histórico familiar de enurese (presente em 70% dos casos); 4. Se enurese na infância + ronco atual: alta suspeita de apneia não tratada, indicar polissonografia; 5. Para crianças: tratamento multimodal com alarme de enurese (primeira linha, 70% eficaz em 3-4 meses), restrição hídrica 2h antes de dormir, micção programada, desmopressina se evento social importante, apoio psicológico; 6. Educar pais sobre natureza não-volitiva da enurese e evitar punições; 7. Tratar condições subjacentes (apneia, constipação, bexiga hiperativa)."
        },

        # Item 5: Iluminação do quarto/ambiente de sono
        "b15a28a0-707d-4684-aed1-d3c1fcd61726": {
            "clinical_explanation": "A exposição à luz durante o período de sono suprime a produção de melatonina pela glândula pineal, ativando células ganglionares retinianas intrinsecamente fotossensíveis (ipRGCs) que contêm melanopsina, particularmente sensível a luz azul (460-480nm). Estudos mostram que exposição a apenas 3-5 lux durante a noite (equivalente a luz noturna fraca) já reduz melatonina em 50% e fragmenta o sono. Luz >10 lux causa despertares parciais e reduz sono de ondas lentas. A poluição luminosa urbana (luz de rua, dispositivos eletrônicos, LEDs indicadores) cria um ambiente de pseudo-dia que desregula o ritmo circadiano, atrasa o início do sono, reduz duração total e compromete a qualidade da arquitetura do sono. Além disso, a exposição à luz durante o sono REM pode causar despertares mais intensos devido à maior ativação cortical nesta fase.",
            "how_it_affects_health": "Exposição à luz noturna está associada a maior risco de obesidade (metanálise OR 1.33), diabetes tipo 2 (OR 1.28), síndrome metabólica, câncer de mama (estudos em trabalhadoras noturnas mostram OR 1.4-1.6), câncer de próstata, depressão (aumento de 30% em estudos de coorte), piora da qualidade do sono, maior latência de sono, redução de sono REM e N3, fadiga diurna, disfunção imune, e aceleração do envelhecimento celular. Estudos em animais mostram que luz noturna causa hiperglicemia, resistência insulínica e ganho de peso independente de dieta. Além disso, a desregulação circadiana aumenta inflamação sistêmica (PCR, IL-6) e estresse oxidativo.",
            "why_it_matters": "A iluminação é um fator modificável que tem impacto direto na qualidade do sono e saúde metabólica. Intervenções simples (cortinas blackout, máscaras de dormir, remoção de LEDs) melhoram significativamente o sono e biomarcadores metabólicos. Estudos de intervenção mostram que reduzir luz noturna para <3 lux melhora eficiência do sono em 5-10%, aumenta melatonina noturna em 100-200%, e reduz marcadores inflamatórios. Além disso, a educação sobre higiene luminosa é essencial para pacientes urbanos expostos a poluição luminosa constante.",
            "recommendations_text": "1. Objetivo: escuridão completa durante o sono (<3 lux, idealmente <1 lux); 2. Implementar cortinas blackout ou persianas opacas que bloqueiem 100% da luz externa; 3. Remover ou cobrir todos os LEDs indicadores de dispositivos eletrônicos (TV, roteador, carregadores); 4. Se necessário luz noturna (idosos, crianças): usar luz vermelha/âmbar de baixíssima intensidade (<1 lux), posicionada abaixo do nível dos olhos; 5. Considerar máscara de dormir de alta qualidade (materiais respiráveis, ajuste confortável) como alternativa eficaz; 6. Durante a noite, se precisar levantar: usar luz vermelha de baixa intensidade, evitar luz branca/azul que suprime melatonina; 7. Avaliar poluição luminosa externa (luz de rua): considerar cortinas adicionais ou realocação de cama para lado oposto da janela; 8. Educar sobre impacto da luz noturna em saúde metabólica e circadiana."
        },

        # Item 6: Padrões de sono na infância
        "43687e67-f80b-472f-97a2-8344d720a7a3": {
            "clinical_explanation": "Os padrões de sono na infância refletem a maturação neurofisiológica, estabelecimento do ritmo circadiano, consolidação do sono noturno e redução de sonos diurnos. Recém-nascidos dormem 14-17h em ciclos polifásicos de 2-4h. Aos 6 meses, 70-80% das crianças consolidam sono noturno de 6h contínuas. Aos 12 meses, a maioria dorme 11-14h com 1-2 sonecas diurnas. Aos 3-5 anos, sonecas diurnas cessam e o sono noturno se estabiliza em 10-13h. Problemas persistentes na infância (resistência ao sono, despertares noturnos frequentes >30min, terrores noturnos, sonambulismo) podem refletir ansiedade de separação, distúrbios respiratórios (adenoides hipertróficas, apneia), refluxo gastroesofágico, dermatite atópica com prurido noturno, ou padrões familiares disfuncionais (cosleeping conflituoso, ausência de rotina).",
            "how_it_affects_health": "Distúrbios do sono na infância estão associados a déficit cognitivo (QI 7-9 pontos menor em estudos longitudinais), dificuldades de aprendizagem, TDAH (70% das crianças com TDAH têm distúrbios do sono), problemas comportamentais (agressividade, impulsividade), obesidade infantil (OR 1.5-2.0), maior risco de diabetes tipo 2, hipertensão, problemas emocionais (ansiedade, depressão), e persistência de insônia na adolescência e vida adulta (risco 3-4x aumentado). Além disso, o sono inadequado na infância afeta desenvolvimento neurológico, consolidação de memórias, neuroplasticidade e crescimento físico (GH é secretado durante sono de ondas lentas).",
            "why_it_matters": "O histórico de sono infantil identifica padrões precoces que podem predizer distúrbios crônicos, revela experiências adversas (trauma, negligência, abuso) que afetam sono na vida adulta, orienta investigação de condições iniciadas na infância (apneia por adenoides, SPI, narcolepsia de início juvenil), e permite intervenções preventivas em filhos do paciente, quebrando ciclos familiares de má higiene do sono. Além disso, problemas de sono não resolvidos na infância frequentemente persistem na vida adulta com maior gravidade.",
            "recommendations_text": "1. Investigar detalhadamente padrões de sono na infância: idade de consolidação do sono noturno, frequência/duração de despertares, terrores noturnos, sonambulismo, ronco, resistência ao sono, rotinas familiares; 2. Se histórico de ronco/apneia infantil: avaliar se foi tratado (adenoamigdalectomia), investigar sequelas (fácies adenoideana, mordida cruzada posterior, apneia residual); 3. Se terrores noturnos/sonambulismo: avaliar se persiste na vida adulta (pode indicar distúrbios do sono N3 ou apneia); 4. Se insônia desde a infância: explorar traumas, ansiedade de separação, eventos adversos (divórcio parental, abuso, negligência); 5. Para pacientes com filhos: educar sobre higiene do sono infantil, rotinas consistentes, evitar cosleeping após 6 meses, estabelecer horários regulares; 6. Considerar avaliação psicológica se histórico sugere trauma infantil não resolvido."
        },

        # Item 7: Presença e tipo de janelas no quarto
        "4bf657f4-3700-4a34-88b8-32070f4d2e24": {
            "clinical_explanation": "A presença, orientação e tratamento de janelas no quarto afetam múltiplos aspectos da fisiologia do sono. Janelas voltadas para leste causam despertar precoce por luz solar matinal (6000-10000 lux), o que pode ser benéfico para cronotipos matutinos mas problemático para vespertinos. Janelas sem cortinas blackout permitem entrada de luz noturna (poluição luminosa urbana, luz de rua, lua cheia) que suprime melatonina e fragmenta o sono. Janelas afetam temperatura do quarto: orientação oeste causa aquecimento vespertino excessivo, janelas sem isolamento térmico causam perda de calor no inverno e ganho no verão. Além disso, janelas são fonte de ruído externo (tráfego, vizinhos, animais) que causa despertares e reduz sono de ondas lentas. A qualidade do sono é melhor em quartos com janelas que permitem ventilação natural (reduz CO2) mas com controle de luz e ruído.",
            "how_it_affects_health": "Quartos com exposição excessiva à luz noturna estão associados a pior qualidade de sono (eficiência 5-10% menor), maior latência de sono, redução de sono REM e N3, despertares mais frequentes, fadiga diurna, e maior risco de obesidade e diabetes (mesmos mecanismos da poluição luminosa). Exposição à luz matinal natural é benéfica para sincronização circadiana, mas despertar forçado antes do fim do ciclo de sono natural causa privação crônica de sono. Ruído externo acima de 35-40 dB causa fragmentação do sono e aumenta risco cardiovascular. Temperatura inadequada (>20°C ou <18°C) compromete termorregulação noturna e reduz sono profundo.",
            "why_it_matters": "A avaliação das janelas permite intervenções ambientais simples e eficazes: instalação de cortinas blackout, persianas opacas, janelas duplas para isolamento acústico, controle de temperatura. Estas modificações melhoram significativamente o sono sem custos recorrentes. Além disso, permite educar sobre exposição adequada à luz natural: janelas devem ser abertas durante o dia para maximizar exposição a luz natural (2000-10000 lux) que fortalece o ritmo circadiano, mas completamente bloqueadas durante a noite.",
            "recommendations_text": "1. Avaliar: presença de janelas, orientação (leste/oeste/norte/sul), tamanho, tipo de cortinas/persianas, nível de luz noturna, ruído externo; 2. Instalar cortinas blackout ou persianas opacas de alta qualidade que bloqueiem 100% da luz externa; 3. Para ruído excessivo: considerar janelas duplas (reduzem 30-40 dB), vedação acústica, realocação de cama para parede oposta; 4. Otimizar exposição à luz natural: abrir cortinas imediatamente ao acordar para exposição a 2000-10000 lux de luz natural, fortalecer ritmo circadiano; 5. Controlar temperatura: janelas com isolamento térmico adequado, uso de ventilação natural noturna no verão (com controle de luz), aquecimento adequado no inverno; 6. Para quartos muito quentes (orientação oeste): considerar cortinas térmicas, ar condicionado programado para manter 18-20°C; 7. Se impossível controlar luz/ruído: considerar máscara de dormir + tampões de ouvido como solução alternativa eficaz."
        },

        # Item 8: Tipo e qualidade de lençóis/roupa de cama
        "0f87c64b-dbb0-4eec-9a64-9c5e0bb9b123": {
            "clinical_explanation": "A qualidade da roupa de cama afeta termorregulação noturna, conforto tátil e qualidade do sono. Tecidos naturais (algodão, linho, bambu) têm alta respirabilidade e absorção de umidade (7-15% do peso), permitindo evaporação do suor noturno (200-500mL/noite) e mantendo microclima cutâneo adequado (32-34°C). Tecidos sintéticos (poliéster, acrílico) retêm calor e umidade, causando superaquecimento (temperatura cutânea >35°C) e despertares noturnos. A densidade da trama (thread count 200-400 é ideal; >600 reduz respirabilidade) afeta conforto e durabilidade. Ácaros (Dermatophagoides pteronyssinus) proliferam em roupas de cama não lavadas frequentemente, causando rinite alérgica e asma que fragmentam o sono. Além disso, a textura dos tecidos afeta conforto sensorial, especialmente importante em indivíduos com sensibilidades táteis (autismo, fibromialgia).",
            "how_it_affects_health": "Roupa de cama inadequada causa superaquecimento noturno, que está associado a fragmentação do sono (3-5x mais despertares), redução de sono de ondas lentas (30-40%), aumento de sono N1 (leve), maior latência de sono, redução de melatonina, sudorese excessiva, e pior qualidade subjetiva do sono. Exposição a ácaros causa sintomas respiratórios (rinite, asma) que fragmentam o sono e estão associados a insônia crônica, fadiga diurna e maior risco de infecções respiratórias. Além disso, desconforto tátil pode causar movimentos noturnos excessivos e microdespertares inconscientes.",
            "why_it_matters": "A roupa de cama é um fator facilmente modificável com impacto significativo no sono. Intervenções simples (trocar para tecidos naturais, lavar semanalmente a 60°C para eliminar ácaros, usar capas antiácaros) melhoram qualidade do sono em 20-30% dos casos. Além disso, permite identificar alergias não diagnosticadas e orientar pacientes sobre escolhas baseadas em evidências. Educar sobre a importância de roupas de cama adequadas é uma intervenção de baixo custo e alta eficácia.",
            "recommendations_text": "1. Recomendações de tecido: priorizar algodão 100%, linho ou bambu (alta respirabilidade e absorção de umidade); evitar sintéticos (poliéster, microfibra) especialmente em climas quentes; 2. Thread count ideal: 200-400 (equilibra conforto, durabilidade e respirabilidade); >600 reduz respirabilidade e pode causar superaquecimento; 3. Higiene: lavar roupa de cama semanalmente a 60°C (elimina 100% dos ácaros), secar ao sol quando possível (radiação UV adicional); 4. Para alérgicos: usar capas antiácaros (barreiras físicas com poros <10μm), lavar a 60°C, aspirar colchão mensalmente com filtro HEPA, manter umidade do quarto <50%; 5. Temperatura: ajustar peso do edredom/cobertor conforme estação (verão: lençol leve; inverno: edredom apropriado mantendo temperatura corporal 36-37°C); 6. Conforto sensorial: para indivíduos com sensibilidades táteis, experimentar diferentes texturas (linho, cetim, flanela) até encontrar a mais confortável; 7. Substituir roupa de cama a cada 2-3 anos ou quando apresentar desgaste visível."
        },

        # Item 9: Melhores épocas/períodos de sono na vida
        "1fe7b666-49a0-494d-aeb9-ac5fbe5b0542": {
            "clinical_explanation": "A identificação de épocas na vida com melhor qualidade de sono revela fatores contextuais, ambientais e psicossociais que favoreceram o sono, além de possíveis mudanças fisiológicas. Períodos frequentemente relatados como de melhor sono incluem: infância/adolescência (antes de responsabilidades adultas, maior necessidade fisiológica de sono), períodos de férias/viagens (redução de estresse, rotinas flexíveis, exposição à natureza), aposentadoria (eliminação de horários rígidos, redução de estresse ocupacional), ou períodos específicos de tratamento bem-sucedido. A comparação entre melhores e piores épocas identifica moduladores-chave: estresse ocupacional, relacionamentos, saúde física, medicações, ambiente de sono, hábitos de vida. Esta análise temporal permite identificar fatores causais versus coincidentes.",
            "how_it_affects_health": "A análise de melhores épocas de sono permite identificar metas terapêuticas realistas e factores modificáveis. Por exemplo, se o melhor sono ocorreu durante férias com exposição solar e atividade física, isto sugere que a ausência destes fatores no dia-a-dia contribui para o problema atual. Se ocorreu antes de iniciar determinada medicação, isto sugere efeito adverso não reconhecido. Se ocorreu em relacionamento prévio ou local de residência diferente, isto sugere fatores ambientais ou interpessoais. Esta análise orienta estratégias de otimização e estabelece expectativas realistas de tratamento.",
            "why_it_matters": "Este histórico fornece insights sobre fatores protetores e de risco, estabelece linha de base realista para metas terapêuticas (pode não ser possível voltar ao sono da adolescência, mas é possível aproximar-se do sono durante férias), identifica gatilhos de piora (início de medicação, mudança de emprego, eventos de vida estressantes), valida que o paciente é capaz de dormir bem sob condições adequadas (excluindo patologia irreversível), e motiva mudanças ao relembrar experiências positivas alcançáveis.",
            "recommendations_text": "1. Explorar detalhadamente os melhores períodos de sono: quando, duração, contexto de vida (trabalho, relacionamentos, local de residência, saúde física, medicações, rotinas); 2. Identificar fatores comuns aos melhores períodos: redução de estresse, rotinas regulares, exercício físico, exposição solar, ausência de medicações específicas, qualidade de relacionamentos; 3. Contrastar com piores períodos para identificar moduladores-chave: mudanças ocupacionais, eventos de vida estressantes (divórcio, luto, doença), início de medicações; 4. Estabelecer metas realistas baseadas nos melhores períodos adultos (não comparar com infância/adolescência); 5. Criar plano de ação para reintroduzir fatores protetores: se exercício físico estava presente, reiniciar progressivamente; se exposição solar, implementar 30min de luz natural matinal; 6. Para fatores não modificáveis (ex: trabalho noturno necessário), buscar compensações (maximizar higiene do sono, TCC-I, fototerapia programada); 7. Usar análise temporal para validar intervenções: se mudança específica coincidiu com piora, reverter é prioritário."
        },

        # Item 10: Motivos/causas percebidas dos problemas de sono
        "ab010c3d-1001-412c-b62f-652209abc623": {
            "clinical_explanation": "A percepção do paciente sobre as causas de seus problemas de sono fornece insights sobre atribuições causais, crenças disfuncionais, fatores psicossociais e possíveis alvos terapêuticos. Causas frequentemente relatadas incluem: estresse/ansiedade (50-60% dos casos de insônia), dor crônica (30-40%), preocupações financeiras/ocupacionais, problemas de relacionamento, luto, trauma, uso de medicações/substâncias, condições médicas (apneia, SPI, refluxo), ou eventos de vida específicos (mudança de emprego, nascimento de filho, menopausa). A validação ou refutação destas percepções através de avaliação objetiva (polissonografia, actigrafia, questionários padronizados) é essencial, pois frequentemente há discrepância: pacientes podem atribuir insônia a 'mente acelerada' quando na verdade têm apneia não diagnosticada, ou acreditar que 'sempre foram assim' quando há condição tratável subjacente.",
            "how_it_affects_health": "A percepção de causas afeta engajamento no tratamento, expectativas de eficácia e escolha de intervenções. Crenças disfuncionais ('sou insone crônico, nada funciona') predizem pior resposta a tratamento e perpetuam insônia. Por outro lado, identificação correta de causas modificáveis (estresse ocupacional, medicação sedativa, apneia tratável) permite intervenções direcionadas com alta taxa de sucesso. Além disso, a discrepância entre percepção e realidade objetiva (ex: paciente acredita dormir 3h mas actigrafia mostra 6h) orienta terapia cognitiva para corrigir percepções distorcidas que amplificam sofrimento.",
            "why_it_matters": "Este histórico orienta investigação diagnóstica (se paciente relata ronco e pausas respiratórias, priorizar polissonografia), identifica alvos terapêuticos imediatos (estresse tratável com TCC, dor com analgesia otimizada), revela crenças disfuncionais que necessitam reestruturação cognitiva, valida experiências do paciente (mesmo que causas percebidas não sejam as únicas/principais), e estabelece aliança terapêutica ao demonstrar que as preocupações do paciente são levadas a sério e investigadas sistematicamente.",
            "recommendations_text": "1. Explorar detalhadamente as causas percebidas pelo paciente: quando iniciaram os problemas, que eventos/mudanças coincidiram, que fatores pioram/melhoram, teorias pessoais sobre causas; 2. Validar percepções quando apropriado ('realmente o estresse afeta muito o sono') mas também educar sobre causas não reconhecidas ('além do estresse, vou investigar apneia do sono que pode contribuir'); 3. Para causas tratáveis identificadas pelo paciente: priorizar intervenções (redução de estresse com mindfulness/TCC, tratamento de dor, resolução de conflitos relacionais com terapia de casal); 4. Para crenças disfuncionais: implementar reestruturação cognitiva ('você acredita que nunca dorme, mas vamos medir objetivamente com actigrafia para entender melhor'); 5. Correlacionar percepções com dados objetivos: se paciente atribui insônia a preocupações mas polissonografia mostra apneia grave, educar sobre múltiplos fatores contribuintes; 6. Estabelecer expectativas realistas: 'o estresse contribui, mas tratar apenas ele pode não ser suficiente; vamos abordar todos os fatores'; 7. Usar modelo biopsicossocial para integrar causas biológicas, psicológicas e sociais."
        },

        # Item 11: Móveis e decoração do quarto
        "15644410-f021-4dc1-a975-b3b9c5e45b3b": {
            "clinical_explanation": "O ambiente físico do quarto afeta o sono através de múltiplos mecanismos psicológicos e fisiológicos. A presença de dispositivos de trabalho (computador, mesa de escritório) e entretenimento (TV, videogame) no quarto cria associação cognitiva entre o ambiente de sono e atividades de alerta, violando o princípio de controle de estímulos da TCC-I. Estudos mostram que pessoas com TV no quarto dormem 20-30min menos por noite. Móveis que obstruem fluxo de ar ou refletem luz comprometem ventilação e controle de luz. Decoração com cores estimulantes (vermelho, laranja vibrante) aumenta ativação simpática, enquanto cores frias (azul, verde) promovem relaxamento. Espelhos grandes podem refletir luz noturna e criar sensação de vigilância. Desordem e bagunça estão associadas a maior ansiedade e latência de sono aumentada.",
            "how_it_affects_health": "Ambiente de quarto inadequado está associado a maior latência de sono (10-30min), pior qualidade subjetiva do sono, maior uso de telas antes de dormir (se dispositivos estão presentes), redução de duração total do sono (20-40min), maior ansiedade noturna, e associação psicológica disfuncional entre cama e atividades de alerta. Além disso, a presença de trabalho no quarto aumenta estresse percebido e rumination noturna, perpetuando insônia. A desordem visual está correlacionada com níveis elevados de cortisol e dificuldade de relaxamento.",
            "why_it_matters": "A otimização do ambiente do quarto é um componente essencial da higiene do sono e controle de estímulos (TCC-I). Intervenções ambientais são relativamente simples e têm impacto significativo: remoção de dispositivos eletrônicos melhora qualidade do sono em 15-25% dos casos. Além disso, criar associação cognitiva forte entre quarto/cama e sono (não trabalho, não preocupações) é fundamental para tratamento de insônia crônica. A avaliação ambiental também identifica fontes ocultas de luz e ruído.",
            "recommendations_text": "1. Princípio fundamental: quarto deve ser associado APENAS a sono e intimidade sexual; 2. Remover completamente do quarto: TV, computador, materiais de trabalho, smartphones (carregar em outro cômodo), dispositivos de entretenimento; 3. Se impossível remover smartphone: colocar em modo avião, distante da cama, tela virada para baixo, usar despertador tradicional; 4. Decoração: preferir cores frias e neutras (azul, verde, cinza, bege), evitar vermelho e laranja vibrantes, minimizar estímulos visuais complexos; 5. Organização: manter quarto limpo e organizado (desordem aumenta ansiedade), remover pilhas de objetos e bagunça; 6. Espelhos: evitar espelhos grandes ou cobri-los durante a noite se refletem luz; 7. Móveis: garantir fluxo de ar adequado, evitar obstrução de janelas, posicionar cama longe de fontes de ruído; 8. Para quem trabalha em casa: estabelecer limite físico claro (porta fechada) e temporal (não entrar no quarto para trabalho após certo horário); 9. Implementar regra: se acordar e não conseguir dormir em 20min, sair do quarto e fazer atividade relaxante, voltar apenas quando sentir sono (controle de estímulos)."
        },

        # Item 12: Mudanças de endereço/cidade e impacto no sono
        "dd2155bf-e866-464f-9b07-b9a13e5b6a62": {
            "clinical_explanation": "Mudanças de endereço afetam o sono através de múltiplos mecanismos: alteração de ambiente físico (ruído, luz, temperatura, qualidade do colchão), estresse psicológico da adaptação, mudança de rotinas, alteração de fuso horário (se mudança significativa de longitude), exposição a novos alérgenos (mofo, ácaros, pólen), e perda de rede social de suporte. O 'efeito primeira noite' (first-night effect) demonstra que o sono em ambiente novo é mais superficial e fragmentado devido a vigilância hemisférica assimétrica (hemisfério esquerdo permanece mais ativo para monitorar ameaças). Mudanças para áreas urbanas aumentam exposição a poluição luminosa e sonora. Mudanças para altitudes elevadas (>2500m) causam despertares por hipóxia intermitente nos primeiros meses. Mudanças para climas muito diferentes requerem adaptação termorregulatória.",
            "how_it_affects_health": "Mudanças de endereço estão associadas a insônia de ajustamento (aguda, durando dias a semanas), exacerbação de insônia crônica pré-existente, ansiedade adaptativa, fragmentação do sono por vigilância aumentada, sintomas depressivos (especialmente se mudança involuntária ou perda de rede social), e em alguns casos melhora significativa do sono (se mudança para ambiente mais adequado, redução de estresse, melhores condições de moradia). O impacto varia conforme voluntariedade da mudança, suporte social disponível, e qualidade do novo ambiente.",
            "why_it_matters": "Este histórico identifica gatilhos ambientais e psicossociais de distúrbios do sono, permite contextualizar início ou piora de insônia (frequentemente coincide com mudanças), orienta intervenções ambientais específicas ao novo local, e valida experiências de estresse adaptativo. Além disso, múltiplas mudanças frequentes podem indicar instabilidade social/financeira que contribui para insônia crônica através de estresse persistente. A identificação de melhora ou piora após mudança específica orienta se fatores ambientais versus intrínsecos são predominantes.",
            "recommendations_text": "1. Documentar histórico completo de mudanças: quando, de onde para onde, motivos (voluntária/involuntária), impacto percebido no sono; 2. Para mudanças recentes (<6 meses): normalizar insônia de ajustamento, educar sobre 'efeito primeira noite', implementar rotinas consistentes para acelerar adaptação; 3. Otimizar novo ambiente: avaliar e corrigir ruído, luz, temperatura, qualidade do colchão; 4. Para mudanças de fuso horário significativas (>2h): implementar estratégias de ajuste circadiano: exposição à luz solar matinal no novo horário, melatonina 0.5-3mg 30min antes do novo horário de dormir, ajuste gradual de horários; 5. Para mudanças para áreas urbanas: maximizar controle de luz (cortinas blackout) e ruído (janelas duplas, tampões); 6. Para mudanças para altitudes elevadas: aguardar aclimatação (2-4 semanas), considerar acetazolamida se sintomas graves, manter saturação >90%; 7. Avaliar suporte social: se mudança causou isolamento, abordar solidão e conexão social como parte do tratamento; 8. Se múltiplas mudanças frequentes: explorar instabilidade subjacente e estressores sociais/financeiros."
        },

        # Item 13: Necessidade de levantar para urinar (noctúria)
        "075e0074-16bc-4db3-8f0b-93594686032e": {
            "clinical_explanation": "A noctúria, definida como necessidade de acordar ≥1 vez por noite para urinar, afeta 20-40% dos adultos e aumenta com a idade (60-80% em >60 anos). Causas incluem: poliúria noturna (produção >33% do volume urinário das 24h durante a noite) por secreção inadequada de ADH, insuficiência cardíaca, diabetes mellitus/insipidus, uso de diuréticos, consumo excessivo de líquidos vespertino; hiperatividade vesical (urgência miccional com volumes pequenos <200mL) por síndrome de bexiga hiperativa, ITU, prostatismo, cistite intersticial; fragmentação do sono primária (apneia obstrutiva do sono causa noctúria por pressão negativa intratorácica aumentando liberação de ANP, e despertares por hipóxia são frequentemente atribuídos erroneamente a necessidade de urinar). Estudos mostram que tratamento de apneia reduz noctúria em 50-70% dos casos.",
            "how_it_affects_health": "Noctúria está associada a fragmentação significativa do sono (cada despertar causa perda de 15-30min de sono total considerando latência para voltar a dormir), redução de sono de ondas lentas e REM, fadiga diurna, sonolência diurna excessiva, maior risco de quedas noturnas (OR 1.5-2.5, especialmente em idosos), fraturas, pior qualidade de vida (comparável a diabetes ou hipertensão), depressão, disfunção sexual, absenteísmo ocupacional, e maior mortalidade em estudos longitudinais (HR 1.3-1.9). Além disso, a privação crônica de sono causada por noctúria aumenta risco cardiovascular, metabólico e cognitivo.",
            "why_it_matters": "A noctúria é frequentemente subdiagnosticada e subtratada, sendo erroneamente aceita como 'normal do envelhecimento'. A investigação adequada identifica causas tratáveis (apneia, diabetes, ICC, prostatismo, bexiga hiperativa) que, quando corrigidas, melhoram dramaticamente o sono e qualidade de vida. Além disso, noctúria pode ser o sintoma apresentante de condições graves (diabetes, insuficiência cardíaca, apneia) que requerem tratamento urgente. A mensuração objetiva com diário miccional de 3 dias diferencia poliúria noturna (requer tratamento da causa subjacente) de hiperatividade vesical (requer antimuscarínicos ou betamiméticos).",
            "recommendations_text": "1. Quantificar noctúria: número de vezes por noite, volume aproximado de cada micção, impacto no sono (consegue voltar a dormir facilmente?); 2. Implementar diário miccional de 3 dias: registrar horário, volume de todas as micções 24h, ingestão de líquidos; 3. Calcular índice de poliúria noturna (volume noturno / volume 24h): se >33%, investigar causas de poliúria (DM, DI, ICC, diuréticos, consumo excessivo de líquidos); 4. Investigar apneia obstrutiva do sono (causa comum e subdiagnosticada): questionário STOP-BANG, considerar polissonografia; 5. Para poliúria noturna: restringir líquidos 2-3h antes de dormir, reduzir cafeína/álcool vespertino, elevação de membros inferiores 2h antes de dormir (mobiliza edema), considerar desmopressina (idosos: cautela por risco de hiponatremia); 6. Para hiperatividade vesical: antimuscarínicos (oxibutinina, tolterodina) ou beta-3 agonistas (mirabegron), evitar antes de dormir: cafeína, álcool, alimentos picantes; 7. Para homens >50 anos: avaliar sintomas prostáticos (IPSS score), considerar alfabloqueadores (tansulosina, doxazosina) ou inibidores 5-alfa-redutase; 8. Tratar causas subjacentes: otimizar controle glicêmico (DM), tratamento de ICC, ajustar horário de diuréticos (tomar pela manhã)."
        },

        # Item 14: Nivel de atividade física e horários de exercício
        "8533025d-d0bb-4fc1-b2ca-df71df8a148e": {
            "clinical_explanation": "O exercício físico afeta o sono através de múltiplos mecanismos: aumento da adenosina (promotora de sono), elevação da temperatura corporal seguida de queda compensatória (facilita início do sono), redução de estresse e ansiedade, fortalecimento do ritmo circadiano (especialmente se realizado ao ar livre com exposição solar), aumento de citocinas anti-inflamatórias (IL-10) e redução de pró-inflamatórias (IL-6, TNF-alfa). Metanálises mostram que exercício regular reduz latência de sono em 3-7min, aumenta duração total em 15-30min, e melhora qualidade subjetiva em 20-30%. O timing do exercício é crucial: exercício intenso (<3h antes de dormir) pode atrasar início do sono por hiperativação simpática, aumento de cortisol e elevação persistente da temperatura corporal. Exercício matinal fortalece ritmo circadiano e melhora sono noturno. Sedentarismo está associado a insônia, apneia do sono (obesidade), e sono de má qualidade.",
            "how_it_affects_health": "A inatividade física está associada a maior risco de insônia (OR 1.4-2.0), apneia obstrutiva do sono (obesidade é principal fator de risco), síndrome das pernas inquietas (exercício reduz sintomas em 40-50%), pior qualidade de sono, maior latência de sono, redução de sono de ondas lentas, fadiga diurna paradoxal ('cansado mas não consigo dormir'), ansiedade, depressão, obesidade, diabetes, doenças cardiovasculares, declínio cognitivo, e maior mortalidade. Por outro lado, exercício excessivo ou mal temporizado (<2-3h antes de dormir) pode causar insônia de início, hiperativação, elevação de cortisol noturno, e overtraining syndrome em atletas (insônia + fadiga + queda de desempenho).",
            "why_it_matters": "O exercício é uma intervenção não-farmacológica de alta eficácia para sono, com efeito comparável a medicações hipnóticas mas sem efeitos adversos e com benefícios multissistêmicos adicionais (cardiovascular, metabólico, cognitivo, mental). A prescrição adequada de exercício (tipo, intensidade, duração, timing) pode resolver ou melhorar significativamente insônia, apneia leve, SPI, e síndrome de fase de sono atrasada. Além disso, o exercício é componente essencial do tratamento da obesidade, principal fator de risco para apneia do sono.",
            "recommendations_text": "1. Objetivo mínimo: 150min/semana de exercício moderado (caminhada rápida, ciclismo leve) ou 75min/semana de exercício vigoroso (corrida, natação); 2. Timing ideal: exercício matinal (6h-10h) maximiza benefícios circadianos e minimiza interferência no sono noturno; exercício vespertino (15h-18h) é aceitável; evitar exercício intenso <3h antes de dormir; 3. Para insônia: começar gradualmente (10-15min/dia) e aumentar progressivamente, exercício de intensidade moderada é mais consistentemente benéfico que vigoroso; 4. Para apneia do sono: combinar exercício aeróbico (30-45min, 4-5x/semana) com perda de peso (meta: 10% do peso corporal reduz IAH em 30-50%); 5. Para SPI: exercício moderado regular reduz sintomas em 40-50%, evitar exercício excessivo que pode piorar; 6. Exposição solar: priorizar exercício ao ar livre pela manhã (30-60min de luz natural fortalece ritmo circadiano); 7. Para sedentários: começar com caminhadas leves de 10min após refeições, aumentar gradualmente; 8. Monitorar sinais de overtraining: insônia persistente + fadiga + queda de desempenho pode indicar excesso, requer redução de volume/intensidade."
        },

        # Item 15: Observações do parceiro sobre o sono
        "1d115ef3-3e57-4d0b-a934-934044a17207": {
            "clinical_explanation": "As observações do parceiro de cama são essenciais para diagnóstico de distúrbios do sono que o paciente não percebe conscientemente. Ronco alto, pausas respiratórias (apneia obstrutiva), movimentos de membros inferiores (síndrome das pernas inquietas, movimentos periódicos de membros), verbalizações (sonilóquio), movimentos violentos (transtorno comportamental do sono REM), levantar e caminhar (sonambulismo), gritos/terror (terror noturno), e ranger de dentes (bruxismo) são frequentemente não percebidos pelo paciente mas claramente observados pelo parceiro. Estudos mostram que 70-80% dos pacientes com apneia obstrutiva não têm percepção consciente de apneias, mas parceiros relatam pausas respiratórias dramáticas de >10s. Estas observações são critérios diagnósticos em classificações internacionais (ICSD-3).",
            "how_it_affects_health": "Distúrbios observados pelo parceiro frequentemente indicam condições graves não diagnosticadas: apneia obstrutiva (risco cardiovascular, AVC, morte súbita), transtorno comportamental do sono REM (precursor de doenças neurodegenerativas como Parkinson em 50-80% dos casos dentro de 10-15 anos), movimentos periódicos de membros (fragmentação do sono, fadiga diurna), bruxismo (desgaste dentário, disfunção temporomandibular, cefaleia), e parassonias complexas (risco de lesões). Além disso, estes distúrbios frequentemente causam insônia secundária no parceiro, afetando ambos na díade.",
            "why_it_matters": "As observações do parceiro são frequentemente o principal motivo de busca de avaliação médica e podem ser a única pista de distúrbios graves como apneia e transtorno comportamental do sono REM. A história colateral é essencial para diagnóstico preciso e pode ser mais confiável que o auto-relato do paciente. Além disso, a gravação de vídeo (com smartphone) durante o sono pode documentar comportamentos para análise clínica. A validação das preocupações do parceiro também é terapêutica, reconhecendo o impacto no sono de ambos.",
            "recommendations_text": "1. SEMPRE questionar o parceiro de cama diretamente: ronco (frequência, intensidade), pausas respiratórias (duração, frequência), movimentos de pernas (chutes, tremores), comportamentos violentos/complexos, verbalizações; 2. Para relato de ronco + pausas respiratórias: ALTA suspeita de apneia obstrutiva, indicar polissonografia diagnóstica; 3. Para movimentos violentos durante sonhos: suspeitar de transtorno comportamental do sono REM, indicar polissonografia com vídeo sincronizado + avaliação neurológica (risco de Parkinson); 4. Para movimentos repetitivos de pernas: investigar síndrome das pernas inquietas vs movimentos periódicos, verificar ferritina; 5. Solicitar gravação de vídeo com smartphone: instruir parceiro a filmar episódios (documento objetivo para análise); 6. Avaliar impacto no sono do parceiro: se significativo, considerar tratamento urgente ou quartos separados temporariamente; 7. Para sonambulismo/terror noturno: medidas de segurança (remover objetos perigosos, trancar portas/janelas), avaliar fatores precipitantes (privação de sono, estresse, álcool, medicações); 8. Incluir parceiro nas consultas de seguimento para monitorar resposta ao tratamento."
        },

        # Item 16: Pausas respiratórias percebidas
        "3ee86f2a-38a0-491d-abf7-6ed993c65d59": {
            "clinical_explanation": "As pausas respiratórias percebidas durante o sono (por parceiros ou, mais raramente, pelo próprio paciente ao acordar) são o marcador clínico mais específico de apneia obstrutiva do sono. Pausas ≥10s, frequentemente acompanhadas de ronco alto, engasgo, sufocamento ou despertar abrupto com sensação de asfixia, indicam episódios de apneia obstrutiva onde as vias aéreas superiores colapsam durante o sono. A apneia obstrutiva é caracterizada por IAH (índice de apneia-hipopneia) que quantifica eventos por hora: leve (5-15), moderada (15-30), grave (>30). Pausas >20s com dessaturação significativa (<80%) indicam apneia grave. Fatores de risco incluem obesidade (circunferência cervical >43cm homens, >38cm mulheres), retrognatia, macroglossia, hipertrofia de tonsilas, congestão nasal crônica, hipotireoidismo, acromegalia.",
            "how_it_affects_health": "A apneia obstrutiva do sono está associada a hipertensão arterial (presente em 50-80% dos casos, resistente a tratamento), fibrilação atrial (OR 2-4), insuficiência cardíaca, doença arterial coronariana (OR 2.5), AVC (OR 2-4), morte súbita noturna (risco 2-3x aumentado), diabetes tipo 2 (OR 1.5-2.5), síndrome metabólica, esteatose hepática, disfunção cognitiva (déficit de memória, atenção, funções executivas), acidentes de trânsito (risco 2-7x aumentado), depressão, disfunção erétil (50-70% dos homens com AOS), noctúria, e maior mortalidade geral (HR 1.5-3.0 em apneia não tratada). O tratamento com CPAP reduz estes riscos significativamente.",
            "why_it_matters": "As pausas respiratórias são indicação ABSOLUTA de investigação com polissonografia, pois identificam população de altíssimo risco cardiovascular e de mortalidade que se beneficia dramaticamente de tratamento. A apneia obstrutiva é subdiagnosticada em 80-90% dos casos, e a identificação precoce previne complicações graves. O tratamento com CPAP é altamente eficaz, reduzindo IAH a <5 eventos/hora em >95% dos casos, melhorando pressão arterial, qualidade de sono, fadiga diurna, e reduzindo risco cardiovascular em 30-50%.",
            "recommendations_text": "1. Para qualquer relato de pausas respiratórias: indicação IMEDIATA de polissonografia diagnóstica; 2. Enquanto aguarda polissonografia: implementar medidas de redução de risco: perda de peso (meta 10% do peso corporal), evitar álcool 3h antes de dormir (relaxa musculatura e piora apneia), evitar sedativos/hipnóticos, dormir de lado (evitar decúbito dorsal que piora apneia em 50% dos casos), tratar congestão nasal; 3. Triagem com questionários: STOP-BANG (≥3 alta sensibilidade para apneia moderada-grave), Epworth Sleepiness Scale; 4. Exame físico: medir circunferência cervical, avaliar Mallampati, retrognatia, congestão nasal; 5. Exames complementares: oximetria noturna domiciliar (triagem), polissonografia (padrão-ouro diagnóstico); 6. Se apneia confirmada: CPAP é tratamento de primeira linha (eficácia >90%), alternativas incluem aparelho intraoral (eficaz em apneia leve-moderada), cirurgia (uvulopalatofaringoplastia, avanço maxilomandibular em casos selecionados); 7. Monitorar adesão ao CPAP: objetivo >4h/noite em >70% das noites; 8. Tratar comorbidades: hipertensão, diabetes, obesidade."
        },

        # Item 17: Pesadelos recorrentes
        "f6db908c-880d-4a6b-a091-4499560783cd": {
            "clinical_explanation": "Pesadelos são sonhos vívidos e perturbadores com conteúdo ameaçador, amedrontador ou causador de ansiedade intensa, que frequentemente causam despertar com recordação clara do conteúdo. Pesadelos ocasionais (1-2x/mês) ocorrem em 50-80% dos adultos e são normais. Pesadelos frequentes (≥1x/semana) afetam 2-6% da população e constituem Transtorno de Pesadelos quando causam sofrimento clinicamente significativo. Causas incluem: transtorno de estresse pós-traumático (80-90% têm pesadelos recorrentes), depressão, ansiedade, medicações (beta-bloqueadores, inibidores de colinesterase, antidepressivos ISRS, dopaminérgicos, descontinuação de benzodiazepínicos/álcool causam rebote REM), privação de sono seguida de rebote REM, apneia do sono (hipóxia fragmenta sono REM aumentando pesadelos), e TEPT subliminar.",
            "how_it_affects_health": "Pesadelos recorrentes estão associados a insônia (medo de dormir, latência aumentada), fragmentação do sono, privação crônica de sono, fadiga diurna grave, ansiedade antecipatória, depressão (relação bidirecional), maior risco de ideação suicida (OR 1.5-3.0 após controlar para depressão), sintomas dissociativos, pior qualidade de vida, absenteísmo, e em casos graves podem levar a tentativas de evitar sono (privação intencional). Além disso, pesadelos são marcador de gravidade em TEPT e predizem pior resposta a tratamento se não abordados especificamente.",
            "why_it_matters": "Pesadelos são frequentemente subtratados mas respondem bem a intervenções específicas. A Terapia de Ensaio de Imagens (Image Rehearsal Therapy - IRT) tem eficácia de 60-70% na redução de frequência e intensidade de pesadelos. Medicações como prazosina (alfabloqueador) reduzem pesadelos em TEPT em 50-60% dos casos. Além disso, pesadelos podem ser o sintoma apresentante de TEPT não diagnosticado, depressão, ou efeito adverso de medicação, todos requerendo intervenção. A investigação de pesadelos pode revelar traumas não divulgados previamente.",
            "recommendations_text": "1. Quantificar pesadelos: frequência, conteúdo (traumático recorrente vs variado), impacto (acorda? consegue voltar a dormir? medo antecipatório de dormir?); 2. Investigar TEPT: história de trauma, sintomas de revivência/evitação/hipervigilância, considerar CAPS-5 ou PCL-5 (escalas validadas); 3. Revisar medicações: beta-bloqueadores, inibidores de colinesterase, ISRS (podem aumentar pesadelos), descontinuação recente de benzodiazepínicos/álcool (rebote REM); 4. Investigar apneia do sono: hipóxia fragmenta REM e pode aumentar pesadelos, tratar apneia melhora pesadelos em 40-50% dos casos; 5. Intervenções psicológicas: Terapia de Ensaio de Imagens (IRT - primeira linha, 4-6 sessões, eficácia 60-70%): paciente escolhe pesadelo recorrente, reescreve com final não-ameaçador, ensaia mentalmente versão revisada 10-20min/dia; 6. Farmacoterapia: prazosina 1-6mg antes de dormir (eficaz em TEPT, reduz pesadelos em 50-60%), alternativas incluem clonidina, gabapentina; 7. Higiene do sono: evitar privação de sono (causa rebote REM com pesadelos), reduzir estresse, evitar álcool (fragmenta REM); 8. Se TEPT: tratamento específico com terapia cognitivo-comportamental focada em trauma ou EMDR."
        },

        # Item 18: Posição preferida para dormir
        "5b3fec09-d335-4192-82ca-989977d9d9d4": {
            "clinical_explanation": "A posição de sono afeta fisiologia respiratória, circulação, pressão sobre articulações/nervos e conforto. Decúbito dorsal (supino) aumenta colapso das vias aéreas superiores por retroposicionamento da língua e tecidos moles, piorando apneia obstrutiva do sono em 50-80% dos casos (apneia posicional). Decúbito lateral esquerdo melhora refluxo gastroesofágico (orientação anatômica do estômago) e circulação em gestantes (evita compressão de veia cava inferior). Decúbito lateral direito pode piorar refluxo. Posição prona (barriga para baixo) reduz ronco e apneia mas aumenta pressão cervical e pode causar dor. Estudos populacionais mostram: 38% dormem de lado, 28% nas costas, 13% de bruços, 21% variam. Mudanças de posição são normais (10-30x/noite), mas imobilidade pode indicar dor ou medicação sedativa excessiva.",
            "how_it_affects_health": "A posição de sono inadequada pode causar ou exacerbar: apneia obstrutiva (decúbito dorsal aumenta IAH em 2-3x), refluxo gastroesofágico (decúbito direito piora sintomas), dor cervical (posição prona com cabeça rotacionada), dor lombar (lordose excessiva em decúbito dorsal sem suporte), compressão de nervos periféricos (parestesias em mãos/braços por compressão de plexo braquial), edema facial (decúbito prono), rugas faciais aceleradas (compressão facial lateral), e síndrome do desfiladeiro torácico. Por outro lado, otimização da posição melhora apneia (terapia posicional reduz IAH em 50-60% em apneia posicional pura), refluxo e qualidade geral do sono.",
            "why_it_matters": "A modificação da posição de sono é intervenção simples, sem custo e eficaz para condições específicas. Apneia posicional (IAH supino ≥2x IAH lateral) afeta 50-60% dos pacientes com apneia, e terapia posicional (dispositivos que impedem decúbito dorsal) é tratamento eficaz que evita CPAP em casos selecionados. Para refluxo noturno, decúbito lateral esquerdo reduz episódios em 40-50%. A educação sobre posicionamento adequado melhora dor musculoesquelética relacionada ao sono.",
            "recommendations_text": "1. Documentar posição preferida e facilidade de mudança durante a noite; 2. Para apneia obstrutiva confirmada ou suspeita: avaliar se apneia posicional (IAH supino ≥2x IAH lateral na polissonografia): implementar terapia posicional: travesseiro posicional, camiseta com bola de tênis nas costas, dispositivo vibratório (promove mudança para lateral sem despertar completo); 3. Para refluxo gastroesofágico noturno: dormir em decúbito lateral ESQUERDO, elevar cabeceira da cama 15-20cm (não apenas usar travesseiros, que aumentam pressão abdominal); 4. Para dor cervical: travesseiro adequado (altura que mantém coluna cervical alinhada), evitar posição prona, considerar travesseiro cervical ergonômico; 5. Para dor lombar: decúbito lateral com travesseiro entre joelhos (reduz rotação pélvica), ou decúbito dorsal com travesseiro sob joelhos (reduz lordose); 6. Para gestantes: decúbito lateral ESQUERDO (evita compressão de veia cava), travesseiro de corpo para suporte; 7. Para ronco sem apneia: evitar decúbito dorsal, terapia posicional pode reduzir ronco significativamente; 8. Avaliar qualidade do colchão e travesseiros: substituir colchão a cada 7-10 anos, travesseiros a cada 1-2 anos."
        },

        # Item 19: Qualidade e idade do colchão
        "f7f2c158-35f9-4bc5-8cd7-4673f4f13134": {
            "clinical_explanation": "O colchão afeta o sono através de suporte postural, distribuição de pressão, termorregulação e conforto. Colchões velhos (>7-10 anos) perdem suporte estrutural, desenvolvem depressões que desalinham coluna, acumulam ácaros (até 10 milhões/colchão), alérgenos, fungos e detritos celulares. A firmeza ideal varia conforme peso corporal, posição de sono e condições musculoesqueléticas: colchões muito firmes aumentam pressão em pontos de apoio (ombros, quadris) causando dor; colchões muito macios não fornecem suporte adequado causando desalinhamento espinhal. Estudos mostram que colchões de firmeza média (5-7 em escala de 10) são mais universalmente confortáveis. Tecnologias de espuma viscoelástica (memory foam) distribuem pressão uniformemente mas retêm calor; molas ensacadas fornecem suporte com melhor ventilação; látex é durável e hipoalergênico mas caro.",
            "how_it_affects_health": "Colchão inadequado está associado a dor lombar (40-60% dos casos de lombalgia inespecífica melhoram com troca de colchão), dor cervical, dor em ombros e quadris, rigidez matinal, sono fragmentado por desconforto e microdespertares, piora de artrite e fibromialgia, sintomas alérgicos (rinite, asma) por ácaros, e pior qualidade subjetiva do sono. Estudos de intervenção mostram que troca de colchão velho por novo melhora qualidade do sono em 50-60% dos casos, reduz dor em 40-50%, e melhora biomarcadores de estresse (redução de cortisol).",
            "why_it_matters": "O colchão é um dos maiores investimentos em saúde do sono (passamos 1/3 da vida nele) e tem vida útil limitada. A avaliação e orientação sobre escolha adequada de colchão pode resolver ou melhorar significativamente dor musculoesquelética relacionada ao sono e qualidade geral do sono. Além disso, permite identificar exposição crônica a alérgenos (ácaros) que fragmentam o sono e causam sintomas respiratórios. A recomendação de troca de colchão antigo pode ser intervenção transformadora.",
            "recommendations_text": "1. Avaliar idade do colchão, tipo (molas, espuma, látex, híbrido), sinais de desgaste (depressões, saliências, ruído), presença de sintomas alérgicos; 2. Recomendação geral: substituir colchão a cada 7-10 anos (molas ensacadas/látex duram mais, espuma menos); 3. Firmeza ideal: média (5-7/10) é mais universalmente confortável; pessoas leves preferem mais macios, pessoas pesadas preferem mais firmes; posição lateral requer maior conformação (meio-macio), dorsal requer maior suporte (meio-firme); 4. Para dor lombar: colchão de firmeza média-alta com boa adaptabilidade, evitar muito firme (aumenta pressão) ou muito macio (falta suporte); 5. Para alergias/asma: usar capa antiácaros impermeável (poros <10μm), lavar a 60°C mensalmente, aspirar colchão com filtro HEPA; preferir látex ou espuma hipoalergênica; 6. Para retenção de calor (pessoas que sentem calor à noite): evitar memory foam denso, preferir molas ensacadas ou híbridos com camada de gel refrigerante, látex com boa ventilação; 7. Período de teste: ao comprar colchão novo, usar período de teste (muitas empresas oferecem 100 noites) para avaliar adaptação; primeiras 2-4 semanas podem ter desconforto adaptativo; 8. Proteção: usar protetor impermeável para aumentar vida útil, rotacionar colchão 180° a cada 3-6 meses (apenas se bidirecional)."
        },

        # Item 20: Ranger de dentes (bruxismo)
        "53066b08-838c-4edb-9cfa-776be8461071": {
            "clinical_explanation": "O bruxismo do sono é caracterizado por atividade rítmica ou não-rítmica dos músculos mastigatórios durante o sono, manifestando-se como ranger (grinding - movimento lateral com ruído) ou apertar (clenching - contração isométrica sem movimento) de dentes. Afeta 8-15% dos adultos e 15-40% das crianças. A etiopatogenia é multifatorial: microdespertares relacionados a ativação do sistema nervoso autônomo simpático (frequentemente associados a apneia obstrutiva do sono em 30-50% dos casos), estresse psicológico, ansiedade, uso de substâncias (SSRIs, metilfenidato, cocaína, MDMA), refluxo gastroesofágico, má oclusão dentária, genética (herdabilidade 20-50%). A polissonografia com EMG de masseter mostra episódios de atividade muscular rítmica (3 contrações/seg) ou tônica >2seg.",
            "how_it_affects_health": "O bruxismo está associado a desgaste dentário patológico (perda de esmalte, exposição de dentina, fraturas dentárias, perda de dimensão vertical), dor orofacial crônica, disfunção temporomandibular (DTM - dor em ATM, limitação de abertura bucal, estalidos), cefaleia tensional (especialmente temporal e frontal ao acordar), hipertrofia de masseter, recessão gengival, sensibilidade dentária, insônia secundária à dor, impacto no sono do parceiro (ruído pode atingir 100 dB), e fragmentação do sono. Além disso, bruxismo associado a apneia indica maior gravidade e risco cardiovascular. As forças geradas (até 10x a força mastigatória normal) causam dano progressivo.",
            "why_it_matters": "O bruxismo frequentemente não é diagnosticado até causar dano dentário significativo e irreversível. A identificação precoce permite prevenção de complicações através de placa oclusal, tratamento de causas subjacentes (apneia, refluxo, medicações, estresse) e proteção dentária. Além disso, o bruxismo pode ser marcador de apneia obstrutiva do sono não diagnosticada, especialmente quando associado a desgaste dentário grave. A associação entre bruxismo e apneia é bidirecional: apneia causa microdespertares que desencadeiam bruxismo, e bruxismo pode ser mecanismo compensatório para reabrir vias aéreas.",
            "recommendations_text": "1. Documentar: frequência (toda noite? ocasional?), manifestação (ranger com ruído vs apertar silencioso), consciência própria vs relato de parceiro, sintomas associados (dor em mandíbula, cefaleia matinal, dentes sensíveis, desgaste visível); 2. Exame físico/odontológico: avaliar desgaste dentário (facetas de desgaste, fraturas), hipertrofia de masseter (palpação), dor/limitação em ATM, recessão gengival; 3. Investigar causas subjacentes: apneia obstrutiva (presente em 30-50% dos casos de bruxismo) - indicar polissonografia, refluxo gastroesofágico, revisar medicações (SSRIs, estimulantes), avaliar estresse/ansiedade; 4. Tratamento primário: placa oclusal (night guard) confeccionada por dentista - protege dentes, redistribui forças, reduz atividade muscular em 30-50%; usar todas as noites; 5. Se apneia associada: tratamento com CPAP reduz bruxismo em 50-70% dos casos; 6. Farmacoterapia adjuvante: relaxantes musculares (ciclobenzaprina 5-10mg) ou benzodiazepínicos (clonazepam 0.5-1mg) antes de dormir em casos graves e refratários (uso criterioso por riscos); 7. Redução de estresse: técnicas de relaxamento, mindfulness, TCC, exercício regular; 8. Evitar: cafeína (especialmente vespertina), álcool, tabaco (todos aumentam bruxismo); 9. Toxina botulínica: injeção em masseter (25-50U cada lado) reduz força de contração e bruxismo em casos refratários, duração 3-6 meses."
        }
    }

    # Busca pelo ID exato
    if item_id in content_map:
        return content_map[item_id]

    # Fallback genérico (não deveria ocorrer)
    return {
        "clinical_explanation": f"Conteúdo clínico para {item_name} (ID: {item_id})",
        "how_it_affects_health": f"Impacto na saúde de {item_name}",
        "why_it_matters": f"Importância clínica de {item_name}",
        "recommendations_text": f"Recomendações para {item_name}"
    }

def generate_sql_updates(items_data: List[Dict]) -> str:
    """Gera SQL com todos os updates."""
    sql_parts = ["-- Batch 41 - SONO Parte 3 - 20 items\n"]
    sql_parts.append("-- Gerado automaticamente\n\n")
    sql_parts.append("BEGIN;\n\n")

    for item in items_data:
        item_id = item['id']
        content = item['content']

        # Monta o texto completo para clinical_relevance (explicação técnica completa)
        clinical_text = f"{content['clinical_explanation']}\n\nIMPACTO NA SAÚDE: {content['how_it_affects_health']}\n\nRELEVÂNCIA CLÍNICA: {content['why_it_matters']}"

        # patient_explanation = versão simplificada baseada no why_it_matters
        patient_text = content['why_it_matters']

        # conduct = recomendações
        conduct_text = content['recommendations_text']

        sql_parts.append(f"-- Item: {item.get('name', item_id)}\n")
        sql_parts.append(f"UPDATE score_items SET\n")
        sql_parts.append(f"  clinical_relevance = {escape_sql_string(clinical_text)},\n")
        sql_parts.append(f"  patient_explanation = {escape_sql_string(patient_text)},\n")
        sql_parts.append(f"  conduct = {escape_sql_string(conduct_text)},\n")
        sql_parts.append(f"  last_review = CURRENT_TIMESTAMP,\n")
        sql_parts.append(f"  updated_at = CURRENT_TIMESTAMP\n")
        sql_parts.append(f"WHERE id = '{item_id}';\n\n")

    sql_parts.append("COMMIT;\n")
    return ''.join(sql_parts)

def escape_sql_string(text: str) -> str:
    """Escapa string para SQL."""
    if not text:
        return "NULL"
    # Escapa aspas simples
    escaped = text.replace("'", "''")
    return f"'{escaped}'"

def main():
    """Processa os 20 items de SONO parte 3."""

    items_info = [
        ("f3a9a72b-813c-4b49-9eab-f0551ae8c311", "Histórico medicamentos/suplementos para dormir"),
        ("cf2629a0-3877-441a-89a6-c8216317e1d2", "Histórico familiar de problemas de sono"),
        ("9bf7ac98-a997-4a1e-9246-56cc681b444c", "Hábitos de sono do cônjuge/parceiro(a)"),
        ("99b8fa5b-a949-4799-abdb-ce0be9930287", "Idade do desfralde (controle esfíncter noturno)"),
        ("b15a28a0-707d-4684-aed1-d3c1fcd61726", "Iluminação do quarto/ambiente de sono"),
        ("43687e67-f80b-472f-97a2-8344d720a7a3", "Padrões de sono na infância"),
        ("4bf657f4-3700-4a34-88b8-32070f4d2e24", "Presença e tipo de janelas no quarto"),
        ("0f87c64b-dbb0-4eec-9a64-9c5e0bb9b123", "Tipo e qualidade de lençóis/roupa de cama"),
        ("1fe7b666-49a0-494d-aeb9-ac5fbe5b0542", "Melhores épocas/períodos de sono na vida"),
        ("ab010c3d-1001-412c-b62f-652209abc623", "Motivos/causas percebidas dos problemas de sono"),
        ("15644410-f021-4dc1-a975-b3b9c5e45b3b", "Móveis e decoração do quarto"),
        ("dd2155bf-e866-464f-9b07-b9a13e5b6a62", "Mudanças de endereço/cidade e impacto no sono"),
        ("075e0074-16bc-4db3-8f0b-93594686032e", "Necessidade de levantar para urinar (noctúria)"),
        ("8533025d-d0bb-4fc1-b2ca-df71df8a148e", "Nível de atividade física e horários de exercício"),
        ("1d115ef3-3e57-4d0b-a934-934044a17207", "Observações do parceiro sobre o sono"),
        ("3ee86f2a-38a0-491d-abf7-6ed993c65d59", "Pausas respiratórias percebidas"),
        ("f6db908c-880d-4a6b-a091-4499560783cd", "Pesadelos recorrentes"),
        ("5b3fec09-d335-4192-82ca-989977d9d9d4", "Posição preferida para dormir"),
        ("f7f2c158-35f9-4bc5-8cd7-4673f4f13134", "Qualidade e idade do colchão"),
        ("53066b08-838c-4edb-9cfa-776be8461071", "Ranger de dentes (bruxismo)")
    ]

    print("=" * 80)
    print("BATCH 41 - SONO PARTE 3")
    print("20 items: Histórico, ambiente, fatores externos")
    print("=" * 80)

    items_data = []
    for idx, (item_id, item_name) in enumerate(items_info, 1):
        print(f"\n[{idx}/20] Processando: {item_name}")
        content = generate_clinical_content(item_name, item_id)
        items_data.append({
            'id': item_id,
            'name': item_name,
            'content': content
        })
        print(f"  ✓ Conteúdo gerado ({len(content['clinical_explanation'])} chars)")

    # Gera SQL
    print("\n" + "=" * 80)
    print("Gerando arquivo SQL...")
    sql_content = generate_sql_updates(items_data)

    sql_file = '/home/user/plenya/batch41_sono_parte3.sql'
    with open(sql_file, 'w', encoding='utf-8') as f:
        f.write(sql_content)

    print(f"✓ SQL gerado: {sql_file}")
    print(f"✓ Total de updates: {len(items_data)}")

    # Gera JSON para referência
    json_file = '/home/user/plenya/batch41_sono_parte3.json'
    with open(json_file, 'w', encoding='utf-8') as f:
        json.dump(items_data, f, indent=2, ensure_ascii=False)

    print(f"✓ JSON de referência: {json_file}")

    print("\n" + "=" * 80)
    print("CONCLUÍDO COM SUCESSO!")
    print("=" * 80)
    print("\nPróximos passos:")
    print("1. Revisar o arquivo SQL gerado")
    print("2. Executar no banco de dados:")
    print(f"   psql -h localhost -U plenya_user -d plenya_db -f {sql_file}")
    print("3. Verificar resultados no frontend")

    return 0

if __name__ == '__main__':
    sys.exit(main())
