-- Completar os 3 items restantes do Batch 6.2

-- Item 37: Higiene e Acompanhamento
UPDATE score_items
SET
  clinical_relevance = E'Higiene oral e acompanhamento profissional regular são pilares prevenção doenças orais (cáries, periodontal, câncer oral). Placa dental (biofilme) se forma 4-12h após escovação, mineraliza em tártaro 10-14 dias (requer remoção profissional). Consultas regulares permitem detecção precoce, prevenção progressão, educação contínua. Na MFI, saúde oral é investimento em saúde sistêmica.',

  patient_explanation = E'Biofilme: comunidade polimicrobiana (Streptococcus, Actinomyces, Veillonella, após 24h anaeróbios Porphyromonas, Tannerella, Treponema). Remoção mecânica (escovação, fio) é ESSENCIAL - enxágues são adjuvantes. Tártaro (cálculo): placa mineralizada (fosfato cálcio), superfície rugosa acumula mais placa, requer remoção profissional (ultrassom, curetas). Frequência consultas: 6 meses (baixo risco) vs. 3-4 meses (periodontal, cáries múltiplas, diabetes, tabagismo).',

  conduct = E'Protocolo MFI higiene e acompanhamento OTIMIZADO: (1) Escovação: (a) Frequência: 2x/dia mínimo (manhã após café, noite antes dormir), idealmente após cada refeição, (b) Escova: elétrica sônica (superior manual - reduz placa 21%, gengivite 11%), cerdas macias, cabeça pequena, trocar a cada 3 meses, (c) Técnica: Bass modificada (45° gengiva, movimentos vibratórios curtos), 2 minutos cronometrados, (d) Creme: flúor 1450ppm OU hidroxiapatita nano, quantidade ervilha; (2) Limpeza interdental - DIARIAMENTE: (a) Fio dental: técnica C (abraça dente), desce até gengiva suavemente, (b) Alternativas: escovas interdentais (se espaço), irrigador oral (Waterpik - complementa, não substitui fio); (3) Raspador língua: 2x/dia após escovação (reduz carga bacteriana 75%, halitose); (4) Enxágue bucal: (a) Sem álcool (álcool resseca), (b) Clorexidina 0,12% apenas curto prazo 2 semanas (uso crônico: manchamento, disgeusia, resistência), (c) Longo prazo: óleos essenciais (Listerine) ou cetilpiridínio, (d) Xilitol enxágue; (5) Oil pulling: óleo coco 10-15min manhã antes escovação, 3-7x/semana (reduz placa 20-30%, gengivite 50%); (6) Probióticos orais: Lactobacillus reuteri Prodentis lozenge noturno após higiene (coloniza durante sono); (7) Hidratação: água após refeições (enxágue mecânico); (8) Dieta: (a) Reduzir açúcar/carboidratos fermentáveis, (b) Evitar snacking frequente (pH ácido prolongado), (c) Xilitol 5-10g/dia (goma pós-refeições); (9) Acompanhamento profissional: (a) Frequência: 6 meses (baixo risco), 3-4 meses (periodontal, diabetes, tabagismo), 4-6 semanas (pós-tratamento periodontal fase ativa), (b) Procedimentos: exame clínico completo, sondagem periodontal anual, profilaxia (limpeza ultrassom + polimento), aplicação flúor/verniz se alto risco cáries, radiografias periapicais bite-wing 1-2 anos (interproximais), panorâmica 3-5 anos, rastreamento câncer oral (inspeção mucosa, palpação linfonodos); (10) Educação contínua: técnica higiene, motivação, identificação sinais alerta (sangramento, dor, mobilidade, lesões); (11) Manejo ansiedade dental: sedação consciente (óxido nitroso), musicoterapia, TCC; (12) Monitorar: índice placa (<20%), profundidade sondagem (<3mm), sangramento sondagem (0%).'
WHERE id = 'f218ba3c-fddf-46f9-8525-94f68cf574ab';

-- Item 38: Com quais médicos e profissionais de saúde faz acompanhamento periódico?
UPDATE score_items
SET
  clinical_relevance = E'Mapeamento completo da rede de cuidado atual do paciente: médicos especialistas, profissionais saúde (nutricionistas, psicólogos, fisioterapeutas, educadores físicos), frequência consultas, coordenação entre profissionais. Na MFI, paciente é centro de equipe multidisciplinar integrada, não fragmentada. Coordenação adequada previne duplicações, lacunas, interações medicamentosas, cascata diagnóstica iatrogênica.',

  patient_explanation = E'Modelo cuidado integrado: Médico primário/integrativo coordena a equipe, mantendo visão holística e acessando especialistas quando necessário. Especialistas aprofundam patologias específicas mas mantêm comunicação com coordenador. Profissionais não-médicos (nutrição, psicologia, atividade física, sono) são pilares MFI. Fragmentação traz riscos: polifarmácia (cada especialista prescreve sem visão global), exames duplicados, lacunas de cuidado, conflitos de orientações, sobrecarga do paciente.',

  conduct = E'Protocolo MFI coordenação cuidado: (1) Estabelecer coordenador: médico primário/família/integrativo como hub central; (2) Mapeamento completo: listar todos profissionais atuais - médicos (clínico geral, cardiologista, endocrinologista, ginecologista/urologista, psiquiatra, outros), profissionais (nutricionista, psicólogo, fisioterapeuta, educador físico, dentista, farmacêutico), terapias complementares (acupuntura, quiropraxia, osteopatia); (3) Frequência acompanhamentos: médico primário 3-6 meses, especialistas conforme patologia, nutricionista mensal/trimestral, psicólogo semanal/quinzenal, fisio conforme demanda, educador físico mensal, dentista 6 meses; (4) Comunicação interprofissional: relatórios compartilhados, prontuário único integrado (ideal), reunião equipe em casos complexos, contato direto quando necessário; (5) Reconciliação medicamentosa: coordenador revisa todas prescrições, identifica duplicações, interações, desprescrição; (6) Plano cuidado integrado: objetivos centrais acordados, responsabilidades claras, timeline definido, revisão trimestral; (7) Empoderamento paciente: lista atualizada medicamentos, comunicar mudanças entre profissionais, perguntar sobre interações; (8) Prevenção: rastreamentos age-appropriate coordenados; (9) Transições cuidado: follow-up pós-alta, reconciliação medicamentos; (10) Identificar lacunas: áreas sem acompanhamento adequado; (11) Evitar especialistas desnecessários; (12) Documentação: pasta/app com relatórios, exames, medicamentos histórico, alergias, cirurgias, vacinas.'
WHERE id = 'bdd131b9-1dd0-49e5-a0c7-9aaca727c5e2';

-- Item 39: Verificar ativamente os mais comuns, e se acompanhamento está em dia
UPDATE score_items
SET
  clinical_relevance = E'Checklist proativo para garantir acompanhamento especializado essencial conforme idade/sexo/comorbidades. Muitos pacientes negligenciam rastreamentos/acompanhamentos preventivos por serem assintomáticos. Na MFI, prevenção e detecção precoce são prioritárias. Especialidades core: Cardiologia (DCV líder mortalidade), Endocrinologia (diabetes, tireoide epidemias), Ginecologia (mulheres), Urologia (homens acima 50 anos).',

  patient_explanation = E'Rastreamentos age-appropriate: Cardiologia (PA anual, lipídios 20+ anos, ECG basal 40 anos, escore cálcio coronário 45-50 anos). Endocrinologia (TSH 35+ anos, HbA1c/glicemia anual 45+ anos, DEXA mulheres 65+/homens 70+). Ginecologia (Papanicolau 21-65 anos cada 3 anos, mamografia 50-74 anos cada 2 anos, HPV DNA 30+). Urologia (PSA controverso 50-70 anos discussão individualizada, toque retal). Gastro (colonoscopia 45-75 anos cada 10 anos se normal). Oftalmologia (40+ anos glaucoma, 60+ catarata). Dermatologia (rastreamento câncer pele anual se fatores risco).',

  conduct = E'Protocolo MFI rastreamento especialidades CORE: (1) CARDIOLOGIA - consulta se HAS (PA 130/80 ou maior), dislipidemia (LDL acima 130), diabetes, histórico familiar DCV precoce, tabagismo, obesidade, sintomas cardíacos. Rastreamento: PA anual, lipídios 20+ anos, ECG basal 40 anos, escore cálcio 45-50 anos, teste ergométrico se indicado. (2) ENDOCRINOLOGIA - consulta se diabetes (HbA1c 6.5% ou maior, glicemia 126 ou maior), pré-diabetes (HbA1c 5.7-6.4%), tireoide (TSH anormal, nódulos, autoimunidade), obesidade refratária, síndrome metabólica, SOP, osteoporose. Rastreamento: TSH 35+ anos cada 5 anos, HbA1c 45+ anual, DEXA mulheres 65+/homens 70+ cada 2 anos, testosterona homens acima 40 se sintomas. (3) GINECOLOGIA (mulheres) - Papanicolau 21-65 anos cada 3 anos, mamografia 50-74 anos cada 2 anos, consulta anual para exame pélvico, mamas, orientações contracepção/menopausa, manejo sintomas menopausa, SOP, endometriose. (4) UROLOGIA (homens) - HPB (sintomas LUTS), PSA rastreamento controverso (discutir 50-70 anos, decisão individual risco-benefício), disfunção erétil, infertilidade, hipogonadismo. (5) GASTRO - colonoscopia 45-75 anos cada 10 anos se normal, cada 5 anos se pólipos adenomatosos, cada 3 anos se múltiplos pólipos, histórico familiar iniciar 40 anos ou 10 anos antes caso índice. (6) OFTALMOLOGIA - consulta 40 anos basal, depois cada 2-4 anos até 65, anual após 65 (glaucoma, catarata, degeneração macular). (7) DERMATOLOGIA - rastreamento câncer pele anual se história pessoal/familiar melanoma, múltiplos nevus, fototipos claros, imunossupressão. (8) PNEUMOLOGIA - espirometria basal 40-45 anos, TC tórax baixa dose 50-80 anos se tabagismo 30+ maços-ano. (9) Coordenação: médico primário/integrativo agenda rastreamentos, referencia especialistas quando indicado, integra informações. (10) Registro: planilha/app rastreamentos (última data, próxima data) para mamografia, Papanicolau, colonoscopia, DEXA, PSA.'
WHERE id = '2bc83256-1557-4094-b47a-00665fa2ba97';
