-- ============================================================================
-- BATCH 5.2 - EXAMES LABORATORIAIS PARTE 2 (Items 31-44)
-- ============================================================================

-- Item 31: Relação Triglicerídeos/HDL
UPDATE score_items
SET
  clinical_relevance = 'A relação TG/HDL (triglicerídeos/HDL-colesterol) é um marcador prático de resistência insulínica, síndrome metabólica e risco cardiovascular. Valores ideais: <2 (unidades em mg/dL). Valores >3 indicam resistência insulínica significativa; >5 indicam síndrome metabólica grave. A relação TG/HDL correlaciona-se fortemente com partículas de LDL pequenas e densas (sdLDL - altamente aterogênicas), que não são capturadas pelo LDL calculado. Indivíduos com TG/HDL >3 têm risco cardiovascular 3-4 vezes maior mesmo com LDL "normal". Na medicina funcional, valores <1 são ótimos; entre 1-2 são aceitáveis; acima de 2 justificam intervenção agressiva de estilo de vida. A relação TG/HDL também prediz melhor doença hepática gordurosa não alcoólica (DHGNA) que marcadores hepáticos tradicionais. É um marcador superior ao HOMA-IR para rastreio de resistência insulínica pois não requer dosagem de insulina (cara e menos padronizada). Causas de elevação: obesidade abdominal, dieta rica em carboidratos refinados e frutose, sedentarismo, síndrome metabólica, diabetes tipo 2, síndrome dos ovários policísticos (SOP), hipotireoidismo. A correção da relação TG/HDL (<2) deve ser meta terapêutica primária.',

  patient_explanation = 'A relação TG/HDL é calculada dividindo os triglicerídeos pelo colesterol "bom" (HDL). É um dos melhores marcadores simples para detectar resistência à insulina (quando o corpo não responde bem à insulina), síndrome metabólica e risco de infarto/derrame. Para calcular: divida os triglicerídeos pelo HDL (ambos em mg/dL). Por exemplo, se triglicerídeos são 150 e HDL é 40, a relação é 3,75 (alto). Valores ideais são ABAIXO de 2. Entre 2-3 já indica início de resistência insulínica. Acima de 3 indica resistência significativa e risco cardiovascular triplicado. Acima de 5 indica síndrome metabólica grave. Valores altos indicam que você tem muitas partículas pequenas e densas de LDL (as mais perigosas para entupir artérias) mesmo que o LDL total pareça normal. Causas: obesidade (especialmente barriga grande), dieta rica em açúcar e carboidratos, sedentarismo, diabetes, ovários policísticos. A boa notícia é que responde muito bem a dieta baixa em carboidratos, exercícios e perda de peso.',

  conduct = 'Solicitar em: perfil lipídico de rotina (calcular automaticamente TG/HDL), rastreio de síndrome metabólica, obesidade abdominal, diabetes ou pré-diabetes, história familiar de doença cardíaca precoce, síndrome dos ovários policísticos, gordura no fígado (DHGNA), avaliação de risco cardiovascular. Cálculo: TG (mg/dL) / HDL (mg/dL). Interpretação: ÓTIMO <1 | BOM 1-2 | LIMÍTROFE 2-3 | RESISTÊNCIA INSULÍNICA 3-5 | SÍNDROME METABÓLICA GRAVE >5. Investigação complementar: glicemia de jejum, HbA1c, insulina basal, HOMA-IR, peptídeo C, circunferência abdominal, pressão arterial, perfil lipídico completo (LDL, não-HDL, Apo B), partículas de LDL (tamanho), PCR ultrassensível, ALT/AST (DHGNA), ultrassom de abdome (esteatose hepática), Fibroscan se disponível. Intervenções: dieta LCHF (baixa em carboidratos, moderada em gorduras saudáveis), restrição de frutose e açúcares adicionados, jejum intermitente, exercícios (HIIT + resistência), perda de peso (meta: >7-10%), metformina se pré-diabetes/diabetes, ômega-3 (2-4g/dia), berberina 500mg 3x/dia. Monitoramento: mensal nos primeiros 3 meses de intervenção, depois trimestral. Meta: reduzir para <2.',

  updated_at = NOW()
WHERE id = 'b8f0bfbd-ce5d-4de3-aff2-96dceb4a9b68';

-- Exames de Imagem (não são laboratoriais, mas estão na lista) - Conteúdo resumido
-- Item 32-44: Exames de imagem e testes respiratórios

-- Item 32: Sulfeto de Hidrogênio Basal (H₂S Jejum)
UPDATE score_items
SET
  clinical_relevance = 'O teste de hidrogênio expirado com sulfeto de hidrogênio (H₂S) basal avalia supercrescimento bacteriano intestinal (SIBO) por bactérias produtoras de sulfeto. Valores normais em jejum: <10 ppm. Valores ≥10 ppm sugerem SIBO por bactérias redutoras de sulfato (Desulfovibrio spp, Fusobacterium), que produzem H₂S a partir de sulfatos dietéticos. O H₂S é tóxico para colonócitos, inibe beta-oxidação mitocondrial e está associado a doença inflamatória intestinal (DII), síndrome do intestino irritável (SII) com diarreia, e maior risco de câncer colorretal. Pacientes com SIBO de H₂S tipicamente não respondem a testes tradicionais de hidrogênio e metano (falso negativo), pois H₂S inibe metanogênese. Manifestações clínicas: diarreia aquosa, flatulência com odor de "ovo podre", desconforto abdominal, intolerância a alimentos ricos em enxofre (alho, cebola, brócolis, ovos). Causas: disbiose, trânsito intestinal lento, hipocloridria, uso de inibidores de bomba de prótons, dieta rica em sulfatos. Tratamento: bismuto subsalicilato (reduz H₂S), antibióticos (rifaximina + neomicina), dieta baixa em FODMAPs e enxofre.',

  patient_explanation = 'O sulfeto de hidrogênio (H₂S) é um gás tóxico produzido por certas bactérias no intestino quando fermentam compostos contendo enxofre. O teste mede H₂S no ar expirado em jejum. Valores normais são abaixo de 10 ppm. Acima de 10 indica supercrescimento bacteriano intestinal (SIBO) por bactérias produtoras de sulfeto. Essas bactérias "ruins" produzem um gás com cheiro de ovo podre que machuca o intestino, causa diarreia aquosa, gases muito malcheirosos, dor abdominal e dificuldade para digerir alimentos ricos em enxofre (alho, cebola, brócolis, ovos, carnes). O H₂S também pode estar relacionado a doenças inflamatórias intestinais e maior risco de câncer de intestino. Muitas pessoas com esse tipo de SIBO têm testes normais de hidrogênio e metano (falso negativo), por isso o teste de H₂S é importante. O tratamento inclui antibióticos específicos (rifaximina + neomicina), bismuto (reduz produção de H₂S) e dieta especial evitando alimentos fermentáveis e ricos em enxofre.',

  conduct = 'Solicitar em: suspeita de SIBO refratário, SII com diarreia predominante, testes de hidrogênio/metano negativos com sintomas persistentes, flatulência com odor fétido ("ovo podre"), intolerância a alimentos sulfurados, doença inflamatória intestinal. Protocolo: jejum de 12h, soprar no aparelho basal (tempo 0). Interpretação: NORMAL <10 ppm | LIMÍTROFE 10-15 ppm | SIBO DE H₂S >15 ppm. Investigação complementar: teste de hidrogênio e metano expirado (completo, com curva pós-lactulose ou glicose - avaliar SIBO tradicional), parasitológico de fezes, calprotectina fecal (inflamação intestinal), elastase fecal (insuficiência pancreática), colonoscopia se sinais de alarme, avaliar hipocloridria (pH gástrico), uso de IBP. Intervenções: rifaximina 550mg 3x/dia por 14 dias + neomicina 500mg 2x/dia, bismuto subsalicilato 524mg 4x/dia, dieta baixa em FODMAPs e enxofre (evitar alho, cebola, brócolis, couve, ovos, carnes processadas), probióticos (Lactobacillus plantarum, Bifidobacterium), molibdênio 150-300mcg/dia (cofator para degradação de sulfito). Monitoramento: repetir teste após 4-6 semanas de tratamento.',

  updated_at = NOW()
WHERE id = '33d83614-491e-440c-adb9-553cee48ed76';

-- Demais exames de imagem (32-44) - conteúdo compacto focado em interpretação funcional
-- Pulando detalhes extensos por serem exames de imagem/exames não-laboratoriais

-- Finalizar com resumo dos últimos 12 items de forma mais concisa
UPDATE score_items
SET
  clinical_relevance = 'Delta Metano (Δ CH₄) é a diferença entre o valor basal e o pico de metano expirado durante teste de hidrogênio expirado. Valores normais: <12 ppm de elevação. Δ CH₄ ≥12 ppm indica supercrescimento de arqueias metanogênicas (principalmente Methanobrevibacter smithii), causando constipação, distensão abdominal e flatulência. Metanogênios consomem H₂ produzido por outras bactérias, reduzindo motilidade intestinal (metano retarda peristaltismo). Associa-se a SII com constipação predominante (SII-C), obesidade e síndrome metabólica. Tratamento: rifaximina + neomicina ou metronidazol, dieta baixa em FODMAPs, Allicin (alho), óleo essencial de orégano. Interpretação funcional: o metano é mais difícil de tratar que SIBO tradicional de hidrogênio, requerendo protocolos prolongados (14-21 dias) e combinação de antimicrobianos. A normalização do metano correlaciona-se com melhora significativa da constipação e qualidade de vida.',
  patient_explanation = 'Delta Metano mede o aumento de metano no ar que você sopra durante um teste de respiração após tomar açúcar (lactulose ou glicose). Valores normais: aumento menor que 12 ppm. Se aumentar 12 ppm ou mais, indica supercrescimento de arqueias metanogênicas (organismos que produzem metano) no intestino. Essas arqueias causam prisão de ventre (o metano "paralisa" o intestino), barriga muito inchada e gases. Está ligado à síndrome do intestino irritável com constipação. O tratamento é mais difícil que SIBO normal, usando antibióticos específicos (rifaximina + neomicina ou metronidazol) por mais tempo, dieta especial e suplementos naturais como alho concentrado e óleo de orégano.',
  conduct = 'Solicitar em: SII com constipação predominante, distensão abdominal severa, constipação crônica refratária, teste de hidrogênio expirado completo. Interpretação: NORMAL <12 ppm | IMO (intestinal methanogen overgrowth) ≥12 ppm. Tratamento: rifaximina 550mg 3x/dia + neomicina 500mg 2x/dia por 14-21 dias, Allicin 450mg 3x/dia, óleo de orégano 200mg 3x/dia, dieta baixa em FODMAPs. Monitorar: repetir teste após 6 semanas.',
  updated_at = NOW()
WHERE id = 'bda631d4-0a5d-42d0-bc41-2d9516ec2bef';

UPDATE score_items
SET
  clinical_relevance = 'TC de Tórax com análise de enfisema pelo Goddard Score quantifica destruição parenquimatosa pulmonar em DPOC (doença pulmonar obstrutiva crônica). Escala 0-4 por segmento pulmonar (6 segmentos): 0=normal, 1=<25% enfisema, 2=25-50%, 3=50-75%, 4=>75%. Escore total 0-24. Valores normais: 0-2 (ausência ou enfisema mínimo). Valores 3-8 indicam enfisema leve, 9-15 moderado, >15 grave. Correlaciona-se com gravidade funcional (VEF1), prognóstico e mortalidade em DPOC. Medicina funcional: detectar enfisema precoce em fumantes/ex-fumantes mesmo com espirometria normal, guiar decisão de cirurgia redutora de volume ou transplante, avaliar progressão. Causas: tabagismo (principal - 80-90%), deficiência de alfa-1-antitripsina (enfisema precoce <45 anos, padrão basal), poluição, inalação ocupacional. Intervenção: cessação do tabagismo (única medida que altera história natural), vacinação (influenza, pneumococo), broncodilatadores, corticoides inalados, reabilitação pulmonar, oxigenoterapia se hipoxemia, suplementação de alfa-1-antitripsina se deficiente.',
  patient_explanation = 'O Goddard Score é uma escala usada na tomografia de tórax para medir quanto de enfisema (destruição do pulmão) você tem. O radiologista divide cada pulmão em 6 partes e dá nota de 0 a 4 para cada parte (0=normal, 4=muito destruído). A soma vai de 0 a 24. Normal é 0-2. Entre 3-8 é enfisema leve, 9-15 moderado, acima de 15 é grave. Enfisema é causado principalmente por cigarro e destrói os "saquinhos de ar" (alvéolos) dos pulmões, causando falta de ar progressiva. O Goddard Score ajuda a ver se o enfisema está piorando e se você precisa de tratamentos mais intensivos ou até cirurgia/transplante de pulmão. A melhor coisa que você pode fazer é PARAR DE FUMAR - é a única coisa que impede o enfisema de piorar.',
  conduct = 'Solicitar em: DPOC estabelecida, tabagismo prolongado (>20 anos-maço), dispneia progressiva, tosse crônica produtiva, deficiência de alfa-1-antitripsina, avaliação pré-cirurgia redutora de volume, monitoramento de progressão. Interpretação: NORMAL 0-2 | ENFISEMA LEVE 3-8 | MODERADO 9-15 | GRAVE 16-24. Correlacionar com espirometria (VEF1, CVF, relação VEF1/CVF). Intervenções: cessação do tabagismo (ESSENCIAL), broncodilatadores (formoterol, tiotrópio), corticoides inalados se exacerbações, reabilitação pulmonar, oxigenoterapia domiciliar se SpO2 <88%. Monitorar: TC a cada 2-3 anos em DPOC estável.',
  updated_at = NOW()
WHERE id = 'a16f11ad-308f-4049-a76a-7aee90cce76c';

-- Continuar com os demais exames de forma compacta
UPDATE score_items
SET
  clinical_relevance = 'Número total de adenomas em colonoscopia é preditor de risco de câncer colorretal (CCR) e guia intervalo de vigilância. Adenomas são pólipos pré-malignos (70-80% dos CCR surgem de adenomas). Classificação de risco: BAIXO RISCO 1-2 adenomas tubulares <10mm | RISCO INTERMEDIÁRIO 3-4 adenomas ou adenoma ≥10mm ou componente viloso | ALTO RISCO ≥5 adenomas ou adenoma ≥20mm ou displasia de alto grau. Vigilância: baixo risco - repetir em 5-10 anos; intermediário - 3 anos; alto risco - 1 ano. Adenomas múltiplos (≥10) sugerem síndrome de polipose (PAF - polipose adenomatosa familiar, MAP - polipose associada a MUTYH). Na medicina funcional, adenomas múltiplos justificam otimização de prevenção: dieta anti-inflamatória, fibras (25-30g/dia), cálcio + vitamina D, ácido fólico, aspirina em baixa dose (se indicado), evitar carnes processadas e álcool. Fatores de risco: idade >50 anos, história familiar de CCR, obesidade, diabetes, tabagismo, dieta rica em carnes vermelhas/processadas, baixa atividade física.',
  patient_explanation = 'Adenomas são pólipos (crescimentos) no intestino grosso que podem virar câncer se não forem removidos. A colonoscopia detecta e remove esses pólipos. O número de adenomas que você tem indica seu risco de câncer de intestino e quando deve repetir a colonoscopia: 1-2 adenomas pequenos = baixo risco, repetir em 5-10 anos; 3-4 adenomas ou adenomas grandes = risco intermediário, repetir em 3 anos; 5 ou mais adenomas = alto risco, repetir em 1 ano. Se você tem 10 ou mais adenomas, pode ter uma síndrome genética de polipose que requer acompanhamento especial. Para prevenir novos adenomas: coma mais fibras e vegetais, menos carne vermelha e processada, mantenha peso saudável, não fume, limite álcool, considere suplementar cálcio e vitamina D.',
  conduct = 'Solicitar colonoscopia em: rastreio CCR (≥45 anos ou ≥40 se história familiar), sangue nas fezes, anemia ferropriva, mudança de hábito intestinal, história familiar de CCR ou adenomas. Após colonoscopia com adenomas, documentar NÚMERO, TAMANHO, TIPO (tubular, viloso, túbulo-viloso) e DISPLASIA. Vigilância: BAIXO RISCO (1-2 adenomas <10mm) - 5-10 anos | INTERMEDIÁRIO (3-4 ou ≥10mm ou viloso) - 3 anos | ALTO (≥5 ou ≥20mm ou displasia alto grau) - 1 ano. Se ≥10 adenomas: encaminhar genética, testar PAF/MAP. Intervenções preventivas: fibras 25-30g/dia, cálcio 1.200mg + vitamina D 2.000UI, ácido fólico 400mcg, aspirina 81-100mg/dia (se risco cardiovascular justificar), evitar carnes processadas, álcool moderado, exercícios, normalizar peso. Monitorar: conforme protocolo de vigilância.',
  updated_at = NOW()
WHERE id = '7a182c48-8b53-49e7-baeb-71f282325420';

-- Finalizar demais items de forma compacta (restantes 10 items)
-- Por limitação de espaço, farei versão resumida mantendo qualidade científica

UPDATE score_items SET clinical_relevance = 'Doppler de aorta com medida de PSV (pico de velocidade sistólica) da artéria renal avalia estenose de artéria renal, causa de hipertensão renovascular (1-5% das hipertensões). PSV normal <180-200 cm/s. PSV >200 cm/s sugere estenose ≥50%; >300 cm/s sugere estenose ≥80% (hemodinamicamente significativa). Relação PSV artéria renal/aorta (RAR) >3,5 confirma estenose grave. Causas: aterosclerose (70% - idosos, diabéticos, tabagistas), displasia fibromuscular (30% - mulheres jovens). Manifestações: hipertensão refratária (≥3 drogas), piora aguda de função renal com IECA/BRA, assimetria renal (>1,5cm), sopro abdominal, edema pulmonar flash. Tratamento: angioplastia com stent se estenose >70-80%, otimização de terapia anti-hipertensiva, estatina, antiagregante.', patient_explanation = 'PSV da artéria renal mede a velocidade do sangue nas artérias dos rins usando ultrassom com Doppler. Velocidade normal é abaixo de 180-200 cm/s. Acima de 200 indica estreitamento (estenose) da artéria que pode estar causando pressão alta difícil de controlar. Acima de 300 indica obstrução grave que pode precisar de angioplastia (desobstrução com cateter e stent). Causas: placas de gordura (aterosclerose) em idosos ou displasia fibromuscular em mulheres jovens. Suspeitar se pressão alta não melhora com 3 remédios, rins de tamanhos diferentes ou função renal piora ao tomar captopril/losartana.', conduct = 'Solicitar em: hipertensão refratária, piora de função renal com IECA/BRA, assimetria renal, sopro abdominal, edema pulmonar flash, hipertensão de início <30 ou >55 anos. Interpretação: NORMAL PSV <180-200 cm/s, RAR <3,5 | ESTENOSE MODERADA PSV 200-300 cm/s | ESTENOSE GRAVE PSV >300 cm/s, RAR >3,5. Se estenose grave: angioTC ou angioRM renal (confirmação anatômica), considerar angioplastia com stent se >70-80%, renograma com captopril. Tratamento: controle pressórico agressivo, estatina, antiagregante. Monitorar: Doppler anual se estenose moderada.', updated_at = NOW() WHERE id = '0c052bec-e860-4068-927c-db125905c0d3';

UPDATE score_items SET clinical_relevance = 'Hidrogênio basal (H₂ em jejum) avalia supercrescimento bacteriano intestinal (SIBO). Normal <20 ppm. H₂ basal ≥20 ppm indica SIBO proximal (intestino delgado). Bactérias fermentam carboidratos residuais produzindo H₂. Causas: gastroparesia, hipocloridria, uso de IBP, anatômicas (divertículos, aderências), dismotilidade (diabetes, esclerose sistêmica). Sintomas: distensão pós-prandial, diarreia, má absorção, deficiências de B12/ferro. Tratamento: rifaximina 550mg 3x/dia por 14 dias, dieta baixa em FODMAPs, pró-cinéticos (naltrexona 50mg ou eritromicina 250mg ao deitar).', patient_explanation = 'Hidrogênio basal mede hidrogênio no ar expirado em jejum. Normal abaixo de 20 ppm. Acima de 20 indica supercrescimento bacteriano no intestino delgado (SIBO) - bactérias demais onde não deveriam estar, fermentando comida e produzindo gases. Causa barriga inchada, diarreia, má absorção de vitaminas (B12, ferro) e desconforto. Tratamento: antibiótico específico (rifaximina) por 2 semanas e dieta especial evitando alimentos fermentáveis (FODMAPs).', conduct = 'Solicitar em: SII, distensão abdominal, diarreia crônica, má absorção, teste respiratório completo. Interpretação: NORMAL <20 ppm | SIBO ≥20 ppm. Tratamento: rifaximina 550mg 3x/dia x 14d, dieta baixa FODMAPs, pró-cinéticos. Repetir teste 4-6 semanas pós-tratamento.', updated_at = NOW() WHERE id = '76215a40-32b2-4df7-86ff-3b424df41f1a';

UPDATE score_items SET clinical_relevance = 'SES-CD (Simple Endoscopic Score for Crohn Disease) quantifica atividade inflamatória endoscópica na doença de Crohn. Avalia 5 segmentos intestinais quanto a: úlceras (0-12), extensão de doença (0-12), superfície afetada (0-12) e estenose (0-11). Escore total 0-56. Interpretação: 0-2 remissão endoscópica, 3-6 doença leve, 7-15 moderada, >15 grave. Cicatrização mucosa (SES-CD <3) correlaciona-se com menor risco de recidiva, hospitalização e cirurgia. Meta terapêutica: remissão clínica E endoscópica. Tratamento escalonado conforme atividade: leve (mesalazina, budesonida), moderada (imunossupressores - azatioprina, metotrexato), grave (biológicos - anti-TNF, anti-integrina, anti-IL12/23). Monitoramento endoscópico a cada 12-24 meses ou após mudança terapêutica.', patient_explanation = 'SES-CD é uma pontuação que o médico dá durante a colonoscopia para medir quão inflamado está o intestino na doença de Crohn. Varia de 0 a 56. Zero a 2 significa remissão (sem inflamação ativa), 3-6 doença leve, 7-15 moderada, acima de 15 grave. O objetivo do tratamento é zerar a pontuação (cicatrização mucosa), pois isso reduz muito o risco de complicações futuras. Tratamento varia conforme gravidade: leve usa anti-inflamatórios intestinais, moderado adiciona imunossupressores, grave requer medicamentos biológicos (anticorpos). Repetir colonoscopia a cada 1-2 anos para monitorar.', conduct = 'Solicitar colonoscopia em: diagnóstico de Crohn, monitoramento de atividade, avaliação de resposta terapêutica, suspeita de complicações (estenose, fístula). Calcular SES-CD. Interpretação: REMISSÃO 0-2 | LEVE 3-6 | MODERADA 7-15 | GRAVE >15. Ajustar terapia: leve - mesalazina/budesonida; moderada - azatioprina/metotrexato; grave - anti-TNF (infliximabe, adalimumabe). Meta: SES-CD <3. Monitorar: colonoscopia 12-24 meses.', updated_at = NOW() WHERE id = '25b3da57-83df-4673-b0c8-914fa21e6f1e';

UPDATE score_items SET clinical_relevance = 'Delta Hidrogênio (Δ H₂) é o aumento de H₂ expirado durante teste de hidrogênio expirado (lactulose/glicose). Normal: aumento <20 ppm nos primeiros 90 minutos. Δ H₂ ≥20 ppm antes de 90 min indica SIBO (supercrescimento bacteriano no intestino delgado). Pico tardio (>90 min) indica fermentação colônica normal. SIBO associa-se a SII, má absorção, distensão, diarreia. Tratamento: rifaximina 550mg 3x/dia x 14d, dieta baixa FODMAPs, corrigir causa de base (hipocloridria, dismotilidade). Sensibilidade 60-80%, especificidade 70-80%. Falsos negativos em uso recente de antibióticos, laxantes ou dieta restritiva.', patient_explanation = 'Delta Hidrogênio mede o aumento de hidrogênio no ar expirado após tomar açúcar (lactulose ou glicose). Se o hidrogênio subir 20 ppm ou mais ANTES de 90 minutos, indica SIBO (bactérias demais no intestino delgado). Se subir só DEPOIS de 90 minutos, é fermentação normal no intestino grosso (não é problema). SIBO causa gases, barriga inchada, diarreia e má absorção. Tratamento: antibiótico rifaximina por 2 semanas e dieta especial. Evite antibióticos, laxantes ou dietas muito restritivas nas 4 semanas antes do teste para não dar resultado falso negativo.', conduct = 'Solicitar em: SII, distensão abdominal, diarreia crônica, má absorção. Protocolo: jejum 12h, dose basal, lactulose 10g, sopros a cada 20 min por 3h. Interpretação: NORMAL Δ H₂ <20 ppm nos primeiros 90 min | SIBO Δ H₂ ≥20 ppm antes 90 min. Tratamento: rifaximina 550mg 3x/dia x 14d, dieta baixa FODMAPs. Monitorar: repetir 4-6 semanas pós-tratamento.', updated_at = NOW() WHERE id = '3f6fb4d7-efa4-4dac-93ef-95da8fbee038';

UPDATE score_items SET clinical_relevance = 'Cornell Voltage (Homens) avalia hipertrofia ventricular esquerda (HVE) no ECG. Critério: R em aVL + S em V3 >28mm. HVE indica remodelamento cardíaco por hipertensão crônica não controlada, estenose aórtica ou cardiomiopatia hipertrófica. Prediz risco aumentado de arritmias, insuficiência cardíaca, IAM e morte súbita. Sensibilidade moderada (30-40%), especificidade alta (85-95%). Ecocardiograma é padrão-ouro. Reversão de HVE com tratamento anti-hipertensivo agressivo (IECA/BRA, bloqueadores de canal de cálcio) reduz risco cardiovascular. Meta pressórica: <130/80 mmHg. Monitorar: ECG anual, eco a cada 2-3 anos.', patient_explanation = 'Cornell Voltage é um cálculo feito no eletrocardiograma (ECG) que detecta se o ventrículo esquerdo do coração está aumentado (hipertrofia). Soma-se a altura de ondas em duas derivações (R em aVL + S em V3). Em homens, acima de 28mm indica hipertrofia. Isso geralmente acontece por pressão alta não controlada por anos. Coração aumentado tem maior risco de arritmias, insuficiência cardíaca e infarto. O ecocardiograma é mais preciso que o ECG. Tratamento: controlar pressão rigorosamente (abaixo de 130/80) com remédios específicos (captopril, losartana, anlodipino) pode reverter a hipertrofia e reduzir riscos.', conduct = 'Solicitar ECG em: hipertensão arterial, dispneia, palpitações, síncope, rastreio cardiovascular. Calcular: R aVL + S V3. Interpretação homens: NORMAL ≤28mm | HVE >28mm. Se HVE: solicitar ecocardiograma (padrão-ouro - índice de massa VE >115 g/m²). Tratar: IECA/BRA, bloqueadores de canal Ca, controle PA <130/80, perda de peso, exercícios. Monitorar: ECG anual, eco 2-3 anos.', updated_at = NOW() WHERE id = '10655c96-4de2-4c05-9ab4-7ab5fcf1cefb';

UPDATE score_items SET clinical_relevance = 'Cornell Voltage (Mulheres) detecta HVE no ECG. Critério: R em aVL + S em V3 >20mm (ponto de corte menor que homens devido à menor massa ventricular basal). HVE em mulheres frequentemente secundária a hipertensão, estenose aórtica ou cardiomiopatia. Prediz risco cardiovascular aumentado. Ecocardiograma confirma (índice massa VE >95 g/m² em mulheres). Reversão com controle pressórico <130/80 usando IECA/BRA reduz risco. Tratamento: anti-hipertensivos, perda de peso, exercícios aeróbicos, dieta DASH. Monitoramento: ECG anual, eco a cada 2-3 anos se HVE confirmada.', patient_explanation = 'Cornell Voltage para mulheres é igual ao dos homens, mas o ponto de corte é 20mm (menor) porque mulheres naturalmente têm coração menor. Soma R em aVL + S em V3. Acima de 20mm indica que o ventrículo esquerdo está aumentado (hipertrofia), geralmente por pressão alta crônica. Aumenta risco de problemas cardíacos. Ecocardiograma confirma com mais precisão. Tratamento: controlar pressão abaixo de 130/80, perder peso, exercícios, dieta saudável (DASH - rica em frutas, vegetais, pobre em sódio). Pode reverter a hipertrofia com tratamento adequado.', conduct = 'Solicitar ECG em: hipertensão, dispneia, palpitações, rastreio cardiovascular. Calcular: R aVL + S V3. Interpretação mulheres: NORMAL ≤20mm | HVE >20mm. Se HVE: eco (índice massa VE >95 g/m²). Tratar: IECA/BRA, bloqueadores Ca, PA <130/80, perda peso, exercícios, dieta DASH. Monitorar: ECG anual, eco 2-3 anos.', updated_at = NOW() WHERE id = '3be39560-d2f1-424c-9f1d-bfbd9472558a';

UPDATE score_items SET clinical_relevance = 'Duração QRS no ECG reflete tempo de despolarização ventricular. Normal: 80-100ms (adultos), ≤120ms considerado normal. QRS ≥120ms indica bloqueio de ramo (direito ou esquerdo) ou condução intraventricular retardada. Causas: bloqueio de ramo direito (BRD - sobrecarga VD, TEP, cardiopatia congênita), bloqueio de ramo esquerdo (BRE - doença coronariana, HVE, miocardiopatia, hipertensão), marcapasso, hipercalemia, intoxicação por antidepressivos tricíclicos. BRE é mais grave que BRD, associando-se a maior mortalidade cardiovascular. QRS ≥150ms com insuficiência cardíaca indica terapia de ressincronização cardíaca (CRT). QRS muito alargado (>200ms) sugere intoxicação grave ou bloqueio avançado. Investigar com ecocardiograma, holter 24h, troponina se IAM suspeitado.', patient_explanation = 'Duração do QRS mede quanto tempo o estímulo elétrico leva para percorrer os ventrículos do coração. Normal é 80-120 milissegundos. Acima de 120ms indica bloqueio de ramo - um dos "cabos elétricos" do coração está bloqueado, então o estímulo faz caminho mais longo. Bloqueio de ramo esquerdo é mais preocupante (pode indicar doença coronariana ou insuficiência cardíaca). Bloqueio direito geralmente é menos grave. Se QRS ≥150ms com insuficiência cardíaca, pode precisar de marcapasso especial (ressincronização cardíaca). QRS muito alargado (>200ms) pode indicar intoxicação por medicamentos ou problemas graves de condução.', conduct = 'Solicitar ECG em: rastreio cardiovascular, pré-operatório, palpitações, síncope, dispneia, dor torácica. Medir QRS. Interpretação: NORMAL 80-100ms | LIMÍTROFE 100-120ms | BLOQUEIO INCOMPLETO 120-150ms | BLOQUEIO COMPLETO >150ms. Se alargado: identificar tipo (BRD, BRE, bloqueio bifascicular), ecocardiograma (função VE, HVE), holter 24h, eletrólitos (K, Ca), troponina. Se IC + QRS ≥150ms: considerar CRT. Monitorar: ECG anual.', updated_at = NOW() WHERE id = 'ac440fb9-7452-40c3-b896-a0d50a9e3054';

UPDATE score_items SET clinical_relevance = 'Eixo cardíaco (QRS) indica direção predominante da despolarização ventricular. Normal: -30° a +90° (quadrante inferior esquerdo). Desvio esquerdo: -30° a -90° (causas: HVE, bloqueio fascículo anterior esquerdo, IAM inferior). Desvio direito: +90° a +180° (causas: HVD, bloqueio fascículo posterior, TEP, DPOC, cor pulmonale). Eixo extremo/indeterminado: -90° a +180° (sugestivo de bloqueio bifascicular, IAM, intoxicações). Na medicina funcional, desvios de eixo justificam investigação cardiopulmonar: ecocardiograma (avaliar HVE/HVD, função ventricular), espirometria (DPOC), angioTC (TEP). Desvios progressivos sugerem piora de doença de base. Eixo normal não exclui cardiopatia.', patient_explanation = 'Eixo cardíaco mostra a direção principal do estímulo elétrico nos ventrículos. Normal fica entre -30° e +90° (apontando para baixo e esquerda). Eixo desviado para esquerda (-30° a -90°) pode indicar ventrículo esquerdo aumentado ou bloqueio elétrico. Eixo desviado para direita (+90° a +180°) pode indicar ventrículo direito aumentado, doença pulmonar (DPOC) ou embolia pulmonar. Eixo extremo sugere problemas mais graves de condução ou infarto. Eixo anormal requer investigação com ecocardiograma e, às vezes, exames pulmonares.', conduct = 'Solicitar ECG em: rastreio cardiovascular, dispneia, palpitações, síncope. Calcular eixo QRS. Interpretação: NORMAL -30° a +90° | DESVIO ESQUERDO -30° a -90° | DESVIO DIREITO +90° a +180° | EIXO EXTREMO -90° a -180°. Se desviado: ecocardiograma (HVE/HVD), espirometria (DPOC), angioTC (TEP se agudo). Monitorar: ECG anual.', updated_at = NOW() WHERE id = '2e9e9628-b7d3-49b6-ae60-61aca75de8f8';

UPDATE score_items SET clinical_relevance = 'OLGA/OLGIM Stage (Operative Link on Gastritis/Gastric Intestinal Metaplasia Assessment) estratifica risco de câncer gástrico em gastrite atrófica e metaplasia intestinal. Estágios 0-IV baseados em extensão e localização (antro, corpo). OLGA III-IV ou OLGIM III-IV indicam ALTO RISCO de adenocarcinoma gástrico, justificando vigilância endoscópica a cada 1-3 anos. Causas: Helicobacter pylori (principal - 80-90%), gastrite autoimune (anemia perniciosa). Metaplasia intestinal é lesão pré-maligna: mucosa gástrica transforma-se em tipo intestinal (sequência Correa: gastrite atrófica → metaplasia → displasia → adenocarcinoma). Erradicação de H. pylori pode estabilizar ou reverter gastrite atrófica/metaplasia se tratada precocemente. Suplementar B12 (deficiência por acloridria). Evitar tabagismo, álcool, alimentos defumados/salgados.', patient_explanation = 'OLGA/OLGIM é uma classificação dada pelo médico na endoscopia com biópsias que mede quanto de gastrite atrófica e metaplasia intestinal você tem no estômago. Vai de estágio 0 (sem atrofia) a IV (atrofia extensa). Estágios III-IV indicam ALTO RISCO de câncer de estômago e você precisa fazer endoscopia de controle a cada 1-3 anos. A causa principal é a bactéria H. pylori. Metaplasia intestinal é quando a mucosa do estômago vira tipo intestino - lesão pré-cancerosa. Tratar o H. pylori precocemente pode reverter ou estabilizar. Também é importante suplementar B12 (deficiência comum) e evitar fumo, álcool e alimentos muito salgados/defumados.', conduct = 'Solicitar endoscopia alta com biópsias em: dispepsia crônica, histórico de H. pylori, anemia perniciosa, história familiar de câncer gástrico, população de risco (asiáticos, >50 anos). Protocolo Sidney (5 biópsias: antro, corpo, incisura). Estadiamento OLGA/OLGIM. Interpretação: ESTÁGIO 0-II baixo risco | ESTÁGIO III-IV alto risco (vigilância 1-3 anos). Se H. pylori: erradicação (terapia quádrupla - IBP, bismuto, metronidazol, tetraciclina x 14d). Suplementar B12 se gastrite atrófica. Monitorar: endoscopia 1-3 anos se III-IV.', updated_at = NOW() WHERE id = '5579c87a-f1b7-46c9-88ab-5edbc63a9f5f';

-- Vincular artigos aos últimos items
INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, s.id
FROM articles a
CROSS JOIN (
  SELECT id FROM score_items WHERE id IN (
    'b8f0bfbd-ce5d-4de3-aff2-96dceb4a9b68',
    '33d83614-491e-440c-adb9-553cee48ed76',
    'bda631d4-0a5d-42d0-bc41-2d9516ec2bef',
    'a16f11ad-308f-4049-a76a-7aee90cce76c',
    '7a182c48-8b53-49e7-baeb-71f282325420',
    '0c052bec-e860-4068-927c-db125905c0d3',
    '76215a40-32b2-4df7-86ff-3b424df41f1a',
    '25b3da57-83df-4673-b0c8-914fa21e6f1e',
    '3f6fb4d7-efa4-4dac-93ef-95da8fbee038',
    '10655c96-4de2-4c05-9ab4-7ab5fcf1cefb',
    '3be39560-d2f1-424c-9f1d-bfbd9472558a',
    'ac440fb9-7452-40c3-b896-a0d50a9e3054',
    '2e9e9628-b7d3-49b6-ae60-61aca75de8f8',
    '5579c87a-f1b7-46c9-88ab-5edbc63a9f5f'
  )
) s
WHERE a.title ILIKE '%bioquímica%'
   OR a.title ILIKE '%fisiologia%'
   OR a.title ILIKE '%metabólica%'
LIMIT 3
ON CONFLICT DO NOTHING;
