-- ============================================
-- BATCH 6.1: HISTÓRICO DE DOENÇAS - PARTE 1 (Continuação)
-- Items 16-25
-- ============================================

-- Item 16: Chikungunya
UPDATE score_items
SET
  clinical_relevance = 'Chikungunya (CHIKV) é arbovirose alfavírus (Togaviridae), transmitida Aedes aegypti/albopictus. Nome deriva makonde "aquele que se curva" (artralgia severa). Epidemias Brasil 2014+. Fase aguda (3-10 dias): febre alta súbita, artralgia poliarticular intensa bilateral simétrica (mãos, punhos, tornozelos, joelhos - incapacitante, pior manhã), edema articular, exantema maculopapular, cefaleia, mialgia, conjuntivite. Diferencial dengue: artralgia muito mais severa e prolongada, febre menor, raramente hemorrágico ou choque. Fase pós-aguda (até 3 meses): artralgia/artrite persistente, fadiga, depressão. Fase crônica (>3 meses): 30-60% pacientes, artralgia/artrite reumatoide-like persistente por meses-anos, tenossinovite, edema, rigidez matinal, incapacitação funcional. Fatores risco cronicidade: idade >45 anos, artropatia prévia, carga viral alta, sexo feminino. Complicações raras: miocardite, meningoencefalite, Guillain-Barré, síndrome hemorrágica. Neonatal: transmissão vertical intraparto, encefalite neonatal grave. Diagnóstico: PCR dias 1-8, sorologia IgM dia 5+. Tratamento: suporte, AINES, corticoides se artrite persistente refratária. Na MFI: modulação inflamação persistente (curcumina, ômega-3, Boswellia), controle dor neuropática (PEA, canabidiol), suporte articular (colágeno tipo II, glucosamina), fisioterapia, acupuntura.',

  patient_explanation = 'Chikungunya é vírus transmitido pelo mosquito Aedes (mesmo da dengue). Nome significa "aquele que se dobra" pela dor articular intensa. Sintomas: febre alta súbita, dor MUITO FORTE nas juntas (mãos, pulsos, joelhos, tornozelos), ambos lados, com inchaço, pior ao acordar - dor é tão forte que impede movimentos. Também: manchas vermelhas, dor cabeça, dor corpo, olhos vermelhos. Dura 3-10 dias. Raramente tem sangramento ou choque (diferente dengue). GRANDE PROBLEMA: 30-60% das pessoas desenvolvem dor crônica nas juntas que persiste por MESES ou ANOS após infecção - vira artrite crônica parecida com artrite reumatoide. Risco maior: >45 anos, mulheres, quem já tinha problema nas juntas. Isso é muito incapacitante e frustrante. Não existe remédio específico, só controle sintomas: anti-inflamatórios, fisioterapia, às vezes corticoides se muito grave. Na medicina funcional, usamos abordagem agressiva anti-inflamatória: curcumina alta dose, ômega-3 EPA/DHA, Boswellia (incenso indiano), PEA e canabidiol (controle dor neuropática), colágeno tipo II (suporte articular), acupuntura, dieta anti-inflamatória rigorosa (sem açúcar, glúten, laticínios). Muitos melhoram significativamente com protocolo integrativo. Prevenção: eliminar água parada, repelente, telas.',

  conduct = 'Diagnóstico: PCR CHIKV soro (dias 1-8, padrão-ouro), sorologia IgM (dia 5+, persiste meses), IgG (dia 7-10+). Hemograma: leucopenia, linfopenia, plaquetopenia leve (menos que dengue). Transaminases: elevação leve-moderada. Fase crônica: avaliar autoanticorpos (FR, anti-CCP geralmente negativos, diferencial artrite reumatoide), PCR, VHS elevados, radiografia articulações (erosões raras). Tratamento agudo: repouso, AINES (ibuprofeno 400-600mg 3x/dia, naproxeno 500mg 2x/dia), paracetamol, hidratação. Evitar AAS até descartar dengue. Fase crônica artralgia: AINES, prednisona 10-20mg se refratária (curto prazo), metotrexato 10-15mg/semana se artrite persistente severa >3 meses (eficácia moderada), hidroxicloroquina 400mg. Fisioterapia: mobilização, fortalecimento, hidroterapia. Protocolo MFI anti-inflamatório agressivo: curcumina lipossomal 2-3g/dia (eficácia próxima AINES), Boswellia serrata 900-1.200mg, ômega-3 EPA/DHA 3-4g, PEA (palmitoiletanolamida) 600-1.200mg (analgésico endógeno), canabidiol 20-40mg, colágeno tipo II não-desnaturado 40mg, glucosamina sulfato 1.500mg + condroitina 1.200mg, MSM 3g, vitamina D3 10.000UI (alvo >60ng/ml), magnésio 400mg, probióticos. Dieta: eliminar açúcar, glúten, laticínios, solanáceas (nightshades), AIP 90 dias. Suplementos adicionais: gengibre 2g, resveratrol 500mg, quercetina 1g, bromelaína 500mg (enzimas anti-inflamatórias). Acupuntura 2-3x/semana. Compressas quentes/frias alternadas. Sono otimizado 8h. Retorno gradual atividades. Monitorar resposta mensal.',

  updated_at = NOW()
WHERE id = 'd13e641d-fec0-4b50-8794-1fb5c541e43a';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, 'd13e641d-fec0-4b50-8794-1fb5c541e43a'
FROM articles a
WHERE a.title ILIKE '%chikungunya%' OR a.title ILIKE '%arbovirose%' OR a.title ILIKE '%artrite%' OR a.title ILIKE '%dor%'
LIMIT 5
ON CONFLICT DO NOTHING;

-- Item 17: COVID
UPDATE score_items
SET
  clinical_relevance = 'COVID-19 é doença por SARS-CoV-2 (betacoronavírus RNA), pandemia 2019-2023. Transmissão: aerossóis, gotículas, fômites. Espectro: assintomático (20-40%), leve (40-60% - febre, tosse, anosmia/ageusia, fadiga, cefaleia), moderado (10-15% - pneumonia, hipoxemia), grave (5% - SARA, choque, falência múltiplos órgãos), crítico (1-2% - UTI, VM, ECMO). Fisiopatologia: ligação receptor ACE2 → inflamação pulmonar, tempestade citocinas (IL-6, TNF-α, IL-1β), hipercoagulabilidade (D-dímero elevado), disfunção endotelial. Complicações agudas: SARA, TEP, IAM, AVC, miocardite, rabdomiólise, lesão renal aguda, coinfecções bacterianas/fúngicas. Fatores risco gravidade: idade >60, obesidade (OR 2-3), diabetes, HAS, cardiopatia, DPOC, imunossupressão, câncer. Síndrome Pós-COVID (Long COVID, 10-30%): fadiga persistente severa, dispneia, brain fog, cefaleia, palpitações, dor torácica, disautonomia (POTS), intolerância esforço, distúrbios sono, ansiedade/depressão, anosmia prolongada. Mecanismos: inflamação persistente, autoimunidade, reativação viral, microtrombos, disfunção mitocondrial. Diagnóstico: RT-PCR (padrão-ouro), teste rápido antígeno, sorologia IgM/IgG. Na MFI: suporte imune agudo (vitamina D, C, zinco, quercetina), anticoagulação, Long COVID (NAC, CoQ10, ômega-3, PEA, reabilitação gradual).',

  patient_explanation = 'COVID-19 é doença causada pelo coronavírus SARS-CoV-2, pandemia mundial 2020-2023. Transmite pelo ar (tosse, espirro, fala) e superfícies contaminadas. Sintomas variam muito: alguns não sentem nada, outros têm sintomas leves (febre, tosse seca, perda olfato/paladar - bem característico, cansaço, dor cabeça, dor corpo), alguns desenvolvem pneumonia grave com falta de ar necessitando oxigênio ou UTI. Fatores risco para forma grave: idade avançada, obesidade, diabetes, pressão alta, doenças cardíacas/pulmonares. Complicações: coágulos sanguíneos (trombose pulmão, AVC), inflamação coração, insuficiência respiratória. LONG COVID (COVID longa): 10-30% ficam com sintomas persistentes por meses após infecção - cansaço extremo, falta de ar, névoa mental (dificuldade concentração/memória), palpitações, dor no peito, tontura ao levantar, intolerância exercício. É muito debilitante e ainda não totalmente compreendido. Pode estar relacionado a inflamação persistente, microcoágulos, autoimunidade, disfunção mitocondrial. Tratamento agudo: suporte (repouso, hidratação), antivirais se grupo risco (Paxlovid), anticoagulantes se hospitalizado, oxigênio/ventilação se grave. Long COVID: abordagem funcional com antioxidantes potentes (NAC, CoQ10), anti-inflamatórios (ômega-3), suporte mitocondrial, reabilitação gradual, fisioterapia respiratória.',

  conduct = 'Diagnóstico: RT-PCR SARS-CoV-2 nasofaringe/orofaringe (padrão-ouro, sensibilidade >95% primeiros 5 dias), teste rápido antígeno (menos sensível 70-80%, resultado 15min), sorologia IgM/IgG (epidemiologia, não diagnóstico agudo). Avaliar gravidade: saturação O2 (SpO2 <94% ar ambiente = moderado, <90% = grave), frequência respiratória (>24irpm), raio-X ou TC tórax (opacidades vidro fosco, consolidação), marcadores inflamatórios (PCR, D-dímero >1.000 pior prognóstico, ferritina, DHL, linfopenia, troponina). Tratamento ambulatorial leve-moderado: isolamento 5-10 dias, repouso, hidratação, sintomáticos, antivirais se grupo risco <5 dias sintomas (Paxlovid, remdesivir). Hospitalizado: oxigenioterapia, dexametasona 6mg 10 dias, anticoagulação profilática/terapêutica (D-dímero elevado), antibióticos se coinfecção bacteriana, tocilizumabe se tempestade citocinas. Long COVID investigação: hemograma, PCR-us, D-dímero, ferritina, perfil tireoidiano, vitamina D/B12, cortisol, ecocardiograma, TC tórax, teste caminhada 6min, avaliação neuropsicológica. Protocolo MFI Long COVID: NAC 1.800mg (antioxidante, anticoagulante), CoQ10 200-400mg (mitocôndria), ômega-3 EPA/DHA 3g, PEA 1.200mg (neuroinflamação), curcumina 2g, vitamina D3 10.000UI (alvo >60ng/ml), vitamina C 2g, zinco 30mg, magnésio 400mg, probióticos multi-cepas, L-glutamina 10g (barreira), colágeno, nattokinase ou lumbrokinase (fibrinólise microtrombos). Dieta anti-inflamatória AIP. Reabilitação respiratória gradual, exercício aeróbico baixa intensidade progressivo. Sono 8-9h. Manejo POTS: hidratação, sal, meias compressão. Acompanhamento multidisciplinar.',

  updated_at = NOW()
WHERE id = '58ca1231-3f26-434a-aef8-dfd8a07933e8';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, '58ca1231-3f26-434a-aef8-dfd8a07933e8'
FROM articles a
WHERE a.title ILIKE '%COVID%' OR a.title ILIKE '%SARS%' OR a.title ILIKE '%pandemia%' OR a.title ILIKE '%long%'
LIMIT 5
ON CONFLICT DO NOTHING;

-- Item 18: Sarampo
UPDATE score_items
SET
  clinical_relevance = 'Sarampo é doença viral altamente contagiosa (Morbillivirus, Paramyxoviridae), R0=12-18 (mais contagiosa que COVID). Transmissão: aerossóis, 90% expostos não-imunes adoecem. Erradicado Américas 2016, ressurgência por queda cobertura vacinal. Período incubação: 10-14 dias. Pródromo (2-4 dias): febre alta (>39°C), tosse, coriza, conjuntivite (3 Cs), manchas Koplik (patognomônicas - pontos brancos mucosa oral). Exantema (dia 3-7): maculopapular eritematoso, inicia face (linha cabelo) → descendente tronco/extremidades, confluente, dura 4-7 dias, descamação fina. Complicações (30%): otite média, pneumonia (causa principal morte - bacteriana secundária ou vírus), diarréia, encefalite aguda (1:1.000, 10-15% mortalidade, sequelas 25%), panencefalite esclerosante subaguda (PEES 1:10.000, 7-10 anos pós-sarampo, degeneração neurológica progressiva, fatal). Desnutridos/imunossuprimidos: sarampo grave, pneumonia de células gigantes. Gestação: aborto, parto prematuro, baixo peso. Mortalidade: 1-3/1.000 países desenvolvidos, >10% países pobres. Complicação tardia: supressão imune transitória 2-3 anos (amnésia imune - perda memória imunológica prévia). Diagnóstico: sorologia IgM, PCR. Notificação compulsória. Prevenção: vacina tríplice viral (sarampo, caxumba, rubéola) 12 meses e 15 meses, eficácia 97% 2 doses. Na MFI: vitamina A alta dose (reduz 50% mortalidade), suporte imune.',

  patient_explanation = 'Sarampo é doença viral extremamente contagiosa - se uma pessoa com sarampo entra em sala com 10 não-vacinados, 9 pegam. Transmite pelo ar facilmente. Havia sido eliminado das Américas, mas voltou porque muita gente parou de vacinar. Sintomas: febre muito alta (39-40°C), tosse, nariz escorrendo, olhos vermelhos/lacrimejantes, depois surgem manchas vermelhas que começam no rosto e descem pelo corpo todo, juntando-se. Dentro da boca aparecem pontos brancos (sinal Koplik). Complicações são comuns (30%): infecção ouvido, pneumonia (principal causa morte), diarreia, encefalite (inflamação cérebro, muito grave, 10-15% morrem, 25% ficam com sequelas). Crianças desnutridas e imunossuprimidos têm formas muito graves. Raramente, 7-10 anos depois, pode desenvolver PEES (degeneração cerebral progressiva fatal). Sarampo também "apaga" memória do sistema imune, deixando pessoa vulnerável a outras infecções por 2-3 anos. PREVENÇÃO É ESSENCIAL: vacina tríplice viral aos 12 meses e reforço 15 meses, protege 97%. Tratamento: não existe antiviral, é suporte (controle febre, hidratação, antibióticos se pneumonia bacteriana). VITAMINA A alta dose reduz mortalidade em 50% - OMS recomenda dar para toda criança com sarampo.',

  conduct = 'Diagnóstico clínico: febre >38,3°C + exantema maculopapular + tosse/coriza/conjuntivite + manchas Koplik. Confirmação laboratorial obrigatória (notificação compulsória): sorologia IgM anti-sarampo (positivo 3-4 dias pós-exantema), PCR nasofaringe/urina (identifica genotipo). IgG: imunidade prévia/vacinal. Avaliar complicações: otoscopia (otite), raio-X tórax (pneumonia), hemograma (leucopenia viral, depois leucocitose se bacteriana), transaminases (hepatite). Sinais encefalite: convulsões, alteração consciência, punção lombar. Tratamento: isolamento respiratório, suporte (hidratação, antitérmicos, repouso). Vitamina A OMS (reduz 50% mortalidade): <6 meses 50.000UI dose única, 6-11 meses 100.000UI, >12 meses 200.000UI, repetir dose no dia seguinte e 4 semanas se deficiência vitamina A ou sinais oculares. Antibióticos se pneumonia bacteriana secundária (amoxicilina-clavulanato, ceftriaxone). Hospitalizar: <1 ano, desnutridos, complicações, imunossuprimidos. Prevenção pós-exposição: vacina tríplice viral <72h exposição (pode prevenir/atenuar), imunoglobulina 0,25-0,5ml/kg IM <6 dias se contraindicação vacina (gestante, imunossuprimido, <6 meses). Vacinação: tríplice viral 12 meses + reforço 15 meses (ou tetraviral SCRV incluindo varicela). Adultos: 2 doses se nascidos após 1960 sem comprovação. Contraindicação: gestação, imunossupressão severa. Protocolo MFI: vitamina A dose terapêutica, vitamina C 1-2g, vitamina D3 2.000-4.000UI, zinco 20mg, probióticos, hidratação, repouso completo.',

  updated_at = NOW()
WHERE id = '11fad7bc-dff2-4e01-8bd5-06b3ae60e8ec';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, '11fad7bc-dff2-4e01-8bd5-06b3ae60e8ec'
FROM articles a
WHERE a.title ILIKE '%sarampo%' OR a.title ILIKE '%viral%' OR a.title ILIKE '%vacina%' OR a.title ILIKE '%pediatria%'
LIMIT 5
ON CONFLICT DO NOTHING;

-- Item 19: Outra doença infecciosa
UPDATE score_items
SET
  clinical_relevance = 'Campo aberto para documentar outras doenças infecciosas não listadas. Inclui: bacterianas (febre tifoide, leptospirose, brucelose, tétano, difteria, coqueluche, meningites bacterianas, endocardite, osteomielite, celulite, abscessos), virais (influenza, H1N1, rinovírus, adenovírus, rotavírus, norovírus, hepatites A/B/C/D/E, HIV, HTLV, raiva, febre amarela, rubéola, caxumba, parvovírus B19, papilomavírus HPV, poliomielite, hantavírus), fúngicas (candidíase sistêmica, aspergilose, histoplasmose, paracoccidioidomicose, criptococose, pneumocystis), parasitárias (malária, leishmaniose, doença Chagas, toxoplasmose, esquistossomose, teníase/cisticercose, estrongiloidíase, giardíase, amebíase, ancilostomíase). Importância: infecções podem cronificar (HIV, hepatites, Chagas), causar sequelas permanentes (meningite → surdez/retardo, pólio → paralisia), desencadear autoimunidade, predispor neoplasias (HPV → câncer, H.pylori → linfoma MALT), indicar imunodeficiência (infecções oportunistas recorrentes). Na MFI: investigar causas raiz imunodeficiência se infecções recorrentes (micronutrientes, sono, estresse, disbiose, autoimunidade), rastreio conforme história (viagens área endêmica, exposições ocupacionais, comportamento risco, imunossupressão), suporte imune, tratamento específico etiológico.',

  patient_explanation = 'Este campo registra qualquer outra doença infecciosa importante que você teve e que não foi perguntada especificamente. Exemplos: hepatites (A, B, C causam inflamação fígado, B e C podem cronificar e causar cirrose/câncer), HIV (vírus da AIDS), leptospirose (xixi rato, enchentes), febre tifoide, meningite (inflamação membranas cérebro, pode deixar surdez/sequelas), pneumonia grave, infecções fúngicas sistêmicas (candidíase invasiva, aspergilose), parasitas (malária, doença Chagas, leishmaniose, esquistossomose), HPV (causa verrugas genitais e câncer colo útero), H.pylori (bactéria estômago que causa úlcera e câncer). É importante documentar porque: 1) Algumas cronificam e precisam acompanhamento (HIV, hepatites B/C, Chagas). 2) Podem deixar sequelas (meningite → surdez, pólio → paralisia). 3) Indicam se sua imunidade está baixa (infecções frequentes/graves não são normais). 4) Algumas aumentam risco câncer no futuro. 5) Tratamento adequado previne complicações. Na medicina funcional, se você tem infecções recorrentes investigamos por que sua imunidade está comprometida: deficiências vitaminas (D, A, C, zinco), sono ruim, estresse crônico, intestino permeável, doenças autoimunes escondidas. Fortalecendo imunidade de base, infecções diminuem drasticamente.',

  conduct = 'História detalhada: tipo infecção, agente etiológico se identificado, ano ocorrência, gravidade (ambulatorial vs hospitalização vs UTI), tratamento realizado, duração, cura/cronicidade, sequelas, recorrências. Epidemiologia: viagens (áreas endêmicas malária, dengue, febre amarela, leishmaniose), exposição ocupacional (leptospirose, brucelose, tuberculose), comportamento risco (DSTs - HIV, sífilis, hepatites, HPV), contato doentes, vacinação. Investigar conforme suspeita: Hepatites: sorologias HAV/HBV/HCV/HDV/HEV (IgM/IgG, HBsAg, anti-HBs, anti-HBc, HCV RNA), transaminases, carga viral se crônica. HIV: teste rápido ou ELISA HIV 1/2 + Western blot, se positivo CD4/carga viral. HPV: Papanicolau, colposcopia, genotipagem HPV alto risco. H.pylori: teste respiratório ureia, sorologia, biópsia. Parasitas: parasitológico fezes 3 amostras, sorologias (Chagas, toxoplasmose, esquistossomose). Fungos: culturas, sorologias, biópsia. Infecções recorrentes: investigar imunodeficiência - hemograma, imunoglobulinas (IgG, IgA, IgM, IgE), subpopulações linfocitárias (CD4/CD8/CD19), complemento, teste HIV, glicemia (diabetes), micronutrientes (vitamina D, zinco, vitamina A, selênio, ferro). Tratamento etiológico específico conforme agente. Suporte MFI: vitamina D3 5.000-10.000UI (alvo >50ng/ml), zinco 30-50mg, vitamina C 1-2g, vitamina A 10.000UI, selênio 200mcg, probióticos multi-cepas, cogumelos medicinais (beta-glucanas), lactoferrina 300mg, própolis 500mg, alho envelhecido 1.200mg, sono 8h, dieta anti-inflamatória, manejo estresse. Vacinação conforme calendário.',

  updated_at = NOW()
WHERE id = 'fa53a419-0431-40ff-b7c5-b9ae4e7eec42';

-- Item 20: Doenças alérgicas
UPDATE score_items
SET
  clinical_relevance = 'Campo categórico para rastrear histórico alergias/atopia. Doenças alérgicas são reações hipersensibilidade tipo I (IgE-mediadas) a alérgenos ambientais (ácaros, pólen, fungos, epitélio animais), alimentares (leite, ovo, trigo, soja, amendoim, frutos-mar), medicamentosas, venenos. Marcha atópica: dermatite atópica lactente → alergia alimentar → rinite alérgica → asma. Genética: história familiar atopia aumenta risco 2-3x. Fisiopatologia: polarização Th2, produção IgE específica, degranulação mastócitos/basófilos → liberação histamina, leucotrienos, prostaglandinas. Manifestações: respiratórias (rinite, rinoconjuntivite, asma, tosse), cutâneas (urticária, angioedema, dermatite atópica, dermatite contato), gastrointestinais (dor abdominal, diarreia, vômitos), sistêmicas (anafilaxia - risco vida). Comorbidades: sinusite crônica, polipose nasal, otite média recorrente, apneia sono, distúrbios comportamento/aprendizado (TDAH associado rinite alérgica). Hipótese higiene: exposição microbiana reduzida infância → falha desenvolvimento tolerância imune → atopia. Na MFI: investigar disbiose (microbiota alterada associada alergias), permeabilidade intestinal, deficiência vitamina D, estresse oxidativo, carga tóxica. Modulação: probióticos lactente/gestação (prevenção), vitamina D >40ng/ml, quercetina, ômega-3, imunoterapia alérgeno-específica, dieta anti-inflamatória, redução exposição alérgenos.',

  patient_explanation = 'Doenças alérgicas acontecem quando sistema imunológico reage exageradamente a substâncias inofensivas (pólen, ácaros pó, pelos animais, alimentos, remédios). Incluem: rinite alérgica (espirros, coriza, nariz entupido), conjuntivite alérgica (olhos coçando/lacrimejando), asma (chiado peito, falta ar), dermatite atópica/eczema (pele seca coçando), urticária (placas vermelhas que coçam), alergias alimentares, alergia medicamentos. Bebês geralmente começam com eczema e alergia leite/ovo, depois desenvolvem rinite e asma (marcha atópica). Se pais têm alergias, filhos têm risco aumentado. Alergias pioram qualidade vida: sono ruim (nariz entupido), cansaço, dificuldade concentração, faltas escola/trabalho. Crianças com rinite alérgica têm mais TDAH. Complicações: sinusite crônica, otites repetidas, pólipos nasais, asma grave. Anafilaxia (reação alérgica grave) é emergência: dificuldade respirar, inchaço língua/garganta, pressão baixa - pode matar, precisa adrenalina urgente. Na medicina funcional investigamos POR QUE você desenvolveu alergias: microbiota intestinal desequilibrada (bebês cesariana + sem amamentação têm mais alergias), intestino permeável, vitamina D baixa, excesso higiene na infância. Tratamento: probióticos desde gestação/lactância previnem, vitamina D >40, quercetina (anti-histamínico natural), ômega-3, dieta anti-inflamatória, imunoterapia dessensibilização.',

  conduct = 'História alérgica detalhada: tipos alergia (respiratória, cutânea, alimentar, medicamentosa, insetos), alérgenos identificados, idade início, evolução, gravidade, sazonalidade, tratamentos prévios/atuais (anti-histamínicos, corticoides, broncodilatadores), historia familiar atopia, comorbidades (asma, sinusite, polipose, dermatite atópica). Sinais anafilaxia prévia: urticária generalizada, angioedema, broncoespasmo, hipotensão, necessidade adrenalina. Investigação: IgE total (elevado sugere atopia mas não específico), IgE específica ou teste cutâneo (prick test) alérgenos suspeitos (inalantes: ácaros, pólen, fungos, epitélio; alimentos: leite, ovo, trigo, soja, amendoim, frutos-mar; venenos). Eosinófilos periféricos elevados. Espirometria se asma. Avaliação MFI: vitamina D (alvo >40ng/ml, baixa associada mais alergias), marcadores intestinais (zonulina, calprotectina), microbioma fezes (disbiose), IgG alimentos (sensibilidades não-IgE), estresse oxidativo. Tratamento: evitar alérgenos (capas anti-ácaros, HEPA filtros, remover carpetes), anti-histamínicos 2ª geração (loratadina, desloratadina, fexofenadina), corticoides nasais (fluticasona, mometasona), broncodilatadores se asma, imunoterapia sublingual/subcutânea (dessensibilização 3-5 anos, 80% eficácia). Anafilaxia: adrenalina autoinjetor, educação. Protocolo MFI: probióticos multi-cepas (Lactobacillus + Bifidobacterium desde gestação/lactância previne atopia), vitamina D3 2.000-4.000UI criança, 5.000UI adulto, quercetina 500-1.000mg (anti-histamínico natural), ômega-3 1-2g, vitamina C 1g, NAC 600mg, magnésio 300mg. Dieta: eliminar ultraprocessados, açúcar, corantes/conservantes, identificar sensibilidades. Amamentação exclusiva 6 meses (protetor). Exposição microbiana saudável infância.',

  updated_at = NOW()
WHERE id = '954177a6-dc1f-4591-983a-1ac670c3da1d';

INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, '954177a6-dc1f-4591-983a-1ac670c3da1d'
FROM articles a
WHERE a.title ILIKE '%alergia%' OR a.title ILIKE '%alérgica%' OR a.title ILIKE '%atopia%' OR a.title ILIKE '%imun%'
LIMIT 5
ON CONFLICT DO NOTHING;
