-- ============================================================================
-- BATCH 5.2 - EXAMES LABORATORIAIS PARTE 2 (Items 1-15)
-- ============================================================================

-- Item 1: Cilindros Patológicos
UPDATE score_items
SET
  clinical_relevance = 'Cilindros patológicos são estruturas formadas nos túbulos renais que indicam lesão renal significativa. Incluem cilindros hemáticos (lesão glomerular ou tubular com hematúria), cilindros leucocitários (inflamação renal como pielonefrite ou nefrite intersticial), cilindros granulosos (degradação celular, indicando lesão tubular avançada) e cilindros céreos (estágio final de degeneração, sugerindo insuficiência renal crônica). A presença desses cilindros diferencia lesão renal parenquimatosa de causas pré-renais ou pós-renais de disfunção. Na medicina funcional, mesmo raros cilindros patológicos justificam investigação aprofundada da função renal, status inflamatório sistêmico, autoimunidade e exposição a nefrotóxicos. A ausência é o valor ótimo. Cilindros hemáticos sugerem glomerulonefrite, vasculite ou trauma renal. Leucocitários indicam pielonefrite, nefrite intersticial (frequentemente medicamentosa) ou doença autoimune. Granulosos aparecem em necrose tubular aguda, doença renal crônica ou proteinúria severa. Céreos são marcadores de estase tubular prolongada e prognóstico reservado.',

  patient_explanation = 'Cilindros patológicos são "moldes" microscópicos formados dentro dos rins que aparecem na urina quando há lesão renal ativa. Diferentes tipos indicam diferentes problemas: cilindros com sangue (sangramento renal), com células brancas (infecção ou inflamação renal), granulosos (lesão dos túbulos renais) ou céreos (lesão avançada e crônica). O normal é não ter nenhum cilindro patológico na urina. A presença deles indica que os rins estão sob estresse significativo e requerem investigação imediata. Não confundir com cilindros hialinos, que podem aparecer em pequena quantidade em pessoas saudáveis. Cilindros patológicos sempre exigem avaliação médica para identificar e tratar a causa da lesão renal antes que ocorra dano permanente.',

  conduct = 'Solicitar em: suspeita de doença renal, hematúria, proteinúria, elevação de creatinina, oligúria, edema inexplicado, hipertensão de início recente, uso de medicamentos nefrotóxicos, doenças autoimunes. Interpretação: AUSÊNCIA é o valor ótimo. PRESENÇA de qualquer cilindro patológico indica lesão renal ativa e requer investigação imediata. Investigação complementar: ureia, creatinina, TFG, proteinúria 24h, relação proteína/creatinina urinária, ultrassom renal, perfil autoimune (ANA, anti-DNA, ANCA), complemento (C3, C4). Considerar biópsia renal conforme contexto clínico. Intervenções: identificar e remover causa (medicamentos nefrotóxicos, infecções, agentes tóxicos), tratar doença de base, hidratação adequada, evitar AINEs e contraste iodado. Monitoramento: semanal inicialmente até resolução, depois mensal por 3-6 meses.',

  updated_at = NOW()
WHERE id = '83d713f2-4b20-43fe-8b7e-c3dea08a3cb1';

-- Item 2: VHS (ESR)
UPDATE score_items
SET
  clinical_relevance = 'A Velocidade de Hemossedimentação (VHS ou ESR) mede indiretamente proteínas de fase aguda, especialmente fibrinogênio. Valores normais: homens <15mm/h (até 20mm/h após 50 anos), mulheres <20mm/h (até 30mm/h após 50 anos). Apesar de inespecífico, VHS elevado indica inflamação sistêmica, infecção, malignidade ou doenças autoimunes. Na medicina funcional, valores no terço superior da normalidade (10-15mm/h) já sugerem inflamação subclínica que merece investigação. Causas de elevação: infecções bacterianas, doenças autoimunes (artrite reumatoide, LES, vasculites), neoplasias (especialmente mieloma múltiplo e linfomas), anemia, gravidez, obesidade, idade avançada. VHS muito elevado (>100mm/h) sugere mieloma, abscesso, osteomielite, endocardite ou vasculite sistêmica. Valores baixos (<2mm/h) podem ocorrer em policitemia, insuficiência cardíaca grave ou uso de corticoides. VHS complementa PCR: VHS reflete inflamação crônica e fibrinogênio, enquanto PCR responde mais rapidamente a inflamação aguda.',

  patient_explanation = 'O VHS mede a velocidade com que os glóbulos vermelhos "caem" em um tubo de sangue. Quando há inflamação no corpo, certas proteínas fazem os glóbulos caírem mais rápido. Valores normais são até 15mm/h para homens e 20mm/h para mulheres (pode aumentar um pouco com a idade). Valores elevados indicam que há algum processo inflamatório, infecção, doença autoimune ou até câncer no organismo. Não é um exame específico, mas é útil para detectar inflamação e monitorar tratamentos. Valores muito altos (acima de 100) geralmente indicam problemas sérios que precisam de investigação urgente. Valores no limite superior mesmo dentro da faixa normal podem sugerir inflamação leve que pode se beneficiar de mudanças no estilo de vida.',

  conduct = 'Solicitar em: sintomas inespecíficos (fadiga, febre, perda de peso), suspeita de doença autoimune, monitoramento de artrite reumatoide ou polimialgia reumática, rastreio de neoplasias hematológicas, avaliação de resposta terapêutica. Interpretação: ÓTIMO <5mm/h | BOM 5-10mm/h | ACEITÁVEL 10-20mm/h (mulheres) ou 10-15mm/h (homens) | ELEVADO >20mm/h (mulheres) ou >15mm/h (homens) | MUITO ELEVADO >100mm/h. Investigação complementar: PCR ultrassensível, hemograma completo, eletroforese de proteínas, ferritina, perfil autoimune (FR, ANA), função renal, função hepática. Se VHS >100: considerar mieloma múltiplo (eletroforese, dosagem de imunoglobulinas), neoplasias, infecções graves. Intervenções: tratar causa de base, dieta anti-inflamatória, ômega-3, cúrcuma, controle de peso. Monitoramento: mensal durante tratamento de condições inflamatórias.',

  updated_at = NOW()
WHERE id = 'ea2ca5b5-3040-42aa-9b59-c2fb66f7d841';

-- Item 3: Gasometria venosa
UPDATE score_items
SET
  clinical_relevance = 'A gasometria venosa avalia equilíbrio ácido-base, ventilação e oxigenação tecidual através de pH, pCO2, pO2, HCO3, BE (excesso de base) e saturação de O2. Valores venosos normais: pH 7,32-7,42, pCO2 40-50mmHg, pO2 30-50mmHg, HCO3 22-28mEq/L, BE -2 a +2. Diferencia-se da gasometria arterial por refletir metabolismo tecidual. Identifica acidose metabólica (diabetes, insuficiência renal, cetoacidose, acidose lática), alcalose metabólica (vômitos, diuréticos), acidose respiratória (DPOC, hipoventilação) ou alcalose respiratória (hiperventilação, ansiedade). Na medicina funcional, desvios sutis do pH (7,35-7,38 em acidose leve) correlacionam-se com fadiga crônica, disfunção mitocondrial e inflamação. Lactato venoso elevado sugere hipóxia tecidual, sepse ou disfunção mitocondrial. O gap aniônico [(Na+K)-(Cl+HCO3)] diferencia causas de acidose metabólica: gap aumentado sugere cetoacidose, acidose láctica ou intoxicações; gap normal sugere perda de bicarbonato (diarreia, acidose tubular renal).',

  patient_explanation = 'A gasometria venosa analisa o equilíbrio químico do sangue, especialmente ácidos e bases (pH), gás carbônico (CO2) e bicarbonato. O pH normal do sangue fica entre 7,32 e 7,42 - qualquer desvio pode causar sintomas sérios. Acidose (pH baixo) pode ocorrer em diabetes descompensado, insuficiência renal ou problemas respiratórios graves. Alcalose (pH alto) pode ocorrer em vômitos excessivos ou hiperventilação. O exame também mede o lactato, que se eleva quando os tecidos não recebem oxigênio suficiente. É fundamental para diagnosticar distúrbios metabólicos, avaliar função renal e detectar condições potencialmente graves como cetoacidose diabética ou sepse. Desequilíbrios sutis podem explicar fadiga crônica ou mal-estar persistente.',

  conduct = 'Solicitar em: suspeita de distúrbio ácido-base, diabetes descompensado (cetoacidose), insuficiência renal crônica, diarreia grave, vômitos persistentes, uso de diuréticos, DPOC, fadiga inexplicada, sepse, intoxicações. Interpretação: pH 7,35-7,42 ÓTIMO | pH 7,32-7,35 ou 7,42-7,45 MONITORAR | pH <7,32 ou >7,45 INTERVENÇÃO URGENTE. Investigação complementar: eletrólitos (Na, K, Cl), ureia, creatinina, glicose, cetonas (se diabetes), lactato, gap aniônico. Se acidose metabólica: investigar cetoacidose (cetonas, glicose), acidose láctica (lactato, função hepática), insuficiência renal (ureia, creatinina) ou perda de bicarbonato (diarreia, acidose tubular renal). Intervenções: corrigir causa de base, hidratação, reposição de bicarbonato se pH <7,2, ajustar medicamentos (diuréticos, metformina). Monitoramento: de acordo com gravidade, pode ser horário em emergências ou semanal em condições crônicas.',

  updated_at = NOW()
WHERE id = 'ad64ed10-2cc6-44c7-8d29-d4ff9ac75fa9';

-- Item 4: Cilindros Hialinos
UPDATE score_items
SET
  clinical_relevance = 'Cilindros hialinos são compostos primariamente pela proteína de Tamm-Horsfall secretada pelos túbulos renais. Diferentemente dos cilindros patológicos, cilindros hialinos podem aparecer em pequena quantidade em indivíduos saudáveis (0-2 por campo), especialmente após exercício intenso, desidratação ou concentração urinária. Valores de referência: 0-5 por campo de baixa potência. Acima de 5/campo ou associados a proteinúria, sugerem disfunção renal leve, doença glomerular inicial ou estresse renal. Na medicina funcional, cilindros hialinos isolados e ocasionais não são preocupantes, mas quantidades aumentadas (>10/campo) justificam investigação de proteinúria, função renal e hidratação. Causas de aumento: desidratação, exercício intenso, febre, uso de diuréticos, insuficiência cardíaca congestiva, doença renal crônica inicial, hipertensão não controlada. Contexto clínico é essencial: cilindros hialinos isolados após exercício ou desidratação são benignos; se persistentes ou acompanhados de proteinúria, edema ou hipertensão, indicam lesão renal.',

  patient_explanation = 'Cilindros hialinos são estruturas microscópicas normais que podem aparecer na urina em pequena quantidade, especialmente após exercícios intensos ou quando você está desidratado. Eles são formados por uma proteína natural dos rins chamada proteína de Tamm-Horsfall. Até 5 cilindros por campo microscópico é considerado normal. Quantidades maiores podem indicar que os rins estão sob algum estresse, mas geralmente não é grave. Diferente dos cilindros patológicos (que sempre indicam problema sério), cilindros hialinos em excesso podem aparecer em situações benignas como desidratação, febre ou após exercício muito intenso. No entanto, se aparecem em grandes quantidades de forma persistente, especialmente junto com proteína na urina, podem indicar doença renal inicial e merecem investigação.',

  conduct = 'Solicitar em: rastreio de rotina com urina tipo I, suspeita de doença renal, proteinúria, hipertensão, diabetes, uso de diuréticos, pós-exercício intenso. Interpretação: 0-5/campo NORMAL | 5-10/campo MONITORAR (repetir em 2-4 semanas, avaliar hidratação) | >10/campo INVESTIGAR (função renal, proteinúria). Investigação complementar: proteinúria 24h ou relação proteína/creatinina urinária, ureia, creatinina, TFG, densidade urinária, sódio e potássio urinários. Avaliar contexto: hidratação, uso de medicamentos, prática de exercício intenso recente. Se persistente >10/campo: ultrassom renal, microalbuminúria. Intervenções: para cilindros hialinos isolados sem proteinúria - garantir hidratação adequada (2-3L água/dia), evitar exercício extenuante antes do exame, controlar hipertensão e diabetes se presentes. Se associados a proteinúria: investigar causa renal de base. Monitoramento: repetir urina I em 1-3 meses se valores borderline.',

  updated_at = NOW()
WHERE id = '05eeba4a-6e52-45bd-a7d7-9393c65ca901';

-- Item 5: Gama Globulina
UPDATE score_items
SET
  clinical_relevance = 'As gama globulinas representam primariamente imunoglobulinas (IgG, IgA, IgM) na eletroforese de proteínas. Valores normais: 0,7-1,6 g/dL (11-20% das proteínas totais). Elevação indica produção aumentada de anticorpos por infecção crônica, doença autoimune, hepatopatia ou gamopatia monoclonal. Na medicina funcional, valores no limite superior (>1,4 g/dL) sugerem ativação imune crônica que merece investigação. Causas de elevação: infecções crônicas (HIV, hepatite C, tuberculose), doenças autoimunes (LES, artrite reumatoide, síndrome de Sjögren), hepatopatia crônica (cirrose - padrão de ponte beta-gama), mieloma múltiplo ou gamopatias monoclonais, sarcoidose. Hipogamaglobulinemia (<0,7 g/dL) sugere imunodeficiência primária ou secundária (desnutrição, síndrome nefrótica, linfomas). Padrão policlonal (aumento difuso) sugere inflamação crônica ou autoimunidade; padrão monoclonal (pico em banda estreita) sugere mieloma múltiplo ou gamopatia monoclonal de significado indeterminado (MGUS). Avaliação complementar com imunofixação é essencial se pico monoclonal detectado.',

  patient_explanation = 'Gama globulinas são principalmente anticorpos (imunoglobulinas) que o corpo produz para combater infecções e substâncias estranhas. O valor normal fica entre 0,7 e 1,6 g/dL. Valores elevados geralmente indicam que o sistema imunológico está muito ativo, seja por infecção crônica, doença autoimune (quando o corpo ataca a si mesmo) ou problemas do fígado. Valores muito baixos indicam que você está produzindo poucos anticorpos, deixando o corpo vulnerável a infecções. Quando o aumento aparece como um "pico" estreito no exame, pode indicar mieloma múltiplo (tipo de câncer do sangue) e requer investigação urgente. Quando o aumento é difuso, geralmente indica inflamação crônica ou autoimunidade. O exame é parte da eletroforese de proteínas e ajuda a detectar problemas imunológicos importantes.',

  conduct = 'Solicitar em: eletroforese de proteínas de rotina, suspeita de mieloma múltiplo, doenças autoimunes, infecções crônicas, hepatopatia crônica, investigação de gamopatias, imunodeficiências. Interpretação: ÓTIMO 0,8-1,2 g/dL | BOM 0,7-0,8 ou 1,2-1,4 g/dL | MONITORAR 1,4-1,6 g/dL ou 0,6-0,7 g/dL | INVESTIGAR >1,6 g/dL ou <0,6 g/dL. Investigação complementar: se elevado - imunofixação (descartar pico monoclonal), dosagem de IgG/IgA/IgM, PCR, VHS, perfil autoimune (ANA, FR), sorologias (HIV, hepatites, CMV, EBV), função hepática. Se pico monoclonal: dosagem de cadeias leves livres, biópsia de medula óssea, radiografia de esqueleto. Se baixo: dosagem quantitativa de imunoglobulinas, avaliar desnutrição, síndrome nefrótica (proteinúria), linfomas. Intervenções: tratar causa de base, suporte nutricional se deficiência proteica. Monitoramento: se elevado - repetir em 3-6 meses com imunofixação; se MGUS ou mieloma - protocolo oncológico específico.',

  updated_at = NOW()
WHERE id = '494a5b20-409f-4184-a354-fcea20db326f';

-- Item 6: Hemoglobina glicada (HbA1c)
UPDATE score_items
SET
  clinical_relevance = 'A hemoglobina glicada (HbA1c) reflete a média glicêmica dos últimos 2-3 meses através da glicosilação não enzimática da hemoglobina. Valores diagnósticos: <5,7% normal, 5,7-6,4% pré-diabetes, ≥6,5% diabetes. Na medicina funcional, valores ótimos são <5,3%, refletindo euglicemia verdadeira e sensibilidade insulínica preservada. HbA1c entre 5,3-5,6% já indica risco aumentado de progressão para diabetes e merece intervenção preventiva. Correlaciona-se com complicações microvasculares: cada 1% de aumento eleva risco de retinopatia, nefropatia e neuropatia em 30-40%. Meta terapêutica em diabéticos: <7% (individualizar conforme idade, comorbidades e risco de hipoglicemia). Valores <5% podem indicar hipoglicemias frequentes, anemia hemolítica ou hemoglobinopatias (resultados falsamente baixos). Limitações: anemias, hemoglobinopatias, transfusões recentes, uremia e suplementação de ferro podem alterar resultados. Nesses casos, usar frutosamina ou glicose média estimada (GME). HbA1c é superior à glicemia de jejum para rastreio pois captura variabilidade glicêmica.',

  patient_explanation = 'A hemoglobina glicada mostra qual foi a média do seu açúcar no sangue nos últimos 2-3 meses. É como uma "nota média" do controle do diabetes. Valores ideais são abaixo de 5,3%. Entre 5,7% e 6,4% indica pré-diabetes (alto risco de desenvolver diabetes). Acima de 6,5% confirma diabetes. Cada 1% de aumento representa cerca de 30 mg/dL a mais de glicose média. O objetivo para quem tem diabetes é manter abaixo de 7% para prevenir complicações nos olhos, rins e nervos. Diferente da glicemia de jejum que mostra apenas um momento, a hemoglobina glicada mostra o controle ao longo do tempo, sendo muito mais útil. É o exame mais importante para diagnosticar e monitorar diabetes. Valores muito baixos (<5%) podem indicar episódios de açúcar baixo no sangue (hipoglicemia) ou problemas com hemoglobina.',

  conduct = 'Solicitar em: rastreio de diabetes (adultos >35 anos ou qualquer idade com fatores de risco), diagnóstico de diabetes, monitoramento de controle glicêmico (trimestral em diabéticos), síndrome metabólica, obesidade, história familiar de diabetes. Interpretação: ÓTIMO <5,3% | BOM 5,3-5,6% | PRÉ-DIABETES 5,7-6,4% | DIABETES ≥6,5% | META EM DIABÉTICOS <7% (individualizar). Investigação complementar: glicemia de jejum, TOTG (teste oral de tolerância à glicose), insulina basal, HOMA-IR, peptídeo C, perfil lipídico, microalbuminúria, função renal. Em valores limítrofes ou discordantes: considerar glicemia média estimada, frutosamina, monitoramento contínuo de glicose. Intervenções: HbA1c 5,3-5,6% - dieta baixo IG, exercícios, perda de peso; 5,7-6,4% - intervenção intensiva de estilo de vida, considerar metformina; ≥6,5% - tratamento farmacológico conforme protocolo. Monitoramento: trimestral em diabéticos, anual em pré-diabéticos, a cada 3-5 anos em indivíduos sem fatores de risco.',

  updated_at = NOW()
WHERE id = '660be9ac-31cd-4255-a15a-f049c099b68b';

-- Item 7: Vitamina A (Retinol)
UPDATE score_items
SET
  clinical_relevance = 'A vitamina A sérica (retinol) reflete reservas hepáticas moderadas a graves, mas não detecta deficiência subclínica. Valores normais: 30-80 mcg/dL (1,05-2,8 mcmol/L). Valores ótimos funcionais: 50-70 mcg/dL. A vitamina A é essencial para visão (rodopsina), função imune (diferenciação de linfócitos T e B), integridade epitelial, reprodução e expressão gênica. Deficiência (<30 mcg/dL) manifesta-se com xeroftalmia, cegueira noturna, hiperqueratose folicular, suscetibilidade a infecções respiratórias e gastrointestinais, crescimento inadequado em crianças. Deficiência subclínica (30-40 mcg/dL) cursa com imunidade reduzida e cicatrização lenta. Toxicidade (>100 mcg/dL) causa hepatotoxicidade, descamação cutânea, alopecia, cefaleia, náuseas e teratogenicidade. Causas de deficiência: má absorção (doença celíaca, Crohn, pancreatite crônica, cirurgia bariátrica), ingestão inadequada (dieta pobre em retinoides e carotenoides), alcoolismo (depleção hepática), hipertireoidismo. Suplementação: 3.000-10.000 UI/dia em deficiência (cuidado com gestantes - máximo 5.000 UI/dia).',

  patient_explanation = 'A vitamina A é essencial para a visão (especialmente à noite), sistema imunológico forte, pele saudável e proteção das mucosas. A forma ativa é encontrada em alimentos de origem animal (fígado, ovos, laticínios) e o corpo também pode converter betacaroteno de vegetais laranjas e verdes em vitamina A. Valores normais ficam entre 30-80 mcg/dL, sendo ideal entre 50-70. Deficiência causa cegueira noturna, pele seca e escamosa, infecções frequentes e cicatrização lenta. Excesso (acima de 100) pode causar problemas no fígado, queda de cabelo e dor de cabeça. Gestantes devem ter cuidado especial pois doses muito altas podem causar problemas no bebê. Pessoas com problemas de absorção intestinal (doença celíaca, Crohn) ou cirurgia bariátrica têm maior risco de deficiência.',

  conduct = 'Solicitar em: cegueira noturna, xeroftalmia, hiperqueratose folicular, infecções recorrentes, má absorção intestinal, doença hepática crônica, alcoolismo, pós-cirurgia bariátrica, desnutrição, monitoramento de suplementação. Interpretação: DEFICIÊNCIA GRAVE <20 mcg/dL | DEFICIÊNCIA 20-30 mcg/dL | SUBÓTIMO 30-40 mcg/dL | ADEQUADO 40-50 mcg/dL | ÓTIMO 50-70 mcg/dL | ALTO 70-100 mcg/dL | TÓXICO >100 mcg/dL. Investigação complementar: betacaroteno sérico, RBP (proteína ligadora de retinol), zinco (cofator), função hepática, testes de má absorção (anticorpos celíacos, elastase fecal), função tireoidiana. Intervenções: deficiência - suplementar 10.000-25.000 UI/dia por 1-2 meses (gestantes máximo 5.000 UI), aumentar consumo de fígado, ovos, laticínios, vegetais laranja/verde escuro. Corrigir má absorção se presente. Reavaliar zinco. Monitoramento: repetir dosagem após 2-3 meses de suplementação, depois semestral até normalização.',

  updated_at = NOW()
WHERE id = '5ac10c74-8a52-4121-86c6-50e1f41ac809';

-- Item 8: Colesterol Total
UPDATE score_items
SET
  clinical_relevance = 'O colesterol total representa a soma de HDL, LDL e VLDL (triglicerídeos/5). Valores de referência tradicionais: desejável <200 mg/dL, limítrofe 200-239 mg/dL, alto ≥240 mg/dL. Na medicina funcional, a interpretação é contextualizada: colesterol total isolado tem valor limitado - mais importante avaliar frações (LDL, HDL, não-HDL), partículas (LDL pequeno e denso), apolipoproteínas (Apo B, Apo A1), triglicerídeos e marcadores inflamatórios (PCR-us). Valores muito baixos (<160 mg/dL) correlacionam-se com maior mortalidade (depressão, hemorragia cerebral, câncer), deficiência de hormônios esteroides e função imune comprometida. Valores ótimos funcionais: 180-220 mg/dL com HDL >60, LDL <100 e TG <100. Colesterol elevado com HDL alto e triglicerídeos baixos (padrão A) tem baixo risco cardiovascular. Colesterol moderado com HDL baixo e TG alto (padrão B) tem alto risco. Causas de elevação: dieta rica em gorduras saturadas/trans, hipotireoidismo, síndrome nefrótica, colestase, diabetes, genética (hipercolesterolemia familiar).',

  patient_explanation = 'O colesterol total é a soma de todos os tipos de colesterol no sangue: o "bom" (HDL), o "ruim" (LDL) e os triglicerídeos divididos por 5. Valores tradicionais consideram ideal abaixo de 200 mg/dL, mas essa visão está desatualizada. Mais importante que o valor total é analisar as frações: ter HDL alto (acima de 60) protege o coração mesmo com colesterol total mais alto. Ter triglicerídeos baixos (abaixo de 100) também é protetor. Por outro lado, colesterol total "normal" com HDL baixo e triglicerídeos altos indica risco cardiovascular alto. Valores muito baixos (abaixo de 160) não são saudáveis - podem aumentar risco de depressão, derrame hemorrágico e problemas hormonais, pois colesterol é matéria-prima para hormônios importantes. O ideal é ter colesterol total entre 180-220 com boas proporções das frações.',

  conduct = 'Solicitar em: rastreio cardiovascular (adultos >20 anos), diabetes, hipertensão, obesidade, história familiar de doença cardíaca precoce, síndrome metabólica, monitoramento de terapia hipolipemiante. Interpretação: BAIXO <160 mg/dL (investigar) | ÓTIMO 180-220 mg/dL (com HDL >60, TG <100) | ACEITÁVEL 200-240 mg/dL (analisar frações) | ELEVADO >240 mg/dL. Investigação complementar: ESSENCIAL - perfil lipídico completo (HDL, LDL, VLDL, triglicerídeos, não-HDL, razão CT/HDL, razão TG/HDL), glicemia, HbA1c, TSH, função renal e hepática. AVANÇADO - LDL oxidado, Apo B, Apo A1, Lp(a), partículas de LDL (sdLDL), PCR-us, homocisteína. Intervenções: se baixo - investigar deficiências nutricionais, hipotireoidismo, má absorção; aumentar gorduras saudáveis. Se elevado - dieta mediterrânea, reduzir carboidratos refinados, ômega-3, fitosteróis, exercícios aeróbicos. Estatinas se LDL >190 ou risco cardiovascular alto. Monitoramento: anual em baixo risco, trimestral se em tratamento.',

  updated_at = NOW()
WHERE id = '498a8637-8bf5-45e0-891b-a0c51a47ccc1';

-- Item 9: Hemoglobina - Mulheres
UPDATE score_items
SET
  clinical_relevance = 'Hemoglobina é a proteína transportadora de oxigênio nos eritrócitos. Valores normais para mulheres: 12,0-16,0 g/dL (pode variar levemente entre laboratórios). Valores ótimos funcionais: 13,5-15,0 g/dL, refletindo oxigenação tecidual ideal, reservas de ferro adequadas e eritropoiese saudável. Anemia (<12,0 g/dL) compromete transporte de oxigênio causando fadiga, dispneia, palpitações, palidez, prejuízo cognitivo e redução de performance. Causas: deficiência de ferro (mais comum em mulheres - menstruação, gestação, má absorção), deficiência de B12/folato, anemia de doença crônica, hemólise, sangramento oculto, insuficiência renal (deficiência de eritropoietina), hipotireoidismo. Valores limítrofes (12,0-12,5 g/dL) já cursam com fadiga subclínica e merecem investigação. Policitemia (>16,0 g/dL) pode ser primária (policitemia vera) ou secundária (hipóxia crônica, apneia do sono, tabagismo, altitudes elevadas, doença pulmonar). Gestantes têm valores fisiologicamente mais baixos (>11,0 g/dL) devido à hemodiluição.',

  patient_explanation = 'A hemoglobina é a proteína dentro dos glóbulos vermelhos que carrega oxigênio dos pulmões para todo o corpo. Valores normais para mulheres ficam entre 12,0 e 16,0 g/dL, sendo ideal entre 13,5 e 15,0. Valores baixos (anemia) causam cansaço intenso, falta de ar, coração acelerado, palidez, unhas quebradiças, queda de cabelo e dificuldade de concentração. As causas mais comuns em mulheres são falta de ferro (por menstruação abundante, dieta pobre ou problemas de absorção), falta de vitamina B12 ou ácido fólico, sangramentos invisíveis (estômago, intestino) ou doenças crônicas. Valores muito altos (acima de 16) podem indicar desidratação, apneia do sono não tratada, doença pulmonar ou, raramente, policitemia vera (doença da medula óssea). Gestantes naturalmente têm valores um pouco mais baixos devido à diluição do sangue.',

  conduct = 'Solicitar em: rastreio de rotina (hemograma), fadiga, palidez, dispneia, palpitações, menstruação abundante, gestação, doação de sangue frequente, vegetarianismo/veganismo, doença crônica, insuficiência renal, monitoramento de tratamento de anemia. Interpretação: ANEMIA GRAVE <10,0 g/dL | ANEMIA MODERADA 10,0-11,5 g/dL | ANEMIA LEVE 11,5-12,0 g/dL | SUBÓTIMO 12,0-12,5 g/dL | ADEQUADO 12,5-13,5 g/dL | ÓTIMO 13,5-15,0 g/dL | ALTO 15,0-16,0 g/dL | POLICITEMIA >16,0 g/dL. Investigação complementar: hemograma completo (VCM, HCM, RDW), ferritina, ferro sérico, saturação de transferrina, vitamina B12, ácido fólico, reticulócitos, bilirrubinas (hemólise), função renal, TSH, pesquisa de sangue oculto nas fezes. Intervenções: anemia ferropriva - sulfato ferroso 200mg 2-3x/dia, vitamina C para absorção; B12/folato se deficientes; investigar sangramento; tratar causa de base. Monitoramento: mensal durante reposição, depois trimestral.',

  updated_at = NOW()
WHERE id = 'bdd1777f-2da3-4c20-879e-21446040170e';

-- Item 10: Vitamina B2 (Riboflavina) por HPLC em sangue total
UPDATE score_items
SET
  clinical_relevance = 'A vitamina B2 (riboflavina) medida por HPLC em sangue total é o padrão-ouro para avaliar status de riboflavina, superior à medida em plasma ou urina. Valores de referência: 5-15 mcg/L (pode variar entre laboratórios). Valores ótimos funcionais: 10-15 mcg/L. A riboflavina é cofator essencial das flavoproteínas (FAD e FMN) envolvidas em metabolismo energético mitocondrial (cadeia respiratória), metabolismo de homocisteína (MTHFR), antioxidação (glutationa redutase), metabolismo de outras vitaminas (B6, folato, niacina) e síntese de neurotransmissores. Deficiência (<5 mcg/L) causa glossite, queilite angular, dermatite seborreica, fotofobia, anemia normocítica e, em casos graves, catarata. Deficiência subclínica (5-8 mcg/L) associa-se a fadiga, enxaqueca (B2 reduz frequência de crises), disfunção mitocondrial, homocisteína elevada e prejuízo cognitivo. Causas de deficiência: ingestão inadequada (dieta pobre em laticínios, carnes, ovos), alcoolismo, má absorção, hipotireoidismo, uso de antidepressivos tricíclicos. Polimorfismo MTHFR aumenta necessidade de B2.',

  patient_explanation = 'A vitamina B2 (riboflavina) é essencial para produção de energia nas células, metabolismo de outras vitaminas do complexo B, proteção antioxidante e saúde dos olhos, pele e sistema nervoso. É encontrada em laticínios, carnes, ovos, vegetais verde-escuros e grãos integrais. Valores normais ficam entre 5-15 mcg/L, sendo ideal entre 10-15. A deficiência causa feridas nos cantos da boca, língua avermelhada e dolorida, pele oleosa e descamativa no rosto, sensibilidade excessiva à luz, fadiga e anemia. Níveis baixos também estão relacionados a enxaquecas frequentes - suplementação de B2 pode reduzir crises em até 50%. Pessoas com mutação no gene MTHFR (comum) precisam de mais B2. Vegetarianos estritos, pessoas com má absorção intestinal e alcoólatras têm maior risco de deficiência. A dosagem no sangue total é mais precisa que no plasma.',

  conduct = 'Solicitar em: enxaqueca crônica, fadiga inexplicada, lesões em boca e lábios (queilite angular, glossite), dermatite seborreica, fotofobia, anemia não responsiva a ferro/B12, polimorfismo MTHFR, má absorção intestinal, alcoolismo, vegetarianismo estrito, avaliação mitocondrial. Interpretação: DEFICIÊNCIA <5 mcg/L | SUBÓTIMO 5-8 mcg/L | ADEQUADO 8-10 mcg/L | ÓTIMO 10-15 mcg/L | ALTO >15 mcg/L (geralmente por suplementação - sem toxicidade conhecida). Investigação complementar: outras vitaminas B (B1, B6, B12, folato), homocisteína (cofator MTHFR), atividade de glutationa redutase eritrocitária (funcional para B2), função tireoidiana, marcadores de má absorção. Intervenções: deficiência - suplementar 100-400mg/dia (enxaqueca: 400mg/dia), aumentar laticínios, carnes, ovos, vegetais verde-escuros. Corrigir má absorção se presente. Reavaliar após 2-3 meses. Monitoramento: repetir após 8-12 semanas de suplementação, depois semestral.',

  updated_at = NOW()
WHERE id = 'dd0ea5f8-2bde-488b-ad37-d52a00b0e594';

-- Item 11: Vitamina C (Ácido Ascórbico)
UPDATE score_items
SET
  clinical_relevance = 'A vitamina C plasmática reflete ingestão recente, enquanto níveis leucocitários refletem reservas teciduais (método preferencial quando disponível). Valores plasmáticos normais: 0,6-2,0 mg/dL. Valores ótimos funcionais: 1,0-1,5 mg/dL. A vitamina C é cofator essencial para síntese de colágeno (hidroxilação de prolina e lisina), carnitina (metabolismo energético), neurotransmissores (dopamina, norepinefrina), hormônios peptídicos e esteroides. É o principal antioxidante hidrossolúvel plasmático, regenera vitamina E, melhora absorção de ferro não-heme e modula função imune. Deficiência (<0,2 mg/dL) causa escorbuto: sangramento gengival, petéquias, equimoses, cicatrização deficiente, hiperqueratose folicular, anemia, fadiga extrema e, em casos graves, hemorragias. Deficiência subclínica (0,2-0,6 mg/dL) cursa com fadiga, infecções recorrentes, cicatrização lenta, gengivite e capilares frágeis. Tabagismo depleta vitamina C (necessidade 35mg/dia maior). Necessidades aumentadas: estresse, infecções, cirurgias, gestação, lactação. Doses altas (>2g/dia) podem causar diarreia osmótica (dose dependente da tolerância intestinal).',

  patient_explanation = 'A vitamina C é um antioxidante poderoso essencial para produção de colágeno (pele, ossos, vasos sanguíneos), sistema imunológico forte, absorção de ferro, cicatrização de feridas e produção de hormônios e neurotransmissores. É encontrada em frutas cítricas, kiwi, morango, pimentão, brócolis e tomate. Valores normais ficam entre 0,6-2,0 mg/dL, sendo ideal entre 1,0-1,5. Deficiência grave causa escorbuto (doença rara hoje): gengivas sangrando, manchas roxas na pele, feridas que não cicatrizam, dentes amolecidos e cansaço extremo. Deficiência leve causa fadiga, resfriados frequentes, cicatrização lenta, hematomas fáceis e gengivas inflamadas. Fumantes precisam de 35mg/dia a mais porque o cigarro destrói vitamina C. Doses muito altas (acima de 2.000mg/dia) podem causar diarreia. A vitamina C não é armazenada no corpo, então precisamos consumir diariamente.',

  conduct = 'Solicitar em: escorbuto (sangramento gengival, petéquias), cicatrização deficiente, infecções recorrentes, fadiga crônica, tabagismo, má absorção, alcoolismo, dieta pobre em frutas/vegetais, pré/pós-operatório, queimaduras, sepse. Interpretação: DEFICIÊNCIA GRAVE (ESCORBUTO) <0,2 mg/dL | DEFICIÊNCIA 0,2-0,4 mg/dL | SUBÓTIMO 0,4-0,6 mg/dL | ADEQUADO 0,6-1,0 mg/dL | ÓTIMO 1,0-1,5 mg/dL | ALTO 1,5-2,0 mg/dL | MUITO ALTO >2,0 mg/dL (geralmente suplementação). Investigação complementar: hemograma (anemia escorbútica), ferritina e ferro (absorção prejudicada), marcadores inflamatórios, avaliação dental, status de outras vitaminas antioxidantes (E, betacaroteno). Intervenções: deficiência - suplementar 500-1.000mg/dia dividido em 2-3 doses até normalização, aumentar frutas cítricas, kiwi, morango, pimentão, brócolis. Tabagistas: adicionar 35mg/dia. Dose de manutenção: 200-500mg/dia. Monitoramento: repetir após 4-8 semanas, depois semestral. Observar sinais clínicos: melhora de sangramento gengival, cicatrização.',

  updated_at = NOW()
WHERE id = '60bf92ab-6288-4ee8-a6b8-75dff9fa892a';

-- Item 12: Hemoglobina - Homens
UPDATE score_items
SET
  clinical_relevance = 'Hemoglobina em homens tem valores de referência mais elevados que mulheres devido à influência androgênica na eritropoiese. Valores normais: 13,5-17,5 g/dL. Valores ótimos funcionais: 14,5-16,5 g/dL, garantindo oxigenação tecidual adequada, performance física e função cognitiva ideais. Anemia (<13,5 g/dL) em homens sempre requer investigação detalhada pois não há perda menstrual fisiológica. Causas principais: sangramento gastrointestinal oculto (úlcera, câncer colorretal, gastrite por H. pylori, uso de AINEs), deficiência de ferro (dieta, má absorção), deficiência de B12/folato (vegetarianismo, gastrite atrófica, uso de metformina/IBP), anemia de doença crônica (inflamação, infecção, neoplasia), insuficiência renal (deficiência de eritropoietina), hipotireoidismo, hipotestosteronemia, mielodisplasia. Policitemia (>17,5 g/dL) em homens pode ser primária (policitemia vera - mutação JAK2) ou secundária (apneia do sono, DPOC, tabagismo, altitudes elevadas, uso de testosterona exógena, tumores produtores de eritropoietina). Hemoconcentração por desidratação também eleva hemoglobina transitoriamente.',

  patient_explanation = 'A hemoglobina é a proteína que transporta oxigênio no sangue. Valores normais para homens são mais altos que para mulheres (13,5-17,5 g/dL versus 12,0-16,0 g/dL) devido à influência da testosterona na produção de glóbulos vermelhos. O ideal fica entre 14,5-16,5. Valores baixos (anemia) em homens sempre precisam de investigação, pois homens não têm perda menstrual. As principais causas são sangramentos invisíveis no estômago ou intestino (úlcera, pólipos, câncer), falta de ferro ou vitaminas B12/folato na dieta, doenças crônicas, problemas renais ou testosterona baixa. Sintomas incluem fadiga intensa, falta de ar, tontura, palpitações e palidez. Valores altos (acima de 17,5) podem indicar apneia do sono não tratada, doença pulmonar, tabagismo, uso de anabolizantes (testosterona) ou policitemia vera (doença da medula óssea). Valores muito altos aumentam risco de trombose.',

  conduct = 'Solicitar em: hemograma de rotina, fadiga, palidez, dispneia aos esforços, tonturas, palpitações, sangramento gastrointestinal, vegetarianismo, insuficiência renal crônica, doenças crônicas, monitoramento de terapia com testosterona, suspeita de policitemia. Interpretação: ANEMIA GRAVE <10,0 g/dL | ANEMIA MODERADA 10,0-12,0 g/dL | ANEMIA LEVE 12,0-13,5 g/dL | SUBÓTIMO 13,5-14,0 g/dL | ADEQUADO 14,0-14,5 g/dL | ÓTIMO 14,5-16,5 g/dL | ALTO 16,5-17,5 g/dL | POLICITEMIA >17,5 g/dL. Investigação complementar: hemograma completo (VCM, HCM, RDW), ferritina, ferro sérico, saturação de transferrina, vitamina B12, ácido fólico, reticulócitos, pesquisa de sangue oculto nas fezes, endoscopia digestiva alta/colonoscopia (se indicado), função renal, TSH, testosterona total e livre, EPO (eritropoietina) se policitemia, mutação JAK2 (policitemia vera). Intervenções: anemia - investigar e tratar causa, repor ferro/B12/folato conforme necessário; policitemia - flebotomia se Hb >18, investigar apneia do sono, suspender testosterona exógena se aplicável. Monitoramento: mensal em reposição, trimestral em terapia com testosterona.',

  updated_at = NOW()
WHERE id = 'a99ff9aa-b39c-46aa-a042-39537a83eb81';

-- Item 13: Monócitos (absoluto)
UPDATE score_items
SET
  clinical_relevance = 'Monócitos são leucócitos mononucleares que se diferenciam em macrófagos e células dendríticas nos tecidos, desempenhando papel central em imunidade inata, fagocitose, apresentação de antígenos e modulação inflamatória. Valores normais: 200-900 células/mm³ (ou 3-10% dos leucócitos). Valores ótimos funcionais: 300-600 células/mm³. Monocitose (>900/mm³) indica resposta imune ativa: infecções crônicas (tuberculose, endocardite bacteriana subaguda, brucelose, sífilis), doenças autoimunes (LES, artrite reumatoide, sarcoidose), neoplasias hematológicas (leucemia mielomonocítica crônica, CMML, leucemia mieloide aguda - subtipos M4/M5), fase de recuperação de infecções agudas ou neutropenia, doença inflamatória intestinal. Monocitopenia (<200/mm³) é rara, ocorrendo em infecções graves (sepse), terapia imunossupressora, leucemia de células pilosas (hairy cell leukemia) ou deficiência de MonoMAC (síndrome genética). Monócitos persistentemente elevados (>1.000/mm³) requerem investigação hematológica para descartar neoplasias mieloproliferativas. Contexto clínico é essencial para interpretação.',

  patient_explanation = 'Monócitos são células de defesa do sangue que combatem infecções e inflamações. Eles circulam no sangue e, quando necessário, entram nos tecidos e se transformam em macrófagos (células que "engolem" bactérias e células mortas). Valores normais ficam entre 200-900 células por microlitro, sendo ideal entre 300-600. Valores elevados (monocitose) geralmente indicam que o corpo está lutando contra uma infecção crônica (como tuberculose ou endocardite), doença autoimune, inflamação intestinal ou, mais raramente, certos tipos de leucemia. Também aumentam durante a recuperação de infecções agudas. Valores muito baixos são raros e podem indicar infecções muito graves (sepse), uso de medicamentos imunossupressores ou, raramente, tipos específicos de leucemia. Se os monócitos estiverem persistentemente acima de 1.000, é importante investigar com um hematologista para descartar doenças do sangue.',

  conduct = 'Solicitar em: hemograma completo de rotina, suspeita de infecção crônica, febre prolongada, fadiga, perda de peso, sudorese noturna, esplenomegalia, doenças autoimunes, monitoramento de doenças hematológicas. Interpretação: BAIXO <200/mm³ (raro, investigar) | ÓTIMO 300-600/mm³ | ADEQUADO 200-300 ou 600-900/mm³ | ELEVADO 900-1.200/mm³ | MUITO ELEVADO >1.200/mm³ (investigar neoplasia hematológica). Investigação complementar: se elevado - hemograma seriado, VHS, PCR, sorologias (HIV, CMV, EBV, tuberculose), radiografia de tórax, ecocardiograma (endocardite), perfil autoimune, eletroforese de proteínas, considerar biópsia de medula óssea se >1.500/mm³ ou sintomas sistêmicos. Se baixo - descartar sepse, revisar medicamentos, considerar imunodeficiências. Intervenções: tratar causa de base (antibióticos para infecções, imunossupressores para autoimunidade, encaminhamento hematológico se neoplasia). Monitoramento: semanal se monocitose aguda, mensal se crônica até esclarecimento diagnóstico.',

  updated_at = NOW()
WHERE id = '11743f0e-ae60-4f4c-a11e-615de3ab8a72';

-- Item 14: Progesterona - Mulheres Gestação 3º Trimestre
UPDATE score_items
SET
  clinical_relevance = 'A progesterona no terceiro trimestre da gestação atinge seus níveis mais elevados, sendo produzida primariamente pela placenta. Valores esperados: 60-260 ng/mL (pode variar entre laboratórios, alguns relatam até 300 ng/mL). Esses níveis extremamente elevados são essenciais para manutenção da gestação, relaxamento uterino (previne contrações prematuras), maturação cervical, desenvolvimento mamário para lactação, imunotolerância materno-fetal e modulação da resposta inflamatória materna. A progesterona também tem efeitos sistêmicos: relaxamento de musculatura lisa (causando constipação, refluxo, varizes), efeitos sedativos no SNC, termogênese (aumento de temperatura basal) e modulação metabólica (resistência insulínica fisiológica). Valores baixos no terceiro trimestre (<60 ng/mL) podem indicar insuficiência placentária, risco de trabalho de parto prematuro ou restrição de crescimento intrauterino. Não há "valor tóxico" em progesterona gestacional. Após o parto, a queda abrupta de progesterona (e estrogênio) desencadeia a lactogênese e pode contribuir para depressão pós-parto em mulheres suscetíveis.',

  patient_explanation = 'A progesterona é o principal hormônio que mantém a gravidez. No terceiro trimestre (últimos 3 meses), os níveis são extremamente altos (60-260 ng/mL), produzidos pela placenta. Esses níveis elevados são normais e necessários para: manter o útero relaxado e evitar contrações prematuras, preparar as mamas para amamentar, proteger o bebê do sistema imune da mãe e garantir o desenvolvimento completo até o parto. A progesterona alta também causa alguns sintomas típicos da gravidez: intestino preso, azia, sensação de calor, sonolência e varizes. Valores baixos no final da gravidez podem indicar que a placenta não está funcionando bem, risco de parto prematuro ou bebê pequeno para a idade gestacional. Após o parto, a progesterona cai rapidamente, o que "dispara" a produção de leite, mas também pode contribuir para tristeza ou depressão pós-parto em algumas mulheres.',

  conduct = 'Solicitar em: avaliação de insuficiência placentária, história de parto prematuro, restrição de crescimento intrauterino, sangramento no terceiro trimestre, suspeita de sofrimento fetal, gestação de alto risco, pesquisa clínica (raramente solicitado na rotina obstétrica padrão). Interpretação: BAIXO <60 ng/mL (insuficiência placentária, investigar) | ADEQUADO 60-150 ng/mL | ÓTIMO 150-260 ng/mL | MUITO ALTO >260 ng/mL (incomum, mas não patológico). Investigação complementar: ultrassom obstétrico com doppler (avaliar função placentária, crescimento fetal, líquido amniótico), cardiotocografia, estriol livre, perfil biofísico fetal, PAPP-A e beta-hCG se início de gestação. Avaliar comorbidades: diabetes gestacional (TOTG), pré-eclâmpsia (proteinúria, pressão arterial, ácido úrico). Intervenções: se progesterona baixa com evidência de insuficiência placentária - monitoramento fetal intensivo, considerar corticoides para maturação pulmonar fetal se <34 semanas, planejamento de parto antecipado se indicado, repouso relativo. Suplementação de progesterona não tem benefício comprovado no terceiro trimestre. Monitoramento: conforme protocolo obstétrico de alto risco.',

  updated_at = NOW()
WHERE id = '455c00f3-f5f6-47ce-9dd7-307b16846c09';

-- Item 15: Testosterona Livre - Mulheres Pós-Menopausa
UPDATE score_items
SET
  clinical_relevance = 'A testosterona livre representa a fração biologicamente ativa (não ligada a SHBG ou albumina), constituindo 1-3% da testosterona total. Em mulheres pós-menopausa, valores normais: 0,5-8,5 pg/mL (laboratórios variam; alguns usam 0,1-0,85 ng/dL). Valores ótimos funcionais: 3-6 pg/mL. Na pós-menopausa, a produção ovariana de estrogênio cessa, mas ovários e adrenais continuam produzindo androgênios (testosterona, androstenediona, DHEA-S). A testosterona livre em mulheres é crucial para libido, energia, massa muscular, densidade óssea, função cognitiva, humor e bem-estar geral. Deficiência (<1 pg/mL) manifesta-se como perda de libido, fadiga persistente, sarcopenia, osteoporose acelerada, depressão, névoa mental e redução de qualidade de vida. Causas de deficiência: insuficiência adrenal, ooforectomia bilateral, uso de corticoides, hipopituitarismo. Valores elevados (>10 pg/mL) são raros na pós-menopausa natural, sugerindo hiperplasia adrenal, tumor produtor de androgênios ou suplementação exógena. Testosterona livre é preferível à total pois SHBG aumenta com idade e uso de estrogênio oral (TRH).',

  patient_explanation = 'A testosterona livre é a forma ativa do hormônio testosterona que está disponível para o corpo usar. Mesmo mulheres precisam de testosterona (em quantidades menores que homens) para energia, libido, músculos, ossos, memória e bem-estar. Após a menopausa, os valores normais ficam entre 0,5-8,5 pg/mL, sendo ideal entre 3-6. Valores baixos causam falta de desejo sexual, cansaço constante, perda de massa muscular, ossos fracos, depressão e dificuldade de concentração. Isso pode acontecer após retirada dos ovários, insuficiência adrenal ou uso prolongado de corticoides. Valores altos são raros e podem indicar tumores produtores de hormônios ou uso de suplementos hormonais. A testosterona livre é melhor que a total para avaliar mulheres porque a proteína que "prende" a testosterona (SHBG) aumenta com a idade e com terapia hormonal oral, então a testosterona total pode parecer normal mas a livre estar baixa.',

  conduct = 'Solicitar em: perda de libido, fadiga crônica pós-menopausa, sarcopenia, osteoporose, depressão resistente, avaliação pré-terapia de reposição androgênica, monitoramento de TRH (terapia de reposição hormonal), história de ooforectomia bilateral, insuficiência adrenal. Interpretação: MUITO BAIXO <1 pg/mL (sintomático) | BAIXO 1-2 pg/mL | SUBÓTIMO 2-3 pg/mL | ADEQUADO 3-4 pg/mL | ÓTIMO 4-6 pg/mL | ALTO 6-8,5 pg/mL | ELEVADO >8,5 pg/mL (investigar). Investigação complementar: testosterona total, SHBG (sex hormone-binding globulin), DHEA-S, androstenediona, FSH e LH (confirmar pós-menopausa), estradiol, prolactina, cortisol, TSH. Se elevada: 17-OH-progesterona (hiperplasia adrenal), ultrassom pélvico e adrenal. Avaliar densidade óssea (DEXA), composição corporal. Intervenções: se baixa - reposição transdérmica de testosterona (gel 0,5-1% ou creme) 0,5-3mg/dia, monitorar resposta clínica e níveis. Otimizar DHEA-S (precursor). Exercícios resistidos. Monitoramento: dosar testosterona livre/total após 6-8 semanas de terapia, depois trimestral.',

  updated_at = NOW()
WHERE id = '88d773d8-1eea-4abb-b210-e6c71ff27988';

-- Vincular artigos relevantes
INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, s.id
FROM articles a
CROSS JOIN (
  SELECT id FROM score_items WHERE id IN (
    '83d713f2-4b20-43fe-8b7e-c3dea08a3cb1',
    'ea2ca5b5-3040-42aa-9b59-c2fb66f7d841',
    'ad64ed10-2cc6-44c7-8d29-d4ff9ac75fa9',
    '05eeba4a-6e52-45bd-a7d7-9393c65ca901',
    '494a5b20-409f-4184-a354-fcea20db326f',
    '660be9ac-31cd-4255-a15a-f049c099b68b',
    '5ac10c74-8a52-4121-86c6-50e1f41ac809',
    '498a8637-8bf5-45e0-891b-a0c51a47ccc1',
    'bdd1777f-2da3-4c20-879e-21446040170e',
    'dd0ea5f8-2bde-488b-ad37-d52a00b0e594',
    '60bf92ab-6288-4ee8-a6b8-75dff9fa892a',
    'a99ff9aa-b39c-46aa-a042-39537a83eb81',
    '11743f0e-ae60-4f4c-a11e-615de3ab8a72',
    '455c00f3-f5f6-47ce-9dd7-307b16846c09',
    '88d773d8-1eea-4abb-b210-e6c71ff27988'
  )
) s
WHERE a.title ILIKE '%vitamina%'
   OR a.title ILIKE '%bioquímica%'
   OR a.title ILIKE '%hormônio%'
   OR a.title ILIKE '%proteína%'
   OR a.title ILIKE '%inflamação%'
LIMIT 5
ON CONFLICT DO NOTHING;
