-- ============================================================================
-- BATCH 5.2 - EXAMES LABORATORIAIS PARTE 2 (Items 16-30)
-- ============================================================================

-- Item 16: Vitamina B12 (Cobalamina)
UPDATE score_items
SET
  clinical_relevance = 'A vitamina B12 (cobalamina) é essencial para síntese de DNA, mielinização neuronal, eritropoiese e metabolismo da homocisteína (via metionina sintase). Valores de referência tradicionais: 200-900 pg/mL. Na medicina funcional, valores ótimos são >500 pg/mL, pois deficiência subclínica (200-400 pg/mL) já pode causar sintomas neuropsiquiátricos. Deficiência (<200 pg/mL) causa anemia megaloblástica, neuropatia periférica (parestesias, ataxia), mielopatia (degeneração combinada subaguda da medula), declínio cognitivo, demência, depressão, fadiga e glossite. Causas: gastrite atrófica (deficiência de fator intrínseco), anemia perniciosa (autoimune), ressecção gástrica ou ileal, doença de Crohn, uso crônico de metformina ou inibidores de bomba de prótons (IBP), dieta vegana estrita, má absorção (doença celíaca, supercrescimento bacteriano - SIBO). Marcadores mais sensíveis que B12 sérica: ácido metilmalônico (MMA) e homocisteína (elevam-se antes da B12 cair). Valores muito elevados (>1.000 pg/mL) podem ocorrer em doenças mieloproliferativas, hepatopatia ou suplementação.',

  patient_explanation = 'A vitamina B12 é essencial para produção de células vermelhas do sangue, funcionamento do sistema nervoso, produção de DNA e metabolismo de energia. É encontrada apenas em alimentos de origem animal (carnes, peixes, ovos, laticínios). Valores normais ficam entre 200-900 pg/mL, mas o ideal é acima de 500 para evitar sintomas sutis. Deficiência causa anemia, formigamento e dormência nas mãos e pés, dificuldade para caminhar, perda de memória, confusão mental, depressão e cansaço extremo. Veganos estritos, pessoas com gastrite crônica, que fizeram cirurgia do estômago ou intestino, usam metformina (para diabetes) ou omeprazol por muito tempo têm alto risco de deficiência. A deficiência pode levar anos para se desenvolver (fígado armazena B12), mas os danos neurológicos podem ser irreversíveis se não tratados a tempo. Níveis entre 200-400, mesmo sendo "normais", podem causar sintomas e merecem suplementação.',

  conduct = 'Solicitar em: anemia macrocítica (VCM >100), neuropatia periférica, declínio cognitivo, demência, depressão, fadiga inexplicada, veganismo, gastrite atrófica, pós-cirurgia bariátrica, doença de Crohn, uso crônico de metformina ou IBP, idosos (>60 anos - rastreio), gestação (prevenção de defeitos do tubo neural). Interpretação: DEFICIÊNCIA <200 pg/mL | SUBÓTIMO 200-400 pg/mL (tratar se sintomas) | ADEQUADO 400-500 pg/mL | ÓTIMO 500-800 pg/mL | ALTO 800-1.000 pg/mL | MUITO ALTO >1.000 pg/mL. Investigação complementar: hemograma (VCM, anemia macrocítica), homocisteína, ácido metilmalônico (MMA - mais sensível), folato, ferritina, anticorpo anti-fator intrínseco (anemia perniciosa), anticorpo anti-células parietais, gastroscopia (gastrite atrófica), teste para H. pylori. Intervenções: deficiência - cianocobalamina IM 1.000mcg/dia por 1 semana, depois semanal por 1 mês, depois mensal (anemia perniciosa: vitalício); ou metilcobalamina sublingual 1.000-2.000mcg/dia. Veganos: suplementação diária 500-1.000mcg. Monitoramento: repetir B12, homocisteína e MMA após 3 meses.',

  updated_at = NOW()
WHERE id = '545e9a5a-ea8c-4d41-9cef-d6d9e32671c0';

-- Item 17: DHEA-S - Mulheres (50-59 anos)
UPDATE score_items
SET
  clinical_relevance = 'O DHEA-S (deidroepiandrosterona sulfato) é o principal androgênio adrenal em mulheres, servindo como pró-hormônio para testosterona e estrogênio periféricos. Valores para mulheres 50-59 anos: 35-260 mcg/dL (laboratórios variam). Valores ótimos funcionais: 100-180 mcg/dL. O DHEA-S declina progressivamente com a idade (adrenopausa), caindo cerca de 80% dos 20 aos 70 anos. Níveis adequados são importantes para energia, libido, massa muscular, densidade óssea, função imune, humor e bem-estar. Deficiência (<35 mcg/dL) associa-se a fadiga, perda de libido, sarcopenia, osteoporose, depressão, disfunção imune e envelhecimento acelerado. Causas de baixa: insuficiência adrenal (Addison, secundária a hipopituitarismo), uso de corticoides, estresse crônico (burnout adrenal), envelhecimento. Valores elevados (>260 mcg/dL) sugerem hiperplasia adrenal congênita (forma tardia - 21-hidroxilase), síndrome de Cushing, tumor adrenal ou ovariano produtor de androgênios, ou síndrome dos ovários policísticos (SOP, embora DHEA-S seja menos afetado que testosterona na SOP). DHEA-S é o melhor marcador de função adrenal androgênica (estável, pouca variação diurna).',

  patient_explanation = 'O DHEA-S é um hormônio produzido pelas glândulas adrenais (acima dos rins) que o corpo usa para fabricar outros hormônios, incluindo testosterona e estrogênio. É chamado de "hormônio da juventude" porque diminui muito com a idade. Para mulheres entre 50-59 anos, valores normais ficam entre 35-260 mcg/dL, sendo ideal entre 100-180. Níveis baixos causam fadiga persistente, perda de libido, perda de massa muscular, ossos fracos, depressão, infecções frequentes e envelhecimento acelerado. Pode indicar que as adrenais estão fracas (por estresse crônico prolongado, uso de corticoides ou doenças como Addison). Níveis altos podem indicar hiperplasia adrenal (condição genética), tumores produtores de hormônios ou síndrome dos ovários policísticos. O DHEA-S é o melhor exame para avaliar a função adrenal porque é estável ao longo do dia, diferente do cortisol que varia muito.',

  conduct = 'Solicitar em: fadiga crônica, perda de libido, sarcopenia, osteoporose, depressão resistente, avaliação de função adrenal, investigação de hiperandrogenismo (hirsutismo, acne, alopecia androgênica), síndrome dos ovários policísticos, monitoramento de terapia de reposição hormonal, suspeita de insuficiência adrenal. Interpretação: MUITO BAIXO <35 mcg/dL (insuficiência adrenal, investigar) | BAIXO 35-60 mcg/dL | SUBÓTIMO 60-100 mcg/dL | ADEQUADO 100-140 mcg/dL | ÓTIMO 140-180 mcg/dL | ALTO 180-260 mcg/dL | ELEVADO >260 mcg/dL (investigar hiperplasia adrenal, tumor). Investigação complementar: cortisol basal e pós-ACTH (insuficiência adrenal), testosterona total e livre, androstenediona, 17-OH-progesterona (hiperplasia adrenal), ultrassom adrenal (se tumor suspeitado), ACTH. Avaliar eixo tireoidiano (TSH, T3, T4) e glicemia. Intervenções: se baixo - DHEA 25-50mg/dia (mulheres), avaliar suporte adrenal (adaptógenos, vitamina C, magnésio, redução de estresse). Se elevado: investigar causa (hiperplasia adrenal, tumor) antes de intervir. Monitoramento: repetir DHEA-S e testosterona após 6-8 semanas de suplementação, depois semestral. Não suplementar se >180 mcg/dL.',

  updated_at = NOW()
WHERE id = '29bd8bb0-edd0-46d4-90ca-12bef80585a3';

-- Item 18: FSH - Homens
UPDATE score_items
SET
  clinical_relevance = 'O FSH (hormônio folículo-estimulante) em homens estimula as células de Sertoli nos testículos para produção de espermatozoides (espermatogênese). Valores normais: 1,5-12,4 mUI/mL (pode variar entre laboratórios). Valores ótimos funcionais: 2-8 mUI/mL, refletindo função testicular adequada e feedback hipofisário balanceado. FSH elevado (>12,4 mUI/mL) indica hipogonadismo primário (falência testicular): as gônadas não respondem adequadamente ao FSH, então a hipófise produz mais FSH tentando compensar. Causas: síndrome de Klinefelter, orquite viral (caxumba), trauma testicular, quimioterapia/radioterapia, torção testicular, criptorquidia, varicocele severa, azoospermia não-obstrutiva, envelhecimento (andropausa - FSH pode subir moderadamente). FSH baixo (<1,5 mUI/mL) com testosterona baixa indica hipogonadismo secundário (central): disfunção hipofisária ou hipotalâmica. Causas: hipopituitarismo, hiperprolactinemia, uso de esteroides anabolizantes exógenos (supressão do eixo), obesidade, tumores hipofisários. FSH é essencial na investigação de infertilidade masculina: FSH elevado sugere falência primária de produção espermática; FSH normal/baixo com espermatogênese ruim sugere obstrução ou problema central.',

  patient_explanation = 'O FSH é um hormônio produzido pela hipófise (glândula na base do cérebro) que estimula os testículos a produzirem espermatozoides. Valores normais ficam entre 1,5-12,4 mUI/mL, sendo ideal entre 2-8. FSH alto (acima de 12,4) indica que os testículos não estão respondendo bem ao estímulo - a hipófise produz mais FSH tentando compensar. Isso acontece em problemas testiculares como síndrome de Klinefelter, caxumba que afetou os testículos, traumas, quimioterapia ou simplesmente envelhecimento. FSH baixo (abaixo de 1,5) junto com testosterona baixa indica que o problema está na hipófise ou hipotálamo (não está enviando o sinal correto). Isso pode acontecer por uso de anabolizantes, tumores na hipófise, prolactina alta ou obesidade. O FSH é essencial para avaliar infertilidade masculina: se está alto, o problema é nos testículos; se está normal ou baixo com contagem de esperma ruim, pode ser obstrução ou problema hormonal central.',

  conduct = 'Solicitar em: infertilidade masculina, oligozoospermia ou azoospermia, hipogonadismo (testosterona baixa), libido reduzida, disfunção erétil, avaliação pré-vasectomia reversa, suspeita de síndrome de Klinefelter, história de caxumba com orquite, pós-quimioterapia, avaliação de andropausa. Interpretação: BAIXO <1,5 mUI/mL (com testosterona baixa = hipogonadismo central; investigar) | ÓTIMO 2-8 mUI/mL | ADEQUADO 1,5-2 ou 8-12 mUI/mL | ELEVADO 12-20 mUI/mL (hipogonadismo primário leve) | MUITO ELEVADO >20 mUI/mL (hipogonadismo primário grave, falência testicular). Investigação complementar: testosterona total e livre, LH, prolactina, SHBG, espermograma (essencial na infertilidade), estradiol, TSH, cariótipo (se suspeita de Klinefelter - FSH muito alto + testículos pequenos), ultrassom testicular, ressonância de hipófise (se hipogonadismo central). Intervenções: hipogonadismo primário (FSH alto) - reposição de testosterona (gel, injeções), mas atenção: piora a fertilidade; se deseja fertilidade, considerar hCG + FSH recombinante. Hipogonadismo central (FSH baixo) - tratar causa (prolactinoma, suspender esteroides), hCG para estimular testículos. Monitoramento: trimestral durante tratamento.',

  updated_at = NOW()
WHERE id = 'edaf4b36-a22c-4b12-88fc-aa754f7afe7a';

-- Item 19: Bactérias - Sedimento Urinário
UPDATE score_items
SET
  clinical_relevance = 'Bactérias no sedimento urinário (bacteriúria) podem indicar infecção do trato urinário (ITU) ou contaminação da amostra. Valores normais: AUSENTES ou RARAS. A presença significativa é geralmente reportada como "++++" ou "numerosas". Bacteriúria verdadeira (>100.000 UFC/mL em cultura) indica ITU, especialmente se acompanhada de leucocitúria (>10 leucócitos/campo), nitritos positivos e sintomas (disúria, urgência, polaciúria, dor suprapúbica). Na medicina funcional, bacteriúria assintomática (sem sintomas, sem piúria) geralmente não requer tratamento antibiótico, exceto em gestantes e pré-procedimentos urológicos. Contaminação por má técnica de coleta (falta de higiene perineal, coleta de jato médio inadequada) é comum, especialmente em mulheres. Bactérias isoladas sem leucócitos geralmente indicam contaminação e justificam repetição do exame com técnica adequada ou cultura quantitativa. Causas de ITU: E. coli (80-85%), Klebsiella, Proteus, Enterococcus, Staphylococcus saprophyticus. Fatores de risco: sexo feminino, atividade sexual, gestação, diabetes, imunossupressão, cateterismo vesical, obstrução urinária, cálculos renais.',

  patient_explanation = 'Bactérias no exame de urina podem indicar infecção urinária ou simplesmente contaminação na hora da coleta. O normal é não ter bactérias ou apenas raras. Quando aparecem muitas bactérias junto com células de defesa (leucócitos) e sintomas como ardência ao urinar, vontade frequente de urinar e dor no pé da barriga, confirma-se infecção urinária que geralmente precisa de antibiótico. No entanto, se aparecem bactérias isoladas sem leucócitos e sem sintomas, geralmente é contaminação da amostra por não ter limpado bem a região genital antes de coletar ou por não ter colhado o jato médio (primeira parte da urina). Nesse caso, deve-se repetir o exame com técnica correta. Bactérias sem sintomas (bacteriúria assintomática) geralmente não requerem tratamento, exceto em gestantes. Mulheres têm mais infecções urinárias que homens devido à uretra mais curta. Diabetes e imunossupressão aumentam o risco.',

  conduct = 'Solicitar em: urina tipo I de rotina, disúria, polaciúria, urgência urinária, dor suprapúbica, febre, hematúria, gestação (rastreio), pós-operatório urológico, diabetes, cateterismo vesical. Interpretação: AUSENTES ou RARAS = NORMAL | MODERADAS sem leucócitos = PROVÁVEL CONTAMINAÇÃO (repetir) | NUMEROSAS com leucócitos e nitritos = ITU (solicitar urocultura) | NUMEROSAS sem sintomas ou leucócitos = BACTERIÚRIA ASSINTOMÁTICA (geralmente não tratar, exceto gestantes). Investigação complementar: urocultura com antibiograma (padrão-ouro para diagnóstico e escolha de antibiótico), leucócitos no sedimento, nitritos, esterase leucocitária, função renal (se ITU complicada), ultrassom renal e vesical (se ITU recorrente, obstrução, cálculos). Intervenções: ITU sintomática - antibiótico conforme cultura (empírico: nitrofurantoína, cefalexina, fosfomicina dose única). Prevenir recorrências: hidratação adequada (2L/dia), esvaziar bexiga após relações sexuais, cranberry, probióticos vaginais, corrigir constipação. Bacteriúria assintomática em gestantes: tratar. Monitoramento: urocultura de controle 1 semana após término do antibiótico se sintomas persistirem.',

  updated_at = NOW()
WHERE id = '9acbde3f-0792-4ecc-a0f6-1a1c7500b766';

-- Item 20: D-dímero
UPDATE score_items
SET
  clinical_relevance = 'O D-dímero é um produto de degradação da fibrina, marcador de ativação do sistema de coagulação e fibrinólise. Valores normais: <500 ng/mL (ou <0,5 mcg/mL FEU). O D-dímero tem ALTA SENSIBILIDADE mas BAIXA ESPECIFICIDADE para tromboembolismo venoso (TEV): valor normal (<500) praticamente EXCLUI TVP/TEP em pacientes de baixo risco (valor preditivo negativo ~99%), mas valor elevado não confirma TEV pois eleva-se em múltiplas condições. Causas de elevação: trombose venosa profunda (TVP), embolia pulmonar (TEP), coagulação intravascular disseminada (CIVD), gestação (aumenta progressivamente, especialmente no terceiro trimestre), pós-operatório, trauma, neoplasias, infecções, insuficiência cardíaca, fibrilação atrial, idade avançada (>50 anos - ajustar ponto de corte: idade x 10 ng/mL), doença renal ou hepática. Na medicina funcional, D-dímero persistentemente elevado (500-1.000 ng/mL) sem causa aparente pode refletir inflamação vascular crônica, aterosclerose ou estado pró-trombótico subclínico. Valores muito elevados (>5.000 ng/mL) sugerem TEP maciço, CIVD ou neoplasia avançada.',

  patient_explanation = 'O D-dímero é uma substância que aparece no sangue quando há formação e dissolução de coágulos. Valores normais são abaixo de 500 ng/mL. É um exame muito usado para DESCARTAR trombose (coágulo) nas pernas (TVP) ou pulmão (embolia pulmonar) - se o D-dímero está normal, é muito improvável que haja trombose. Porém, se está elevado, NÃO confirma trombose, pois sobe em várias situações: gravidez, após cirurgias ou traumas, infecções, câncer, idade avançada, insuficiência cardíaca e até após exercício intenso. Por isso, D-dímero elevado sempre precisa de outros exames (ultrassom doppler das pernas, tomografia do pulmão) para confirmar ou descartar trombose. Valores muito altos (acima de 5.000) são mais preocupantes e sugerem embolia pulmonar grave, coagulação disseminada (CIVD - condição grave) ou câncer avançado. Idosos naturalmente têm valores mais altos (ajuste: idade x 10).',

  conduct = 'Solicitar em: suspeita de TVP (dor, edema, empastamento de panturrilha) ou TEP (dispneia súbita, dor torácica, taquicardia), CIVD, monitoramento de terapia trombolítica, investigação de estado pró-trombótico, gestação com suspeita de trombose. NÃO solicitar como rastreio em pacientes assintomáticos ou alto risco pré-teste (baixa especificidade). Interpretação: NORMAL <500 ng/mL (exclui TVP/TEP em baixo risco) | LEVEMENTE ELEVADO 500-1.000 ng/mL | MODERADAMENTE ELEVADO 1.000-5.000 ng/mL | MUITO ELEVADO >5.000 ng/mL (TEP maciço, CIVD). Ajustar para idade >50 anos: corte = idade x 10 ng/mL. Investigação complementar: se elevado com suspeita de TVP - ultrassom doppler venoso de membros inferiores; se TEP - angiotomografia de tórax, gasometria arterial, BNP/troponina. Avaliar fatores de risco: pesquisar trombofilias (proteína C, proteína S, fator V Leiden, anticoagulante lúpico, anticardiolipina) se trombose sem causa aparente. Intervenções: se TVP/TEP confirmado - anticoagulação (heparina → varfarina ou DOACs). Monitoramento: não repetir D-dímero durante tratamento (permanece elevado); usar exames de imagem para avaliar resolução.',

  updated_at = NOW()
WHERE id = 'b6881c39-3a87-40f5-bce6-eb2c8c729a4b';

-- Item 21: Estradiol - Mulheres Fase Lútea (Dias 19-21)
UPDATE score_items
SET
  clinical_relevance = 'O estradiol (E2) na fase lútea média (dias 19-21 após início da menstruação, assumindo ciclo de 28 dias) deve estar em níveis moderados, refletindo produção do corpo lúteo. Valores esperados: 80-200 pg/mL (pode variar entre laboratórios). A fase lútea é caracterizada por progesterona dominante (>10 ng/mL), mas o estradiol permanece presente em níveis intermediários. A relação estradiol:progesterona adequada é crucial para preparação endometrial para implantação. Estradiol muito baixo na fase lútea (<50 pg/mL) pode indicar insuficiência do corpo lúteo, anovulação ou fase lútea curta, comprometendo fertilidade e aumentando risco de abortamento precoce. Estradiol muito alto (>250 pg/mL) pode sugerir múltiplos folículos (síndrome dos ovários policísticos), cistos ovarianos ou, raramente, tumores produtores de estrogênio. A dosagem de estradiol na fase lútea é útil na investigação de infertilidade, irregularidades menstruais e avaliação de resposta a indução de ovulação. Idealmente, dosar junto com progesterona para avaliar qualidade da fase lútea (progesterona >10 ng/mL confirma ovulação).',

  patient_explanation = 'O estradiol é o principal hormônio feminino (estrogênio). Na fase lútea do ciclo menstrual (segunda metade, dias 19-21, após a ovulação), o estradiol fica em níveis moderados (80-200 pg/mL) enquanto a progesterona fica alta. Essa fase prepara o útero para uma possível gravidez. Estradiol muito baixo (abaixo de 50) nessa fase pode indicar que você não ovulou corretamente ou que o corpo lúteo (estrutura que produz hormônios após ovulação) está fraco. Isso dificulta engravidar e aumenta risco de aborto espontâneo precoce. Estradiol muito alto (acima de 250) pode sugerir múltiplos cistos nos ovários, síndrome dos ovários policísticos ou tumores produtores de hormônio (raro). Para avaliar corretamente a fase lútea, é importante dosar estradiol E progesterona juntos: a progesterona deve estar acima de 10 ng/mL (confirma que ovulou) e o estradiol entre 80-200. Esse exame ajuda a investigar dificuldade para engravidar e irregularidades menstruais.',

  conduct = 'Solicitar em: infertilidade, irregularidade menstrual, ciclos anovulatórios, insuficiência de corpo lúteo, abortamento recorrente, avaliação de qualidade da fase lútea, monitoramento de indução de ovulação, sintomas de dominância estrogênica (TPM intensa, mastalgia). Coletar idealmente nos dias 19-21 do ciclo (fase lútea média) junto com progesterona. Interpretação: MUITO BAIXO <50 pg/mL (insuficiência lútea, anovulação) | BAIXO 50-80 pg/mL | ADEQUADO 80-150 pg/mL | ÓTIMO 100-150 pg/mL (com progesterona >10) | ALTO 150-200 pg/mL | ELEVADO >200 pg/mL (investigar SOP, cistos, tumor). Investigação complementar: ESSENCIAL - progesterona sérica (mesmo momento), LH, FSH (dia 3 do ciclo), testosterona, SHBG, ultrassom pélvico transvaginal (avaliar folículos, corpo lúteo, endométrio), curva de temperatura basal. Se anovulação: TSH, prolactina, andrógenos (DHEA-S, androstenediona), insulina, HOMA-IR. Intervenções: insuficiência lútea - suplementação de progesterona (200-400mg micronizada vaginal/oral na fase lútea), vitamina B6, magnésio, Vitex agnus-castus. Se anovulação: citrato de clomifeno para indução. Monitoramento: repetir dosagem hormonal em ciclos subsequentes até normalização.',

  updated_at = NOW()
WHERE id = 'c28ad2a2-2ac0-4dff-a8f4-328b0a41e9e9';

-- Item 22: Microalbuminúria/creatininúria - urina amostra isolada
UPDATE score_items
SET
  clinical_relevance = 'A relação microalbuminúria/creatininúria (também chamada relação albumina/creatinina urinária - ACR ou UACR) é o padrão-ouro para rastreio de doença renal precoce. Valores normais: <30 mg/g creatinina. Microalbuminúria (30-300 mg/g) indica lesão glomerular inicial, refletindo disfunção endotelial renal antes de proteinúria franca (>300 mg/g). É marcador precoce de nefropatia diabética (presente em 20-40% dos diabéticos tipo 2), nefropatia hipertensiva e fator de risco cardiovascular independente. Na medicina funcional, valores no limite superior do normal (20-30 mg/g) já justificam otimização de controle glicêmico e pressórico. Causas de microalbuminúria: diabetes mellitus (principal), hipertensão arterial não controlada, obesidade, síndrome metabólica, doença renal crônica inicial, glomerulonefrites, pré-eclâmpsia, exercício intenso (transitório), febre, insuficiência cardíaca. A microalbuminúria é REVERSÍVEL com controle rigoroso de glicemia (HbA1c <7%), pressão arterial (<130/80 mmHg), uso de IECA ou BRA (bloqueiam RAAS) e perda de peso. Progressão para macroalbuminúria (>300 mg/g) indica lesão renal estabelecida.',

  patient_explanation = 'A microalbuminúria mede pequenas quantidades de proteína (albumina) na urina que não aparecem no exame de urina comum. É o primeiro sinal de que os rins estão começando a "vazar" proteína, indicando lesão inicial nos filtros renais. Valores normais são abaixo de 30 mg por grama de creatinina. Entre 30-300 é microalbuminúria (lesão inicial, REVERSÍVEL), acima de 300 é macroalbuminúria (lesão estabelecida). É especialmente importante em diabéticos e hipertensos, pois detecta doença renal ANOS antes dos exames tradicionais (creatinina, ureia). Também indica risco aumentado de infarto e derrame, mesmo sem doença renal grave. A boa notícia é que microalbuminúria pode ser revertida com controle rigoroso da glicemia (abaixo de 7% de hemoglobina glicada), pressão arterial bem controlada (abaixo de 130/80), medicamentos que protegem os rins (captopril, losartana) e perda de peso. Detectar e tratar precocemente previne insuficiência renal no futuro.',

  conduct = 'Solicitar em: diabetes mellitus (rastreio anual OBRIGATÓRIO), hipertensão arterial, síndrome metabólica, obesidade, doença renal crônica, história familiar de doença renal, pré-eclâmpsia, monitoramento de nefropatia estabelecida. Coletar em amostra isolada (primeira urina da manhã preferencial) - mais prático que urina 24h. Interpretação: ÓTIMO <10 mg/g | NORMAL 10-30 mg/g | MICROALBUMINÚRIA LEVE 30-100 mg/g | MICROALBUMINÚRIA MODERADA 100-300 mg/g | MACROALBUMINÚRIA (PROTEINÚRIA) >300 mg/g. Investigação complementar: ureia, creatinina, TFG (taxa de filtração glomerular), glicemia, HbA1c, perfil lipídico, pressão arterial, ultrassom renal. Se >300: investigar glomerulonefrite (complemento C3/C4, ANA, anti-DNA, ANCA), mieloma (eletroforese). Intervenções: controle rigoroso de glicemia (HbA1c <7%), PA <130/80 mmHg, IECA ou BRA (enalapril, losartana - reduzem proteinúria mesmo sem hipertensão), dieta hipossódica (<2g/dia), perda de peso, cessar tabagismo. Monitoramento: repetir ACR trimestralmente até estabilização, depois semestral. Objetivo: reduzir para <30 mg/g.',

  updated_at = NOW()
WHERE id = 'b24b19e7-b791-4cce-9809-9b202222501e';

-- Item 23: Progesterona - Mulheres Gestação 1º Trimestre
UPDATE score_items
SET
  clinical_relevance = 'A progesterona no primeiro trimestre da gestação é produzida primariamente pelo corpo lúteo (até ~10 semanas), depois progressivamente pela placenta. Valores esperados: 10-90 ng/mL (ampla variação, aumenta progressivamente). Na 4ª semana: 10-30 ng/mL; 5ª-6ª semana: 15-40 ng/mL; 7ª-10ª semana: 25-90 ng/mL. Progesterona adequada é ESSENCIAL para manutenção da gestação inicial: suprime contrações uterinas, promove decidualização endometrial, imunotolerância materno-fetal e desenvolvimento placentário. Valores baixos (<10 ng/mL) no primeiro trimestre associam-se a risco aumentado de abortamento espontâneo, especialmente se <5 ng/mL (aborto iminente). A suplementação de progesterona é controversa: estudos mostram benefício em mulheres com história de abortamento recorrente ou sangramento vaginal no primeiro trimestre, mas não previne aborto em gestações sem fatores de risco. A dosagem isolada de progesterona tem valor limitado pois há grande variabilidade individual; mais útil é avaliar tendência (dosagens seriadas) e beta-hCG (deve dobrar a cada 48h em gestação viável até 6-7 semanas).',

  patient_explanation = 'A progesterona é o hormônio mais importante para manter a gravidez no início. No primeiro trimestre (primeiras 12 semanas), é produzida pelo corpo lúteo (estrutura no ovário que libera o óvulo) até a placenta assumir essa função. Valores normais variam muito (10-90 ng/mL) e aumentam progressivamente. Progesterona mantém o útero relaxado (evita contrações), prepara o revestimento do útero para o bebê se fixar e protege a gravidez do sistema imune da mãe. Valores abaixo de 10 ng/mL podem indicar risco de aborto espontâneo, especialmente se abaixo de 5. No entanto, um único valor baixo não confirma aborto - é preciso repetir e comparar com beta-hCG (outro hormônio que dobra a cada 2 dias em gravidez saudável). A suplementação com progesterona (via vaginal ou oral) pode ajudar mulheres com histórico de abortos repetidos ou sangramento no início da gravidez, mas não previne aborto em todas as situações. Cada caso deve ser avaliado individualmente.',

  conduct = 'Solicitar em: sangramento vaginal no primeiro trimestre, história de abortamento recorrente (≥2 abortos), dor pélvica, suspeita de gravidez ectópica, monitoramento de fertilização in vitro (FIV), insuficiência de corpo lúteo conhecida. Idealmente, dosar junto com beta-hCG. Interpretação: <5 ng/mL = ALTO RISCO de aborto ou gravidez ectópica | 5-10 ng/mL = RISCO MODERADO (reavaliar) | 10-25 ng/mL = ADEQUADO (início do 1º trimestre) | 25-90 ng/mL = ÓTIMO (meio-fim do 1º trimestre) | >90 ng/mL = MUITO ALTO (gestação múltipla, mola hidatiforme). Investigação complementar: ESSENCIAL - beta-hCG seriado (deve dobrar a cada 48h até 6-7 semanas), ultrassom transvaginal (visualizar saco gestacional, embrião, batimentos cardíacos). Se progesterona baixa: repetir em 48-72h para avaliar tendência, tipagem sanguínea e Rh (profilaxia se Rh negativo com sangramento), hemograma. Intervenções: progesterona <10 ng/mL com beta-hCG subindo adequadamente e história de aborto recorrente - suplementar progesterona micronizada 200-400mg/dia vaginal ou oral até 12 semanas. Repouso relativo se sangramento. Se beta-hCG não dobra + progesterona baixa: suspeitar aborto ou ectópica. Monitoramento: dosagens seriadas a cada 48-72h até estabilização ou definição diagnóstica.',

  updated_at = NOW()
WHERE id = 'de37b146-6568-4e27-9128-3776a32fa99b';

-- Item 24: Progesterona - Mulheres Fase Lútea
UPDATE score_items
SET
  clinical_relevance = 'A progesterona na fase lútea (pós-ovulatória, dias 19-21 do ciclo) confirma ovulação e avalia qualidade do corpo lúteo. Valores esperados: >10 ng/mL (confirma ovulação); ideal >15 ng/mL. A progesterona transforma o endométrio proliferativo em secretor, preparando-o para implantação embrionária. Valores <3 ng/mL indicam anovulação. Valores entre 3-10 ng/mL sugerem ovulação com insuficiência de corpo lúteo (fase lútea inadequada - LPD), associada a infertilidade, abortamento recorrente, ciclos curtos (<25 dias), TPM intensa e spotting pré-menstrual. Causas de LPD: disfunção tireoidiana, hiperprolactinemia, obesidade ou baixo peso, estresse, exercício excessivo, síndrome dos ovários policísticos (SOP), reserva ovariana diminuída, deficiência de vitamina B6 ou magnésio. Progesterona adequada (>15 ng/mL) também melhora sintomas de TPM, reduz ansiedade e melhora sono devido aos metabólitos neuroativos (alopregnanolona). A dosagem deve ser realizada 7 dias após ovulação presumida (dia 21 em ciclo de 28 dias; ajustar se ciclo diferente). Em ciclos irregulares, monitorar com temperatura basal ou LH urinário para timing correto.',

  patient_explanation = 'A progesterona na fase lútea (segunda metade do ciclo menstrual, após ovulação) é essencial para confirmar que você ovulou e para preparar o útero para uma possível gravidez. Valores acima de 10 ng/mL confirmam que houve ovulação; ideal é acima de 15. Valores abaixo de 3 indicam que você não ovulou naquele ciclo. Entre 3-10 significa que ovulou mas o corpo lúteo (estrutura que produz progesterona após ovulação) está fraco - isso dificulta engravidar e manter a gravidez inicial, além de causar TPM intensa, ansiedade, insônia, seios doloridos e sangramento antes da menstruação. Causas incluem problemas na tireoide, prolactina alta, peso muito baixo ou muito alto, estresse, exercício excessivo, ovários policísticos ou deficiências nutricionais (vitamina B6, magnésio). O exame deve ser feito 7 dias depois da ovulação (geralmente dia 21 do ciclo se ele tem 28 dias). Progesterona adequada não só ajuda a engravidar, mas também melhora humor, sono e reduz TPM.',

  conduct = 'Solicitar em: infertilidade, abortamento recorrente, ciclos irregulares ou curtos (<25 dias), TPM intensa, spotting pré-menstrual, confirmar ovulação, avaliação de qualidade da fase lútea. Coletar idealmente dia 21 do ciclo (ou 7 dias após ovulação). Interpretação: ANOVULAÇÃO <3 ng/mL | INSUFICIÊNCIA LÚTEA 3-10 ng/mL | OVULAÇÃO CONFIRMADA >10 ng/mL | ÓTIMO >15 ng/mL | EXCELENTE >20 ng/mL. Investigação complementar: TSH (hipotireoidismo causa LPD), prolactina (hiperprolactinemia inibe corpo lúteo), LH e FSH (dia 3 - avaliar reserva ovariana), estradiol fase lútea, testosterona e DHEA-S (se SOP suspeitado), vitamina B6, magnésio, curva de temperatura basal, ultrassom pélvico (avaliar corpo lúteo, espessura endometrial). Intervenções: insuficiência lútea - progesterona micronizada 200-400mg/dia via vaginal ou oral (dias 14-28 do ciclo), vitamina B6 50-100mg/dia, magnésio 400mg/dia, Vitex agnus-castus 400mg/dia, otimizar tireoide, reduzir estresse, normalizar peso. Se anovulação: citrato de clomifeno para indução. Monitoramento: repetir em 2-3 ciclos até normalização.',

  updated_at = NOW()
WHERE id = '468fd606-65ff-4439-81a1-4cc0d2d1df7e';

-- Item 25: Basófilos (absoluto)
UPDATE score_items
SET
  clinical_relevance = 'Basófilos são os leucócitos menos abundantes (<1% dos leucócitos totais), com papel em reações de hipersensibilidade imediata (tipo I), liberando histamina, leucotrienos e citocinas pró-inflamatórias. Valores normais: 20-100 células/mm³ (ou 0-1% dos leucócitos). Valores ótimos funcionais: 30-70/mm³. Basofilia (>100/mm³) é rara e geralmente associada a neoplasias hematológicas: leucemia mieloide crônica (LMC - basofilia é critério diagnóstico menor), leucemia basofílica aguda (rara), policitemia vera, mielofibrose. Causas não-malignas: reações alérgicas graves, hipotireoidismo, infecções virais (varicela, influenza), doença inflamatória intestinal, hiperlipidemia, pós-esplenectomia. Basofilia persistente (>150/mm³) requer investigação hematológica urgente para descartar LMC (solicitar cromossomo Philadelphia, BCR-ABL). Basopenia (<20/mm³) é mais comum mas clinicamente menos relevante, podendo ocorrer em infecções agudas, estresse, hipertireoidismo, urticária crônica (desgranulação) ou terapia com corticoides. Basófilos são difíceis de contar com precisão devido à baixa quantidade; variações pequenas podem não ser significativas.',

  patient_explanation = 'Basófilos são as células de defesa menos comuns no sangue (menos de 1% dos glóbulos brancos). Eles liberam histamina durante reações alérgicas, causando coceira, inchaço e vermelhidão. Valores normais são 20-100 células por microlitro. Valores altos (acima de 100) são raros e podem indicar doenças graves do sangue, especialmente leucemia mieloide crônica (LMC) - um tipo de câncer do sangue. Outras causas menos graves incluem alergias intensas, tireoide lenta (hipotireoidismo), infecções virais ou colesterol muito alto. Se os basófilos estiverem persistentemente acima de 150, é importante fazer exames com um hematologista para descartar leucemia (exame do cromossomo Philadelphia). Valores baixos (abaixo de 20) são mais comuns e menos preocupantes, podendo ocorrer em infecções, estresse, tireoide acelerada (hipertireoidismo), alergias crônicas ou uso de corticoides. Devido ao número muito baixo de basófilos, pequenas variações podem não significar nada.',

  conduct = 'Solicitar em: hemograma completo de rotina, investigação de basofilia (se detectada em hemograma prévio), suspeita de leucemia mieloide crônica, reações alérgicas graves, hipotireoidismo. Interpretação: BAIXO <20/mm³ (comum, geralmente sem significado clínico) | ÓTIMO 30-70/mm³ | ADEQUADO 20-30 ou 70-100/mm³ | ELEVADO 100-150/mm³ (investigar) | MUITO ELEVADO >150/mm³ (suspeita de LMC, encaminhar hematologista urgente). Investigação complementar: se basofilia - hemograma seriado, esfregaço de sangue periférico (morfologia), cromossomo Philadelphia, PCR para BCR-ABL (padrão-ouro para LMC), JAK2 V617F (policitemia vera), ultrassom de abdome (esplenomegalia), TSH (hipotireoidismo), IgE total (alergia), triptase sérica. Se basofilia persistente >150: encaminhamento hematológico, considerar biópsia de medula óssea. Intervenções: tratar causa de base (LMC: inibidores de tirosinoquinase - imatinibe; hipotireoidismo: levotiroxina; alergia: anti-histamínicos, evitar alérgenos). Monitoramento: se basofilia sem causa aparente - hemograma mensal por 3 meses; se LMC - protocolo hematológico específico.',

  updated_at = NOW()
WHERE id = '8b6b9782-9273-499a-bb56-ce792ca61ade';

-- Item 26: Progesterona - Mulheres Fase Folicular
UPDATE score_items
SET
  clinical_relevance = 'A progesterona na fase folicular (primeira metade do ciclo, antes da ovulação, dias 1-14) deve estar em níveis basais, pois a ovulação ainda não ocorreu e o corpo lúteo não foi formado. Valores esperados: <1,5 ng/mL (idealmente <1,0 ng/mL). Progesterona elevada na fase folicular (>1,5 ng/mL) pode indicar: ovulação recente (ciclo anterior ainda não finalizou completamente - common em ciclos curtos), luteinização folicular prematura (síndrome LUF - luteinized unruptured follicle), insuficiência adrenal (produção adrenal aumentada de progesterona), hiperplasia adrenal congênita (forma tardia), gravidez inicial não reconhecida ou erro de timing (paciente não está realmente na fase folicular). Valores muito elevados (>3 ng/mL) praticamente descartam fase folicular verdadeira. A dosagem de progesterona na fase folicular é menos comumente solicitada que na fase lútea, mas pode ser útil em protocolos de fertilização in vitro (FIV), onde progesterona elevada pré-ovulatória pode comprometer receptividade endometrial e reduzir taxas de implantação. Em ciclos naturais, progesterona folicular elevada pode sugerir que o óvulo foi "aprisionado" no folículo sem ruptura (LUF - anovulação com luteinização).',

  patient_explanation = 'A progesterona na fase folicular (primeira metade do ciclo menstrual, antes da ovulação) deve estar muito baixa (abaixo de 1,5 ng/mL, idealmente abaixo de 1,0) porque você ainda não ovulou. Progesterona só sobe significativamente DEPOIS da ovulação. Se a progesterona está elevada (acima de 1,5) na fase folicular, pode significar: você ovulou recentemente mas o ciclo ainda não acabou (comum em ciclos curtos), o óvulo ficou "preso" no folículo sem ser liberado (síndrome LUF - você não ovulou de verdade mesmo achando que sim), problema nas glândulas adrenais produzindo muita progesterona, ou você coletou o exame no momento errado do ciclo. Valores muito altos (acima de 3) praticamente descartam que você esteja realmente na fase folicular. Em tratamentos de fertilização in vitro, progesterona alta antes da ovulação é ruim porque impede o embrião de se fixar no útero. Esse exame é menos solicitado que a progesterona da fase lútea, mas pode ajudar a entender problemas de ovulação.',

  conduct = 'Solicitar em: protocolos de FIV (fertilização in vitro - progesterona elevada pré-ovulatória prediz pior prognóstico), investigação de anovulação com LUF (síndrome do folículo luteinizado não roto), ciclos irregulares, avaliação hormonal basal (dias 2-3 do ciclo). Interpretação: ÓTIMO <0,5 ng/mL | ADEQUADO 0,5-1,0 ng/mL | LIMÍTROFE 1,0-1,5 ng/mL | ELEVADO 1,5-3,0 ng/mL (investigar) | MUITO ELEVADO >3,0 ng/mL (erro de timing ou patologia). Investigação complementar: confirmar dia do ciclo (pela menstruação), LH e FSH (dia 2-3 - perfil basal), estradiol folicular, ultrassom transvaginal (avaliar folículos, espessura endometrial, presença de corpo lúteo residual), curva de temperatura basal ou monitor de LH urinário (confirmar timing de ovulação). Se elevado: 17-OH-progesterona (hiperplasia adrenal), cortisol, DHEA-S, ultrassom seriado (documentar ruptura folicular vs LUF). Intervenções: se LUF (anovulação com luteinização) - indução de ovulação com citrato de clomifeno ou gonadotrofinas, hCG para trigger ovulatório. Em FIV, se progesterona >1,5 pré-retrieval: considerar freeze-all (congelar embriões e transferir em ciclo subsequente). Monitoramento: ultrassom seriado + dosagens hormonais para confirmar ovulação adequada.',

  updated_at = NOW()
WHERE id = 'dcf82f66-c41f-43b6-b043-0d94a74d69bd';

-- Item 27: Potássio
UPDATE score_items
SET
  clinical_relevance = 'O potássio é o principal cátion intracelular, essencial para potencial de membrana, contração muscular (cardíaca, esquelética, lisa), condução nervosa, equilíbrio ácido-base e função renal. Valores normais: 3,5-5,5 mEq/L (mmol/L). Valores ótimos funcionais: 4,0-4,8 mEq/L. A homeostase é mantida por excreção renal regulada por aldosterona. Hipocalemia (<3,5 mEq/L) causa fraqueza muscular, câimbras, constipação, arritmias (extrassístoles, taquicardia ventricular, torsades de pointes), rabdomiólise (se <2,5), alterações eletrocardiográficas (onda U, depressão de ST, QT prolongado). Causas: perdas renais (diuréticos - especialmente tiazídicos e furosemida, hiperaldosteronismo, acidose tubular renal, hipomagnesemia), perdas gastrointestinais (diarreia, vômitos, laxantes), deslocamento intracelular (alcalose, insulina, beta-agonistas, paralisia periódica hipocalêmica). Hipercalemia (>5,5 mEq/L) é potencialmente fatal: arritmias (bradicardia, bloqueios AV, fibrilação ventricular, assistolia), fraqueza muscular, parestesias. Causas: insuficiência renal (principal), medicamentos (IECA, BRA, espironolactona, AINEs, trimetoprim), acidose, hemólise, rabdomiólise, hipoaldosteronismo, pseudohipercalemia (hemólise in vitro, leucocitose/trombocitose extrema).',

  patient_explanation = 'O potássio é um mineral essencial que controla batimentos cardíacos, contração muscular, condução nervosa e pressão arterial. A maior parte está dentro das células, não no sangue. Valores normais ficam entre 3,5-5,5 mEq/L, sendo ideal entre 4,0-4,8. Potássio baixo (hipocalemia, abaixo de 3,5) causa fraqueza muscular, câimbras, prisão de ventre, cansaço e arritmias cardíacas perigosas. Causas principais: diuréticos (remédios para pressão alta ou inchaço), diarreia ou vômitos prolongados, uso excessivo de laxantes ou baixa ingestão (dieta pobre em frutas e vegetais). Potássio alto (hipercalemia, acima de 5,5) é muito perigoso, podendo causar arritmias fatais, fraqueza e formigamento. Causas: insuficiência renal (rins não eliminam potássio), medicamentos (captopril, losartana, espironolactona, ibuprofeno), acidose ou destruição muscular. Hipercalemia acima de 6,0 é emergência médica. Nunca suplementar potássio sem orientação médica.',

  conduct = 'Solicitar em: eletrólitos de rotina, hipertensão arterial, uso de diuréticos ou IECA/BRA, insuficiência renal, diarreia ou vômitos, fraqueza muscular, câimbras, arritmias, cetoacidose diabética, rabdomiólise, monitoramento de terapia de reposição. Interpretação: HIPOCALEMIA GRAVE <2,5 mEq/L (EMERGÊNCIA) | HIPOCALEMIA MODERADA 2,5-3,0 | HIPOCALEMIA LEVE 3,0-3,5 | SUBÓTIMO 3,5-4,0 | ÓTIMO 4,0-4,8 | ADEQUADO 4,8-5,0 | LIMÍTROFE 5,0-5,5 | HIPERCALEMIA LEVE 5,5-6,0 | HIPERCALEMIA MODERADA 6,0-6,5 | HIPERCALEMIA GRAVE >6,5 (EMERGÊNCIA). Investigação complementar: ECG (alterações características), função renal (ureia, creatinina, TFG), magnésio (hipomagnesemia causa hipocalemia refratária), gasometria (acidose/alcalose), aldosterona e renina (se suspeita de hiperaldosteronismo), potássio urinário (diferenciar perdas renais vs extrarrenais). Intervenções: hipocalemia - KCl oral 20-40 mEq 2-3x/dia, aumentar ingesta (banana, laranja, batata, abacate, espinafre), corrigir magnésio. Hipercalemia leve: dieta hipopotássica, resina trocadora (sorcal); moderada-grave: gluconato de cálcio IV (proteção cardíaca), insulina + glicose, bicarbonato, diálise se refratária. Monitoramento: hipocalemia - diário até >3,5, depois semanal; hipercalemia - de acordo com gravidade (pode ser horário).',

  updated_at = NOW()
WHERE id = '8dd694fa-4128-4e94-a0b6-a5a4e838d745';

-- Item 28: Eosinófilos (absoluto)
UPDATE score_items
SET
  clinical_relevance = 'Eosinófilos são leucócitos especializados em defesa contra parasitas helmintos e modulação de reações alérgicas, liberando proteínas citotóxicas (proteína básica maior, peroxidase eosinofílica) e mediadores pró-inflamatórios. Valores normais: 50-500 células/mm³ (ou 1-4% dos leucócitos). Valores ótimos funcionais: 100-300/mm³. Eosinofilia (>500/mm³) indica: parasitoses (ascaris, ancilóstomo, estrongiloide, esquistossomose), alergias (asma, rinite alérgica, dermatite atópica, alergia alimentar), reações medicamentosas (DRESS, pneumonite eosinofílica), doenças autoimunes (granulomatose eosinofílica com poliangeite - EGPA/Churg-Strauss), neoplasias (leucemia eosinofílica, linfoma de Hodgkin, tumores sólidos), síndrome hipereosinofílica (eosinófilos >1.500/mm³ por >6 meses com dano orgânico). Eosinofilia >1.500/mm³ requer investigação urgente para descartar malignidade e síndrome hipereosinofílica. Eosinopenia (<50/mm³) é menos relevante clinicamente, ocorrendo em infecções agudas, estresse, uso de corticoides ou síndrome de Cushing. Contexto clínico é essencial: eosinofilia em viajante recente a área endêmica sugere parasitose; em asmático, reflete controle inadequado.',

  patient_explanation = 'Eosinófilos são células de defesa especializadas em combater vermes parasitas e participar de reações alérgicas. Valores normais ficam entre 50-500 células por microlitro (1-4% dos glóbulos brancos). Valores altos (acima de 500) geralmente indicam: parasitas intestinais (vermes como lombrigas, amarelão), alergias (asma, rinite, dermatite atópica, alergia a alimentos), reação a medicamentos, doenças autoimunes ou, mais raramente, certos tipos de leucemia ou linfoma. Se os eosinófilos estiverem muito altos (acima de 1.500), é importante investigar urgentemente para descartar câncer do sangue ou síndrome hipereosinofílica (condição grave onde eosinófilos atacam órgãos). Valores baixos (abaixo de 50) são menos importantes, geralmente ocorrendo em infecções agudas, estresse ou uso de corticoides. Se você tem eosinófilos altos e viajou recentemente para áreas tropicais, pense em parasitas. Se tem asma ou alergias, reflete controle inadequado.',

  conduct = 'Solicitar em: hemograma de rotina, parasitoses (investigação ou controle pós-tratamento), asma ou alergias, reações medicamentosas, febre com eosinofilia, história de viagem a áreas endêmicas, suspeita de síndrome hipereosinofílica. Interpretação: BAIXO <50/mm³ (geralmente sem significado) | ÓTIMO 100-300/mm³ | ADEQUADO 50-100 ou 300-500/mm³ | EOSINOFILIA LEVE 500-1.500/mm³ | EOSINOFILIA MODERADA 1.500-5.000/mm³ (investigar urgente) | EOSINOFILIA GRAVE >5.000/mm³ (emergência hematológica). Investigação complementar: parasitológico de fezes (3 amostras), IgE total e específica (alérgenos), radiografia de tórax (pneumonite eosinofílica, asma), função renal e hepática (dano orgânico), troponina e ECG (miocardite eosinofílica), ANCA (vasculite EGPA), triptase (mastocitose), esfregaço de sangue periférico, considerar sorologia para Strongyloides (comum em imigrantes). Se >1.500: biópsia de medula óssea, pesquisa de rearranjos FIP1L1-PDGFRA. Intervenções: tratar causa de base (antiparasitários, anti-histamínicos para alergias, suspender medicamento ofensor, corticoides se síndrome hipereosinofílica). Monitoramento: mensal até normalização, depois trimestral se doença crônica.',

  updated_at = NOW()
WHERE id = 'c49a524b-ccfb-48a7-b289-15cc5fbd1c3d';

-- Item 29: FSH - Mulheres Pré-menopausa (Dia 3)
UPDATE score_items
SET
  clinical_relevance = 'O FSH (hormônio folículo-estimulante) no dia 3 do ciclo menstrual avalia reserva ovariana e função gonadal em mulheres pré-menopáusicas. Valores normais: 3-10 mUI/mL (fase folicular). Valores ótimos funcionais: 4-8 mUI/mL, refletindo reserva ovariana adequada. FSH elevado (>10 mUI/mL) indica reserva ovariana diminuída (DOR - diminished ovarian reserve): os ovários estão respondendo mal ao FSH, então a hipófise produz mais FSH compensatoriamente. Causas: idade avançada (>35 anos), menopausa precoce, insuficiência ovariana primária (POI - premature ovarian insufficiency), quimioterapia ou radioterapia pélvica, cirurgia ovariana, endometriose, tabagismo. FSH >15-20 mUI/mL sugere menopausa iminente ou POI. FSH >40 mUI/mL em mulher <40 anos define POI (infertilidade, sintomas menopausais precoces). FSH baixo (<3 mUI/mL) pode indicar hipogonadismo central (hipopituitarismo, hiperprolactinemia, anorexia nervosa), síndrome dos ovários policísticos (SOP - relação LH:FSH aumentada). Interpretar sempre com LH, estradiol e AMH (hormônio antimülleriano - melhor marcador de reserva ovariana). FSH flutua entre ciclos; valores altos devem ser confirmados.',

  patient_explanation = 'O FSH é um hormônio produzido pela hipófise que estimula os ovários a amadurecerem óvulos. Dosar FSH no dia 3 do ciclo menstrual ajuda a avaliar a "reserva ovariana" (quantos óvulos você ainda tem e quão bem funcionam). Valores normais ficam entre 3-10 mUI/mL, sendo ideal entre 4-8. FSH alto (acima de 10) significa que seus ovários estão respondendo mal - a hipófise produz mais FSH tentando compensar. Isso indica reserva ovariana diminuída, comum após os 35 anos, mas também pode ocorrer por menopausa precoce, quimioterapia, cirurgias ovarianas, endometriose ou tabagismo. FSH acima de 15-20 sugere menopausa próxima; acima de 40 em mulheres abaixo dos 40 anos indica insuficiência ovariana prematura (POI). FSH baixo (abaixo de 3) pode indicar problema na hipófise, prolactina alta, anorexia ou ovários policísticos. FSH deve ser interpretado junto com LH, estradiol e especialmente AMH (melhor marcador de reserva). FSH varia entre ciclos, valores altos devem ser confirmados.',

  conduct = 'Solicitar em: infertilidade, idade >35 anos (pré-concepção), ciclos irregulares, amenorreia, avaliação de reserva ovariana pré-FIV, suspeita de menopausa precoce, história de quimioterapia ou cirurgia ovariana. Coletar no DIA 3 do ciclo (dia 1 = primeiro dia de menstruação). Interpretação: MUITO BAIXO <3 mUI/mL (hipogonadismo central, SOP) | ÓTIMO 4-8 mUI/mL | ADEQUADO 3-4 ou 8-10 mUI/mL | RESERVA DIMINUÍDA 10-15 mUI/mL | RESERVA MUITO BAIXA 15-25 mUI/mL | MENOPAUSA/POI >25 mUI/mL (em mulher <40 anos = POI; >45 anos = menopausa). Investigação complementar: ESSENCIAL - LH (dia 3), estradiol (dia 3), AMH (hormônio antimülleriano - pode ser colhido qualquer dia), contagem de folículos antrais (ultrassom transvaginal). Se FSH alto: TSH, prolactina, cariótipo (se POI <30 anos - descartar Turner), FMR1 (pré-mutação X frágil), anticorpos anti-ovário. Se baixo: prolactina, ressonância de hipófise. Intervenções: reserva diminuída - acelerar tentativa de gravidez, considerar FIV, preservação de fertilidade (congelamento de óvulos). POI: TRH (reposição hormonal) até idade natural da menopausa. Monitoramento: repetir FSH em ciclo subsequente se elevado (confirmação).',

  updated_at = NOW()
WHERE id = '5e413f2c-875d-4e6d-b5e2-9661db7156a8';

-- Item 30: Colesterol não-HDL
UPDATE score_items
SET
  clinical_relevance = 'O colesterol não-HDL representa todas as lipoproteínas aterogênicas (LDL, VLDL, IDL, Lp(a), remanescentes), calculado como: colesterol total - HDL. É superior ao LDL isolado para predição de risco cardiovascular pois captura TODAS as partículas que transportam colesterol para as artérias. Valores desejáveis: <130 mg/dL (prevenção primária), <100 mg/dL (prevenção secundária ou diabetes), <70 mg/dL (risco muito alto). Valores ótimos funcionais: <100 mg/dL. O não-HDL é especialmente útil em pacientes com triglicerídeos elevados (>200 mg/dL), onde o cálculo de LDL pela fórmula de Friedewald se torna impreciso. Em indivíduos com triglicerídeos altos, o não-HDL captura melhor o risco residual conferido por VLDL e remanescentes. Não-HDL elevado (>160 mg/dL) indica dislipidemia aterogênica e requer intervenção. Diretrizes atuais recomendam usar não-HDL como meta secundária de tratamento (meta = LDL + 30 mg/dL). Causas de elevação: dieta rica em gorduras saturadas/trans e carboidratos refinados, diabetes, síndrome metabólica, hipotireoidismo, síndrome nefrótica, obesidade, sedentarismo, genética (hipercolesterolemia familiar).',

  patient_explanation = 'O colesterol não-HDL é o colesterol total MENOS o colesterol "bom" (HDL). Ele representa TODOS os tipos de colesterol "ruim" que entopem as artérias: LDL, VLDL e outros. É melhor que o LDL isolado para prever risco de infarto e derrame porque captura partículas adicionais que o LDL não conta. Valores ideais são abaixo de 100 mg/dL para prevenção; abaixo de 70 se você já teve infarto, derrame ou tem diabetes. Acima de 130 já indica risco aumentado; acima de 160 é alto e requer tratamento. O não-HDL é especialmente útil quando seus triglicerídeos estão altos (acima de 200), porque nessa situação o cálculo do LDL fica impreciso, mas o não-HDL continua confiável. Para calcular: pegue o colesterol total e subtraia o HDL. Por exemplo, se seu colesterol total é 220 e HDL é 50, seu não-HDL é 170 (alto). Causas de não-HDL elevado são as mesmas do colesterol ruim: dieta inadequada, diabetes, obesidade, sedentarismo, hipotireoidismo ou genética.',

  conduct = 'Solicitar em: perfil lipídico de rotina (calculado automaticamente), avaliação de risco cardiovascular, diabetes, síndrome metabólica, hipertrigliceridemia (>200 mg/dL - onde LDL calculado é impreciso), monitoramento de terapia hipolipemiante, história familiar de doença cardíaca precoce. Interpretação: ÓTIMO <100 mg/dL | DESEJÁVEL 100-130 mg/dL | LIMÍTROFE 130-160 mg/dL | ALTO 160-190 mg/dL | MUITO ALTO >190 mg/dL. Metas terapêuticas: PREVENÇÃO PRIMÁRIA <130 | DIABETES ou DOENÇA ATEROSCLERÓTICA <100 | RISCO MUITO ALTO <70. Investigação complementar: perfil lipídico completo (LDL, HDL, triglicerídeos, VLDL), Apo B (padrão-ouro para partículas aterogênicas - cada partícula tem 1 Apo B), LDL oxidado, Lp(a), partículas de LDL (tamanho), PCR ultrassensível, glicemia, HbA1c, TSH, função renal e hepática, escore de cálcio coronariano (se risco intermediário). Intervenções: dieta mediterrânea, reduzir carboidratos refinados e gorduras trans, aumentar fibras solúveis (aveia, psyllium), ômega-3 (2-4g/dia), fitosteróis (2g/dia), exercícios aeróbicos. Estatinas se não-HDL >130 com risco moderado-alto ou >100 em diabéticos. Ezetimiba se meta não atingida. Monitoramento: trimestral até atingir meta, depois semestral.',

  updated_at = NOW()
WHERE id = 'ac752e50-6c53-4eaf-b72e-1d4e810251cb';

-- Vincular artigos relevantes
INSERT INTO article_score_items (article_id, score_item_id)
SELECT a.id, s.id
FROM articles a
CROSS JOIN (
  SELECT id FROM score_items WHERE id IN (
    '545e9a5a-ea8c-4d41-9cef-d6d9e32671c0',
    '29bd8bb0-edd0-46d4-90ca-12bef80585a3',
    'edaf4b36-a22c-4b12-88fc-aa754f7afe7a',
    '9acbde3f-0792-4ecc-a0f6-1a1c7500b766',
    'b6881c39-3a87-40f5-bce6-eb2c8c729a4b',
    'c28ad2a2-2ac0-4dff-a8f4-328b0a41e9e9',
    'b24b19e7-b791-4cce-9809-9b202222501e',
    'de37b146-6568-4e27-9128-3776a32fa99b',
    '468fd606-65ff-4439-81a1-4cc0d2d1df7e',
    '8b6b9782-9273-499a-bb56-ce792ca61ade',
    'dcf82f66-c41f-43b6-b043-0d94a74d69bd',
    '8dd694fa-4128-4e94-a0b6-a5a4e838d745',
    'c49a524b-ccfb-48a7-b289-15cc5fbd1c3d',
    '5e413f2c-875d-4e6d-b5e2-9661db7156a8',
    'ac752e50-6c53-4eaf-b72e-1d4e810251cb'
  )
) s
WHERE a.title ILIKE '%vitamina%'
   OR a.title ILIKE '%bioquímica%'
   OR a.title ILIKE '%hormônio%'
   OR a.title ILIKE '%proteína%'
   OR a.title ILIKE '%inflamação%'
LIMIT 5
ON CONFLICT DO NOTHING;
