#!/usr/bin/env python3
"""
Enriquecimento manual de 20 items de exames laboratoriais diversos.
Conteúdo clínico baseado em fontes médicas confiáveis.
"""

import json
import requests
from typing import Dict, Any

# Configuração
API_URL = "http://localhost:3001/api/v1"
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTliMzk2OC0zNTI4LTQ2YTUtYWRkNi03ODYyNmQ1NGJmMTgiLCJlbWFpbCI6ImltcG9ydEBwbGVueWEuY29tIiwicm9sZSI6ImFkbWluIiwiaXNzIjoicGxlbnlhLWVtciIsImV4cCI6MTc2OTQ4NTc3NiwiaWF0IjoxNzY5NDg0ODc2fQ.uQefgudKrzfDfmC5vE_3OKR52fZCXSwXKbNn6uAaeSs"

# Base de conhecimento clínico
CLINICAL_DATABASE = {
    "Albumina": {
        "clinical_explanation": "A albumina é a principal proteína plasmática sintetizada exclusivamente pelos hepatócitos no fígado, representando aproximadamente 60% das proteínas totais do plasma sanguíneo. Com peso molecular de cerca de 66 kDa, a albumina desempenha múltiplas funções fisiológicas essenciais, incluindo a manutenção da pressão oncótica plasmática (responsável por 70-80% da pressão oncótica), o transporte de substâncias hidrofóbicas (hormônios tireoidianos, ácidos graxos livres, bilirrubina não conjugada, drogas), e ação antioxidante através de seus grupos tiol. A síntese hepática de albumina é influenciada por diversos fatores, incluindo estado nutricional, pressão oncótica plasmática, hormônios (insulina, cortisol, hormônio do crescimento), e processos inflamatórios. Sua meia-vida plasmática é de aproximadamente 20 dias, tornando-a um marcador útil para avaliar o estado nutricional proteico em médio prazo e a função de síntese hepática. Além disso, a albumina participa da regulação do equilíbrio ácido-base, possui propriedades anti-inflamatórias e anticoagulantes, e influencia a farmacocinética de diversos medicamentos. A dosagem de albumina sérica é amplamente utilizada na prática clínica para avaliação do estado nutricional, função hepática, perdas proteicas renais ou gastrointestinais, e como componente de escores prognósticos em diversas condições clínicas.",

        "low_explanation": "A hipoalbuminemia (albumina sérica <3,5 g/dL) resulta de três mecanismos fisiopatológicos principais: síntese hepática diminuída, perdas aumentadas ou redistribuição. A redução da síntese ocorre em hepatopatias crônicas (cirrose, hepatite crônica), onde a massa de hepatócitos funcionantes está reduzida, e em estados de desnutrição proteico-calórica, onde há deficiência de substratos. Processos inflamatórios agudos e crônicos também suprimem a síntese de albumina através de citocinas inflamatórias (IL-6, TNF-α), que redirecionam a síntese hepática para proteínas de fase aguda. As perdas aumentadas ocorrem na síndrome nefrótica (proteinúria >3,5 g/dia), enteropatia perdedora de proteínas (doença inflamatória intestinal, linfangiectasia intestinal), e queimaduras extensas. A redistribuição da albumina do compartimento intravascular para o interstício ocorre em estados de aumento da permeabilidade capilar, como sepse, síndrome do desconforto respiratório agudo (SDRA), e outras condições inflamatórias sistêmicas. Mecanismos adicionais incluem hemodiluição em estados de hipervolemia e aumento do catabolismo proteico em estados hipercatabólicos (trauma, cirurgias extensas, neoplasias avançadas). A hipoalbuminemia tem importantes implicações clínicas, incluindo desenvolvimento de edema e ascite (pela redução da pressão oncótica), alteração na farmacocinética de medicamentos ligados à albumina, e aumento do risco de infecções. É importante reconhecer que a albumina é um marcador tardio de desnutrição, refletindo deficiências nutricionais prolongadas devido à sua longa meia-vida.",

        "high_explanation": "A hiperalbuminemia verdadeira (albumina sérica >5,0 g/dL) é incomum e geralmente representa desidratação ou hemoconcentração, não refletindo aumento absoluto da massa de albumina corporal. Os mecanismos envolvem perda de água livre desproporcional à perda de proteínas, resultando em concentração relativa da albumina plasmática. Causas comuns incluem desidratação por redução da ingesta hídrica (particularmente em idosos com alteração do mecanismo de sede), perdas gastrintestinais (vômitos, diarreia sem reposição adequada), perdas renais (diabetes insipidus, diurese osmótica), perdas insensíveis aumentadas (febre, hiperventilação, sudorese excessiva em ambientes quentes), e uso excessivo de diuréticos sem reposição adequada de fluidos. Em alguns casos, a hemoconcentração pode ocorrer em situações de sequestro de líquidos no terceiro espaço, como em obstrução intestinal ou pancreatite aguda, onde o volume plasmático efetivo está reduzido apesar de retenção corporal total de líquidos. A hiperalbuminemia factícia pode ocorrer por coleta inadequada de amostra (garroteamento prolongado, hemoconcentração local) ou erro laboratorial. É importante distinguir a hiperalbuminemia verdadeira de elevações em outras proteínas plasmáticas, como na gamopatia monoclonal, onde a albumina pode estar normal ou reduzida. A interpretação da hiperalbuminemia deve sempre considerar o contexto clínico, sinais de desidratação (mucosas secas, turgor cutâneo reduzido, hipotensão ortostática), e outros marcadores laboratoriais de hemoconcentração (hematócrito elevado, ureia desproporcional à creatinina).",

        "clinical_significance": "A albumina sérica é um dos marcadores bioquímicos mais importantes na prática clínica, refletindo múltiplos aspectos da homeostase fisiológica. Valores normais variam entre 3,5-5,0 g/dL, podendo haver pequenas variações entre laboratórios. Na avaliação nutricional, a albumina é considerada um marcador de desnutrição proteico-calórica crônica, embora tenha limitações por sua longa meia-vida e influência de processos inflamatórios. Valores <3,0 g/dL indicam desnutrição moderada, e <2,5 g/dL desnutrição grave, correlacionando-se com aumento de morbimortalidade, complicações pós-operatórias, retardo na cicatrização, e resposta imunológica comprometida. Na avaliação de hepatopatias, a albumina é um componente essencial de escores prognósticos como Child-Pugh e MELD, refletindo a capacidade de síntese hepática e correlacionando-se com sobrevida. Em doenças renais, a hipoalbuminemia na síndrome nefrótica correlaciona-se com o grau de proteinúria e risco de complicações tromboembólicas. A albumina também é utilizada no cálculo do gradiente de albumina sérica-ascite (GASA), fundamental para investigação etiológica de ascite (GASA ≥1,1 g/dL indica hipertensão portal). Na medicina intensiva, a hipoalbuminemia é marcador de gravidade em sepse, preditor de mortalidade, e associada a maior tempo de ventilação mecânica e internação hospitalar. A correção da hipoalbuminemia com infusões de albumina é controversa, sendo indicada principalmente em situações específicas como paracentese volumosa, síndrome hepatorrenal, e algumas situações de choque refratário. A interpretação da albumina deve sempre considerar o contexto clínico completo, incluindo marcadores inflamatórios (proteína C reativa), função renal e hepática, e estado volêmico.",

        "interpretation_guide": "Na interpretação da dosagem de albumina sérica, é fundamental considerar os valores de referência (tipicamente 3,5-5,0 g/dL), variações fisiológicas, e contexto clínico. Valores entre 3,0-3,5 g/dL sugerem hipoalbuminemia leve, entre 2,5-3,0 g/dL moderada, e <2,5 g/dL grave. A albumina pode estar falsamente reduzida em gestação (hemodiluição fisiológica), posição supina prolongada durante coleta, e imediatamente após administração de fluidos intravenosos. Quando encontrada hipoalbuminemia, o primeiro passo é verificar as proteínas totais: se ambas estão reduzidas, considerar perdas proteicas (síndrome nefrótica, enteropatia) ou desnutrição; se apenas a albumina está reduzida com globulinas normais ou elevadas, pensar em hepatopatia ou inflamação. A investigação deve incluir: proteinúria de 24 horas (síndrome nefrótica se >3,5 g/dia), provas de função hepática (TGO, TGP, bilirrubinas, tempo de protrombina), marcadores inflamatórios (PCR, VHS), eletroforese de proteínas (padrão de gamopatia, perda proteica), e avaliação nutricional. Em pacientes críticos, valores <2,5 g/dL associam-se a prognóstico reservado e maior risco de complicações. A albumina deve ser solicitada em avaliação pré-operatória (preditor de complicações), seguimento de hepatopatias crônicas, investigação de edema/ascite, avaliação nutricional em doenças crônicas, e monitorização de pacientes em terapia nutricional. A decisão de repor albumina exógena deve considerar a etiologia (ineficaz em desnutrição ou inflamação crônica), gravidade (geralmente indicada se <2,0 g/dL com edema/ascite), e situações específicas (paracentese >5L, síndrome hepatorrenal, choque séptico refratário em alguns casos).",

        "recommendations": [
            "Solicitar albumina sérica como parte da avaliação nutricional em pacientes com doenças crônicas, desnutrição suspeita, ou em preparo pré-operatório de cirurgias de grande porte",
            "Avaliar em conjunto com proteína C reativa (PCR) para diferenciar desnutrição (albumina baixa, PCR normal) de processo inflamatório (ambos alterados)",
            "Em hipoalbuminemia, investigar perdas renais com proteinúria de 24 horas e perdas gastrintestinais com calprotectina fecal e endoscopia se indicado",
            "Monitorar albumina sérica em pacientes cirróticos a cada 3-6 meses como parte da avaliação prognóstica (escore de Child-Pugh)",
            "Considerar albumina como marcador prognóstico em pacientes críticos, mas não como alvo isolado de terapia de reposição",
            "Em pacientes com síndrome nefrótica e albumina <2,0 g/dL, avaliar risco tromboembólico aumentado e considerar anticoagulação profilática",
            "Repetir dosagem após 2-4 semanas em pacientes em terapia nutricional para avaliar resposta (melhora lenta esperada devido à meia-vida longa)",
            "Na presença de ascite, calcular o gradiente de albumina sérica-ascite (GASA) para investigação etiológica"
        ],

        "related_conditions": [
            "Cirrose hepática",
            "Síndrome nefrótica",
            "Desnutrição proteico-calórica",
            "Doença inflamatória intestinal",
            "Linfangiectasia intestinal",
            "Sepse e síndrome de resposta inflamatória sistêmica",
            "Síndrome de má-absorção intestinal",
            "Queimaduras extensas",
            "Neoplasias avançadas",
            "Insuficiência cardíaca congestiva"
        ],

        "patient_friendly_explanation": "A albumina é a principal proteína presente no sangue, produzida pelo fígado. Ela tem várias funções importantes: ajuda a manter o líquido dentro dos vasos sanguíneos (evitando inchaço), transporta medicamentos e hormônios pelo corpo, e fornece nutrição aos tecidos. Este exame mede a quantidade de albumina no sangue e é útil para avaliar se o fígado está funcionando bem, se você está recebendo nutrição adequada, e se há perda de proteínas pelos rins ou intestino. Valores baixos podem indicar problemas no fígado, desnutrição, inflamação crônica, ou perda de proteínas pelos rins (como na síndrome nefrótica) ou pelo intestino. Quando a albumina está baixa, pode haver inchaço nas pernas e barriga devido ao acúmulo de líquido. Valores muito altos são raros e geralmente indicam desidratação. O resultado deve ser interpretado junto com outros exames e sua condição clínica geral. Se sua albumina estiver alterada, seu médico pode solicitar exames adicionais para identificar a causa e planejar o tratamento apropriado, que pode incluir melhora da nutrição, tratamento da doença de base, ou em alguns casos, reposição de albumina."
    },

    "Alfa-1 Globulina": {
        "clinical_explanation": "A alfa-1 globulina é uma fração proteica sérica identificada por eletroforese de proteínas, compreendendo principalmente a alfa-1-antitripsina (AAT), que representa aproximadamente 90% desta fração, além de alfa-1-glicoproteína ácida (orosomucoide), alfa-1-lipoproteína (HDL), protrombina, transcortina e tiroglobulina. A alfa-1-antitripsina é uma glicoproteína de 52 kDa sintetizada principalmente pelos hepatócitos e macrófagos, pertencente à família das serpinas (serine protease inhibitors). Sua principal função fisiológica é inibir elastase neutrofílica e outras proteases séricas, protegendo tecidos da degradação por enzimas liberadas durante processos inflamatórios, particularmente no pulmão. A AAT constitui uma proteína de fase aguda positiva, com níveis elevando-se 3-4 vezes durante processos inflamatórios ou infecciosos sob estímulo de citocinas como IL-6 e IL-1. A deficiência genética de alfa-1-antitripsina (Déficit de AAT) é uma condição autossômica codominante causada por mutações no gene SERPINA1, resultando em produção reduzida ou formas defeituosas da proteína. Os fenótipos mais comuns são PiMM (normal), PiMZ (deficiência leve) e PiZZ (deficiência grave <35% dos valores normais). A deficiência de AAT predispõe a enfisema pulmonar precoce (especialmente em fumantes), doença hepática (hepatite neonatal, cirrose), e raramente paniculite necrosante e vasculites. A avaliação da fração alfa-1 globulina na eletroforese de proteínas pode sugerir deficiência de AAT quando reduzida, embora a dosagem específica de alfa-1-antitripsina e fenotipagem sejam necessárias para confirmação diagnóstica.",

        "low_explanation": "A redução da fração alfa-1 globulina na eletroforese de proteínas sugere principalmente deficiência de alfa-1-antitripsina, podendo ser de origem genética ou adquirida. A deficiência genética de AAT resulta de mutações no gene SERPINA1, sendo a deficiência hereditária mais comum em caucasianos (1:2.500-5.000). O fenótipo PiZZ é o mais grave, com níveis de AAT <35% do normal, predispondo a enfisema pulmonar precoce (terceira-quarta década em fumantes, quinta-sexta década em não fumantes) de predomínio em bases pulmonares, hepatopatia crônica (cirrose infantil, cirrose em adultos, hepatocarcinoma), e raramente paniculite necrosante. Heterozigotos PiMZ têm risco discretamente aumentado de doença pulmonar, especialmente se fumantes. A deficiência adquirida pode ocorrer em hepatopatias graves (cirrose avançada, hepatite fulminante) devido à redução da síntese hepática, síndrome nefrótica com perdas proteicas maciças, enteropatia perdedora de proteínas, ou desnutrição grave. Em síndrome do desconforto respiratório agudo (SDRA) e sepse, pode haver consumo aumentado de AAT devido à liberação excessiva de elastase neutrofílica. A deficiência de AAT resulta em desequilíbrio entre proteases e antiproteases no pulmão, levando à destruição descontrolada do tecido elástico pulmonar pelos neutrófilos. No fígado, os mecanismos incluem acúmulo de proteína Z mutante nos hepatócitos (fenômeno gain-of-function), causando estresse do retículo endoplasmático e lesão hepatocelular. A investigação de alfa-1 globulina reduzida deve incluir dosagem quantitativa de alfa-1-antitripsina, fenotipagem (PiMM, PiMZ, PiZZ, etc.), genotipagem se indicado, provas de função pulmonar, e tomografia computadorizada de tórax em pacientes sintomáticos.",

        "high_explanation": "O aumento da fração alfa-1 globulina na eletroforese de proteínas geralmente reflete elevação de proteínas de fase aguda, principalmente alfa-1-antitripsina e alfa-1-glicoproteína ácida, em resposta a processos inflamatórios, infecciosos ou neoplásicos. Durante a resposta de fase aguda, citocinas pró-inflamatórias (IL-6, IL-1, TNF-α) estimulam os hepatócitos a aumentar a síntese de proteínas de fase aguda, incluindo a alfa-1-antitripsina, que pode elevar-se 3-4 vezes acima dos valores basais. Condições associadas incluem infecções bacterianas agudas ou crônicas, processos inflamatórios sistêmicos (artrite reumatoide, doença inflamatória intestinal, vasculites), neoplasias (especialmente linfomas e alguns carcinomas), trauma extenso, queimaduras, cirurgias de grande porte, e infarto agudo do miocárdio. A alfa-1-glicoproteína ácida (orosomucoide) também aumenta em processos inflamatórios e tem propriedades imunomoduladoras. Em gestação, há aumento fisiológico da fração alfa-1 devido à elevação de proteínas transportadoras e proteínas de fase aguda. Em doenças hepáticas compensadas, pode haver aumento paradoxal de algumas proteínas de fase aguda enquanto a albumina está reduzida. O aumento isolado de alfa-1 globulina sem elevação concomitante de alfa-2 globulina é menos comum e pode sugerir condições específicas. A interpretação deve considerar o padrão completo da eletroforese de proteínas: elevação de alfa-1 e alfa-2 sugere inflamação aguda; elevação de alfa-1, alfa-2 e gama sugere inflamação crônica com resposta imune. A confirmação com marcadores inflamatórios específicos (proteína C reativa, velocidade de hemossedimentação) e investigação da causa subjacente são essenciais.",

        "clinical_significance": "A avaliação da fração alfa-1 globulina tem importância clínica principalmente na triagem de deficiência de alfa-1-antitripsina e na avaliação de processos inflamatórios. Valores normais variam entre 0,1-0,4 g/dL ou 2-5% das proteínas totais, dependendo do método laboratorial. A principal aplicação clínica é na suspeita de deficiência de AAT, que deve ser considerada em: pacientes com enfisema precoce (<45 anos), enfisema de predomínio basal, DPOC em não fumantes ou com tabagismo leve, doença hepática crônica de causa indeterminada, hepatite neonatal, história familiar de enfisema ou hepatopatia, paniculite necrosante, ou vasculite c-ANCA positiva. A eletroforese de proteínas mostrando redução da fração alfa-1 (<0,1 g/dL ou <2%) é sugestiva mas não diagnóstica, requerendo confirmação com dosagem quantitativa de alfa-1-antitripsina (valores normais 90-200 mg/dL; deficiência grave <57 mg/dL) e fenotipagem. O rastreamento de familiares de pacientes com deficiência de AAT é recomendado. Em pacientes com deficiência confirmada, o manejo inclui cessação rigorosa do tabagismo (fator modificável mais importante), vacinação contra pneumococo e influenza, broncodilatadores conforme sintomas, terapia de reposição de AAT em casos selecionados (enfisema progressivo com AAT <57 mg/dL), e transplante pulmonar em casos avançados. O aumento da fração alfa-1 tem menor especificidade diagnóstica, refletindo geralmente processos inflamatórios inespecíficos, sendo mais útil em conjunto com outras frações proteicas e marcadores inflamatórios para caracterizar o tipo e cronicidade do processo inflamatório.",

        "interpretation_guide": "Na interpretação da fração alfa-1 globulina, é essencial considerar o contexto clínico e correlacionar com outras frações proteicas na eletroforese. Valores normais são tipicamente 0,1-0,4 g/dL ou 2-5% das proteínas totais. Alfa-1 reduzida (<0,1 g/dL ou <2%) sugere deficiência de alfa-1-antitripsina e requer dosagem quantitativa específica de AAT. Em pacientes com AAT <140 mg/dL, considerar fenotipagem (PiMM normal, PiMZ heterozigoto, PiZZ homozigoto). Alfa-1 aumentada (>0,4 g/dL ou >5%) geralmente reflete processos inflamatórios; quando associada a aumento de alfa-2, sugere inflamação aguda; quando acompanhada de aumento de gama-globulinas, sugere processo inflamatório crônico. A eletroforese de proteínas deve ser solicitada em: investigação de enfisema precoce ou em não fumantes, hepatopatia crônica de etiologia indeterminada, avaliação de processos inflamatórios crônicos, investigação de gamopatias monoclonais, avaliação de edema sem causa aparente, e síndrome nefrótica. Quando a deficiência de AAT é confirmada (AAT <57 mg/dL, fenótipo PiZZ), avaliar função pulmonar com espirometria e tomografia de tórax (enfisema basal característico), enzimas hepáticas, e considerar terapia de reposição em casos específicos. A cessação do tabagismo é IMPERATIVA em pacientes com deficiência de AAT. Em pacientes com alfa-1 elevada, investigar causa inflamatória subjacente com história clínica detalhada, exame físico, PCR, VHS, e exames direcionados conforme suspeita (infecção, doença autoimune, neoplasia). Repetir eletroforese após 4-8 semanas pode ajudar a diferenciar processos agudos (normalização esperada) de crônicos (persistência de alterações).",

        "recommendations": [
            "Solicitar eletroforese de proteínas com dosagem de frações em pacientes com enfisema precoce (<45 anos), enfisema em não fumantes, ou DPOC com características atípicas",
            "Em alfa-1 globulina reduzida (<0,1 g/dL), solicitar dosagem quantitativa de alfa-1-antitripsina e fenotipagem para confirmar deficiência",
            "Rastrear familiares de primeiro grau de pacientes com deficiência confirmada de alfa-1-antitripsina (padrão PiZZ ou PiSZ)",
            "Em deficiência confirmada de AAT, realizar espirometria anualmente e tomografia de tórax a cada 2-3 anos para monitorar progressão de enfisema",
            "Orientar rigorosamente pacientes com deficiência de AAT sobre a NECESSIDADE ABSOLUTA de cessação do tabagismo e evitar exposições ocupacionais a poeiras e fumos",
            "Considerar terapia de reposição de alfa-1-antitripsina (infusões semanais de AAT purificada) em pacientes com fenótipo PiZZ, AAT <57 mg/dL, e enfisema progressivo",
            "Em alfa-1 globulina elevada, investigar processo inflamatório subjacente e correlacionar com proteína C reativa e outras frações proteicas",
            "Vacinar pacientes com deficiência de AAT contra pneumococo (PCV13 e PPSV23) e influenza anualmente para prevenção de exacerbações pulmonares"
        ],

        "related_conditions": [
            "Deficiência de alfa-1-antitripsina",
            "Enfisema pulmonar precoce",
            "Doença pulmonar obstrutiva crônica (DPOC)",
            "Cirrose hepática por deficiência de AAT",
            "Hepatite neonatal colestática",
            "Paniculite necrosante",
            "Processos inflamatórios agudos e crônicos",
            "Infecções bacterianas",
            "Neoplasias (linfomas, carcinomas)",
            "Síndrome nefrótica"
        ],

        "patient_friendly_explanation": "A alfa-1 globulina é um grupo de proteínas no sangue, sendo a principal delas a alfa-1-antitripsina (AAT), produzida pelo fígado. A função mais importante da AAT é proteger os pulmões da destruição por enzimas liberadas pelas células de defesa durante inflamações. Ela age como um 'escudo' protetor para o tecido pulmonar. Este exame mede a quantidade dessas proteínas e é especialmente importante para detectar a deficiência de alfa-1-antitripsina, uma condição hereditária que pode levar ao desenvolvimento precoce de enfisema pulmonar (principalmente em fumantes) e, em alguns casos, doença no fígado. Valores baixos podem indicar deficiência genética de AAT, que é importante diagnosticar porque requer cuidados especiais, especialmente evitar o tabagismo de forma absoluta. Valores altos geralmente indicam inflamação ou infecção no corpo. Se o resultado sugerir deficiência de AAT, exames adicionais mais específicos serão solicitados para confirmar o diagnóstico, e pode ser recomendado investigar outros membros da família. O tratamento da deficiência de AAT inclui obrigatoriamente parar de fumar, vacinações, medicamentos para os sintomas respiratórios, e em casos específicos, pode ser indicado tratamento de reposição da proteína deficiente."
    },

    "Alfa-2 Globulina": {
        "clinical_explanation": "A alfa-2 globulina é uma fração proteica sérica identificada por eletroforese de proteínas, composta principalmente por haptoglobina (45-50%), alfa-2-macroglobulina (25-30%), ceruloplasmina (5-10%), alfa-2-antiplasmina, e apolipoproteínas. Essas proteínas desempenham funções diversas e essenciais na homeostase. A haptoglobina é uma proteína de fase aguda que se liga à hemoglobina livre liberada por hemólise intravascular, formando complexos que são rapidamente removidos pelo sistema reticuloendotelial, prevenindo perda de ferro renal e dano oxidativo. A alfa-2-macroglobulina é um inibidor de amplo espectro de proteases (tripsina, plasmina, trombina), importante na modulação de processos inflamatórios e coagulação, além de transportar citocinas e fatores de crescimento. A ceruloplasmina é a principal proteína transportadora de cobre no plasma, possuindo também atividade oxidase essencial no metabolismo do ferro, facilitando sua incorporação à transferrina. Durante processos inflamatórios agudos ou crônicos, citocinas pró-inflamatórias (IL-6, IL-1) estimulam a síntese hepática de proteínas de fase aguda, resultando em elevação da fração alfa-2 globulina. A alfa-2-macroglobulina aumenta particularmente em síndrome nefrótica, sendo a principal responsável pelo aumento de alfa-2 nesta condição, enquanto haptoglobina está reduzida em hemólise intravascular. A avaliação da fração alfa-2 globulina fornece informações sobre processos inflamatórios, hemólise, síndrome nefrótica e, quando reduzida, pode sugerir doença de Wilson (deficiência de ceruloplasmina) ou hemólise.",

        "low_explanation": "A redução da fração alfa-2 globulina é menos comum que sua elevação e geralmente reflete diminuição de um dos seus principais componentes. A causa mais importante é a hemólise intravascular, onde há consumo de haptoglobina para ligação com hemoglobina livre, resultando em depleção de haptoglobina e redução da fração alfa-2. Mecanismos de hemólise incluem hemólise autoimune (anemia hemolítica autoimune, doença hemolítica do recém-nascido), hemólise mecânica (próteses valvares cardíacas, microangiopatia trombótica, hemoglobinúria paroxística noturna), hemoglobinopatias (anemia falciforme, talassemia maior), infecções (malária, clostridium), e hemólise induzida por drogas. Em hemólise grave, a haptoglobina pode estar indetectável, e a redução de alfa-2 na eletroforese pode ser o primeiro indicativo laboratorial. A doença de Wilson (degeneração hepatolenticular) é outra causa importante de alfa-2 reduzida, causada por mutações no gene ATP7B que codifica uma ATPase transportadora de cobre. A deficiência resulta em redução de ceruloplasmina sérica (<20 mg/dL) e acúmulo tóxico de cobre no fígado, cérebro (gânglios da base), córnea (anel de Kayser-Fleischer), e outros órgãos. Manifestações incluem hepatopatia (hepatite aguda, hepatite crônica, cirrose), sintomas neuropsiquiátricos (tremor, disartria, distonia, alterações de personalidade), e anemia hemolítica. Hepatopatias graves podem reduzir a síntese de alfa-2 globulinas por insuficiência hepatocelular. Desnutrição proteico-calórica grave e má-absorção intestinal também podem reduzir a síntese dessas proteínas. A investigação de alfa-2 reduzida deve incluir marcadores de hemólise (LDH, bilirrubina indireta, reticulócitos, haptoglobina sérica), dosagem de ceruloplasmina, cobre sérico e urinário em 24 horas, exame oftalmológico com lâmpada de fenda (anel de Kayser-Fleischer), e avaliação hepática.",

        "high_explanation": "O aumento da fração alfa-2 globulina é comum e geralmente reflete processos inflamatórios agudos ou crônicos (elevação de haptoglobina), síndrome nefrótica (elevação pronunciada de alfa-2-macroglobulina), ou condições específicas. Na resposta de fase aguda a infecções, trauma, infarto do miocárdio, cirurgias, queimaduras, ou doenças inflamatórias crônicas (artrite reumatoide, doença inflamatória intestinal, vasculites), há aumento de 2-4 vezes nos níveis de haptoglobina. Na síndrome nefrótica, a elevação da fração alfa-2 é particularmente pronunciada e característica, resultando do aumento seletivo de alfa-2-macroglobulina. O mecanismo envolve perda preferencial de proteínas de menor peso molecular (albumina, IgG) pela barreira glomerular alterada, com retenção de proteínas de alto peso molecular como alfa-2-macroglobulina (720 kDa), resultando em aumento relativo. Adicionalmente, há aumento da síntese hepática compensatória de alfa-2-macroglobulina. O padrão eletroforético na síndrome nefrótica mostra albumina reduzida, alfa-1 normal ou discretamente elevada, alfa-2 marcadamente elevada (pode duplicar), beta variável, e gama geralmente reduzida. Em neoplasias, particularmente linfomas, mieloma múltiplo, carcinomas metastáticos, e leucemias, pode haver aumento de alfa-2 globulina como parte da resposta inflamatória paraneoplásica. Em diabetes mellitus descompensado, há aumento de haptoglobina e ceruloplasmina. Gravidez causa aumento fisiológico de ceruloplasmina (estimulada por estrogênio). Hipertireoidismo pode elevar ceruloplasmina. A interpretação deve considerar o padrão completo da eletroforese e correlação clínica.",

        "clinical_significance": "A avaliação da fração alfa-2 globulina tem importância clínica principalmente na identificação de síndrome nefrótica, processos inflamatórios, e hemólise. Valores normais variam entre 0,5-1,0 g/dL ou 7-13% das proteínas totais. O aumento pronunciado de alfa-2 (>1,2 g/dL ou >15%) com redução de albumina e gama-globulinas é altamente sugestivo de síndrome nefrótica, devendo-se prosseguir com proteinúria de 24 horas (>3,5 g/dia confirma síndrome nefrótica), perfil lipídico (hipercolesterolemia e hipertrigliceridemia frequentes), e investigação etiológica com biópsia renal. Aumento moderado de alfa-2 com aumento concomitante de alfa-1 sugere processo inflamatório agudo, enquanto aumento de alfa-1, alfa-2 e gama sugere processo inflamatório crônico. A redução de alfa-2 (<0,5 g/dL ou <7%) deve levantar suspeita de hemólise intravascular, sendo necessário avaliar marcadores de hemólise: LDH elevado, bilirrubina indireta elevada, haptoglobina sérica reduzida ou ausente, reticulocitose, e esfregaço de sangue periférico (esquizócitos em hemólise mecânica, esferócitos em autoimune). A dosagem específica de haptoglobina (<25 mg/dL confirma hemólise significativa) complementa a avaliação. Em suspeita de doença de Wilson (pacientes jovens com hepatopatia, sintomas neurológicos, ou história familiar), a redução de alfa-2 deve ser investigada com dosagem de ceruloplasmina (<20 mg/dL sugestivo), cobre sérico (total reduzido, mas cobre livre aumentado), cobre urinário de 24 horas (>100 mcg/dia), exame oftalmológico para anel de Kayser-Fleischer, e genotipagem se disponível. A eletroforese de proteínas é útil como exame de triagem que pode direcionar investigações mais específicas.",

        "interpretation_guide": "Na interpretação da fração alfa-2 globulina, considerar valores de referência (0,5-1,0 g/dL ou 7-13%), padrão das demais frações, e contexto clínico. Alfa-2 aumentada (>1,0 g/dL ou >13%): se muito elevada (>1,5 g/dL ou >18%) com albumina baixa, pensar em síndrome nefrótica; se moderadamente elevada com alfa-1 também elevada, considerar inflamação aguda; se elevada com gama também aumentada, pensar em inflamação crônica. Alfa-2 reduzida (<0,5 g/dL ou <7%): solicitar marcadores de hemólise (LDH, bilirrubina indireta, reticulócitos, haptoglobina sérica, esfregaço periférico); se hemólise descartada, considerar doença de Wilson com dosagem de ceruloplasmina, cobre sérico e urinário, e avaliação oftalmológica. A eletroforese de proteínas deve ser solicitada em: investigação de síndrome nefrótica (proteinúria maciça, edema, hipoalbuminemia), avaliação de processos inflamatórios crônicos, suspeita de hemólise (anemia com LDH elevado), investigação de hepatopatia em pacientes jovens (pensar Wilson), rastreamento de gamopatias monoclonais, e avaliação de edema de causa indeterminada. Em síndrome nefrótica confirmada, investigar etiologia: glomérulo esclerose segmentar e focal, doença de lesões mínimas, glomerulonefrite membranosa, nefropatia diabética, amiloidose, todas requerem biópsia renal para diagnóstico definitivo. Em hemólise confirmada, diferenciar mecanismo: teste de Coombs direto (autoimune se positivo), hemoglobina eletroforese (hemoglobinopatias), enzimas eritrocitárias (deficiência G6PD, piruvato quinase), teste de Ham (hemoglobinúria paroxística noturna). Em doença de Wilson suspeita, a confirmação requer critérios de Leipzig (sistema de pontos considerando ceruloplasmina, cobre, anel de Kayser-Fleischer, sintomas, e genética).",

        "recommendations": [
            "Solicitar eletroforese de proteínas em pacientes com proteinúria significativa, edema, ou hipoalbuminemia para identificar padrão de síndrome nefrótica",
            "Em alfa-2 globulina muito elevada (>1,5 g/dL) com albumina baixa, solicitar proteinúria de 24 horas e considerar biópsia renal para diagnóstico de glomerulopatia",
            "Em alfa-2 reduzida, solicitar painel de hemólise completo: LDH, bilirrubina total e frações, haptoglobina sérica, reticulócitos, e esfregaço de sangue periférico",
            "Considerar doença de Wilson em pacientes <40 anos com hepatopatia de causa indeterminada ou sintomas neuropsiquiátricos e alfa-2 reduzida, solicitando ceruloplasmina e cobre",
            "Monitorar alfa-2 globulina em pacientes com síndrome nefrótica para avaliar resposta ao tratamento imunossupressor (normalização gradual esperada)",
            "Em processos inflamatórios crônicos com alfa-2 elevada persistente, investigar doença de base (autoimune, neoplásica, infecciosa crônica) com exames direcionados",
            "Avaliar alfa-2 globulina em pacientes com próteses valvares cardíacas e anemia, pois hemólise mecânica crônica é comum e pode reduzir alfa-2 e haptoglobina",
            "Repetir eletroforese após tratamento da condição subjacente para confirmar normalização das frações proteicas"
        ],

        "related_conditions": [
            "Síndrome nefrótica (glomeruloesclerose focal e segmentar, doença de lesões mínimas, glomerulonefrite membranosa)",
            "Hemólise intravascular (anemia hemolítica autoimune, próteses valvares, microangiopatia trombótica)",
            "Doença de Wilson (degeneração hepatolenticular)",
            "Processos inflamatórios agudos (infecções, trauma, infarto agudo do miocárdio, cirurgias)",
            "Doenças inflamatórias crônicas (artrite reumatoide, doença inflamatória intestinal, vasculites)",
            "Neoplasias (linfomas, mieloma múltiplo, carcinomas)",
            "Diabetes mellitus descompensado",
            "Gravidez (elevação fisiológica)",
            "Hepatopatias graves",
            "Desnutrição proteico-calórica"
        ],

        "patient_friendly_explanation": "A alfa-2 globulina é um conjunto de proteínas presentes no sangue que desempenham diversas funções importantes. As principais são: a haptoglobina, que captura hemoglobina liberada quando hemácias se rompem, protegendo os rins; a alfa-2-macroglobulina, que ajuda a controlar inflamações; e a ceruloplasmina, que transporta cobre pelo corpo. Este exame mede a quantidade dessas proteínas e é útil para identificar várias condições. Valores aumentados podem indicar problemas nos rins (especialmente síndrome nefrótica, onde os rins perdem muita proteína), inflamações ou infecções no corpo, ou gravidez (aumento normal). Valores diminuídos podem indicar destruição de hemácias (hemólise), onde as células do sangue se rompem, ou doença de Wilson, uma condição genética rara onde o cobre se acumula no corpo. Na síndrome nefrótica, além do aumento da alfa-2 globulina, você pode ter inchaço nas pernas e rosto, urina espumosa (devido à perda de proteínas), e colesterol elevado. Se houver hemólise, você pode ter anemia, urina escura, e icterícia (pele amarelada). O resultado deste exame deve ser interpretado junto com outros exames e seus sintomas, e seu médico pode solicitar testes adicionais conforme necessário para identificar a causa e planejar o tratamento apropriado."
    },

    "Alfafetoproteína": {
        "clinical_explanation": "A alfafetoproteína (AFP) é uma glicoproteína oncofetal com peso molecular de aproximadamente 70 kDa, pertencente à família das albuminas. Durante o desenvolvimento fetal, a AFP é a principal proteína sérica, sendo sintetizada principalmente pelo saco vitelínico até a 12ª semana de gestação, e posteriormente pelo fígado e trato gastrintestinal fetais. A AFP desempenha funções importantes no feto, incluindo transporte de substâncias (ácidos graxos, esteroides, bilirrubina), modulação do crescimento celular, e propriedades imunorreguladoras. Após o nascimento, os níveis de AFP declinam rapidamente, atingindo valores adultos (<10-15 ng/mL) por volta de 8-12 meses de idade. Em adultos, a AFP é normalmente indetectável ou presente em níveis muito baixos, sendo produzida em pequenas quantidades pelo fígado. A reexpressão de AFP em adultos ocorre principalmente em condições de regeneração hepática intensa e em neoplasias, tornando-a um marcador tumoral importante. A AFP é utilizada clinicamente em três contextos principais: (1) como marcador tumoral para hepatocarcinoma e tumores de células germinativas, (2) no rastreamento pré-natal de defeitos do tubo neural e síndrome de Down, e (3) na avaliação de hepatopatias crônicas com risco de malignização. Valores de AFP devem ser interpretados considerando idade, condição clínica, e presença de hepatopatia de base. A meia-vida da AFP é de aproximadamente 5-7 dias, permitindo seu uso no monitoramento de resposta terapêutica em neoplasias AFP-secretoras.",

        "low_explanation": "Valores baixos ou indetectáveis de alfafetoproteína (<10 ng/mL) são considerados normais em adultos não gestantes, representando o estado fisiológico esperado. Níveis baixos de AFP não têm significado clínico patológico em adultos e não requerem investigação adicional. Durante a gestação, níveis de AFP materna baixos (abaixo do percentil 0,5 para idade gestacional) podem estar associados a síndrome de Down (trissomia do 21), trissomia do 18 (síndrome de Edwards), e outras aneuploidias cromossômicas. O mecanismo proposto envolve produção reduzida de AFP pelo feto afetado. Na avaliação pré-natal moderna, a AFP materna faz parte do teste triplo (AFP, hCG, estriol não conjugado) ou teste quádruplo (adicionando inibina A) no segundo trimestre (15-20 semanas) para rastreamento de aneuploidias. AFP baixa isolada tem baixa especificidade, e o resultado é geralmente expresso como múltiplos da mediana (MoM), sendo considerado baixo se <0,5 MoM. Causas não patológicas de AFP materna baixa incluem erro na datação da gestação (gestação mais recente que estimada), obesidade materna (efeito de diluição), e diabetes mellitus. Gestações gemelares têm AFP mais elevada, e a interpretação deve ser ajustada. Um resultado de rastreamento anormal (AFP baixa em conjunto com outros marcadores alterados) não é diagnóstico e requer confirmação com ultrassonografia morfológica detalhada e, se indicado, teste invasivo (amniocentese ou biópsia de vilo corial) para cariótipo fetal. É importante ressaltar que o teste de rastreamento apenas identifica gestações de maior risco, não sendo diagnóstico definitivo.",

        "high_explanation": "A elevação da alfafetoproteína em adultos não gestantes (>10-20 ng/mL) é sempre patológica e requer investigação. As principais causas incluem hepatocarcinoma (carcinoma hepatocelular - CHC), tumores de células germinativas, regeneração hepática intensa, e hepatopatias crônicas. O hepatocarcinoma é a principal causa de AFP muito elevada (>400 ng/mL), com sensibilidade de 60-70% e especificidade >90% quando AFP >200 ng/mL. O mecanismo envolve reexpressão do gene da AFP pelas células neoplásicas hepatocíticas, refletindo desdiferenciação celular. Aproximadamente 20-30% dos CHC não secretam AFP (AFP-negativos), sendo necessário complementar com outros marcadores (des-gama-carboxi-protrombina - DCP) e exames de imagem. Tumores de células germinativas (teratomas não seminomatosos, carcinoma embrionário, tumor de saco vitelínico) frequentemente secretam AFP, sendo útil para diagnóstico, estadiamento e monitoramento. Hepatites agudas e crônicas podem elevar AFP (geralmente <500 ng/mL) durante períodos de necrose e regeneração hepatocelular intensa. Cirrose hepática de qualquer etiologia apresenta AFP elevada em 15-30% dos casos, geralmente <100 ng/mL, relacionada à regeneração nodular. Na gestação, AFP materna elevada (>2,0-2,5 MoM) associa-se a defeitos do tubo neural (anencefalia, espinha bífida aberta, encefalocele), defeitos da parede abdominal (gastrosquise, onfalocele), necrose hepática fetal, e morte fetal. Causas obstétricas de AFP elevada incluem gestação gemelar, ameaça de abortamento, oligoâmnio, e contaminação com sangue fetal. Outras neoplasias raramente elevam AFP: carcinomas gástrico, pancreático, pulmonar, e ovariano. A interpretação deve considerar magnitude da elevação, contexto clínico, e exames complementares.",

        "clinical_significance": "A AFP tem importância clínica fundamental como marcador tumoral e em obstetrícia. Em oncologia, os principais usos são: (1) Rastreamento de hepatocarcinoma em pacientes de alto risco (cirróticos, hepatite B/C crônica, esteato-hepatite não alcoólica com fibrose avançada): AFP semestral ou trimestral associada a ultrassonografia abdominal. Elevação progressiva de AFP em cirrótico, mesmo <200 ng/mL, aumenta significativamente o risco de CHC e requer investigação com TC ou RM com contraste multifásico. (2) Diagnóstico de CHC: AFP >400 ng/mL em contexto de nódulo hepático em cirrótico tem especificidade muito alta, dispensando biópsia em alguns casos. Valores <400 ng/mL requerem confirmação por imagem característica (realce arterial com washout portal/tardio) ou biópsia. (3) Estadiamento e prognóstico: AFP >400 ng/mL associa-se a tumores mais agressivos, invasão vascular, e pior prognóstico. Utilizad em sistemas de estadiamento como BCLC. (4) Monitoramento de tratamento: queda de 50% após 4-6 semanas indica resposta favorável; elevação sugere progressão. Meia-vida de 5-7 dias permite avaliação precoce. (5) Vigilância pós-tratamento: elevação de AFP após tratamento potencialmente curativo sugere recidiva. Em tumores de células germinativas, AFP é crucial para diagnóstico, classificação histológica, estadiamento, e monitoramento. Na obstetrícia, AFP faz parte do rastreamento pré-natal de aneuploidias (teste triplo/quádruplo) e defeitos do tubo neural. Valores da AFP devem ser interpretados com cautela em hepatopatas, considerando sempre a possibilidade de elevações benignas relacionadas à inflamação e regeneração.",

        "interpretation_guide": "Valores de referência para AFP em adultos não gestantes são geralmente <10-15 ng/mL, podendo variar entre laboratórios. Interpretação: AFP <20 ng/mL: normal em adultos, não requer investigação adicional. AFP 20-200 ng/mL: elevação leve-moderada, pode ocorrer em hepatites agudas/crônicas, cirrose hepática, regeneração hepatocelular. Investigar com enzimas hepáticas, sorologias virais, e ultrassonografia abdominal. Acompanhamento evolutivo é importante; elevação progressiva aumenta preocupação para CHC. AFP 200-400 ng/mL: elevação moderada-alta, sugestiva mas não diagnóstica de CHC. Requer investigação urgente com TC ou RM de abdome com contraste multifásico. Considerar também tumores de células germinativas (testicular em homens, ovariano em mulheres) com ultrassonografia testicular/pélvica. AFP >400 ng/mL: elevação muito alta, altamente sugestiva de CHC em paciente com hepatopatia crônica ou nódulo hepático. Em paciente jovem sem hepatopatia, considerar tumor de células germinativas (solicitar também beta-hCG, LDH, TC de tórax/abdome/pelve). Elevações extremas (>10.000 ng/mL) são típicas de hepatocarcinoma avançado ou tumor de saco vitelínico. Na gestação, AFP materna é medida em múltiplos da mediana (MoM): <0,5 MoM sugere aneuploidia; >2,5 MoM sugere defeito do tubo neural, requerendo ultrassonografia morfológica detalhada. Situações especiais: (1) Cirróticos com AFP persistentemente <20 ng/mL têm baixíssimo risco de CHC; entre 20-200 ng/mL, acompanhar trimestralmente com imagem; >200 ng/mL, investigar agressivamente. (2) Após ressecção/ablação de CHC, AFP deve normalizar em 4-6 semanas; persistência/elevação sugere doença residual. (3) Durante tratamento sistêmico de CHC, avaliar AFP a cada ciclo; elevação precoce (apesar de tratamento) indica refratariedade.",

        "recommendations": [
            "Solicitar AFP semestralmente em pacientes cirróticos ou com hepatite B/C crônica para rastreamento de hepatocarcinoma, sempre associada a ultrassonografia abdominal",
            "Em AFP >20 ng/mL em hepatopata crônico, realizar investigação com TC ou RM de abdome com contraste multifásico para descartar hepatocarcinoma",
            "Considerar tumores de células germinativas (testicular/ovariano) em pacientes jovens com AFP elevada sem hepatopatia, solicitando beta-hCG, LDH, e TC de tórax/abdome/pelve",
            "Monitorar AFP a cada 4-6 semanas durante tratamento oncológico para avaliar resposta (queda ≥50% sugere resposta favorável)",
            "Solicitar AFP no seguimento pós-tratamento de hepatocarcinoma ou tumores de células germinativas; elevação pode indicar recidiva antes de alterações radiológicas",
            "Em gestantes, solicitar AFP materna entre 15-20 semanas como parte do teste triplo/quádruplo para rastreamento de aneuploidias e defeitos do tubo neural",
            "AFP materna >2,5 MoM requer ultrassonografia morfológica detalhada para investigar defeitos do tubo neural e outras anomalias estruturais",
            "Evitar solicitar AFP isoladamente; sempre considerar contexto clínico, exames de imagem, e outros marcadores tumorais conforme suspeita diagnóstica"
        ],

        "related_conditions": [
            "Hepatocarcinoma (carcinoma hepatocelular)",
            "Tumores de células germinativas (tumor de saco vitelínico, carcinoma embrionário, teratoma não seminomatoso)",
            "Cirrose hepática (todas as etiologias)",
            "Hepatite B e C crônicas",
            "Esteato-hepatite não alcoólica (NASH) com fibrose avançada",
            "Hepatite aguda fulminante",
            "Defeitos do tubo neural (anencefalia, espinha bífida, encefalocele)",
            "Aneuploidias cromossômicas (síndrome de Down, síndrome de Edwards)",
            "Gastrosquise e onfalocele",
            "Neoplasias gastrointestinais (raramente)"
        ],

        "patient_friendly_explanation": "A alfafetoproteína (AFP) é uma proteína produzida normalmente pelo bebê durante a gravidez, mas que geralmente desaparece do sangue após o nascimento. Em adultos, níveis muito baixos ou indetectáveis são normais. Este exame é utilizado principalmente para duas finalidades importantes: detectar certos tipos de câncer (especialmente no fígado e testículos/ovários) e, durante a gravidez, rastrear problemas no desenvolvimento do bebê. Se você tem doença crônica no fígado (como cirrose ou hepatite B/C), seu médico pode solicitar este exame regularmente para detectar precocemente câncer de fígado (hepatocarcinoma). Valores elevados podem indicar câncer de fígado, tumores nos testículos ou ovários, ou em alguns casos, inflamação intensa no fígado. Durante a gravidez, valores muito altos podem sugerir problemas na coluna do bebê (espinha bífida) ou outros defeitos, enquanto valores muito baixos podem sugerir síndrome de Down, mas estes resultados precisam ser confirmados com ultrassonografia detalhada e outros exames. Se você está em tratamento para câncer que produz AFP, o exame ajuda a avaliar se o tratamento está funcionando (valores devem diminuir) ou se o câncer voltou após tratamento (valores sobem novamente). É importante entender que valores levemente elevados não significam necessariamente câncer, especialmente em pessoas com doenças do fígado, por isso seu médico avaliará o resultado junto com outros exames e sua condição geral."
    }
}

# Continua no próximo arquivo devido ao limite de tamanho...
