UPDATE score_items
SET
    clinical_relevance = 'A vitamina E (alfa-tocoferol) é o principal antioxidante lipossolúvel do organismo, essencial para proteção celular contra estresse oxidativo e danos causados por radicais livres. Sua ação se estende além da função antioxidante clássica, incluindo modulação da expressão gênica, metabolismo lipídico e funções neuromusculares. O alfa-tocoferol é crítico para manutenção da integridade de membranas celulares, especialmente em tecidos de alta demanda metabólica como sistema nervoso, muscular e cardiovascular. Valores séricos normais situam-se entre 5-18 mg/L, sendo que níveis abaixo de 5 mg/L indicam deficiência, embora a interpretação deva considerar o perfil lipídico, utilizando a relação alfa-tocoferol/lipídios totais (<0,8 mg/g) como indicador mais preciso em pacientes com hiperlipidemia. A deficiência verdadeira é rara em indivíduos saudáveis, ocorrendo principalmente em contextos de má absorção de gorduras (doença celíaca, fibrose cística, colestase crônica, doença de Crohn), abetalipoproteinemia e síndromes de malabsorção grave. Manifestações clínicas incluem neuropatia periférica progressiva, ataxia espinocerebelar, oftalmoplegia, retinopatia, fraqueza muscular profunda e, em casos extremos, cegueira e arritmias cardíacas. O papel terapêutico do alfa-tocoferol tem sido extensivamente estudado em esteatohepatite não alcoólica (NASH), onde metanálises demonstram redução significativa de transaminases (ALT, AST), melhora histológica de esteatose e inflamação lobular, embora sem impacto consistente na fibrose hepática. Estudos recentes revelaram atividades biológicas independentes de antioxidação, incluindo modulação da biossíntese de colesterol e regulação de genes específicos, com profundas implicações clínicas e translacionais.',

    patient_explanation = 'A vitamina E é uma vitamina encontrada em alimentos como óleos vegetais, nozes, sementes e vegetais de folhas verdes. Ela atua como um escudo protetor para as células do seu corpo, defendendo-as contra danos causados por substâncias chamadas radicais livres. Essa vitamina é especialmente importante para o bom funcionamento dos nervos, músculos e para manter seu sistema imunológico forte. O exame de sangue mede quanto de vitamina E você tem no corpo. Valores normais geralmente ficam entre 5 e 18 mg/L. A deficiência de vitamina E é rara em pessoas saudáveis, mas pode acontecer se você tem problemas para absorver gorduras da alimentação, como em doenças intestinais crônicas. Quando falta vitamina E, você pode apresentar fraqueza muscular, dificuldade para coordenar movimentos, formigamentos nas mãos e pés, problemas de visão e, em casos graves, dificuldade para andar. Se seus níveis estiverem baixos, o médico pode recomendar suplementação com cápsulas de vitamina E em doses específicas. É importante não tomar suplementos por conta própria em doses muito altas, pois isso pode aumentar o risco de sangramentos. A vitamina E também tem sido estudada para tratamento de problemas no fígado relacionados ao acúmulo de gordura (esteatose hepática), mostrando benefícios quando usada sob orientação médica.',

    conduct = 'Avaliação inicial: solicitar dosagem sérica de alfa-tocoferol em jejum de 8-12 horas, preferencialmente junto com perfil lipídico completo para cálculo da relação alfa-tocoferol/lipídios totais (normal >0,8 mg/g). Valores <5 mg/L ou relação <0,8 mg/g sugerem deficiência e exigem investigação de causa subjacente. Investigação etiológica: pesquisar condições de má absorção intestinal (dosagem de elastase fecal, gordura fecal, testes celíacos, calprotectina), doenças hepatobiliares (perfil hepático, ultrassom abdominal), fibrose cística (teste do suor, genética), abetalipoproteinemia (perfil lipídico com apolipoproteínas) e uso de medicamentos quelantes de gordura. Avaliar manifestações neurológicas com exame físico detalhado: reflexos osteotendinosos, propriocepção, marcha, movimentos oculares, força muscular e sensibilidade. Em casos com sinais neurológicos, considerar ressonância magnética de crânio/medula e eletroneuromiografia. Tratamento da deficiência: corrigir causa-base sempre que possível. Suplementação oral com RRR-alfa-tocoferol (forma natural mais biodisponível): adultos 15-25 mg/dia (22,5-37,5 UI/dia) em casos leves; 100-800 UI/dia em casos moderados; 100-200 UI/kg/dia em abetalipoproteinemia ou deficiências graves com manifestações neurológicas. Associar com refeições contendo gordura para otimizar absorção. Monitoramento: dosar alfa-tocoferol sérico após 3-6 meses de suplementação, ajustar dose conforme resposta. Em pacientes com manifestações neurológicas, reavaliar clinicamente a cada 3 meses e realizar exames de imagem de controle após 6-12 meses. Uso em NASH: considerar vitamina E 800 UI/dia em pacientes adultos não diabéticos, sem cirrose, com NASH confirmada por biópsia e histologia agressiva, por período mínimo de 18-24 meses, com monitoramento trimestral de transaminases. Contraindicações e precauções: evitar doses >1000 mg/dia pelo risco de AVC hemorrágico e efeitos pró-oxidantes. Cautela em pacientes anticoagulados (aumenta risco de sangramento). Não indicar para prevenção primária de doenças cardiovasculares ou câncer conforme diretrizes USPSTF 2022. Reavaliação periódica a cada 6-12 meses mesmo após normalização dos níveis.',

    last_review = CURRENT_DATE
WHERE id = '80ffc2b2-545b-4389-891f-b6aba1f7865c';
